import {MusicDirector} from './music.mjs';
import {SCORE} from './score.mjs';
import {DialogueDirector} from './dialogue.mjs';
import {VOICE_LINES} from './voice-lines.mjs';
import {MISSIONS,newFPS,updateFPS,fireFPS,clamp} from './missions.mjs';
import {World} from './world.mjs';
import {Board,newBoard,updateBoard,boardAction} from './boards.mjs';
const $=id=>document.getElementById(id),ui=$('ui'),view=$('view'),canvas=$('board'),dialog=$('journal');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const btn=(text,action,cls='primary',attrs='')=>`<button class="${cls}" data-action="${action}" ${attrs}>${text}</button>`;
const KEY='crown-current-action-v1',ROUTE=[5,0,1,2,3,4,6];
let storageOK=true,saved={route:0,started:false,completed:{},bestQuiz:0,difficulty:'normal',sound:true,music:true,musicVolume:.6,voice:true,voiceVolume:.9,effectsVolume:.75,subtitles:true};
try{const old=JSON.parse(localStorage.getItem(KEY));if(old&&old.completed&&typeof old.completed==='object'&&Number.isInteger(old.route)&&old.route>=0&&old.route<ROUTE.length)saved={...saved,...old};}catch{storageOK=false;}
const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(saved));}catch{storageOK=false;}};
let world,board=new Board(canvas),model=null,missionIndex=5,running=false,paused=false,campaign=true,current='home',last=performance.now(),keys={},mouse={x:500,y:300},aimHeld=false,fireHeld=false,hadLock=false,subtitleUntil=0,lineIndex=0,lastPoint=0,lastHUD=0,hitUntil=0,quiz=null,journalTab='focus',audio=null,master=null,voiceActive=false,suspendedVoice=false,reacted=new Set();
const coarse=matchMedia('(pointer:coarse)').matches;let notice='';
const music=new MusicDirector({tracks:SCORE,onStatus(state){
 document.body.dataset.music=state.id||'';document.body.dataset.musicState=state.state;document.body.dataset.musicDucked=String(state.ducked);document.body.dataset.musicLevel=String(state.level);
 const label=$('music-status');if(label)label.textContent=state.state==='muted'?'Music is off.':state.state==='paused'?'Music resumes with the game.':state.state==='unavailable'?'Music could not load. Gameplay and voices are still available.':`${state.state==='loading'?'Loading':'Score'} · ${state.title}`;
}});
const dialogue=new DialogueDirector({media:$('voice-track'),lines:VOICE_LINES,
 onCaption(line){const sub=$('subtitle');sub.innerHTML=line?`<b>${esc(line.speaker)}</b> &nbsp; ${esc(line.text)}`:'';sub.classList.toggle('visible',!!line);},
 onActivity(active){voiceActive=active;$('subtitle').classList.toggle('voice-active',active);mixAudio();},
 onLast(line){$('voice-track').dataset.clip=line.id;}
});
function mixAudio(){music.duck(voiceActive);if(master&&audio){master.gain.setTargetAtTime(saved.sound?.24*saved.effectsVolume*(voiceActive?.35:1):0,audio.currentTime,.08);}}
function configureAudio(){music.configure({enabled:saved.sound&&saved.music,volume:saved.musicVolume});dialogue.configure({enabled:saved.sound&&saved.voice,volume:saved.voiceVolume,subtitles:saved.subtitles});mixAudio();}
function cue(id,options={}){return dialogue.say(id,options);}
function reactOnce(id){if(reacted.has(id))return;reacted.add(id);cue(id,{priority:0,ttl:6});}
configureAudio();
function sound(kind){if(!saved.sound)return;try{if(!audio){audio=new(window.AudioContext||window.webkitAudioContext)();master=audio.createGain();master.gain.value=.24*saved.effectsVolume*(voiceActive?.35:1);master.connect(audio.destination);}if(audio.state==='suspended')audio.resume();const now=audio.currentTime;
 if(['shot','boom','hurt'].includes(kind)){const len=kind==='boom'?.5:.24,buffer=audio.createBuffer(1,audio.sampleRate*len,audio.sampleRate),d=buffer.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1)*Math.pow(1-i/d.length,3);const source=audio.createBufferSource(),filter=audio.createBiquadFilter();filter.type='lowpass';filter.frequency.value=kind==='boom'?500:1700;source.buffer=buffer;source.connect(filter);filter.connect(master);source.start();}
 else {const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.setValueAtTime(kind==='hit'?640:kind==='collect'?780:400,now);o.frequency.exponentialRampToValueAtTime(260,now+.14);g.gain.setValueAtTime(.2,now);g.gain.exponentialRampToValueAtTime(.001,now+.18);o.connect(g);g.connect(master);o.start();o.stop(now+.2);}}
 catch{} }
function speak(name,text,seconds=5){const line=dialogue.find(name,text)||{id:name+'-'+text,speaker:name,text,duration:seconds};dialogue.say(line,{priority:1,ttl:30});}
function stopPlay(){dialogue.stop();paused=false;running=false;keys={};fireHeld=false;aimHeld=false;hadLock=false;if(document.pointerLockElement)document.exitPointerLock();$('play-hud').hidden=true;view.style.display='none';canvas.style.display='none';document.body.classList.remove('touch-play');}
function background(art='harbor'){$('backdrop').style.backgroundImage=`linear-gradient(90deg,#031119e0,transparent),linear-gradient(0deg,#091015,transparent 70%),url('${art}.webp')`;}
function home(){stopPlay();music.select('menu');music.resume();current='home';background('frontier');ui.innerHTML=`<section class="menu"><div class="menu-top"><a href="./" class="brand" style="text-decoration:none">DC / US HISTORY · CHAPTER 4</a>${btn('FIELD MANUAL','manual','quiet')}</div><div class="menu-body"><p class="eyebrow">Rule Britannia · An action campaign</p><h1>Crown<br><em>& Current</em></h1><p class="tagline">Take the heights. Outrun the patrol.<br>Survive the empire you helped build.</p><div class="button-row">${btn(saved.started?'Continue campaign →':'Play campaign →','campaign')}${btn('Quick battle','quick','secondary')}</div><div class="modes"><span>FIRST-PERSON COMBAT</span><span>NAVAL CHASES</span><span>STRATEGY</span></div></div><footer class="menu-foot"><span>7 MISSIONS &nbsp; / &nbsp; 1676–1763${!storageOK?' · Saving unavailable in this browser':''}</span><div class="button-row">${btn('Mission select','missions','quiet')}${btn('Quiz practice','quiz','quiet')}${btn('Settings','settings','quiet')}</div></footer></section>`;}
function missionSelect(){stopPlay();music.select('menu');music.resume();current='missions';ui.innerHTML=`<section class="panel-screen"><div class="panel-inner"><p class="eyebrow">Choose your battlefield</p><h1>Seven ways to play.</h1><div class="chapter-list">${MISSI0NS().map((m,i)=>btn(`<b>${String(i+1).padStart(2,'0')}</b><span>${esc(m.title)}<small>${m.year} · ${m.genre}${saved.completed[m.id]?' · COMPLETED':''}</small></span>`,'mission','chapter',`data-index="${i}"`)).join('')}</div>${btn('Back','home','quiet')}</div></section>`;}
function MISSI0NS(){return MISSIONS;}
function controls(m){if(['fps','stealth'].includes(m.mode))return[[coarse?'PAD / SWIPE':'W A S D','Move · mouse or arrows to look'],['CLICK / F',m.mode==='fps'?'Fire · automatic reload':'Throw a stone to distract guards'],['SHIFT / C','Sprint / crouch'],['SPACE','Jump'],['ESC / P','Pause']];if(m.mode==='naval')return[['W A S D','Sail · arrows also work'],['MOUSE','Aim cannons'],['CLICK / SPACE','Fire'],['SHIFT','Full sail']];if(m.mode==='builder')return[['1 / 2 / 3','Choose a home, farm, or meetinghouse'],['CLICK','Place it on a plot · collect floating crates'],['4','Demolish and recover half the cost']];if(m.mode==='defense')return[['1 / 2','Choose militia or cannon'],['CLICK','Place defenders on the rings'],['SPACE','Barrage at the cursor, recharges in 8s']];return[['CLICK','Resupply a garrison for £18'],['1 / 2','Raise taxes / borrow £40'],['60 SECONDS','Hold all three garrisons']];}
function brief(i){stopPlay();missionIndex=i;current='brief';const m=MISSIONS[i];music.select(m.id);music.resume();background(m.art);ui.innerHTML=`<section class="panel-screen"><div class="panel-inner brief"><div><p class="eyebrow">${m.place} · ${m.year}</p><span class="badge">${m.genre}</span><h1>${esc(m.title)}</h1><p>${esc(m.brief)}</p><div class="button-row">${btn(m.mode==='fps'?'Enter battle →':'Deploy →','deploy')}${btn('Replay briefing','brief-replay','quiet')}${btn('Back','home','quiet')}</div></div><div class="controls">${controls(m).map(([k,t])=>`<div class="control"><kbd>${k}</kbd><span>${t}</span></div>`).join('')}<p class="small muted" style="margin-top:22px">${coarse?'Landscape gives you more room. Touch controls are included.':['fps','stealth'].includes(m.mode)?'Click the world to capture your mouse. Escape releases it.':''}</p></div></div></section>`;cue(m.id+'.brief',{caption:false,priority:2});}
function startMission(){
 dialogue.reset();reacted.clear();configureAudio();
 const m=MISSIONS[missionIndex];model=['fps','stealth'].includes(m.mode)?newFPS(m,saved.difficulty):newBoard(m.mode,saved.difficulty);lineIndex=0;lastPoint=0;lastHUD=0;subtitleUntil=0;hitUntil=0;keys={};paused=false;current='playing';$('subtitle').classList.remove('visible');$('subtitle').textContent='';$('hitmarker').style.opacity='0';$('damage').style.opacity='0';$('bearing').textContent='';$('prompt').textContent='';
 if(['fps','stealth'].includes(m.mode)){
  try{world??=new World(view);world.load(m,model);world.resize();}catch(error){ui.innerHTML=`<section class="panel-screen"><div class="panel-inner"><h1>3D graphics are unavailable.</h1><p>This browser could not start WebGL. Naval combat, town building, and strategy still work.</p>${btn('Choose another mission','missions')}${btn('Try again','deploy','secondary')}</div></section>`;return;}
  view.style.display='block';canvas.style.display='none';$('reticle').hidden=false;
 }else{view.style.display='none';canvas.style.display='block';board.resize();$('reticle').hidden=true;}
 music.select(m.id);music.resume();ui.innerHTML='';$('play-hud').hidden=false;document.body.classList.toggle('touch-play',coarse&&['fps','stealth','naval'].includes(m.mode));running=true;model.aim={...mouse};configureHotbar();updateHUD();if(m.mode==='fps'||m.mode==='stealth')world.update(model,0,{});else board.draw(model);sound('start');last=performance.now();
 if(m.mode==='fps'||m.mode==='stealth'){view.focus();if(!coarse)tryLock();}else canvas.focus();
}
function tryLock(){try{const p=view.requestPointerLock?.();p?.catch?.(()=>{});}catch{}}
function configureHotbar(){const m=MISSIONS[missionIndex],s=model;let html='';if(m.mode==='builder')html=[['house','1 · HOME','£22'],['farm','2 · FARM','£18'],['meeting','3 · MEETINGHOUSE','£28'],['remove','4 · REMOVE','Half refund']].map(([v,t,c])=>btn(`${t}<small>${c}</small>`,'select',s.selected===v?'active':'',`data-value="${v}"`)).join('');
 if(m.mode==='defense')html=btn('1 · MILITIA<small>£25</small>','select',s.selected==='militia'?'active':'',`data-value="militia"`)+btn('2 · CANNON<small>£60</small>','select',s.selected==='cannon'?'active':'',`data-value="cannon"`)+btn('BARRAGE<small>Space · aim with cursor</small>','barrage');
 if(m.mode==='crisis')html=btn('1 · TAX COLONIES<small>+£40 · more unrest</small>','tax')+btn('2 · BORROW<small>+£40 · more debt</small>','borrow');$('hotbar').innerHTML=html;
}
function input(){return{forward:keys.KeyW||keys.ArrowUp,back:keys.KeyS||keys.ArrowDown,left:keys.KeyA,right:keys.KeyD,sprint:keys.ShiftLeft||keys.ShiftRight||keys.Shift,crouch:keys.KeyC,turn:(keys.ArrowLeft?1:0)-(keys.ArrowRight?1:0),aim:aimHeld};}
function trigger(){if(!running)return;const m=MISSIONS[missionIndex];let result;if(m.mode==='fps'||m.mode==='stealth'){result=fireFPS(model,m);if(result==='hit'){hitUntil=model.time+.22;sound('hit');}if(result)sound(m.mode==='fps'?'shot':'build');}
 else if(m.mode==='naval'){result=boardAction(model,mouse.x,mouse.y);if(result)sound(result);}else if(m.mode==='defense'){result=boardAction(model,mouse.x,mouse.y,'barrage');if(result)sound(result);}}
function pause(){if(!running&&!paused)return;dialogue.pause();music.pause();running=false;paused=true;keys={};fireHeld=false;if(document.pointerLockElement)document.exitPointerLock();current='pause';ui.innerHTML=`<section class="panel-screen"><div class="panel-inner"><p class="eyebrow">${MISSIONS[missionIndex].place} · ${MISSIONS[missionIndex].year}</p><h1>Hold your position.</h1><div class="button-row">${btn('Resume →','resume')}${btn('Restart mission','restart','secondary')}${btn('Mission select','missions','quiet')}${btn('Audio & settings','settings','quiet')}${btn('Field manual','manual','quiet')}${btn('Main menu','home','quiet')}</div><p class="small muted" style="margin-top:25px">${controls(MISSIONS[missionIndex]).map(([k,t])=>`${k}: ${t}`).join(' · ')}</p></div></section>`;}
function resume(){if(!model)return;music.resume();dialogue.resume();ui.innerHTML='';running=true;paused=false;current='playing';last=performance.now();const m=MISSIONS[missionIndex];if(m.mode==='fps'||m.mode==='stealth'){view.focus();if(!coarse)tryLock();}else canvas.focus();}
function complete(won){
 dialogue.stop();music.select(won?'menu':'debt');music.resume();running=false;keys={};fireHeld=false;if(document.pointerLockElement)document.exitPointerLock();$('play-hud').hidden=true;current='debrief';const m=MISSIONS[missionIndex];
 if(won){const score=model.score??Math.round(1500+model.kills*100-model.time*3);saved.completed[m.id]={time:Math.round(model.time),score:Math.max(0,score)};if(campaign&&saved.route<ROUTE.length-1)saved.route++;save();sound('collect');}
 const final=won&&m.id==='debt';const nextText=campaign?(m.id==='quebec'?'Rewind to where it began →':final?'Finish the campaign →':'Next mission →'):'Choose another mission →';
 cue(won?m.id+'.after':'fail.'+m.mode,{caption:false,priority:3});
 ui.innerHTML=`<section class="panel-screen"><div class="panel-inner"><p class="eyebrow">${m.place} · ${m.year}</p><h1>${won?(final?'Victory has a price.':'Objective complete.'):'Regroup. Try again.'}</h1>${won?`<p class="afterline">${esc(m.after)}</p><div class="debrief-score"><span>MISSION TIME<strong>${Math.floor(model.time/60)}:${String(Math.floor(model.time%60)).padStart(2,'0')}</strong></span><span>${model.kills!==undefined?'POSITIONS SECURED':m.mode==='crisis'?'COLONIAL UNREST':'FINAL SCORE'}<strong>${model.kills!==undefined?model.point+'/3':m.mode==='crisis'?model.unrest:saved.completed[m.id].score}</strong></span></div>`:`<p class="lead">${m.mode==='fps'?'Use cover, let your health recover, and clear defenders near the gold flags.':m.mode==='stealth'?'Crouch to stay unseen. Throw a stone away from your path to distract a patrol.':m.mode==='naval'?'Keep moving across cannon fire. Your cannons follow the cursor.':m.mode==='defense'?'Place defenders in all three lanes. Use your free barrage while waiting for Pitt’s funding.':'Watch the supply bars. Raise revenue before a garrison runs empty.'}</p>`}<div class="button-row">${btn(won?nextText:'Retry mission →',won?'next':'restart')}${won?btn('Replay','restart','secondary'):btn('Use Story difficulty','easier','secondary')}${btn('Main menu','home','quiet')}</div>${won&&final?`<p class="small muted" style="margin-top:23px">Your actions kept the empire supplied: unrest ${model.unrest}, new borrowing ${model.debt}. These are game values, not historical statistics.</p>`:''}</div></section>`;
}
function ending(){stopPlay();music.select('menu');music.resume();background('harbor');current='ending';cue('ending',{caption:false,priority:2});ui.innerHTML=`<section class="panel-screen"><div class="panel-inner"><p class="eyebrow">Chapter 4 · Completed</p><h1>You won the empire.<br>Can you keep it?</h1><p class="lead">In 1763, many colonists were proud to be British. Debt, new territory, and tighter control would turn victory into a conflict over who should pay—and who should decide.</p><div class="button-row">${btn('15-question final dispatch','quiz')}${btn('Play any mission','missions','secondary')}${btn('Main menu','home','quiet')}</div></div></section>`;}
function updateHUD(){const s=model,m=MISSIONS[missionIndex];$('hud-era').textContent=`${m.place.toUpperCase()} · ${m.year}`;$('hud-objective').textContent=m.objective;$('sound-toggle').textContent=saved.sound?'SOUND ON':'SOUND OFF';
 if(m.mode==='fps'||m.mode==='stealth'){
  const goal=m.points[s.point];$('hud-progress').textContent=goal?`${s.point} / 3 · ${goal[2]}`:'3 / 3';$('vitals').innerHTML=`<strong>${Math.ceil(s.player.hp)}</strong><span>HEALTH</span><div class="healthbar"><i style="width:${s.player.hp}%"></i></div>`;
  const alert=Math.max(...s.enemies.map(e=>e.alert));$('loadout').innerHTML=m.mode==='fps'?`<strong>${s.reload>0?'…':s.round}</strong><span>FLINTLOCK</span><div class="small">${s.reload>0?'RELOADING':'F / CLICK · FIRE'}</div>`:`<strong>${alert>.65?'SEEN':alert>.1?'CAUTION':'HIDDEN'}</strong><div class="small">${s.noise>0?'STONE RECHARGING':'F / CLICK · DISTRACT'}</div>`;
  if(goal){const d=Math.round(Math.hypot(goal[0]-s.player.x,goal[1]-s.player.z));const a=Math.atan2(-(goal[0]-s.player.x),-(goal[1]-s.player.z))-s.player.yaw,dir=Math.atan2(Math.sin(a),Math.cos(a));$('bearing').textContent=`${Math.abs(dir)<.3?'◆':dir<0?'→':'←'} ${d} m`;
   const contested=m.mode==='fps'&&s.enemies.some(e=>e.hp>0&&Math.hypot(e.x-goal[0],e.z-goal[1])<8);$('prompt').textContent=d<4?(contested?'Clear nearby defenders':`SECURING · ${Math.min(100,Math.floor(s.capture/1.1*100))}%`):s.time<11?'WASD move · Mouse / arrows aim · F fire · Shift sprint':'';
  }
  $('damage').style.opacity=s.hurt>0?'1':'0';$('hitmarker').style.opacity=s.time<hitUntil?'1':'0';
 }else{
  $('bearing').textContent='';$('prompt').textContent='';$('vitals').innerHTML=m.mode==='builder'?`<strong>${Math.floor(s.money)}</strong><span>SUPPLIES</span>`:m.mode==='crisis'?`<strong>£${Math.floor(s.money)}</strong><span>TREASURY</span>`:`<strong>${Math.ceil(s.hp)}</strong><span>${m.mode==='naval'?'HULL':'FORT'}</span><div class="healthbar"><i style="width:${s.hp}%"></i></div>`;
  $('hud-progress').textContent=m.mode==='naval'?`${s.cargo} / 5 cargo barrels`:m.mode==='builder'?`${s.people} / 12 settlers housed`:m.mode==='defense'?`${s.spawned} / 24 attackers${s.funded?' · PITT’S FUNDING ACTIVE':''}`:`${Math.max(0,Math.ceil(60-s.time))} seconds to hold`;
  $('loadout').innerHTML=m.mode==='defense'?`<strong>£${Math.floor(s.money)}</strong><span>WAR CHEST</span>`:m.mode==='crisis'?`<span>UNREST ${s.unrest} · DEBT ${s.debt}</span>`:m.mode==='naval'?'<span>CLICK / SPACE · CANNONS</span>':'<span>CLICK FLOATING CRATES · +12</span>';
  if(m.mode==='defense'){const b=$('hotbar').querySelector('[data-action="barrage"]');if(b)b.disabled=s.barrage>0;}
  if(m.mode==='crisis')$('hotbar').querySelectorAll('button').forEach(b=>b.disabled=s.financeCool>0);
 }
}
function loop(now){requestAnimationFrame(loop);const dt=Math.min(.05,(now-last)/1000);last=now;dialogue.update(dt);if(!running||!model)return;const m=MISSIONS[missionIndex],inp=input();
 if(m.mode==='fps'||m.mode==='stealth'){
  const oldPoint=model.point,oldHurt=model.hurt;updateFPS(model,m,inp,dt);if(model.point>oldPoint){cue(m.id+'.point'+oldPoint,{priority:3,ttl:Infinity});sound('collect');}if(model.hurt>oldHurt)sound('hurt');if(fireHeld||keys.KeyF)trigger();world.update(model,dt,inp);
 }else{
  if(m.mode==='naval'){inp.left=inp.left||keys.ArrowLeft;inp.right=inp.right||keys.ArrowRight;if(fireHeld||keys.Space)trigger();}
  const cargo=model.cargo;updateBoard(model,inp,dt);if(model.cargo>cargo){sound('collect');if(model.cargo===5)cue('cargo.full',{priority:3});else if(model.cargo===1)reactOnce('cargo.first');else if(model.cargo===3)reactOnce('cargo.three');}board.draw(model);
 }
 while(lineIndex<m.lines.length&&model.time>=m.lines[lineIndex][0]){const [,name,text]=m.lines[lineIndex++];speak(name,text,6);}
 reactToMission();if(model.time-lastHUD>.09){updateHUD();lastHUD=model.time;}
 if(model.done)complete(true);else if(model.failed)complete(false);
}
function reactToMission(){const m=MISSIONS[missionIndex],s=model;
 if(m.mode==='fps'&&s.player.hp<35)cue('health',{priority:0,ttl:5,cooldown:24});
 if(m.mode==='stealth'&&s.enemies.some(e=>e.alert>.8))cue(m.id==='crown'?'spotted.crown':'spotted',{priority:0,ttl:4,cooldown:25});
 if(m.mode==='naval'&&s.hp<40)cue('hull',{priority:0,ttl:5,cooldown:25});
 if(m.mode==='builder'){
  if(s.plots.some(p=>p.type==='house'))reactOnce('home.built');
  if(s.plots.some(p=>p.type==='farm'))reactOnce('farm.built');
  if(s.plots.some(p=>p.type==='meeting'))reactOnce('meeting.built');
 }
 if(m.mode==='defense'&&s.hp<75)reactOnce('fort');
 if(m.mode==='crisis'){
  if(s.money<18&&s.time>5)cue('treasury',{priority:0,ttl:5,cooldown:25});
  s.garrisons.forEach((g,i)=>{if(g.supply<28)cue(['canada','ohio','florida'][i],{priority:0,ttl:5,cooldown:30});});
 }
}
function settings(){
 dialogue.pause();current='settings';
 const slider=(id,label,value)=>`<div class="audio-setting"><label for="${id}">${label}</label><input id="${id}" type="range" min="0" max="100" step="5" value="${Math.round(value*100)}"><output for="${id}" id="${id}-value">${Math.round(value*100)}%</output></div>`;
 ui.innerHTML=`<section class="panel-screen"><div class="panel-inner settings-panel"><p class="eyebrow">Settings</p><h1>Make it yours.</h1><div class="settings-line"><label for="difficulty">Difficulty</label><select id="difficulty"><option value="normal" ${saved.difficulty==='normal'?'selected':''}>Standard</option><option value="story" ${saved.difficulty==='story'?'selected':''}>Story · less damage, more room</option></select></div>
 <div class="audio-toggles">${btn(saved.sound?'Sound: on':'Sound: off','sound','secondary',`aria-pressed="${saved.sound}"`)}${btn(saved.music?'Music: on':'Music: off','music','secondary',`aria-pressed="${saved.music}"`)}${btn(saved.voice?'Voices: on':'Voices: off','voice','secondary',`aria-pressed="${saved.voice}"`)}${btn(saved.subtitles?'Subtitles: on':'Subtitles: off','subtitles','secondary',`aria-pressed="${saved.subtitles}"`)}</div>
 ${slider('music-volume','Music volume',saved.musicVolume)}${slider('voice-volume','Voice volume',saved.voiceVolume)}${slider('effects-volume','Effects volume',saved.effectsVolume)}
 <div class="button-row">${btn('Test voice','voice-test','quiet')}${btn('Stop preview','voice-stop','quiet')}</div><p class="muted small" style="margin-top:16px"><span id="music-status"></span><br>Music and effects soften during speech. Character voices are AI-generated.</p>
 <div class="button-row">${btn(paused?'Back to pause menu':'Back',paused?'settings-back':'home')}${!paused?btn('Start campaign over','new-campaign','quiet'):''}</div></div></section>`;music.report();
}
function openManual(tab='focus'){dialogue.pause();journalTab=tab;renderManual();if(!dialog.open)dialog.showModal();}
function renderManual(){let content='';if(journalTab==='focus')content=HISTORY.priorities.map(([title,text])=>`<h3>${esc(title)}</h3><p>${esc(text)}</p>`).join('');if(journalTab==='terms')content=`<dl>${HISTORY.glossary.map(([t,d])=>`<dt>${esc(t)}</dt><dd>${esc(d)}</dd>`).join('')}</dl>`;if(journalTab==='timeline')content=HISTORY.timeline.map(([y,t])=>`<h3>${esc(y)}</h3><p>${esc(t)}</p>`).join('');if(journalTab==='credits')content=`<h3>Action with historical context</h3><p>Combat encounters, characters, timings, maps, and resources are fictional game scenarios. Musket reloads are accelerated for play. They are not reconstructions of particular skirmishes or exact period tactics.</p><p>The historical spine follows the supplied edited Chapter 4 of OpenStax U.S. History. Bacon’s Rebellion, the Albany Plan, and war legacies follow the supplied class-priority list. Hobbes and Locke use standard accounts because separate class notes were not supplied.</p><p>Original practice questions are not the teacher’s actual quiz. The default run contains 10 priority questions, 3 key terms, and one question each on Hobbes and Locke.</p><h3>Sources</h3><ul><li><a href="https://openstax.org/books/us-history/pages/4-introduction" target="_blank" rel="noopener">OpenStax · Chapter 4</a></li><li><a href="https://openstax.org/books/us-history/pages/3-3-english-settlements-in-america" target="_blank" rel="noopener">OpenStax · Bacon’s Rebellion</a></li><li><a href="https://history.state.gov/milestones/1750-1775/albany-plan" target="_blank" rel="noopener">Office of the Historian · Albany Plan</a></li><li><a href="https://history.state.gov/milestones/1750-1775/french-indian-war" target="_blank" rel="noopener">Office of the Historian · War and consequences</a></li><li><a href="https://www.gutenberg.org/files/73957/73957-h/73957-h.htm" target="_blank" rel="noopener">Hobbes · Leviathan</a></li><li><a href="https://www.gutenberg.org/cache/epub/7370/pg7370-images.html" target="_blank" rel="noopener">Locke · Second Treatise</a></li></ul><h3>Credits & privacy</h3><p>Three.js by its contributors (MIT). Three menu environments made with OpenAI ImageGen. Character dialogue is prerecorded synthetic speech generated locally with Kokoro-82M (Apache 2.0). Voices are stock synthetic characters, not historical recordings. No microphone is used. Eight original instrumental score loops were composed and synthesized for this game; see MUSIC-CREDITS.md in the repository. All 3D gameplay geometry, game systems, narrative, and questions are original. Progress stays in your browser. No accounts, trackers, or AI services are used in gameplay.</p>`;
 dialog.innerHTML=`${btn('×','close-manual','close','aria-label="Close field manual"')}<h2 id="journal-title">Field manual</h2><div class="journal-tabs">${[['focus','Quiz focus'],['terms','Key terms'],['timeline','Timeline'],['credits','Sources']].map(([id,label])=>btn(label,'manual-tab',journalTab===id?'active':'',`data-tab="${id}"`)).join('')}</div>${content}`;}
function startQuiz(broad=false){stopPlay();music.select('menu');music.resume();current='quiz';background('printshop');quiz={deck:buildQuizDeck(QUESTION_BANK,broad),answers:[],index:0,broad};renderQuiz();}
function renderQuiz(){const item=quiz.deck[quiz.index],q=QUESTION_BANK.find(q=>q.id===item.id),choice=quiz.answers[quiz.index],answered=choice!==undefined;
 ui.innerHTML=`<section class="quiz-screen"><div class="quiz-wrap"><div class="quiz-top"><span class="eyebrow" style="margin:0">Final dispatch · ${quiz.index+1} / 15</span>${btn('Exit','home','quiet')}</div><div class="progress-line"><i style="width:${quiz.index/15*100}%"></i></div><h1>${esc(q.q)}</h1>${item.options.map((index,i)=>btn(`<b>${'ABCD'[i]}</b><span>${esc(q.a[index])}${answered&&index===q.correct?' ✓':''}</span>`,'answer',`answer ${answered&&index===q.correct?'correct':''} ${answered&&index===choice&&choice!==q.correct?'wrong':''}`,`data-index="${index}" ${answered?'disabled':''}`)).join('')}${answered?`<p class="feedback">${esc(q.why)}</p>${btn(quiz.index===14?'See results →':'Next →','quiz-next')}`:''}</div></section>`;
}
function quizResults(){const results=quiz.deck.map((item,i)=>({q:QUESTION_BANK.find(q=>q.id===item.id),choice:quiz.answers[i]})),missed=results.filter(r=>r.q.correct!==r.choice),score=15-missed.length;saved.bestQuiz=Math.max(saved.bestQuiz,score);save();ui.innerHTML=`<section class="quiz-screen"><div class="quiz-wrap"><p class="eyebrow">Final dispatch received</p><h1>${score} / 15</h1><p class="muted">10 priority topics · 3 key terms · 2 Hobbes & Locke<br>Best on this device: ${saved.bestQuiz}/15</p><div class="button-row">${btn('Play the game','home')}${btn('Try another run','quiz','secondary')}${btn('Whole-chapter mix','broad-quiz','quiet')}</div><h2 style="font-size:34px;margin:35px 0 20px">${missed.length?'Threads to revisit':'Everything connected.'}</h2>${missed.map(({q,choice})=>`<div class="review"><strong>${esc(q.q)}</strong><p>You chose: ${esc(q.a[choice])}</p><p style="color:var(--gold)">${esc(q.a[q.correct])}</p><p>${esc(q.why)}</p></div>`).join('')}</div></section>`;}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action;
 if(a==='home')home();if(a==='campaign'){campaign=true;saved.started=true;save();brief(ROUTE[saved.route]);}if(a==='quick'){campaign=false;brief(5);}if(a==='missions')missionSelect();if(a==='mission'){campaign=false;brief(Number(b.dataset.index));}if(a==='deploy'||a==='restart')startMission();if(a==='resume')resume();if(a==='easier'){saved.difficulty='story';save();startMission();}
 if(a==='next'){if(campaign){if(missionIndex===6)ending();else brief(ROUTE[saved.route]);}else missionSelect();}
 if(a==='settings')settings();if(['sound','music','voice','subtitles'].includes(a)){saved[a]=!saved[a];save();configureAudio();settings();music.unlock();}if(a==='settings-back'){dialogue.stop();pause();}if(a==='voice-test'){dialogue.stop();cue('test',{caption:false});}if(a==='voice-stop')dialogue.stop();if(a==='brief-replay'){dialogue.stop();cue(MISSIONS[missionIndex].id+'.brief',{caption:false});}if(a==='new-campaign'){saved.route=0;saved.started=false;save();home();}
 if(a==='manual'){if(running)pause();openManual();}if(a==='manual-tab'){journalTab=b.dataset.tab;renderManual();}if(a==='close-manual')dialog.close();
 if(a==='select'&&running){model.selected=b.dataset.value;configureHotbar();}if(a==='barrage')trigger();if(['tax','borrow'].includes(a)&&running){const result=boardAction(model,0,0,a);if(result){sound(result);cue(a,{priority:2,cooldown:5});}}
 if(a==='quiz'||a==='broad-quiz')startQuiz(a==='broad-quiz');if(a==='answer'&&quiz.answers[quiz.index]===undefined){quiz.answers[quiz.index]=Number(b.dataset.index);renderQuiz();}if(a==='quiz-next'){if(quiz.index===14)quizResults();else{quiz.index++;renderQuiz();}}
});
dialog.addEventListener('close',()=>{if(!paused&&!document.hidden)dialogue.resume();});
document.addEventListener('input',e=>{if(['music-volume','voice-volume','effects-volume'].includes(e.target.id)){const prop={'music-volume':'musicVolume','voice-volume':'voiceVolume','effects-volume':'effectsVolume'}[e.target.id];saved[prop]=Number(e.target.value)/100;$(e.target.id+'-value').textContent=e.target.value+'%';configureAudio();save();}});
document.addEventListener('change',e=>{if(e.target.id==='difficulty'){saved.difficulty=e.target.value;save();}});
document.addEventListener('keydown',e=>{
 if(dialog.open)return;if((e.code==='Escape'||e.code==='KeyP')&&running){e.preventDefault();pause();return;}if(e.code==='KeyP'&&paused){resume();return;}if(!running)return;if(['Space','ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Tab'].includes(e.code))e.preventDefault();keys[e.code]=true;const m=MISSIONS[missionIndex];
 if(e.repeat)return;
 if(e.code==='Space'){if(['fps','stealth'].includes(m.mode)&&model.player.jump===0)model.player.vy=5;else if(m.mode==='defense')trigger();}
 if(e.code==='KeyF')trigger();if(e.code==='KeyR'&&m.mode==='fps'&&model.round===0&&model.reload<=0)model.reload=1.35;
 if(m.mode==='builder'&&/^Digit[1-4]$/.test(e.code)){model.selected=['house','farm','meeting','remove'][Number(e.code.slice(-1))-1];configureHotbar();}
 if(m.mode==='defense'&&/^Digit[12]$/.test(e.code)){model.selected=e.code==='Digit1'?'militia':'cannon';configureHotbar();}
 if(m.mode==='crisis'&&/^Digit[12]$/.test(e.code)){const a=e.code==='Digit1'?'tax':'borrow';const result=boardAction(model,0,0,a);if(result){sound(result);cue(a,{priority:2,cooldown:5});}}
});
document.addEventListener('keyup',e=>{keys[e.code]=false;});
document.addEventListener('mousemove',e=>{if(!running)return;if(document.pointerLockElement===view||aimHeld){model.player.yaw-=e.movementX*.0024;model.player.pitch=clamp(model.player.pitch-e.movementY*.002,-.65,.65);}});
view.addEventListener('pointerdown',e=>{if(!running)return;if(e.pointerType==='touch')return;if(e.button===2)aimHeld=true;else{if(document.pointerLockElement!==view)tryLock();trigger();}});
document.addEventListener('pointerup',()=>{aimHeld=false;fireHeld=false;});
view.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('contextmenu',e=>e.preventDefault());
let touchLook=null;view.addEventListener('pointerdown',e=>{if(e.pointerType==='touch')touchLook={id:e.pointerId,x:e.clientX,y:e.clientY};});view.addEventListener('pointermove',e=>{if(!running||!touchLook||e.pointerId!==touchLook.id)return;model.player.yaw-=(e.clientX-touchLook.x)*.006;model.player.pitch=clamp(model.player.pitch-(e.clientY-touchLook.y)*.004,-.65,.65);touchLook.x=e.clientX;touchLook.y=e.clientY;});view.addEventListener('pointerup',()=>touchLook=null);
canvas.addEventListener('pointermove',e=>{mouse=board.point(e);});canvas.addEventListener('pointerdown',e=>{if(!running)return;mouse=board.point(e);const result=boardAction(model,mouse.x,mouse.y);if(result)sound(result);});
$('pause-button').addEventListener('click',pause);$('sound-toggle').addEventListener('click',()=>{saved.sound=!saved.sound;save();configureAudio();updateHUD();});
document.querySelectorAll('[data-key]').forEach(b=>{const map={w:'KeyW',a:'KeyA',s:'KeyS',d:'KeyD'};const key=map[b.dataset.key]||b.dataset.key;b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys[key]=true;});for(const type of['pointerup','pointercancel','lostpointercapture'])b.addEventListener(type,()=>keys[key]=false);});
$('touch-fire').addEventListener('pointerdown',e=>{e.preventDefault();fireHeld=true;trigger();});
document.addEventListener('pointerlockchange',()=>{if(document.pointerLockElement===view)hadLock=true;else if(hadLock){hadLock=false;if(running)pause();}});
document.addEventListener('visibilitychange',()=>{music.setHidden(document.hidden);if(document.hidden){if(running)pause();else if(!paused){suspendedVoice=true;dialogue.pause();}}else if(suspendedVoice){suspendedVoice=false;dialogue.resume();}});window.addEventListener('pagehide',()=>{dialogue.stop();music.stop();});window.addEventListener('blur',()=>{keys={};fireHeld=false;});window.addEventListener('resize',()=>{world?.resize();board.resize();});
for(const type of ['pointerdown','keydown','click'])document.addEventListener(type,()=>music.unlock(),{capture:true});
home();requestAnimationFrame(loop);

