// Prerecorded synthetic performances; generated locally with Kokoro-82M.
export const C5_VOICES = [
  {
    "id": "prologue.0",
    "speaker": "ROWAN",
    "text": "Boston. Seventeen seventy-four. The harbor is closed. Our press is burning.",
    "voice": "am_fenrir",
    "speed": 1.03,
    "lang": "en-us",
    "file": "c5-voice-prologue-0-0dc00c704.mp3",
    "duration": 4.761,
    "peak": 0.86,
    "rms": 0.0928
  },
  {
    "id": "prologue.1",
    "speaker": "MARA",
    "text": "You always said a page could travel farther than a soldier. Prove it.",
    "voice": "af_heart",
    "speed": 1.02,
    "lang": "en-us",
    "file": "c5-voice-prologue-1-d957aee01.mp3",
    "duration": 3.794,
    "peak": 0.86,
    "rms": 0.1281
  },
  {
    "id": "prologue.2",
    "speaker": "ROWAN",
    "text": "Eleven years ago, I thought I was carrying messages. I was carrying the first pieces of a revolution.",
    "voice": "am_fenrir",
    "speed": 1.03,
    "lang": "en-us",
    "file": "c5-voice-prologue-2-471d2aa62.mp3",
    "duration": 6.175,
    "peak": 0.86,
    "rms": 0.1081
  },
  {
    "id": "epilogue.0",
    "speaker": "ISAIAH",
    "text": "Philadelphia. The First Continental Congress backs resistance. The colonies are learning to act together.",
    "voice": "am_michael",
    "speed": 1.04,
    "lang": "en-us",
    "file": "c5-voice-epilogue-0-ff1bbd688.mp3",
    "duration": 6.666,
    "peak": 0.86,
    "rms": 0.1234
  },
  {
    "id": "epilogue.1",
    "speaker": "MARA",
    "text": "The Association means more than refusing imports. No exports. No consumption. Our workshops have work to do.",
    "voice": "af_heart",
    "speed": 1.02,
    "lang": "en-us",
    "file": "c5-voice-epilogue-1-328013733.mp3",
    "duration": 7.2,
    "peak": 0.86,
    "rms": 0.1126
  },
  {
    "id": "epilogue.2",
    "speaker": "THOMAS",
    "text": "I still believe in Britain. I still believe you are my brother. Do not make me choose which one survives.",
    "voice": "bm_fable",
    "speed": 1.04,
    "lang": "en-gb",
    "file": "c5-voice-epilogue-2-dcf6c3fd8.mp3",
    "duration": 6.448,
    "peak": 0.86,
    "rms": 0.1286
  },
  {
    "id": "epilogue.3",
    "speaker": "ROWAN",
    "text": "A press can be rebuilt. A city can be fed. And a story does not end just because someone orders it to.",
    "voice": "am_fenrir",
    "speed": 1.03,
    "lang": "en-us",
    "file": "c5-voice-epilogue-3-242fa4c9a.mp3",
    "duration": 6.551,
    "peak": 0.86,
    "rms": 0.1014
  },
  {
    "id": "line.in0",
    "speaker": "WARD",
    "text": "The war is won, Rowan. Now London has an empire it cannot afford.",
    "voice": "bm_george",
    "speed": 1.01,
    "lang": "en-gb",
    "file": "c5-voice-line-in0-fef4ebc32.mp3",
    "duration": 4.57,
    "peak": 0.6567,
    "rms": 0.15
  },
  {
    "id": "line.in1",
    "speaker": "ROWAN",
    "text": "My brother says the west is ours. Our family could start again.",
    "voice": "am_fenrir",
    "speed": 1.03,
    "lang": "en-us",
    "file": "c5-voice-line-in1-37c9163db.mp3",
    "duration": 3.605,
    "peak": 0.86,
    "rms": 0.1114
  },
  {
    "id": "line.in2",
    "speaker": "WARD",
    "text": "Native nations still hold their lands. A British map does not make them disappear. Stay close.",
    "voice": "bm_george",
    "speed": 1.01,
    "lang": "en-gb",
    "file": "c5-voice-line-in2-7167bae28.mp3",
    "duration": 6.538,
    "peak": 0.7401,
    "rms": 0.15
  },
  {
    "id": "line.out0",
    "speaker": "WARD",
    "text": "You carried the bag when it mattered. A good courier remembers what is inside.",
    "voice": "bm_george",
    "speed": 1.01,
    "lang": "en-gb",
    "file": "c5-voice-line-out0-de7fbd52a.mp3",
    "duration": 4.884,
    "peak": 0.86,
    "rms": 0.1344
  },
  {
    "id": "line.out1",
    "speaker": "ROWAN",
    "text": "A bag today. Maybe something that changes things tomorrow.",
    "voice": "am_fenrir",
    "speed": 1.03,
    "lang": "en-us",
    "file": "c5-voice-line-out1-9167df91a.mp3",
    "duration": 3.311,
    "peak": 0.86,
    "rms": 0.0999
  },
  {
    "id": "line.goal0",
    "speaker": "WARD",
    "text": "Road thieves. Use the rocks for cover. Take the bag and keep moving.",
    "voice": "bm_george",
    "speed": 1.01,
    "lang": "en-gb",
    "file": "c5-voice-line-goal0-9660d56e1.mp3",
    "duration": 4.556,
    "peak": 0.86,
    "rms": 0.1448
  },
  {
    "id": "line.goal1",
    "speaker": "ROWAN",
    "text": "The Proclamation Line. No British settlement west of the Appalachians. So much for our new beginning.",
    "voice": "am_fenrir",
    "speed": 1.03,
    "lang": "en-us",
    "file": "c5-voice-line-goal1-0b1ff7ef0.mp3",
    "duration": 6.133,
    "peak": 0.86,
    "rms": 0.1172
  },
  {
    "id": "line.goal2",
    "speaker": "WARD",
    "text": "Britain wants to prevent another frontier war. The settlers see a promise taken away.",
    "voice": "bm_george",
    "speed": 1.01,
    "lang": "en-gb",
    "file": "c5-voice-line-goal2-30fd788cc.mp3",
    "duration": 5.599,
    "peak": 0.86,
    "rms": 0.1287
  },
  {
    "id": "line.goal3",
    "speaker": "ROWAN",
    "text": "Then we go east. Thomas has work at the harbor. There must be a place for me there.",
    "voice": "am_fenrir",
    "speed": 1.03,
    "lang": "en-us",
    "file": "c5-voice-line-goal3-9090dd9d2.mp3",
    "duration": 4.66,
    "peak": 0.86,
    "rms": 0.0978
  },
  {
    "id": "line.hint",
    "speaker": "WARD",
    "text": "Look for the pale lantern. It marks your next stop.",
    "voice": "bm_george",
    "speed": 1.01,
    "lang": "en-gb",
    "file": "c5-voice-line-hint-41c4ef189.mp3",
    "duration": 3.277,
    "peak": 0.826,
    "rms": 0.15
  },
  {
    "id": "ink.in0",
    "speaker": "THOMAS",
    "text": "The Sugar Act lowered the molasses duty, but customs is finally enforcing it. We have war debts to pay.",
    "voice": "bm_fable",
    "speed": 1.04,
    "lang": "en-gb",
    "file": "c5-voice-ink-in0-bef51513e.mp3",
    "duration": 6.658,
    "peak": 0.86,
    "rms": 0.1086
  },
  {
    "id": "ink.in1",
    "speaker": "ISAIAH",
    "text": "And my cargo case goes to a vice-admiralty court. A royal court for trade at sea. No jury.",
    "voice": "am_michael",
    "speed": 1.04,
    "lang": "en-us",
    "file": "c5-voice-ink-in1-5b2a2c045.mp3",
    "duration": 6.785,
    "peak": 0.86,
    "rms": 0.1409
  },
  {
    "id": "ink.in2",
    "speaker": "ROWAN",
    "text": "Now stamps on paper, too. Help me get the press running before the watch closes the street.",
    "voice": "am_fenrir",
    "speed": 1.03,
    "lang": "en-us",
    "file": "c5-voice-ink-in2-9550e0d35.mp3",
    "duration": 5.292,
    "peak": 0.86,
    "rms": 0.101
  },
  {
    "id": "ink.out0",
    "speaker": "THOMAS",
    "text": "You put our name on those sheets?",
    "voice": "bm_fable",
    "speed": 1.04,
    "lang": "en-gb",
    "file": "c5-voice-ink-out0-95c09597b.mp3",
    "duration": 2.244,
    "peak": 0.86,
    "rms": 0.0973
  },
  {
    "id": "ink.out1",
    "speaker": "ROWAN",
    "text": "I put the argument on them. You taught me there was a difference.",
    "voice": "am_fenrir",
    "speed": 1.03,
    "lang": "en-us",
    "file": "c5-voice-ink-out1-932143503.mp3",
    "duration": 3.301,
    "peak": 0.86,
    "rms": 0.1001
  },
  {
    "id": "ink.goal0",
    "speaker": "ISAIAH",
    "text": "No neighbors on a jury. Just the crown’s judge deciding our maritime case.",
    "voice": "am_michael",
    "speed": 1.04,
    "lang": "en-us",
    "file": "c5-voice-ink-goal0-d9c2c9fd4.mp3",
    "duration": 5.289,
    "peak": 0.86,
    "rms": 0.0864
  },
  {
    "id": "ink.goal1",
    "speaker": "ROWAN",
    "text": "The consumer pays for the stamp. A direct tax, right on the page.",
    "voice": "am_fenrir",
    "speed": 1.03,
    "lang": "en-us",
    "file": "c5-voice-ink-goal1-8d0d5d04f.mp3",
    "duration": 3.936,
    "peak": 0.86,
    "rms": 0.11
  },
  {
    "id": "ink.goal2",
    "speaker": "ISAIAH",
    "text": "The Sons of Liberty paid for this ink. Artisans, shopkeepers, small merchants. British patriots opposing the Stamp Act.",
    "voice": "am_michael",
    "speed": 1.04,
    "lang": "en-us",
    "file": "c5-voice-ink-goal2-e7c1a45fe.mp3",
    "duration": 8.301,
    "peak": 0.86,
    "rms": 0.094
  },
  {
    "id": "ink.goal3",
    "speaker": "ROWAN",
    "text": "No taxation without representation. Virginia’s resolutions put it plainly: if Parliament taxes us, where is our voice?",
    "voice": "am_fenrir",
    "speed": 1.03,
    "lang": "en-us",
    "file": "c5-voice-ink-goal3-bed2c4c8a.mp3",
    "duration": 7.931,
    "peak": 0.86,
    "rms": 0.0972
  },
  {
    "id": "ink.hint",
    "speaker": "ISAIAH",
    "text": "Crouch behind crates. A thrown stone will pull a patrol away.",
    "voice": "am_michael",
    "speed": 1.04,
    "lang": "en-us",
    "file": "c5-voice-ink-hint-2d67a1677.mp3",
    "duration": 4.504,
    "peak": 0.86,
    "rms": 0.1367
  },
  {
    "id": "homespun.in0",
    "speaker": "MARA",
    "text": "A boycott is easy to promise. Try keeping twelve families clothed through one.",
    "voice": "af_heart",
    "speed": 1.02,
    "lang": "en-us",
    "file": "c5-voice-homespun-in0-3499eac12.mp3",
    "duration": 4.688,
    "peak": 0.86,
    "rms": 0.1234
  },
  {
    "id": "homespun.in1",
    "speaker": "ROWAN",
    "text": "Tell me where you need me.",
    "voice": "am_fenrir",
    "speed": 1.03,
    "lang": "en-us",
    "file": "c5-voice-homespun-in1-e59ebcb3b.mp3",
    "duration": 1.211,
    "peak": 0.86,
    "rms": 0.0948
  },
  {
    "id": "homespun.in2",
    "speaker": "MARA",
    "text": "Flax to the wheel. Yarn to the loom. Cloth to the door. Keep the room moving.",
    "voice": "af_heart",
    "speed": 1.02,
    "lang": "en-us",
    "file": "c5-voice-homespun-in2-c29efc86c.mp3",
    "duration": 4.632,
    "peak": 0.86,
    "rms": 0.1174
  },
  {
    "id": "homespun.out0",
    "speaker": "MARA",
    "text": "The Daughters of Liberty will keep making. The couriers will keep moving. That is how a boycott survives.",
    "voice": "af_heart",
    "speed": 1.02,
    "lang": "en-us",
    "file": "c5-voice-homespun-out0-e2c472303.mp3",
    "duration": 5.868,
    "peak": 0.86,
    "rms": 0.1269
  },
  {
    "id": "homespun.out1",
    "speaker": "ISAIAH",
    "text": "And when you write about liberty, leave room for the people still denied it.",
    "voice": "am_michael",
    "speed": 1.04,
    "lang": "en-us",
    "file": "c5-voice-homespun-out1-f43e17491.mp3",
    "duration": 3.961,
    "peak": 0.86,
    "rms": 0.1425
  },
  {
    "id": "homespun.event0",
    "speaker": "MARA",
    "text": "The Daughters of Liberty organize the spinning and the boycott. We can make what we refuse to import.",
    "voice": "af_heart",
    "speed": 1.02,
    "lang": "en-us",
    "file": "c5-voice-homespun-event0-62914e64b.mp3",
    "duration": 5.79,
    "peak": 0.86,
    "rms": 0.1116
  },
  {
    "id": "homespun.event1",
    "speaker": "ROWAN",
    "text": "No British imports. Every local delivery keeps the non-importation movement alive.",
    "voice": "am_fenrir",
    "speed": 1.03,
    "lang": "en-us",
    "file": "c5-voice-homespun-event1-dd126fcce.mp3",
    "duration": 5.407,
    "peak": 0.86,
    "rms": 0.119
  },
  {
    "id": "homespun.event2",
    "speaker": "ISAIAH",
    "text": "Townshend’s import duties fall on merchants first. An indirect tax: they pass the cost to customers.",
    "voice": "am_michael",
    "speed": 1.04,
    "lang": "en-us",
    "file": "c5-voice-homespun-event2-864eb80bd.mp3",
    "duration": 6.904,
    "peak": 0.86,
    "rms": 0.1223
  },
  {
    "id": "homespun.event3",
    "speaker": "MARA",
    "text": "Take Samuel Adams’s Massachusetts Circular with the next bundle. It challenges taxation without representation and asks other colonies to boycott.",
    "voice": "af_heart",
    "speed": 1.02,
    "lang": "en-us",
    "file": "c5-voice-homespun-event3-3dc6605a6.mp3",
    "duration": 9.439,
    "peak": 0.86,
    "rms": 0.0947
  },
  {
    "id": "homespun.hint",
    "speaker": "MARA",
    "text": "The next wheel is waiting. Keep moving; we have each other.",
    "voice": "af_heart",
    "speed": 1.02,
    "lang": "en-us",
    "file": "c5-voice-homespun-hint-2f8a8c29c.mp3",
    "duration": 3.248,
    "peak": 0.86,
    "rms": 0.1331
  },
  {
    "id": "kingstreet.in0",
    "speaker": "ISAIAH",
    "text": "A crowd at the customs house. Soldiers in the street. Rowan, get Mara out of here.",
    "voice": "am_michael",
    "speed": 1.04,
    "lang": "en-us",
    "file": "c5-voice-kingstreet-in0-a8ac463d8.mp3",
    "duration": 5.483,
    "peak": 0.86,
    "rms": 0.1175
  },
  {
    "id": "kingstreet.in1",
    "speaker": "ROWAN",
    "text": "Those shots... Isaiah!",
    "voice": "am_fenrir",
    "speed": 1.03,
    "lang": "en-us",
    "file": "c5-voice-kingstreet-in1-6dc68d516.mp3",
    "duration": 2.107,
    "peak": 0.86,
    "rms": 0.096
  },
  {
    "id": "kingstreet.in2",
    "speaker": "MARA",
    "text": "Help the people still moving. The wounded go to the blue lantern. Now.",
    "voice": "af_heart",
    "speed": 1.02,
    "lang": "en-us",
    "file": "c5-voice-kingstreet-in2-bccfaf569.mp3",
    "duration": 4.123,
    "peak": 0.86,
    "rms": 0.1353
  },
  {
    "id": "kingstreet.out0",
    "speaker": "ROWAN",
    "text": "The whole city will read about this. I could make the soldiers look like monsters.",
    "voice": "am_fenrir",
    "speed": 1.03,
    "lang": "en-us",
    "file": "c5-voice-kingstreet-out0-c0257a426.mp3",
    "duration": 4.601,
    "peak": 0.86,
    "rms": 0.0915
  },
  {
    "id": "kingstreet.out1",
    "speaker": "ISAIAH",
    "text": "Write what happened. People are dead. They are not ink for your argument.",
    "voice": "am_michael",
    "speed": 1.04,
    "lang": "en-us",
    "file": "c5-voice-kingstreet-out1-e9b05b424.mp3",
    "duration": 4.66,
    "peak": 0.86,
    "rms": 0.1055
  },
  {
    "id": "kingstreet.goal0",
    "speaker": "MARA",
    "text": "The confrontation will be remembered as the Boston Massacre. Five people died, including Crispus Attucks.",
    "voice": "af_heart",
    "speed": 1.02,
    "lang": "en-us",
    "file": "c5-voice-kingstreet-goal0-a8076210c.mp3",
    "duration": 6.536,
    "peak": 0.86,
    "rms": 0.1195
  },
  {
    "id": "kingstreet.goal1",
    "speaker": "ROWAN",
    "text": "I have you. Just keep looking at the light.",
    "voice": "am_fenrir",
    "speed": 1.03,
    "lang": "en-us",
    "file": "c5-voice-kingstreet-goal1-96b1ef546.mp3",
    "duration": 2.065,
    "peak": 0.86,
    "rms": 0.1093
  },
  {
    "id": "kingstreet.goal2",
    "speaker": "ISAIAH",
    "text": "Through the side lane. Keep clear of the panic in the square.",
    "voice": "am_michael",
    "speed": 1.04,
    "lang": "en-us",
    "file": "c5-voice-kingstreet-goal2-c18c5b673.mp3",
    "duration": 3.609,
    "peak": 0.7317,
    "rms": 0.15
  },
  {
    "id": "kingstreet.goal3",
    "speaker": "MARA",
    "text": "They are breathing. Go. There is someone by the carriage.",
    "voice": "af_heart",
    "speed": 1.02,
    "lang": "en-us",
    "file": "c5-voice-kingstreet-goal3-fc1ac1c2d.mp3",
    "duration": 3.044,
    "peak": 0.86,
    "rms": 0.1101
  },
  {
    "id": "kingstreet.goal4",
    "speaker": "ROWAN",
    "text": "Nobody gets left here if we can carry them.",
    "voice": "am_fenrir",
    "speed": 1.03,
    "lang": "en-us",
    "file": "c5-voice-kingstreet-goal4-e08b84e2c.mp3",
    "duration": 2.28,
    "peak": 0.86,
    "rms": 0.1115
  },
  {
    "id": "kingstreet.goal5",
    "speaker": "ISAIAH",
    "text": "Attucks cannot be brought back. Tell their names. Tell the truth.",
    "voice": "am_michael",
    "speed": 1.04,
    "lang": "en-us",
    "file": "c5-voice-kingstreet-goal5-e9c227910.mp3",
    "duration": 3.961,
    "peak": 0.86,
    "rms": 0.1079
  },
  {
    "id": "kingstreet.hint",
    "speaker": "MARA",
    "text": "Stay away from the moving crowd. Sprint when your hands are free.",
    "voice": "af_heart",
    "speed": 1.02,
    "lang": "en-us",
    "file": "c5-voice-kingstreet-hint-1c20abec4.mp3",
    "duration": 3.448,
    "peak": 0.8168,
    "rms": 0.15
  },
  {
    "id": "tea.in0",
    "speaker": "ISAIAH",
    "text": "The Committees of Correspondence linked the towns. Outside royal government, we plan our resistance together.",
    "voice": "am_michael",
    "speed": 1.04,
    "lang": "en-us",
    "file": "c5-voice-tea-in0-ab76feffc.mp3",
    "duration": 7.046,
    "peak": 0.86,
    "rms": 0.1069
  },
  {
    "id": "tea.in1",
    "speaker": "ROWAN",
    "text": "The Tea Act makes Company tea cheaper, but the old tax remains. Buying it concedes the principle.",
    "voice": "am_fenrir",
    "speed": 1.03,
    "lang": "en-us",
    "file": "c5-voice-tea-in1-b379961da.mp3",
    "duration": 5.838,
    "peak": 0.86,
    "rms": 0.0982
  },
  {
    "id": "tea.in2",
    "speaker": "ISAIAH",
    "text": "Destroy the tea, not the ship. No harm to the crew. Stay off the lantern beams.",
    "voice": "am_michael",
    "speed": 1.04,
    "lang": "en-us",
    "file": "c5-voice-tea-in2-208ef9c31.mp3",
    "duration": 5.361,
    "peak": 0.86,
    "rms": 0.1287
  },
  {
    "id": "tea.out0",
    "speaker": "ROWAN",
    "text": "You are my brother. That does not mean I can stand where you stand.",
    "voice": "am_fenrir",
    "speed": 1.03,
    "lang": "en-us",
    "file": "c5-voice-tea-out0-65db18c57.mp3",
    "duration": 3.531,
    "peak": 0.86,
    "rms": 0.1101
  },
  {
    "id": "tea.out1",
    "speaker": "THOMAS",
    "text": "Then remember that when the next orders come.",
    "voice": "bm_fable",
    "speed": 1.04,
    "lang": "en-gb",
    "file": "c5-voice-tea-out1-9e497a759.mp3",
    "duration": 2.868,
    "peak": 0.86,
    "rms": 0.1246
  },
  {
    "id": "tea.goal0",
    "speaker": "ROWAN",
    "text": "One signal from the committees. The port cities are acting together.",
    "voice": "am_fenrir",
    "speed": 1.03,
    "lang": "en-us",
    "file": "c5-voice-tea-goal0-8b38c7f27.mp3",
    "duration": 3.775,
    "peak": 0.86,
    "rms": 0.103
  },
  {
    "id": "tea.goal1",
    "speaker": "ISAIAH",
    "text": "The East India Company gets direct sales and an advantage over our merchants. Cheap tea still carries the tax.",
    "voice": "am_michael",
    "speed": 1.04,
    "lang": "en-us",
    "file": "c5-voice-tea-goal1-2ae1cd09a.mp3",
    "duration": 7.422,
    "peak": 0.86,
    "rms": 0.0996
  },
  {
    "id": "tea.goal2",
    "speaker": "ROWAN",
    "text": "Only the tea. Leave their personal belongings.",
    "voice": "am_fenrir",
    "speed": 1.03,
    "lang": "en-us",
    "file": "c5-voice-tea-goal2-b172dbb83.mp3",
    "duration": 2.682,
    "peak": 0.86,
    "rms": 0.1054
  },
  {
    "id": "tea.goal3",
    "speaker": "ISAIAH",
    "text": "The Dartmouth, Eleanor, and Beaver. All their tea goes into the water tonight.",
    "voice": "am_michael",
    "speed": 1.04,
    "lang": "en-us",
    "file": "c5-voice-tea-goal3-5f4f495a8.mp3",
    "duration": 4.488,
    "peak": 0.86,
    "rms": 0.1073
  },
  {
    "id": "tea.goal4",
    "speaker": "THOMAS",
    "text": "Some of us remain loyal to Great Britain, Rowan. Loyalists. Does that make us your enemy now?",
    "voice": "bm_fable",
    "speed": 1.04,
    "lang": "en-gb",
    "file": "c5-voice-tea-goal4-74809ade9.mp3",
    "duration": 6.234,
    "peak": 0.86,
    "rms": 0.1323
  },
  {
    "id": "tea.hint",
    "speaker": "ISAIAH",
    "text": "Watch the lantern sweep. Wait behind a chest, then move.",
    "voice": "am_michael",
    "speed": 1.04,
    "lang": "en-us",
    "file": "c5-voice-tea-hint-3b87e239e.mp3",
    "duration": 3.669,
    "peak": 0.86,
    "rms": 0.1198
  },
  {
    "id": "harbor.in0",
    "speaker": "MARA",
    "text": "Lord North’s answer to the tea: the Coercive Acts. The port is closed until the loss is paid.",
    "voice": "af_heart",
    "speed": 1.02,
    "lang": "en-us",
    "file": "c5-voice-harbor-in0-00d0cd97d.mp3",
    "duration": 5.576,
    "peak": 0.86,
    "rms": 0.1136
  },
  {
    "id": "harbor.in1",
    "speaker": "ISAIAH",
    "text": "No trade means no wages. Other colonies are sending relief. We bring it in through the shallows.",
    "voice": "am_michael",
    "speed": 1.04,
    "lang": "en-us",
    "file": "c5-voice-harbor-in1-1c058ae4e.mp3",
    "duration": 6.51,
    "peak": 0.86,
    "rms": 0.0971
  },
  {
    "id": "harbor.in2",
    "speaker": "ROWAN",
    "text": "If they mean to leave Boston alone, let us disappoint them.",
    "voice": "am_fenrir",
    "speed": 1.03,
    "lang": "en-us",
    "file": "c5-voice-harbor-in2-5bf43e1cb.mp3",
    "duration": 3.201,
    "peak": 0.86,
    "rms": 0.1023
  },
  {
    "id": "harbor.out0",
    "speaker": "ISAIAH",
    "text": "Thomas passed me an order. They are coming for the dispatches at the press.",
    "voice": "am_michael",
    "speed": 1.04,
    "lang": "en-us",
    "file": "c5-voice-harbor-out0-c33efd2dd.mp3",
    "duration": 4.462,
    "peak": 0.7791,
    "rms": 0.1477
  },
  {
    "id": "harbor.out1",
    "speaker": "MARA",
    "text": "Then we move them tonight. Every town is waiting.",
    "voice": "af_heart",
    "speed": 1.02,
    "lang": "en-us",
    "file": "c5-voice-harbor-out1-bd240ca39.mp3",
    "duration": 2.654,
    "peak": 0.86,
    "rms": 0.1363
  },
  {
    "id": "harbor.event0",
    "speaker": "MARA",
    "text": "The Port Act closes the harbor. The Government Act tightens crown control. Two of the four Coercive Acts.",
    "voice": "af_heart",
    "speed": 1.02,
    "lang": "en-us",
    "file": "c5-voice-harbor-event0-d2eadf326.mp3",
    "duration": 6.297,
    "peak": 0.86,
    "rms": 0.0908
  },
  {
    "id": "harbor.event1",
    "speaker": "ISAIAH",
    "text": "The Justice Act allows officials’ trials to leave Massachusetts. The Quartering Act expands troop housing. Four punishments in all.",
    "voice": "am_michael",
    "speed": 1.04,
    "lang": "en-us",
    "file": "c5-voice-harbor-event1-58b957a2e.mp3",
    "duration": 8.542,
    "peak": 0.86,
    "rms": 0.1011
  },
  {
    "id": "harbor.event2",
    "speaker": "ROWAN",
    "text": "Patriots call the Coercive Acts, together with the Quebec Act, the Intolerable Acts.",
    "voice": "am_fenrir",
    "speed": 1.03,
    "lang": "en-us",
    "file": "c5-voice-harbor-event2-bab176ac1.mp3",
    "duration": 4.996,
    "peak": 0.86,
    "rms": 0.1158
  },
  {
    "id": "harbor.event3",
    "speaker": "MARA",
    "text": "They meant to isolate Massachusetts. Instead, more colonies are sending help.",
    "voice": "af_heart",
    "speed": 1.02,
    "lang": "en-us",
    "file": "c5-voice-harbor-event3-6739cfdf3.mp3",
    "duration": 4.764,
    "peak": 0.86,
    "rms": 0.1198
  },
  {
    "id": "harbor.hint",
    "speaker": "ISAIAH",
    "text": "Low wake through the lantern beams. Full oars only in open water.",
    "voice": "am_michael",
    "speed": 1.04,
    "lang": "en-us",
    "file": "c5-voice-harbor-hint-e859d4682.mp3",
    "duration": 4.425,
    "peak": 0.86,
    "rms": 0.1222
  },
  {
    "id": "dispatch.in0",
    "speaker": "WARD",
    "text": "The press is lost. The words are not. Rowan, take the dispatch.",
    "voice": "bm_george",
    "speed": 1.01,
    "lang": "en-gb",
    "file": "c5-voice-dispatch-in0-ff988278d.mp3",
    "duration": 4.265,
    "peak": 0.8394,
    "rms": 0.15
  },
  {
    "id": "dispatch.in1",
    "speaker": "MARA",
    "text": "The Suffolk Resolves: prepare the militias. Refuse imports, exports, and consumption. Congress must hear us.",
    "voice": "af_heart",
    "speed": 1.02,
    "lang": "en-us",
    "file": "c5-voice-dispatch-in1-d8c5d7b73.mp3",
    "duration": 6.811,
    "peak": 0.86,
    "rms": 0.1051
  },
  {
    "id": "dispatch.in2",
    "speaker": "THOMAS",
    "text": "The west gate will be open for one minute. I can give you that much. Go.",
    "voice": "bm_fable",
    "speed": 1.04,
    "lang": "en-gb",
    "file": "c5-voice-dispatch-in2-2bc9643ff.mp3",
    "duration": 4.865,
    "peak": 0.86,
    "rms": 0.0614
  },
  {
    "id": "dispatch.out0",
    "speaker": "THOMAS",
    "text": "Ward surrendered. Alive. I will find where they take him. You have to keep moving.",
    "voice": "bm_fable",
    "speed": 1.04,
    "lang": "en-gb",
    "file": "c5-voice-dispatch-out0-719788d51.mp3",
    "duration": 5.649,
    "peak": 0.86,
    "rms": 0.0661
  },
  {
    "id": "dispatch.out1",
    "speaker": "MARA",
    "text": "We did not save the press. We saved what it was for.",
    "voice": "af_heart",
    "speed": 1.02,
    "lang": "en-us",
    "file": "c5-voice-dispatch-out1-de673cc3d.mp3",
    "duration": 2.972,
    "peak": 0.86,
    "rms": 0.1326
  },
  {
    "id": "dispatch.goal0",
    "speaker": "ROWAN",
    "text": "The Suffolk Resolves. Massachusetts’s resistance plan will help shape the First Continental Congress’s response.",
    "voice": "am_fenrir",
    "speed": 1.03,
    "lang": "en-us",
    "file": "c5-voice-dispatch-goal0-3fdfe2606.mp3",
    "duration": 6.951,
    "peak": 0.86,
    "rms": 0.1033
  },
  {
    "id": "dispatch.goal1",
    "speaker": "MARA",
    "text": "I can walk. Slowly. Save your strength for the road.",
    "voice": "af_heart",
    "speed": 1.02,
    "lang": "en-us",
    "file": "c5-voice-dispatch-goal1-745a81ad3.mp3",
    "duration": 3.247,
    "peak": 0.86,
    "rms": 0.1307
  },
  {
    "id": "dispatch.goal2",
    "speaker": "WARD",
    "text": "I am staying to draw the patrol. Keep your people together. That is the whole mission.",
    "voice": "bm_george",
    "speed": 1.01,
    "lang": "en-gb",
    "file": "c5-voice-dispatch-goal2-7b148e027.mp3",
    "duration": 5.422,
    "peak": 0.7361,
    "rms": 0.15
  },
  {
    "id": "dispatch.goal3",
    "speaker": "ROWAN",
    "text": "We are through. Isaiah, take the papers. I am going back for him.",
    "voice": "am_fenrir",
    "speed": 1.03,
    "lang": "en-us",
    "file": "c5-voice-dispatch-goal3-147b7b6ab.mp3",
    "duration": 3.964,
    "peak": 0.86,
    "rms": 0.1078
  },
  {
    "id": "dispatch.hint",
    "speaker": "WARD",
    "text": "Do not stand in the open. Breathe behind cover; then push.",
    "voice": "bm_george",
    "speed": 1.01,
    "lang": "en-gb",
    "file": "c5-voice-dispatch-hint-18bff9904.mp3",
    "duration": 4.06,
    "peak": 0.7842,
    "rms": 0.15
  },
  {
    "id": "retry",
    "speaker": "WARD",
    "text": "Take a breath. Remember the cover. We try again from the last checkpoint.",
    "voice": "bm_george",
    "speed": 1.01,
    "lang": "en-gb",
    "file": "c5-voice-retry-456432c22.mp3",
    "duration": 4.577,
    "peak": 0.7487,
    "rms": 0.15
  }
];
