import {CHAPTER5,CAST,TERMS,PROLOGUE,EPILOGUE,quizDeck} from './c5-data.mjs?v=3.2';
import {freshMission,freshBoard,tickField,tickBoard,snapshot,boardSnapshot,nearGoal,STATIONS,clamp,angleDelta} from './c5-sim.mjs?v=3.0.1';
import {CampaignWorld} from './c5-world.mjs?v=3.2';
import {CampaignBoard} from './c5-board.mjs';
import {DialogueDirector} from './dialogue.mjs';
import {MusicDirector} from './music.mjs';
import {SCORE} from './score.mjs';
import {C5_VOICES} from './c5-voices.mjs?v=3.2';
import {CINEMATICS,sceneKey,FilmClock} from './c5-cinema-plan.mjs?v=3.2';
const voiceIndex=new Map(C5_VOICES.map(v=>[v.id,v]));
let settleTime=0;
const $=id=>document.getElementById(id),ui=$('ui'),view=$('scene3d'),canvas=$('scene2d');
const esc=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const button=(text,action,cls='primary',attrs='')=>`<button class="${cls}" data-action="${action}" ${attrs}>${text}</button>`;
const KEY='dc-us-history-chapter5-v1';let storageOK=true;
let saved={started:false,mission:0,finished:false,completed:[],terms:[],checkpoint:null,bestQuiz:0,sound:true,music:true,voices:true,subtitles:true,musicVolume:.55,voiceVolume:.95,effectsVolume:.65,sensitivity:1,difficulty:'normal'};
try{const old=JSON.parse(localStorage.getItem(KEY));if(old&&Number.isInteger(old.mission)&&old.mission>=0&&old.mission<7&&Array.isArray(old.completed)&&Array.isArray(old.terms))saved={...saved,...old};}catch{storageOK=false;}
const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(saved));}catch{storageOK=false;}};
let state='menu',pausedFrom='playing',world=null,worldError=false,board=new CampaignBoard(canvas),model=null,index=0,movie=null,keys={},fire=false,aim=false,hadLock=false,last=performance.now(),lastHUD=0,toastEnd=0,checkpointEnd=0,hitEnd=0,hinted=false,quiz=null,archiveTab='terms',settingsBack='menu',audio=null,fxBus=null,voiceActive=false,previewBefore=null;
const coarse=matchMedia('(pointer:coarse)').matches,reduced=matchMedia('(prefers-reduced-motion:reduce)').matches;
const music=new MusicDirector({tracks:SCORE,onStatus(s){document.body.dataset.music=s.id||'';document.body.dataset.musicState=s.state;document.body.dataset.musicDucked=String(s.ducked);const label=$('score-label');if(label)label.textContent=s.state==='paused'?'Score paused with the scene':s.state==='muted'?'Music is off':s.state==='unavailable'?'Score unavailable; gameplay continues':'Score · '+s.title;}});
const dialogue=new DialogueDirector({media:$('dialogue-audio'),lines:C5_VOICES,
 onCaption(line){$('subtitle').innerHTML=line?`<b>${esc(CAST[line.speaker]?.name||line.speaker)}</b>${esc(line.text)}`:'';$('subtitle').classList.toggle('visible',!!line);},
 onActivity(active){voiceActive=active;music.duck(active);mixFX();},onLast(line){$('dialogue-audio').dataset.clip=line.id;}
});
function mixFX(){if(audio&&fxBus)fxBus.gain.setTargetAtTime(saved.sound?saved.effectsVolume*.25*(voiceActive?.3:1):0,audio.currentTime,.08);}
function configure(){music.configure({enabled:saved.sound&&saved.music,volume:saved.musicVolume});dialogue.configure({enabled:saved.sound&&saved.voices,volume:saved.voiceVolume,subtitles:saved.subtitles});mixFX();}
function sound(kind){if(!saved.sound)return;try{if(!audio){audio=new(window.AudioContext||window.webkitAudioContext)();fxBus=audio.createGain();fxBus.connect(audio.destination);mixFX();}if(audio.state==='suspended')audio.resume();const now=audio.currentTime;
 if(['shot','hit','hurt','stone','dash'].includes(kind)){const length=kind==='shot'?.4:.17,buf=audio.createBuffer(1,Math.ceil(audio.sampleRate*length),audio.sampleRate),d=buf.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1)*Math.pow(1-i/d.length,3);const n=audio.createBufferSource(),f=audio.createBiquadFilter();n.buffer=buf;f.type='lowpass';f.frequency.value=kind==='shot'?1350:kind==='hurt'?650:400;n.connect(f);f.connect(fxBus);n.start();}
 else{const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.setValueAtTime(kind==='goal'?620:460,now);o.frequency.exponentialRampToValueAtTime(kind==='goal'?930:680,now+.18);g.gain.setValueAtTime(.16,now);g.gain.exponentialRampToValueAtTime(.001,now+.35);o.connect(g);g.connect(fxBus);o.start();o.stop(now+.4);}}catch{}}
function cue(id,options={}){dialogue.say(id,{priority:1,ttl:Infinity,...options});}
function setState(next){state=next;document.body.dataset.gameState=state;document.body.classList.toggle('cinematic',['cut','settle'].includes(state));document.body.classList.toggle('touch-play',coarse&&state==='playing');}
function resetInputs(){keys={};fire=false;aim=false;hadLock=false;if(document.pointerLockElement)document.exitPointerLock();}
function hideGame(){resetInputs();$('hud').hidden=true;$('cinema').hidden=true;view.style.display=canvas.style.display='none';dialogue.stop();document.body.classList.remove('cinematic','touch-play');}
function shell(content,narrow=false){ui.innerHTML=`<section class="panel"><div class="panel-inner ${narrow?'narrow':''}">${content}</div></section>`;}
function home(){hideGame();setState('menu');music.select('menu');music.resume();ui.innerHTML=`<section class="menu"><header class="topline"><a class="brand" href="./">DC <i>/</i> US HISTORY</a><nav class="nav">${button('CHAPTERS','chapters','ghost')}${button('SETTINGS','settings','ghost')}</nav></header><div class="hero"><p class="overline">Chapter 05 · 1763–1774</p><h1>THE LAST<br><span>DISPATCH</span></h1><p class="lede">A printer. A divided family.<br>A city on the edge of revolution.<br>Carry the story out.</p><div class="row">${button(saved.started&&!saved.finished?'Continue story →':'Begin story →','campaign')}${button('Missions','missions','secondary')}</div><div class="moodline"><span>7 PLAYABLE MISSIONS</span><span>A VOICED STORY</span><span>ONE CREW</span></div>${!storageOK?'<p class="save-warning">Saving is unavailable in this browser.</p>':''}</div><footer class="menu-foot"><span>A FICTIONAL STORY THROUGH REAL HISTORY</span><div class="row">${button('Dispatch archive','archive','ghost')}${button('5-term practice','quiz','ghost')}</div></footer></section>`;}
function chapters(){hideGame();setState('chapters');music.select('menu');music.resume();shell(`<p class="overline">DC / US History</p><h1>Choose your chapter.</h1><div class="chapter-grid"><a class="chapter-card" href="chapter4.html"><div><p class="overline">Chapter 04 · 1676–1763</p><h2>Crown & Current</h2><p>Seven missions through the making of an empire.</p><span>Play Chapter 4 →</span></div></a><button class="chapter-card" data-action="home"><div><p class="overline">Chapter 05 · 1763–1774</p><h2>The Last Dispatch</h2><p>A courier crew on the road to revolution.</p><span>Play Chapter 5 →</span></div></button></div>${button('Back','home','ghost')}`);}
function missions(){hideGame();setState('missions');music.select('menu');music.resume();shell(`<p class="overline">The Last Dispatch</p><h1>Every road leads here.</h1><p class="muted">Play the story in order, or revisit any mission.</p><div class="mission-list">${CHAPTER5.map((m,i)=>button(`<b>${String(i+1).padStart(2,'0')}</b><span><strong>${esc(m.title)}</strong><small>${esc(m.year)} · ${m.genre}</small></span>`,'mission','mission-card '+(saved.completed.includes(m.id)?'complete':''),`data-index="${i}"`)).join('')}</div><div class="row">${button('Back','home','ghost')}${button('Story scenes','scenes','ghost')}</div>`);}
function ensureWorld(m,s){try{world??=new CampaignWorld(view);world.load(m,s);world.resize();worldError=false;return true;}catch(error){worldError=true;console.warn('3D renderer unavailable',error);return false;}}
function scenes(){
 hideGame();setState('scenes');music.select('menu');music.resume();shell(`<p class="overline">The Last Dispatch · screening room</p><h1>The story, in scenes.</h1><p class="muted">Replay any scene. Includes endings. Your campaign progress stays saved.</p><div class="mission-list">${Object.entries(CINEMATICS).map(([key,s],i)=>button(`<b>${String(i+1).padStart(2,'0')}</b><span><strong>${esc(s.title)}</strong><small>${key==='prologue'?'OPENING':key==='epilogue'?'EPILOGUE':key.endsWith('.in')?'MISSION '+(s.mission+1)+' · BEFORE':'MISSION '+(s.mission+1)+' · AFTER'}</small></span>`,'scene','mission-card',`data-scene="${key}"`)).join('')}</div>${button('Back','missions','ghost')}`);
}
function playScene(key){
 const spec=CINEMATICS[key];if(!spec)return;index=spec.mission;const m=CHAPTER5[index];ensureWorld(m,freshMission(index));music.select(key==='prologue'?'debt':key==='epilogue'?'menu':m.music);configure();
 const ids=C5_VOICES.filter(v=>sceneKey(v.id)===key&&(v.id.startsWith('prologue')||v.id.startsWith('epilogue')||/\.(in|out)\d+$/.test(v.id))).map(v=>v.id);
 cinema(ids,scenes,{title:spec.title,year:key==='epilogue'?'PHILADELPHIA · 1774':m.place.toUpperCase()+' · '+m.year});
}
function cinema(ids,after,{title=CHAPTER5[index].title,year=CHAPTER5[index].place+' · '+CHAPTER5[index].year}={}){
 dialogue.stop();resetInputs();setState('cut');$('hud').hidden=true;$('cinema').hidden=false;canvas.style.display='none';view.style.display=world&&!worldError?'block':'none';ui.innerHTML='';
 $('film-title').textContent=title;$('film-year').textContent=year;movie=new FilmClock(ids);movie.after=after;music.resume();nextBeat(false);
}
function nextBeat(advance=true){
 if(!movie)return;if(advance){dialogue.stop();movie.advance();}
 if(movie.at>=movie.ids.length){const done=movie.after;movie=null;$('cinema').hidden=true;done();return;}
 $('film-progress').innerHTML=movie.ids.map((_,i)=>`<i class="${i<=movie.at?'active':''}"></i>`).join('');
}
function filmFrame(clock,dt){
 const line=voiceIndex.get(clock.ids[clock.at]);if(!line)return;
 $('cinema').classList.toggle('show-title',clock.at===0&&clock.time<3.2);
 if(worldError)return;
 const result=world?.cinematic({key:sceneKey(clock.ids[0]),beat:clock.at,time:clock.time,lineTime:clock.lineTime,duration:line.duration,speaker:line.speaker,speaking:clock.started&&dialogue.current?.line.id===line.id&&dialogue.current.state!=='loading',reduced},dt);
 view.dataset.scene=sceneKey(clock.ids[0]);view.dataset.shot=result?.shot||'';view.dataset.beat=String(clock.at);view.dataset.renderMs=(result?.renderMs||0).toFixed(1);
}
function filmSound(id){
 const key=sceneKey(id),beat=Number(id.match(/(\d+)$/)?.[1]||0);let type=null;
 if(key==='kingstreet.in'&&beat===1)type='distant-shot';else if(key.startsWith('harbor'))type='water';else if((key==='prologue'||key==='dispatch.in')&&beat===0)type='fire';else if(key.startsWith('ink')||key==='epilogue')type='paper';else if(key==='homespun.in')type='wood';
 if(!type||!saved.sound)return;
 try{if(!audio){audio=new(window.AudioContext||window.webkitAudioContext)();fxBus=audio.createGain();fxBus.connect(audio.destination);mixFX();}audio.resume();const length=type==='fire'?1.3:type==='water'?1.1:type==='distant-shot'?.8:.28,buf=audio.createBuffer(1,Math.ceil(audio.sampleRate*length),audio.sampleRate),d=buf.getChannelData(0);for(let i=0;i<d.length;i++){const p=i/d.length;d[i]=(Math.random()*2-1)*Math.pow(1-p,2)*(type==='paper'?.13:type==='water'?.22:type==='fire'?.18:.40);if(type==='wood')d[i]+=Math.sin(i*.06)*Math.exp(-p*14)*.3;}const src=audio.createBufferSource(),filter=audio.createBiquadFilter();src.buffer=buf;filter.type=type==='paper'?'highpass':'lowpass';filter.frequency.value=type==='distant-shot'?440:type==='water'?380:1200;src.connect(filter);filter.connect(fxBus);src.start();}catch{}
}
function skipScene(){if(state==='settle'){dialogue.stop();outro();return;}if(!movie)return;const done=movie.after;movie=null;dialogue.stop();$('cinema').hidden=true;done();}
function campaign(){
 if(saved.started&&!saved.finished){launch(saved.mission,!!saved.checkpoint);return;}
 saved.started=true;saved.finished=false;saved.mission=0;saved.checkpoint=null;save();index=6;const s=freshMission(6,saved.difficulty);ensureWorld(CHAPTER5[6],s);music.select('debt');cinema(PROLOGUE.map((_,i)=>'prologue.'+i),()=>launch(0),{title:'Before the last light',year:'BOSTON · SEPTEMBER 1774'});
}
function launch(i,checkpoint=false,skip=false){
 hideGame();index=i;saved.started=true;saved.mission=i;if(!checkpoint)saved.checkpoint=null;save();hinted=false;const m=CHAPTER5[i];
 model=['workshop','boat'].includes(m.mode)?freshBoard(i,saved.difficulty,checkpoint?saved.checkpoint:null):freshMission(i,saved.difficulty,checkpoint?saved.checkpoint:null);
 ensureWorld(m,['workshop','boat'].includes(m.mode)?freshMission(i):model);music.select(m.music);music.resume();configure();
 if(checkpoint||skip)beginPlay();else cinema(m.intro.map((_,j)=>m.id+'.in'+j),ready,{title:m.title,year:m.place.toUpperCase()+' · '+m.year});
}
function instructions(m){return ['workshop','boat'].includes(m.mode)?m.mode==='workshop'?'WASD / arrows move · Hold E at the lit station · Space dash · P pause':'WASD / arrows steer · Shift fast oars · C low wake hides from beams · Return relief to the bottom dock':'WASD move · Mouse / arrows look · Hold E to interact · Shift sprint · C crouch · Space jump · '+(m.armed?'Click / F fire':'Click / F throw stone')+' · P pause';}
function ready(){
 setState('ready');view.style.display='none';const m=CHAPTER5[index];shell(`<p class="overline">${m.place} · ${m.year}</p><h1>${esc(m.title)}</h1><p class="end-copy">${m.mode==='workshop'?'Keep the workshop moving. Make and deliver four bundles of homespun.':m.mode==='boat'?'Bring four relief crates home. Avoid patrol lanterns; low wake keeps you hidden.':esc(m.goals[model.stage].label)+'.'}</p><p class="muted small" style="max-width:590px;margin:24px 0">${instructions(m)}</p><div class="row">${button('Enter mission →','enter')}${button('Replay scene','replay-intro','ghost')}${button('Back','home','ghost')}</div>`);
}
function beginPlay(){
 const m=CHAPTER5[index];if(worldError&&!['boat','workshop'].includes(m.mode)){shell(`<p class="overline">Graphics unavailable</p><h1>We need a different route.</h1><p class="muted">This browser could not start WebGL. The workshop and harbor missions still work.</p>${button('Choose a mission','missions')}${button('Try again','retry','secondary')}`);setState('error');return;}
 dialogue.reset();music.resume();setState('playing');ui.innerHTML='';$('cinema').hidden=true;$('hud').hidden=false;resetInputs();last=performance.now();lastHUD=0;checkpointEnd=0;toastEnd=0;
 const flat=['workshop','boat'].includes(m.mode);canvas.style.display=flat?'block':'none';view.style.display=flat?'none':'block';$('crosshair').hidden=flat||m.mode==='rescue';board.resize();$('instruction').textContent=instructions(m);updateHUD();if(flat){board.draw(model);canvas.focus();}else{world.render(model,{},0);view.focus();if(!coarse)tryLock();}sound('collect');
}
function tryLock(){try{view.requestPointerLock?.()?.catch?.(()=>{});}catch{}}
function pause(){if(!['playing','cut','settle'].includes(state))return;pausedFrom=state;dialogue.pause();music.pause();resetInputs();setState('paused');$('hud').hidden=true;$('cinema').hidden=true;shell(`<p class="overline">${CHAPTER5[index].title}</p><h1>Hold the line.</h1><div class="row">${button('Resume →','resume')}${button(pausedFrom==='cut'?'Restart scene':'Restart checkpoint','retry','secondary')}${button('Audio & settings','settings','ghost')}${button('Archive','archive','ghost')}${button('Main menu','home','ghost')}</div><p class="muted small" style="margin-top:25px">${instructions(CHAPTER5[index])}</p>`,true);}
function resume(){ui.innerHTML='';setState(pausedFrom);$('hud').hidden=state!=='playing';music.resume();dialogue.resume();last=performance.now();$('cinema').hidden=!['cut','settle'].includes(state);if(state==='playing'&&!['workshop','boat'].includes(CHAPTER5[index].mode)){view.focus();if(!coarse)tryLock();}}
function unlockTerms(ids){for(const id of ids)if(!saved.terms.includes(id))saved.terms.push(id);if(ids.length){$('term-toast').innerHTML=`DISPATCH RECORDED<b>${ids.map(id=>esc(TERMS.find(t=>t.id===id)?.term||id)).join(' · ')}</b>`;toastEnd=model.time+4;}save();}
function events(){
 const m=CHAPTER5[index];for(const e of model.events.splice(0)){
  if(e.type==='goal'){unlockTerms(e.terms);cue(m.id+(['workshop','boat'].includes(m.mode)?'.event':'.goal')+e.stage);sound('goal');}
  else if(e.type==='checkpoint'){saved.checkpoint=model.checkpoint;save();checkpointEnd=model.time+3;}
  else{sound(e.type);if(e.type==='hit')hitEnd=model.time+.2;}
 }
}
function finish(){
 if(!saved.completed.includes(CHAPTER5[index].id))saved.completed.push(CHAPTER5[index].id);saved.checkpoint=null;if(index<6)saved.mission=index+1;save();resetInputs();settleTime=0;setState('settle');$('hud').hidden=true;$('cinema').hidden=false;canvas.style.display='none';view.style.display=worldError?'none':'block';$('film-title').textContent=CHAPTER5[index].title;$('film-year').textContent='DISPATCH COMPLETE';$('film-progress').innerHTML='';music.select(index===6?'debt':'menu');
}
function outro(){cinema(CHAPTER5[index].outro.map((_,i)=>CHAPTER5[index].id+'.out'+i),()=>{
 if(index===6){music.select('menu');cinema(EPILOGUE.map((_,i)=>'epilogue.'+i),ending,{title:'The road ahead',year:'PHILADELPHIA · 1774'});}
 else{setState('complete');view.style.display='none';shell(`<p class="overline">Mission ${String(index+1).padStart(2,'0')} complete</p><h1>${index===3?'Carry their names.':'The dispatch continues.'}</h1><p class="muted">Next: ${esc(CHAPTER5[index+1].title)} · ${CHAPTER5[index+1].year}</p><div class="row">${button('Continue story →','next-mission')}${button('Mission select','missions','ghost')}${button('Main menu','home','ghost')}</div>`,true);}
 });}
function fail(){dialogue.stop();music.pause();resetInputs();setState('failed');shell(`<p class="overline">${CHAPTER5[index].title}</p><h1>Not the end.</h1><p class="end-copy">${model.mission.mode==='workshop'?'Time ran out. Dash between stations and hold E only when you reach the lit circle.':model.mission.mode==='boat'?'The patrol caught your wake. Hold C to pass quietly through the beams; use open water for speed.':model.mission.mode==='rescue'?'The crowd closed in. Take the side lanes and follow the blue lantern back to shelter.':'Use cover while you reload. Break the patrol’s sightline, recover, and move again.'}</p><div class="row">${button('Restart checkpoint →','retry')}${button('Try Story difficulty','story','secondary')}${button('Mission select','missions','ghost')}</div>`,true);}
function ending(){saved.finished=true;saved.mission=6;saved.checkpoint=null;save();hideGame();setState('ending');music.select('menu');music.resume();shell(`<p class="overline">The Last Dispatch · End of Chapter 5</p><h1>Every letter<br>is a beginning.</h1><p class="end-copy">The road to revolution was built from choices: what to buy, whom to trust, whose rights to defend. Rowan’s crew has carried its part of the story.</p><p class="muted">${saved.terms.length} / 15 Chapter 5 terms encountered.</p><div class="row">${button('5-term practice →','quiz')}${button('Replay missions','missions','secondary')}${button('The crew & history','archive','ghost')}${button('Chapters','chapters','ghost')}</div>`,true);}
function updateHUD(){if(!model)return;const m=CHAPTER5[index],flat=['workshop','boat'].includes(m.mode),p=model.player;$('era').textContent=m.place.toUpperCase()+' · '+m.year;$('audio-toggle').textContent=saved.sound?'SOUND ON':'SOUND OFF';
 $('health').textContent=flat?m.mode==='workshop'?Math.max(0,Math.ceil(model.timeLeft)):Math.ceil(model.hp):Math.ceil(p.hp);$('health-bar').style.width=clamp(flat?m.mode==='workshop'?model.timeLeft/160*100:model.hp:p.hp,0,100)+'%';$('stamina-bar').style.width=(flat?100:p.stamina)+'%';
 if(flat){$('objective').textContent=m.mode==='workshop'?['Pick up flax','Spin the flax into yarn','Weave the yarn into cloth','Deliver the homespun cloth'][model.carrying]:model.cargo?'Bring the relief back to the dock':'Collect the next relief crate';$('step').textContent=`${model.delivered} / 4 ${m.mode==='workshop'?'bundles delivered':'relief runs'}`;$('compass').textContent='';$('loadout').innerHTML=m.mode==='workshop'?`<strong>${model.cool>0?'…':'READY'}</strong>SPACE · DASH`:`<strong>${model.cargo?'RELIEF':'EMPTY'}</strong>C · LOW WAKE`;
  const station=m.mode==='workshop'?STATIONS[model.carrying]:null;const near=station&&Math.hypot(p.x-station.x,p.z-station.z)<72;$('prompt').innerHTML=near?`<kbd>E</kbd> HOLD · ${station.label}<i class="interact-meter" style="width:${Math.min(100,model.hold/1.05*100)}%"></i>`:'';
 }else{const g=m.goals[model.stage];$('objective').textContent=g?.label||'Dispatch complete';$('step').textContent=`${Math.min(model.stage+1,m.goals.length)} / ${m.goals.length}`;
  if(g){const a=Math.atan2(-(g.x-p.x),-(g.z-p.z)),delta=angleDelta(a,p.yaw);$('compass').textContent=`${Math.abs(delta)<.22?'◆':delta<0?'→':'←'} ${Math.round(Math.hypot(g.x-p.x,g.z-p.z))} m`;}
  $('prompt').innerHTML=nearGoal(model)?`<kbd>E</kbd> HOLD · ${esc(g.label)}<i class="interact-meter" style="width:${Math.min(100,model.hold/g.hold*100)}%"></i>`:'';
  const seen=Math.max(0,...model.enemies.map(e=>e.alert));$('loadout').innerHTML=m.armed?`<strong>${model.reload>0?'RELOADING':model.round+' / ∞'}</strong>FLINTLOCK · F / CLICK`:m.mode==='rescue'?`<strong>${model.carrying?'CARRYING':'HANDS FREE'}</strong>GET THEM TO SHELTER`:`<strong>${seen>.7?'SPOTTED':seen>.2?'CAUTION':'HIDDEN'}</strong>${model.cool>0?'DISTRACTION RECHARGING':'F / CLICK · DISTRACT'}`;
 }
 $('damage').style.opacity=model.hurt>0?'1':'0';$('crosshair').classList.toggle('hit',model.time<hitEnd);$('checkpoint').classList.toggle('visible',model.time<checkpointEnd);$('term-toast').hidden=model.time>=toastEnd;$('instruction').hidden=model.time>15;
}
function settings(){
 settingsBack=state==='paused'?'paused':settingsBack==='paused'&&state==='settings'?'paused':'menu';setState('settings');
 const slider=(id,label,value,max=100)=>`<div class="setting"><label for="${id}">${label}</label><input id="${id}" type="range" min="0" max="${max}" step="5" value="${Math.round(value*100)}"><output id="${id}-out">${Math.round(value*100)}%</output></div>`;
 shell(`<p class="overline">Settings</p><h1>Your way through.</h1><div class="row"><label for="difficulty">Difficulty</label><select id="difficulty"><option value="normal" ${saved.difficulty==='normal'?'selected':''}>Standard</option><option value="story" ${saved.difficulty==='story'?'selected':''}>Story · gentler damage & timers</option></select></div><div class="toggles">${[['sound','All sound'],['music','Music'],['voices','Voices'],['subtitles','Subtitles']].map(([k,v])=>button(v+': '+(saved[k]?'on':'off'),'toggle','',`data-setting="${k}" aria-pressed="${saved[k]}"`)).join('')}</div><div class="settings-grid">${slider('musicVolume','Music volume',saved.musicVolume)}${slider('voiceVolume','Voice volume',saved.voiceVolume)}${slider('effectsVolume','Effects volume',saved.effectsVolume)}${slider('sensitivity','Look sensitivity',saved.sensitivity,200)}</div><p id="score-label" class="muted small"></p><p class="muted small">Music softens during dialogue. Progress and preferences stay in this browser.</p><div class="row">${button('Back','settings-back')}${button('Test voice','test-voice','ghost')}${button('Stop preview','stop-voice','ghost')}</div>`,true);music.report();
}
function archive(){if(state==='paused')settingsBack='paused';else if(state!=='archive')settingsBack='menu';setState('archive');let content='';
 if(archiveTab==='terms')content=`<p class="muted small">All 15 supplied Chapter 5 terms. ${saved.terms.length} encountered in the story. The Chapter 1–5 test includes earlier chapters too; this practice covers Chapter 5 only.</p><div class="archive-grid">${TERMS.map(t=>`<article class="term-entry"><h3>${saved.terms.includes(t.id)?'◆ ':''}${esc(t.term)}</h3><p>${esc(t.definition)}</p><p class="memory">${esc(t.memory)}</p></article>`).join('')}</div>`;
 if(archiveTab==='crew')content=`<p class="muted small">The cast and personal story are fictional. Their choices take place within the documented history of 1763–1774.</p>${Object.values(CAST).map(c=>`<article class="cast-entry"><h3>${c.name}</h3><p class="role">${c.role}</p><p>${c.bio}</p></article>`).join('')}`;
 if(archiveTab==='history')content=`<div class="sources"><div class="term-entry"><h3>A story, not a reenactment</h3><p>Rowan, the crew, their rescues, road thieves, the printshop raid, and armed encounters are fictional. Levels compress distance and time. The Boston Massacre was March 5, 1770, before the War for Independence began in 1775. The supplied class text calls Crispus Attucks its first official casualty. Five people died from the confrontation; the three rescue characters here are invented bystanders, not the historical victims. Isaiah’s shoulder wound and survival are also fictional; he is not one of the five people who died.</p><p>The Tea Party took place December 16, 1773. Participants destroyed tea from three ships; this game does not depict it as a pitched battle. Some participants historically used Mohawk disguises. The game does not use those disguises.</p><p>The Coercive Acts and Quebec Act were separate legislation. Patriots grouped them under the name Intolerable Acts. The Quartering Act should not be reduced to a blanket rule letting troops take any occupied private home.</p></div><div class="term-entry"><h3>Sources & credits</h3><p>Historical facts and key-term coverage follow your supplied class list and <a href="https://openstax.org/books/us-history/pages/5-introduction" target="_blank" rel="noopener">OpenStax U.S. History, Chapter 5</a>, sections 5.1–5.5. This game does not reproduce the teacher’s actual test.</p><p>Access the textbook for free at <a href="https://openstax.org/books/us-history/pages/1-introduction" target="_blank" rel="noopener">OpenStax U.S. History</a>. The reference adaptations in this chapter are attributed to OpenStax’s authors and shared under <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank" rel="noopener">CC BY-NC-SA 4.0</a>. See C5-SOURCES.md in the repository.</p><p>Original characters, 3D geometry, script and gameplay. Three.js (MIT). Stock synthetic character voices generated locally with Kokoro-82M. Original illustrated cover generated with OpenAI ImageGen. Original instrumental score. No microphones, accounts, ads, analytics, or AI service calls during play.</p></div></div>`;
 shell(`<p class="overline">The Last Dispatch</p><div class="row" style="justify-content:space-between"><h1 style="margin:0">Dispatch archive.</h1>${button('Back','archive-back','ghost')}</div><div class="manual-tabs">${[['terms','15 key terms'],['crew','The crew'],['history','History & sources']].map(([id,label])=>button(label,'archive-tab',archiveTab===id?'active':'',`data-tab="${id}"`)).join('')}${button('Practice 5 terms','quiz','')}</div>${content}`);
}
function startQuiz(all=false){hideGame();setState('quiz');music.select('menu');music.resume();quiz={deck:quizDeck(all?15:5),at:0,answers:[]};renderQuiz();}
function renderQuiz(){const q=quiz.deck[quiz.at],answer=quiz.answers[quiz.at],term=TERMS.find(t=>t.id===q.id);shell(`<div class="row" style="justify-content:space-between"><p class="overline" style="margin:0">Chapter 5 · ${quiz.at+1} / ${quiz.deck.length}</p>${button('Exit','home','ghost')}</div><h2 class="quiz-question">${esc(q.question)}</h2>${q.options.map((o,i)=>button(`<b>${'ABCD'[i]}</b>${esc(o.text)}`,'answer','answer '+(answer!==undefined&&o.id===q.id?'correct':answer===o.id?'wrong':''),`data-answer="${o.id}" ${answer!==undefined?'disabled':''}`)).join('')}${answer!==undefined?`<div class="feedback">${esc(term.definition)}<p class="small muted" style="margin:9px 0 0">${esc(term.memory)}</p></div>${button(quiz.at===quiz.deck.length-1?'See results →':'Next →','quiz-next')}`:'<p class="muted small" style="margin-top:25px">Chapter 5 key terms only. Your Chapter 1–5 test also includes earlier material.</p>'}`,true);}
function quizResults(){const missed=quiz.deck.filter((q,i)=>q.id!==quiz.answers[i]),score=quiz.deck.length-missed.length;if(quiz.deck.length===5){saved.bestQuiz=Math.max(saved.bestQuiz,score);save();}shell(`<p class="overline">Dispatch received</p><div class="end-stat">${score} / ${quiz.deck.length}</div><div class="row">${button('Another five →','quiz')}${button('All 15 terms','all-terms','secondary')}${button('Play the story','home','ghost')}</div>${missed.length?'<h2 style="margin-top:35px;font-size:32px">Revisit these dispatches.</h2>':'<p class="muted" style="margin-top:25px">Every dispatch connected.</p>'}${missed.map(q=>{const t=TERMS.find(t=>t.id===q.id);return `<div class="review"><strong>${esc(t.term)}</strong><p>${esc(t.definition)}</p>${esc(t.memory)}</div>`;}).join('')}`,true);}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action;
 if(a==='scenes')scenes();if(a==='scene')playScene(b.dataset.scene);if(a==='home')home();if(a==='chapters')chapters();if(a==='campaign')campaign();if(a==='missions')missions();if(a==='mission')launch(Number(b.dataset.index));if(a==='enter')beginPlay();if(a==='replay-intro')launch(index);if(a==='next-mission')launch(index+1);if(a==='next-line'&&state==='cut')nextBeat();if(a==='skip-scene'&&['cut','settle'].includes(state))skipScene();if(a==='pause-cut')pause();if(a==='resume')resume();
 if(a==='retry'){if(pausedFrom==='cut'&&state==='paused'&&movie){dialogue.stop();movie.restart();resume();nextBeat(false);}else launch(index,!!saved.checkpoint,true);}if(a==='story'){saved.difficulty='story';save();launch(index,!!saved.checkpoint,true);}
 if(a==='settings')settings();if(a==='toggle'){saved[b.dataset.setting]=!saved[b.dataset.setting];save();configure();settings();music.unlock();}if(a==='settings-back'){if(previewBefore){dialogue.stop();if(previewBefore.id)cue(previewBefore.id);dialogue.pause();previewBefore=null;}if(settingsBack==='paused'){setState(pausedFrom);pause();}else home();}if(a==='test-voice'){if(!previewBefore)previewBefore={id:settingsBack==='paused'?dialogue.current?.line.id:null};dialogue.stop();cue('prologue.1');}if(a==='stop-voice'&&previewBefore)dialogue.stop();
 if(a==='archive')archive();if(a==='archive-tab'){archiveTab=b.dataset.tab;archive();}if(a==='archive-back'){if(settingsBack==='paused'){setState(pausedFrom);pause();}else home();}if(a==='quiz')startQuiz();if(a==='all-terms')startQuiz(true);if(a==='answer'&&quiz.answers[quiz.at]===undefined){quiz.answers[quiz.at]=b.dataset.answer;renderQuiz();}if(a==='quiz-next'){if(quiz.at===quiz.deck.length-1)quizResults();else{quiz.at++;renderQuiz();}}
});
document.addEventListener('input',e=>{const id=e.target.id;if(['musicVolume','voiceVolume','effectsVolume','sensitivity'].includes(id)){saved[id]=Number(e.target.value)/100;$(id+'-out').textContent=e.target.value+'%';configure();save();}});
document.addEventListener('change',e=>{if(e.target.id==='difficulty'){saved.difficulty=e.target.value;save();if(model)model.difficulty=saved.difficulty;}});
document.addEventListener('keydown',e=>{
 if(['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName))return;
 if(e.code==='Escape'||e.code==='KeyP'){if(['playing','cut','settle'].includes(state)){e.preventDefault();pause();}else if(state==='paused'&&e.code==='KeyP')resume();return;}
 if(state==='cut'&&e.code==='Space'&&!e.repeat){e.preventDefault();nextBeat();return;}
 if(state!=='playing')return;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','KeyE'].includes(e.code))e.preventDefault();keys[e.code]=true;
});document.addEventListener('keyup',e=>{keys[e.code]=false;});
function input(){const flat=['workshop','boat'].includes(CHAPTER5[index].mode);return{forward:keys.KeyW||keys.ArrowUp,back:keys.KeyS||keys.ArrowDown,left:keys.KeyA||(flat&&keys.ArrowLeft),right:keys.KeyD||(flat&&keys.ArrowRight),turn:flat?0:(keys.ArrowLeft?1:0)-(keys.ArrowRight?1:0),sprint:keys.ShiftLeft||keys.ShiftRight,crouch:keys.KeyC,interact:keys.KeyE,jump:keys.Space,fire:fire||keys.KeyF,aim};}
view.addEventListener('pointerdown',e=>{if(state!=='playing'||e.pointerType==='touch')return;if(e.button===2)aim=true;else{fire=true;if(document.pointerLockElement!==view)tryLock();}});view.addEventListener('contextmenu',e=>e.preventDefault());
document.addEventListener('pointerup',()=>{fire=false;aim=false;});document.addEventListener('pointercancel',()=>{fire=false;aim=false;});
document.addEventListener('mousemove',e=>{if(state==='playing'&&model?.player&&document.pointerLockElement===view){model.player.yaw-=e.movementX*.0021*Math.max(.15,saved.sensitivity);model.player.pitch=clamp(model.player.pitch-e.movementY*.0021*Math.max(.15,saved.sensitivity),-.8,.8);}});
let look=null;view.addEventListener('pointerdown',e=>{if(e.pointerType==='touch')look={id:e.pointerId,x:e.clientX,y:e.clientY};});view.addEventListener('pointermove',e=>{if(state!=='playing'||!look||e.pointerId!==look.id)return;model.player.yaw-=(e.clientX-look.x)*.005;model.player.pitch=clamp(model.player.pitch-(e.clientY-look.y)*.004,-.8,.8);look.x=e.clientX;look.y=e.clientY;});for(const type of ['pointerup','pointercancel'])view.addEventListener(type,()=>look=null);
document.querySelectorAll('[data-key]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys[b.dataset.key]=true;});for(const type of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(type,()=>keys[b.dataset.key]=false);});
$('pause').addEventListener('click',pause);$('audio-toggle').addEventListener('click',()=>{saved.sound=!saved.sound;save();configure();music.unlock();updateHUD();});
document.addEventListener('pointerlockchange',()=>{if(document.pointerLockElement===view)hadLock=true;else if(hadLock){hadLock=false;if(state==='playing')pause();}});
document.addEventListener('visibilitychange',()=>{music.setHidden(document.hidden);if(document.hidden){if(['playing','cut','settle'].includes(state))pause();else dialogue.pause();}else if(!['paused','settings','archive'].includes(state))dialogue.resume();});
window.addEventListener('pagehide',()=>{dialogue.stop();music.stop();});window.addEventListener('blur',()=>{keys={};fire=false;});window.addEventListener('resize',()=>{world?.resize();board.resize();});
for(const type of ['pointerdown','keydown','click'])document.addEventListener(type,()=>music.unlock(),{capture:true});
function frame(now){requestAnimationFrame(frame);const elapsed=Math.min(2,(now-last)/1000),dt=Math.min(.05,elapsed);last=now;dialogue.update(state==='cut'?elapsed:dt);
 if(state==='cut'&&movie){
  const current=dialogue.current,active=current&&current.line.id===movie.ids[movie.at]?{time:current.state==='playing'?$('dialogue-audio').currentTime:current.elapsed}:null;
  const event=movie.tick(elapsed,active);if(event==='cue'){cue(movie.ids[movie.at]);filmSound(movie.ids[movie.at]);}else if(event==='advance'){nextBeat();}
  if(movie)filmFrame(movie,dt);
 }
 else if(state==='settle'){settleTime+=dt;$('cinema').classList.remove('show-title');if(!worldError)world?.cinematic({key:CHAPTER5[index].id+'.out',time:settleTime,beat:0,lineTime:settleTime,duration:20,speaker:dialogue.current?.line.speaker,speaking:!!dialogue.current,reduced},dt);if(!dialogue.current&&!dialogue.queue.length)outro();}
 else if(state==='playing'&&model){const inp=input(),flat=['workshop','boat'].includes(model.mission.mode);if(flat)tickBoard(model,inp,dt);else tickField(model,inp,dt);events();if(flat)board.draw(model);else world.render(model,inp,dt);if(model.time-lastHUD>.08){updateHUD();lastHUD=model.time;}if(!hinted&&model.time>17){hinted=true;cue(model.mission.id+'.hint',{priority:0,ttl:5});}if(model.done)finish();else if(model.failed)fail();}
}
configure();home();requestAnimationFrame(frame);

