import test from 'node:test';
import assert from 'node:assert/strict';
import {fresh,tick,collide,currentGoal,goalNear,restore,snapshot} from './c6-sim.mjs';
import {SCENES,LEVELS,LINES,continueProgress} from './c6-data.mjs';
import {albanyOperating,albanyFighting,albanyCanUse} from './c6-albany.mjs';
import {rememberOutcome,cleanRecord} from './c6-record.mjs';
const step=(s,input={},seconds=1)=>{const events=[];for(let i=0;i<seconds/.025;i++)events.push(...tick(s,input,.025));return events;};
function walk(s,x,z){const start={x:Math.round(s.player.x),z:Math.round(s.player.z)},key=p=>p.x+','+p.z,queue=[start],parents=new Map([[key(start),null]]);let end;
 for(let i=0;i<queue.length&&i<21000;i++){const p=queue[i];if(p.x===Math.round(x)&&p.z===Math.round(z)){end=p;break;}for(const [dx,dz] of [[1,0],[-1,0],[0,1],[0,-1]]){const n={x:p.x+dx,z:p.z+dz};if(parents.has(key(n))||collide(s,n.x,n.z,.3,0))continue;parents.set(key(n),p);queue.push(n);}}
 assert.ok(end,'physical route to '+x+','+z);const path=[];while(end){path.unshift(end);end=parents.get(key(end));}
 for(const p of path)for(let i=0;i<80&&Math.hypot(p.x-s.player.x,p.z-s.player.z)>.14;i++){s.player.yaw=0;tick(s,{right:p.x-s.player.x>.1,left:p.x-s.player.x<-.1,back:p.z-s.player.z>.1,forward:p.z-s.player.z<-.1,crouch:s.armed},.025);assert.equal(s.failed,false,'alive on route');}assert.ok(Math.hypot(s.player.x-x,s.player.z-z)<.5);
}
function use(s){assert.ok(goalNear(s));assert.ok(albanyCanUse(s));return step(s,{interact:true},(currentGoal(s).time||1)+.1);}
function route(s,n){for(let i=0;i<n;i++){const g=currentGoal(s);walk(s,g.x,g.z);use(s);}}
function fight(s){const g=currentGoal(s);walk(s,g.x,g.z);for(let i=0;i<5000&&albanyFighting(s);i++)tick(s,{interact:true,crouch:true},.025);assert.equal(s.failed,false);assert.ok(!albanyFighting(s));}
test('northern road requires all three map routes, protected parley, physical timed cuts and an open civilian passage',()=>{let s=fresh('albanywoods','story');route(s,5);const g=currentGoal(s);walk(s,g.x,g.z);const events=use(s);assert.ok(events.some(e=>e.type==='albanyScene'&&e.key==='albanyParley'));assert.equal(s.stage,6);assert.ok(s.albany.parley);s=restore(snapshot(s));route(s,1);assert.ok(albanyOperating(s));for(let n=0;n<3;n++){for(let i=0;i<100&&Math.abs(s.albany.beat-.5)>.05;i++)tick(s,{},.025);tick(s,{press:true},.025);assert.equal(s.albany.cuts,n+1);s=restore(snapshot(s));}assert.ok(s.albany.fallen);step(s,{},2);assert.equal(collide(s,0,-24),true);assert.equal(collide(s,-19,-27),true);route(s,2);assert.ok(s.finished&&s.albany.passage&&s.albany.north&&s.albany.west&&s.albany.south);assert.equal(collide(s,-19,-27),false);});
test('axe strokes miss off-band, cannot work remotely, do not jump and resume without held-key extra cuts',()=>{let s=fresh('albanywoods');s.stage=7;s.albany.axe=true;s.player.x=-6;s.player.z=-22;tick(s,{press:true,jump:true},.025);assert.equal(s.albany.cuts,0);assert.equal(s.player.y,0);s.albany.beat=.48;s.player.x=0;tick(s,{press:true},.025);assert.equal(s.albany.cuts,0);s.player.x=-6;s.albany.beat=.48;tick(s,{jump:true},.025);assert.equal(s.albany.cuts,1);s=restore(snapshot(s));step(s,{jump:true,press:false},3);assert.equal(s.albany.cuts,1);step(s,{back:true},1);assert.ok(s.player.z>-19);});
test('Bemis local assault has a reachable flank, section pressure, required papers and walking exit',()=>{const s=fresh('bemis','story');route(s,2);assert.ok(s.albany.flank&&s.armed);assert.equal(s.enemies.length,9);fight(s);route(s,2);assert.ok(s.finished&&s.albany.dispatch);});
test('abandoning either closing line stops time progress and eventually fails the operation',()=>{for(const level of ['bemis','saratogaring']){const s=fresh(level);s.stage=level==='bemis'?2:3;s.player.z=28;step(s,{},12);assert.equal(s.albany.clock,0);assert.ok(s.albany.line<80);step(s,{},45);assert.equal(s.failed,true);}});
test('Isaiah sends separate river signals and physically brings the courier back to the covered relay',()=>{const s=fresh('hudsonwatch','story');route(s,3);assert.ok(s.albany.firstSignal&&s.albany.dispatch);route(s,1);assert.ok(s.carrying&&!s.armed);s.player.pitch=0;tick(s,{lookUp:true},.025);assert.ok(s.player.pitch>0);route(s,1);assert.ok(s.albany.rescued&&!s.carrying);route(s,2);assert.ok(s.finished&&s.albany.secondSignal);assert.ok(s.enemies.every(e=>e.retreat));});
test('encirclement closes a physical exit, requires holding the section and protects a white-flag packet',()=>{const s=fresh('saratogaring','story');route(s,3);assert.equal(collide(s,18,-22),true);fight(s);route(s,1);assert.ok(s.albany.ceasefire&&!s.armed);assert.ok(s.enemies.every(e=>e.retreat));route(s,1);assert.ok(s.finished&&s.albany.dispatch);});
test('all northern saves reject malformed action state and completed outcomes preserve local care',()=>{for(const level of ['albanywoods','bemis','hudsonwatch','saratogaring']){const raw=snapshot(fresh(level));assert.ok(restore(raw));for(const patch of [{cuts:4},{cuts:.5},{beat:1},{axeFlash:-1},{fall:2},{parley:1},{volley:Infinity},{ally:9}]){const bad=structuredClone(raw);Object.assign(bad.albany,patch);assert.equal(restore(bad),null);}}const saved={outcomes:{}};for(const [level,field] of [['albanywoods','passage'],['hudsonwatch','rescued'],['saratogaring','ceasefire']]){const s=fresh(level);s.finished=true;s.albany[field]=true;rememberOutcome(saved,s);}const clean=cleanRecord(saved,LEVELS,SCENES);assert.ok(clean.outcomes.albanywoods.safePassage);assert.equal(clean.outcomes.hudsonwatch.rescues,1);assert.ok(clean.outcomes.saratogaring.ceasefireHonored);});
test('Philadelphia completion continues to the dated northern campaign while Saratoga remains an installment',()=>{const old={complete:true,completedPart:'philadelphia',seen:['philadelphiaEnding']};assert.equal(continueProgress(old).scene,'albanyIntro');const done={...old,completedPart:'albany',seen:['albanySurrender']};assert.equal(continueProgress(done).scene,'winterIntro');assert.equal(SCENES.philadelphiaEnding.after,'albanyIntro');assert.equal(SCENES.albanySurrender.after,'winterIntro');assert.equal(SCENES.albanyParley.after,'checkpoint');assert.ok(SCENES.albanyRiver.place.includes('OCTOBER 8'));const text=LINES.filter(l=>/^(albany\.|bemis\.|hudson\.|ring\.)/.test(l.id)).map(l=>l.text).join(' ');for(const term of ['Germain','Lord North','Montreal','Oswego','Quebec','Ticonderoga','July','October seventeenth','Gates','five thousand','Seven Years','Oneida','Thayendanegea','my family','alliance still have to be won'])assert.ok(text.includes(term),term);});
