import test from 'node:test';
import assert from 'node:assert/strict';
import * as T from './three.module.js';
import {fresh,tick,collide,currentGoal,goalNear,restore,snapshot,angle} from './c6-sim.mjs';
import {SCENES,LINES,LEVELS,continueProgress} from './c6-data.mjs';
import {crossingCanUse,iceFloes} from './c6-crossing.mjs';
import {crossingCamera} from './c6-crossing-world.mjs';
import {cleanRecord,rememberOutcome,rememberScene,carryOutcome} from './c6-record.mjs';
const step=(s,input={},seconds=1)=>{let events=[];for(let i=0;i<seconds/.025;i++)events.push(...tick(s,input,.025));return events;};
function walk(s,x,z){const start={x:Math.round(s.player.x),z:Math.round(s.player.z)},key=p=>p.x+','+p.z,queue=[start],parent=new Map([[key(start),null]]);let found;
 for(let i=0;i<queue.length&&i<18000;i++){const p=queue[i];if(p.x===Math.round(x)&&p.z===Math.round(z)){found=p;break;}for(const [dx,dz] of [[1,0],[-1,0],[0,1],[0,-1]]){const n={x:p.x+dx,z:p.z+dz};if(parent.has(key(n))||collide(s,n.x,n.z))continue;parent.set(key(n),p);queue.push(n);}}
 assert.ok(found,'physical route to '+x+','+z);const path=[];while(found){path.unshift(found);found=parent.get(key(found));}
 for(const p of path)for(let i=0;i<75&&Math.hypot(p.x-s.player.x,p.z-s.player.z)>.14;i++){s.player.yaw=0;tick(s,{right:p.x-s.player.x>.1,left:p.x-s.player.x<-.1,back:p.z-s.player.z>.1,forward:p.z-s.player.z<-.1,crouch:s.armed},.025);assert.equal(s.failed,false,'alive on route');}assert.ok(Math.hypot(x-s.player.x,z-s.player.z)<.45);
}
function use(s){assert.ok(goalNear(s));assert.ok(crossingCanUse(s));step(s,{interact:true},(currentGoal(s).time||1)+.15);}
function sail(s,g){for(let i=0;i<32000;i++){const q=s.crossing,goal=typeof g==='function'?g():g,d=Math.hypot(q.boatX-goal.x,q.boatZ-goal.z);if(d<3.75&&q.speed<1.15)return;
  const target=Math.atan2(-(goal.x-q.boatX-q.vx*1.6),-(goal.z-q.boatZ-q.vz*1.6));let heading=target,best=Infinity;
  for(const offset of [0,-.3,.3,-.65,.65,-1.05,1.05]){const a=target+offset,px=q.boatX-Math.sin(a)*7,pz=q.boatZ-Math.cos(a)*7;const obstruction=iceFloes(q.iceTime+1).some(f=>Math.hypot(f.x-px,f.z-pz)<f.r+2.1)||collide(s,px,pz,1.5,0);const score=Math.hypot(px-goal.x,pz-goal.z)+(obstruction?80:0)+Math.abs(offset)*2;if(score<best){best=score;heading=a;}}
  const delta=angle(heading-q.boatYaw),brake=d<3.3||d<9&&q.speed>2;tick(s,{left:delta>.045,right:delta<-.045,forward:!brake&&Math.abs(delta)<.23,back:brake},.025);
 }assert.fail('ferry route failed: '+JSON.stringify(s.crossing));}
test('the Delaware can be crossed with real steering, drifting ice, equipment recovery and a slow landing',()=>{const s=fresh('delaware','story');walk(s,3,15);use(s);walk(s,0,11);use(s);assert.equal(s.crossing.aboard,true);sail(s,()=>currentGoal(s));use(s);assert.equal(s.crossing.recovered,true);assert.ok(restore(snapshot(s)));sail(s,{x:0,z:-120});use(s);assert.equal(s.finished,true);assert.equal(s.crossing.moored,true);assert.equal(s.failed,false);});
test('ice impacts are recoverable, look is independent of tiller, upward camera look remains positive, and fast landings are blocked',()=>{const s=fresh('delaware');s.stage=2;Object.assign(s.crossing,{covered:true,aboard:true,moored:false});step(s,{lookUp:true,lookLeft:true},1);assert.equal(s.crossing.boatYaw,0);assert.ok(s.player.pitch>0);step(s,{left:true},1);assert.ok(s.crossing.boatYaw>.5);const f=iceFloes(s.crossing.iceTime)[0];Object.assign(s.crossing,{boatX:f.x,boatZ:f.z,vx:2,vz:2});tick(s,{},.025);assert.ok(s.crossing.impacts>=1);assert.equal(s.failed,false);assert.ok(s.crossing.wetness>0);step(s,{back:true},3);assert.ok(s.crossing.speed<1.3);const w={camera:new T.PerspectiveCamera(),cast:{ISAIAH:{}}};w.camera.rotation.order='YXZ';s.player.pitch=0;crossingCamera(w,s,true);const low=w.camera.getWorldDirection(new T.Vector3()).y;s.player.pitch=.3;crossingCamera(w,s,true);assert.ok(w.camera.getWorldDirection(new T.Vector3()).y>low);s.stage=3;Object.assign(s.crossing,{boatX:0,boatZ:-120,speed:5});s.player.x=0;s.player.z=-120;assert.equal(crossingCanUse(s),false);});
test('Trenton requires assembly, both signals, covering participation, surrender and water',()=>{const s=fresh('trenton','story');for(let i=0;i<4;i++){const g=currentGoal(s);walk(s,g.x,g.z);if(i===3)step(s,{},6);use(s);}assert.ok(s.crossing.west&&s.crossing.east);walk(s,0,-28);for(let i=0;i<6000&&s.stage===4;i++)tick(s,{interact:true,crouch:true},.025);assert.equal(s.stage,5);assert.ok(s.enemies.every(e=>e.surrender));for(let i=5;i<8;i++){const g=currentGoal(s);walk(s,g.x,g.z);use(s);}assert.equal(s.finished,true);assert.ok(s.crossing.surrendered&&s.crossing.water);assert.equal(s.armed,false);});
test('surrendered soldiers cannot be shot or return fire',()=>{const s=fresh('trenton');s.stage=5;s.armed=true;s.enemies=[{id:0,x:0,z:-45,hp:1,yaw:0,cooldown:0,dead:0,fired:0,surrender:true}];s.player.z=-43;s.player.yaw=0;step(s,{fire:true},.05);assert.equal(s.enemies[0].hp,1);assert.equal(s.kills,0);assert.equal(s.enemies[0].fired,0);});
test('Princeton has a real flank and a complete walking extraction for Nathan',()=>{const s=fresh('princeton','story');for(let i=0;i<3;i++){const g=currentGoal(s);walk(s,g.x,g.z);use(s);}walk(s,-14,-28);for(let i=0;i<7000&&s.stage===3;i++)tick(s,{interact:true,crouch:true},.025);assert.equal(s.stage,4);for(let i=4;i<7;i++){const g=currentGoal(s);walk(s,g.x,g.z);use(s);}assert.equal(s.crossing.rescued,true);assert.equal(s.carrying,false);assert.equal(s.finished,true);});
test('storm and combat checkpoints restore mechanics and reject malformed boat state',()=>{for(const id of ['delaware','trenton','princeton']){const raw=snapshot(fresh(id));assert.ok(restore(raw));for(const patch of [{boatX:1000},{wetness:-1},{west:1},{impacts:Infinity},{crateZ:200},{speed:999}]){const bad=structuredClone(raw);Object.assign(bad.crossing,patch);assert.equal(restore(bad),null);}}const s=fresh('delaware');s.stage=2;Object.assign(s.crossing,{aboard:true,moored:false,boatX:8,boatZ:-43,wetness:.4,impacts:2});Object.assign(s.player,{x:8,z:-43});const r=restore(snapshot(s));assert.equal(r.crossing.boatZ,-43);assert.equal(r.crossing.wetness,.4);});
test('completed outcomes persist, unfinished work is excluded, and a watched scene can replace a skipped record',()=>{const saved={seen:[],skipped:[],outcomes:{}};const s=fresh('delaware');assert.equal(rememberOutcome(saved,s),false);s.finished=true;s.crossing.wetness=.3;s.crossing.impacts=2;rememberOutcome(saved,s);const n=carryOutcome(fresh('trenton'),saved);assert.equal(n.crossing.wetness,.3);rememberScene(saved,'crossingIntro',true);assert.deepEqual(saved.seen,[]);assert.deepEqual(saved.skipped,['crossingIntro']);rememberScene(saved,'crossingIntro');assert.deepEqual(saved.seen,['crossingIntro']);assert.deepEqual(saved.skipped,[]);const clean=cleanRecord({...saved,skipped:['crossingLanding','fake'],outcomes:{...saved.outcomes,fake:{completed:true},trenton:{completed:true,rescues:99,wetness:Infinity}}},LEVELS,SCENES);assert.equal(clean.outcomes.delaware.impacts,2);assert.equal(clean.outcomes.trenton.rescues,10);assert.equal(clean.outcomes.trenton.wetness,0);assert.deepEqual(clean.skipped,['crossingLanding']);});
test('New York completion migrates to the dated winter campaign and its ending remains only an installment',()=>{const old={complete:true,seen:['retreatEnding'],checkpoint:null};assert.equal(continueProgress(old).scene,'crossingIntro');const done={...old,seen:['crossingEnding']};assert.equal(continueProgress(done),done);assert.equal(SCENES.retreatEnding.after,'crossingIntro');assert.equal(SCENES.crossingLanding.after,'trenton');assert.equal(SCENES.crossingTrenton.after,'crossingPrinceton');assert.equal(SCENES.crossingEnding.after,'complete');const text=LINES.filter(l=>/^(crossing\.|trenton\.|princeton\.)/.test(l.id)).map(l=>l.text).join(' ');for(const term of ['December twenty-fifth','December twenty-sixth','January third','nine hundred','German soldiers hired','winter quarters','summer season','Princeton'])assert.ok(text.includes(term),term);});
