import test from 'node:test';import assert from 'node:assert/strict';
import {fresh,tick,collide,currentGoal,goalNear,snapshot,restore,angle} from './c6-sim.mjs';
import {chaseCanUse,chaseMounted} from './c6-chase.mjs';
import {LEVELS,SCENES,LINES,continueProgress} from './c6-data.mjs';
import {rememberOutcome,cleanRecord,carryOutcome} from './c6-record.mjs';
const step=(s,input={},sec=1)=>{const events=[];for(let i=0;i<sec/.025;i++)events.push(...tick(s,input,.025));return events;};
function walk(s,x,z){const key=p=>p.x+','+p.z,start={x:Math.round(s.player.x),z:Math.round(s.player.z)},queue=[start],parents=new Map([[key(start),null]]);let end;
 for(let i=0;i<queue.length&&i<45000;i++){const p=queue[i];if(p.x===Math.round(x)&&p.z===Math.round(z)){end=p;break;}for(const [dx,dz] of [[1,0],[-1,0],[0,1],[0,-1]]){const n={x:p.x+dx,z:p.z+dz};if(parents.has(key(n))||collide(s,n.x,n.z,.3,0))continue;parents.set(key(n),p);queue.push(n);}}assert.ok(end,'walkable '+x+','+z);const path=[];while(end){path.unshift(end);end=parents.get(key(end));}
 for(const p of path)for(let i=0;i<100&&Math.hypot(p.x-s.player.x,p.z-s.player.z)>.15;i++){s.player.yaw=0;tick(s,{right:p.x-s.player.x>.1,left:p.x-s.player.x<-.1,back:p.z-s.player.z>.1,forward:p.z-s.player.z<-.1},.025);assert.equal(s.failed,false,'survives actual walking');}assert.ok(Math.hypot(s.player.x-x,s.player.z-z)<.6,'arrived '+x+','+z);}
function use(s){assert.ok(goalNear(s),'near stage '+s.stage);assert.ok(chaseCanUse(s),'usable stage '+s.stage);const stage=s.stage;step(s,{interact:true},currentGoal(s).time+.2);assert.equal(s.stage,stage+1);}
function go(s){const g=currentGoal(s);walk(s,g.x,g.z);use(s);}
function ride(s,x,z){const q=s.chase;for(let i=0;i<10000;i++){const d=Math.hypot(x-q.horseX,z-q.horseZ);if(d<1.35&&q.speed<.6)break;const yaw=Math.atan2(-(x-q.horseX),-(z-q.horseZ)),turn=angle(yaw-q.horseYaw),steer=Math.abs(turn)>.018;tick(s,{left:steer&&turn>0,right:steer&&turn<0,forward:d>1.25&&Math.abs(turn)<.3,back:(d<5&&q.speed>.9)||d<1.25||Math.abs(turn)>.35,sprint:d>10},.025);assert.equal(s.failed,false);assert.equal(collide(s,q.horseX,q.horseZ,.64,q.hoofY),false,'horse remains outside geometry');}assert.ok(Math.hypot(x-q.horseX,z-q.horseZ)<1.5,'horse arrived '+x+','+z);assert.ok(q.speed<1.1,'braked for interaction');}
function cowpens(allDead=false){let s=carryOutcome(fresh('cowpens'),{outcomes:{drill:{formationTrained:true}}});go(s);go(s);assert.equal(s.chase.squad.length,6);if(allDead)s.enemies.forEach(e=>e.hp=0);step(s,{},3);step(s,{interact:true},.1);assert.equal(s.chase.volleys,1);step(s,{interact:true},6);assert.equal(s.chase.volleys,1,'held command does not fire twice');step(s,{},.1);step(s,{interact:true},.1);assert.equal(s.stage,3);assert.equal(s.chase.volleys,2);s=restore(snapshot(s));walk(s,0,3);for(let i=0;i<3000&&!chaseCanUse(s);i++)tick(s,{},.025);use(s);s.player.yaw=0;for(let i=0;i<3000&&!chaseCanUse(s);i++)tick(s,{},.025);use(s);walk(s,-19,-13);for(let i=0;i<2000&&Math.hypot(s.chase.squad[0].x-s.player.x,s.chase.squad[0].z-s.player.z)>9;i++)tick(s,{},.025);use(s);walk(s,0,-43);for(let i=0;i<4000&&!chaseCanUse(s);i++){const center=s.chase.squad[0];if(Math.hypot(center.x-s.player.x,center.z-s.player.z)>12)walk(s,center.x,center.z);tick(s,{},.025);}walk(s,0,-43);use(s);go(s);assert.ok(s.finished&&s.chase.roll&&s.chase.surrender&&s.chase.withdrawn&&s.chase.turned);assert.equal(s.armed,false);return s;}
test('Cowpens physically forms, fires twice, retires, turns, counterattacks and preserves surrender',()=>{const s=cowpens();const record={};rememberOutcome(record,s);const r=record.outcomes.cowpens;assert.equal(r.cowpensVolleys,2);assert.ok(r.controlledWithdrawal&&r.counterattack&&r.surrenderPreserved&&r.drillReused);assert.ok(s.enemies.some(e=>e.surrender));});
test('defeating every visible local enemy early cannot softlock army orders',()=>{cowpens(true);});
test('a remote section and wrong turn facing cannot satisfy formation gates',()=>{const s=fresh('cowpens');s.stage=3;s.chase.formed=true;s.chase.squad=Array.from({length:6},(_,i)=>({x:i,z:-34,yaw:0}));s.player.z=3;step(s,{interact:true},3);assert.equal(s.stage,3);assert.equal(chaseCanUse(s),false);s.stage=4;s.chase.armyZ=-8;s.player.yaw=Math.PI;assert.equal(chaseCanUse(s),false);});
test('both heavy and light courier loads finish through real steering, braking and bridge passage',()=>{for(const load of ['heavy','light']){let s=fresh('danrelay');go(s);walk(s,load==='heavy'?-7:7,10);use(s);go(s);assert.ok(chaseMounted(s));ride(s,-18,0);ride(s,-18,-55);use(s);s=restore(snapshot(s));ride(s,-26,-90);ride(s,-26,-118);ride(s,-22,-126);ride(s,-22,-155);use(s);ride(s,-18,-177);ride(s,16,-177);ride(s,16,-208);ride(s,0,-225);use(s);assert.ok(s.finished&&s.chase.delivered&&s.chase.packet&&s.chase.bridge);assert.ok(s.chase.pursuit&&s.chase.travel>220);assert.equal(s.chase.load,load);const record={};rememberOutcome(record,s);assert.ok(record.outcomes.danrelay.ferryOrder&&record.outcomes.danrelay.loosePacket&&record.outcomes.danrelay.raisedCrossing);assert.equal(record.outcomes.danrelay.horseLoad,load);}});
test('mounted steering leaves look independent and upward looking positive',()=>{const s=fresh('danrelay');s.stage=3;s.chase.mounted=true;s.chase.load='light';step(s,{left:true,lookUp:true},.5);assert.ok(s.chase.horseYaw>.4);assert.equal(s.player.yaw,0);assert.ok(s.player.pitch>0);step(s,{lookRight:true},.5);assert.ok(s.player.yaw<0);assert.ok(s.chase.horseYaw>.4);});
test('horse acceleration, weight, braking, stamina and recoverable obstacle contacts are bounded',()=>{const speeds=[];for(const load of ['heavy','light']){const s=fresh('danrelay');Object.assign(s.chase,{mounted:true,load,horseX:-30,horseZ:0});s.stage=3;step(s,{forward:true,sprint:true},3);speeds.push(s.chase.speed);assert.ok(s.chase.horseStamina<100);step(s,{back:true},2);assert.ok(s.chase.speed<.01);step(s,{},3);assert.ok(s.chase.horseStamina>70);}assert.ok(speeds[1]>speeds[0]+1);const s=fresh('danrelay');s.stage=3;Object.assign(s.chase,{mounted:true,load:'light',horseZ:-20});step(s,{forward:true},4);assert.ok(s.chase.impacts>0&&s.player.health>0);assert.ok(s.chase.horseZ>-26.4);});
test('jump clears the low fallen log while ordinary movement and jumping water stay blocked',()=>{const s=fresh('danrelay');s.stage=4;Object.assign(s.chase,{mounted:true,load:'light',packet:true,horseX:-16,horseZ:-102,speed:5});step(s,{forward:true,jump:true},.3);assert.ok(s.player.y>.8,'own mounted height survives generic gravity');step(s,{forward:true,jump:true},.7);assert.ok(s.chase.horseZ<-106,'low log cleared');assert.equal(s.chase.impacts,0);assert.equal(collide(s,0,-137,.65,1.1),true);assert.equal(collide(s,-22,-137,.65,0),false);assert.equal(collide(s,0,-239,.65,1.1),true);});
test('fast riding cannot take a packet or teleport to the next checkpoint',()=>{const s=fresh('danrelay');s.stage=3;Object.assign(s.chase,{mounted:true,load:'light',horseX:-18,horseZ:-55,speed:5});s.player.x=-18;s.player.z=-55;assert.equal(chaseCanUse(s),false);step(s,{forward:true,interact:true},.2);assert.equal(s.chase.packet,false);assert.equal(s.stage,3);});
test('a late or slow jump cannot leave the horse trapped inside a log on landing',()=>{for(const speed of [1,4.4]){const s=fresh('danrelay');s.stage=4;Object.assign(s.chase,{mounted:true,load:'light',packet:true,horseX:-16,horseZ:-103.2,speed});step(s,{forward:true,jump:true},1.3);assert.equal(collide(s,s.chase.horseX,s.chase.horseZ,.65,0),false);assert.equal(s.player.y,0);assert.ok(s.chase.horseZ<-106||s.chase.horseZ>-104);}});
test('malformed mounted saves are rejected and completed records remain distinct',()=>{const raw=snapshot(fresh('danrelay'));assert.ok(restore(raw));for(const patch of [{load:'teleport'},{horseX:99},{horseZ:-999},{speed:20},{hoofY:4},{horseStamina:-1},{armyZ:1},{volleys:3},{mounted:1},{squad:[{x:0,z:0,yaw:NaN}]}]){const bad=structuredClone(raw);Object.assign(bad.chase,patch);assert.equal(restore(bad),null);}const record={};const s=fresh('danrelay');s.chase.load='heavy';assert.equal(rememberOutcome(record,s),false);s.finished=true;rememberOutcome(record,s);assert.equal(cleanRecord(record,LEVELS,SCENES).outcomes.danrelay.horseLoad,'heavy');});
test('inland completion migrates to Cowpens and the scene chronology credits the actual commanders',()=>{assert.equal(continueProgress({complete:true,completedPart:'inland',seen:['inlandEnding']}).scene,'chaseIntro');const done={complete:true,completedPart:'chase',seen:['chaseEnding']};assert.equal(continueProgress(done),done);assert.equal(SCENES.inlandEnding.after,'chaseIntro');assert.equal(SCENES.chaseEnding.after,'complete');assert.match(SCENES.chaseIntro.place,/JANUARY 17, 1781/);assert.match(SCENES.chaseEnding.place,/FEBRUARY 14, 1781/);const text=LINES.filter(l=>l.id.startsWith('chase.')).map(l=>l.text).join(' ');for(const phrase of ['Morgan','Greene','Tarleton','Pickens','Howard','William Washington','misunderstood','von Steuben','burned baggage','North Carolina','Carrington','Irvin’s','Boyd’s','Virginia','Samuel'])assert.ok(text.includes(phrase),phrase);});
