// Cowpens section orders and the fictional mounted relay during the race north.
const g=(x,z,label,verb,time=1.2)=>({x,z,label,verb,time});
export const CHASE_LEVELS={
 cowpens:{title:'Make Them Chase',place:'COWPENS · JANUARY 17, 1781 · ROWAN VALE',spawn:[0,25],bounds:[-40,40,-76,34],music:'chase',mode:'ORDERED VOLLEYS / CONTROLLED WITHDRAWAL / COUNTERATTACK',intro:'chaseIntro',after:'chaseVictory',description:'Deliver Morgan’s local order, call two section volleys, withdraw in formation and turn back as the pursuing force overextends. Reach the militia flank and preserve the surrender.',goals:[g(-4,20,'Take Morgan’s local order from Ward','Take the order'),g(0,-36,'Join the militia section at the forward line','Form the section',2),g(0,-36,'Call two volleys from a clear forward line','E calls a volley when the approaching line is close',0),g(0,3,'Bring the actual section back to the Continental line','Wait for the last man',1.5),g(0,3,'Face the approaching line and give the turn order','Give the turn order',1.5),g(-19,-13,'Reach the militia’s western counterattack flank','Signal the flank'),g(0,-43,'Move the section forward to the surrender line','Honor the surrender',1.5),g(-4,-47,'Take the captured roll without firing','Take the roll',1.5)]},
 danrelay:{title:'The Road Ahead of Them',place:'NORTHBOUND RELAY ROAD · FEBRUARY 14, 1781 · A FICTIONAL LOCAL COURIER PASSAGE',spawn:[0,25],bounds:[-43,43,-248,34],music:'ride',mode:'ROWAN · HORSEBACK COURIER / WEIGHT / CROSSING',intro:'chaseRoad',after:'chaseEnding',description:'Choose the carried load, mount the relay horse and bring orders down a guarded road. Brake for the loose packet, jump the low fallen log and take the raised western bridge before the Dan landing.',goals:[g(-4,20,'Take the northbound ferry order','Take the order'),g(0,10,'Choose what the relay horse will carry','Load the horse',1.5),g(0,0,'Mount the relay horse','Mount',1.5),g(-18,-55,'Brake beside the loose dispatch packet','Secure the packet',1.5),g(-22,-155,'Bring the packet over the raised western crossing','Confirm the bridge report',1.5),g(0,-225,'Reach the ferry crew ahead of the pursuing riders','Deliver the ferry order',1.5)]},
};
export const CHASE_BLOCKS={cowpens:[[-10,-20,10,.8,1.1],[19,-35,9,.8,1.1],[-29,8,5,12,4],[29,-57,6,13,4]],danrelay:[[0,-31,14,8,1.2],[12,-78,16,8,1.2],[-16,-105,15,.7,.65],[27,-165,12,12,4],[-28,-194,9,14,4],[0,-189,11,6,1.3]]};
const dist=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z),angle=v=>Math.atan2(Math.sin(v),Math.cos(v)),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),emit=(s,type,data={})=>s.events.push({type,...data}),say=(s,id)=>emit(s,'voice',{id});
export function freshChase(){return {order:false,useHeld:false,formed:false,trainedBefore:false,armyZ:-66,squad:[],volleys:0,volley:0,withdrawn:false,turned:false,flank:false,surrender:false,roll:false,load:'',mounted:false,horseX:0,horseZ:0,horseYaw:0,speed:0,jumpAge:1,jumpStartX:0,jumpStartZ:0,jumpHeld:false,hoofY:0,horseStamina:100,travel:0,impacts:0,bump:0,packet:false,bridge:false,delivered:false,pursuit:false,riderX:20,riderZ:25,riderLeg:0,warning:0,lastShot:0};}
export function validChase(q,b){return !!q&&['order','useHeld','formed','trainedBefore','withdrawn','turned','flank','surrender','roll','mounted','jumpHeld','packet','bridge','delivered','pursuit'].every(k=>typeof q[k]==='boolean')&&['armyZ','volleys','volley','horseX','horseZ','horseYaw','speed','jumpAge','jumpStartX','jumpStartZ','hoofY','horseStamina','travel','impacts','bump','riderX','riderZ','riderLeg','warning','lastShot'].every(k=>Number.isFinite(q[k]))&&['','heavy','light'].includes(q.load)&&Number.isInteger(q.volleys)&&q.volleys>=0&&q.volleys<=2&&q.armyZ>=-70&&q.armyZ<=-8&&q.volley>=0&&q.volley<1000000&&q.speed>=0&&q.speed<=9.01&&q.jumpAge>=0&&q.jumpAge<=1&&q.hoofY>=0&&q.hoofY<=1.11&&q.horseStamina>=0&&q.horseStamina<=100&&q.travel>=0&&q.travel<1000000&&Number.isInteger(q.impacts)&&q.impacts>=0&&q.impacts<10000&&q.bump>=0&&q.bump<=2&&q.warning>=0&&q.warning<=10&&q.lastShot>=0&&q.lastShot<1000000&&Number.isInteger(q.riderLeg)&&q.riderLeg>=0&&q.riderLeg<=8&&[['horseX','horseZ'],['jumpStartX','jumpStartZ'],['riderX','riderZ']].every(([x,z])=>q[x]>=b[0]&&q[x]<=b[1]&&q[z]>=b[2]&&q[z]<=b[3])&&Array.isArray(q.squad)&&q.squad.length<=6&&q.squad.every(a=>['x','z','yaw'].every(k=>Number.isFinite(a[k]))&&a.x>=b[0]&&a.x<=b[1]&&a.z>=b[2]&&a.z<=b[3]);}
export const chaseMounted=s=>s.level==='danrelay'&&s.chase?.mounted&&!s.chase.delivered;
export const chaseOperating=s=>s.level==='cowpens'&&s.stage===2;
export const chaseFollowing=s=>s.level==='cowpens'&&s.chase?.formed&&s.stage>=3&&!s.chase.roll;
export function chaseGoal(s){const q=s.chase,g=CHASE_LEVELS[s.level].goals[s.stage];if(!g)return null;if(s.level==='danrelay'&&s.stage===1){const heavy=dist(s.player,{x:-7,z:10})<=dist(s.player,{x:7,z:10});return {...g,x:heavy?-7:7,label:heavy?'Keep the heavier cloth and tent load':'Carry food and orders; leave the extra tent canvas',verb:heavy?'Keep the heavier load':'Leave the extra canvas'};}if(s.level==='cowpens'&&[3,5,6].includes(s.stage)&&q.squad.length&&dist(s.player,q.squad[0])>10)return {...g,x:q.squad[0].x,z:q.squad[0].z,label:'Return to the moving section',verb:'Stay with the section'};return g;}
export const chaseNear=s=>!!chaseGoal(s)&&dist(s.player,chaseGoal(s))<(chaseMounted(s)?4:2.5);
export function chaseCanUse(s){const q=s.chase;if(chaseOperating(s))return false;if(chaseMounted(s)&&q.speed>1.1)return false;if(s.level==='cowpens'&&s.stage===3)return q.squad.length===6&&q.squad.every(a=>dist(a,{x:0,z:3})<5);if(s.level==='cowpens'&&s.stage===4)return Math.abs(angle(s.player.yaw))<.3&&q.armyZ>-17;if(s.level==='cowpens'&&s.stage===6)return q.surrender&&q.squad.every(a=>dist(a,{x:0,z:-43})<7);return true;}
export function chaseBlocked(s,x,z,r,feet){if(s.level==='danrelay'&&z<-235+r&&feet<3)return true;if(s.level==='danrelay'&&z<-128+r&&z>-146-r&&feet<2.5)return Math.abs(x+22)>3-r;return false;}
function next(s){s.stage++;s.hold=0;emit(s,'checkpoint');if(s.stage>=CHASE_LEVELS[s.level].goals.length){s.finished=true;emit(s,'finish');}}
export function interactChase(s){const q=s.chase,st=s.stage;if(s.level==='cowpens'){
 if(st===0){q.order=true;say(s,'chase.order');}if(st===1){q.formed=true;q.squad=Array.from({length:6},(_,i)=>({x:(i-2.5)*1.6,z:-34,yaw:0}));s.enemies=Array.from({length:10},(_,i)=>({id:i,x:(i%5-2)*4,z:-66-Math.floor(i/5)*3,hp:1,yaw:Math.PI,cooldown:4+i*.5,dead:0,fired:0,moving:false,route:[0,5]}));s.armed=true;s.ammo=18;say(s,'chase.formed');}if(st===3){q.withdrawn=true;say(s,'chase.withdrawn');}if(st===4){q.turned=true;say(s,'chase.turn');emit(s,'chaseVolley');const targets=s.enemies.filter(e=>e.hp>0&&!e.surrender).slice(0,4);targets.forEach(e=>e.hp=0);}if(st===5){q.flank=true;say(s,'chase.flank');}if(st===6){s.armed=false;say(s,'chase.ceasefire');}if(st===7){q.roll=true;say(s,'chase.roll');}
 }else{if(st===0){q.order=true;say(s,'chase.ferry.order');}if(st===1){q.load=chaseGoal(s).x<0?'heavy':'light';say(s,'chase.load.'+q.load);}if(st===2){q.mounted=true;s.armed=false;s.player.x=q.horseX;s.player.z=q.horseZ;say(s,'chase.mount');}if(st===3){q.packet=true;say(s,'chase.packet');}if(st===4){q.bridge=true;say(s,'chase.bridge');}if(st===5){q.delivered=true;q.speed=0;say(s,'chase.delivered');}}next(s);}
function approach(s,a,x,z,dt,pace,collide){const d=dist(a,{x,z}),step=Math.min(d,dt*pace),nx=a.x+(x-a.x)/(d||1)*step,nz=a.z+(z-a.z)/(d||1)*step;if(!collide(s,nx,nz,.25,0)){a.x=nx;a.z=nz;}else{if(!collide(s,nx,a.z,.25,0))a.x=nx;if(!collide(s,a.x,nz,.25,0))a.z=nz;}a.yaw=Math.atan2(-(x-a.x),-(z-a.z));}
export function moveChaseHorse(s,input,dt,collide){const q=s.chase,p=s.player;q.bump=Math.max(0,q.bump-dt);q.horseYaw=angle(q.horseYaw+(((input.left||input.leftTap)?1:0)-((input.right||input.rightTap)?1:0))*dt*(.9+q.speed*.025));const pressed=!!input.jump&&!q.jumpHeld;q.jumpHeld=!!input.jump;if(pressed&&q.jumpAge===1){q.jumpAge=0;q.jumpStartX=q.horseX;q.jumpStartZ=q.horseZ;emit(s,'horseJump');}q.jumpAge=Math.min(1,q.jumpAge+dt/1.05);q.hoofY=q.jumpAge===1?0:Math.pow(Math.sin(q.jumpAge*Math.PI),.35)*1.1;const maximum=q.load==='heavy'?6.5:9,brake=input.back,drive=input.forward;q.horseStamina=clamp(q.horseStamina+dt*(input.sprint&&drive?-16:8),0,100);const speedGoal=brake?0:drive?(input.sprint&&q.horseStamina>1?maximum:maximum*.78):0;q.speed+=(speedGoal-q.speed)*Math.min(1,dt*(brake?5:drive?1.5:.7));const nx=q.horseX-Math.sin(q.horseYaw)*q.speed*dt,nz=q.horseZ-Math.cos(q.horseYaw)*q.speed*dt;if(collide(s,nx,nz,.65,q.hoofY)){q.speed*=.15;if(q.bump===0){q.bump=1.5;q.impacts++;say(s,'chase.obstacle');emit(s,'wood');}}else{q.travel+=Math.hypot(nx-q.horseX,nz-q.horseZ);q.horseX=nx;q.horseZ=nz;}if(q.jumpAge===1&&collide(s,q.horseX,q.horseZ,.65,0)){q.horseX=q.jumpStartX;q.horseZ=q.jumpStartZ;q.speed=0;emit(s,'wood');}p.x=q.horseX;p.z=q.horseZ;p.y=q.hoofY;p.vy=0;}
export function updateChase(s,input,dt,{collide,blocked}){const q=s.chase,p=s.player,use=!!input.useTap||!!input.interact&&!q.useHeld;q.useHeld=!!input.interact;q.volley=Math.max(0,q.volley-dt);q.warning=Math.max(0,q.warning-dt);
 if(s.level==='cowpens'&&q.formed){
  q.armyZ=Math.min(s.stage<=2?-47:-8,q.armyZ+dt*(s.stage===3?1.9:1.25));
  if(s.stage===2){const near=dist(p,{x:0,z:-36})<9,aligned=Math.abs(angle(p.yaw))<.35,eligible=q.armyZ>-64&&q.armyZ<=-46;if(use&&q.volley===0&&near&&aligned&&eligible){q.volley=5;q.volleys++;emit(s,'orderUsed');emit(s,'chaseVolley');const targets=s.enemies.filter(e=>e.hp>0).slice(0,2);targets.forEach(e=>e.hp=0);say(s,'chase.volley.'+q.volleys);if(q.volleys===2)next(s);}}
  const center=q.squad.reduce((a,b)=>({x:a.x+b.x/6,z:a.z+b.z/6}),{x:0,z:0});if(chaseFollowing(s)&&dist(p,center)<13){const tx=s.stage===3||s.stage===4?0:s.stage===5?-19:0,tz=s.stage===3||s.stage===4?3:s.stage===5?-13:-43;q.squad.forEach((a,i)=>approach(s,a,tx+(i-2.5)*1.6,tz,dt,2.8,collide));}
  for(const e of s.enemies){e.fired=Math.max(0,e.fired-dt);if(e.hp<=0){e.dead+=dt;continue;}if(e.surrender)continue;const goal=s.stage<=2?-47:s.stage<=4?-8:-26,pace=s.stage===3?1.9:1.25;if(e.z<goal){approach(s,e,e.x,goal,dt,pace,collide);e.moving=true;}else e.moving=false;e.cooldown-=dt;e.aiming=e.cooldown<1.5;if(e.cooldown<=0&&dist(e,p)<48&&!blocked(s.level,{...e,y:1.4},{...p,y:input.crouch?1:1.7})){e.cooldown=10;e.fired=.2;emit(s,'enemyShot',e);if((e.id+Math.floor(s.time))%5===0){p.health=Math.max(0,p.health-(s.difficulty==='story'?4:9));s.lastDamage=s.time;emit(s,'hurt');}}}
  if(q.flank&&!q.surrender&&dist(p,{x:0,z:-29})<25){if(input.interact&&q.volley===0&&!chaseNear(s)){q.volley=5;const e=s.enemies.find(e=>e.hp>0&&!e.surrender);if(e)e.hp=0;emit(s,'chaseVolley');}if(Math.floor(s.time/7)>Math.floor((s.time-dt)/7)){const e=s.enemies.find(e=>e.hp>0);if(e)e.hp=0;emit(s,'chaseVolley');}if(s.enemies.filter(e=>e.hp>0).length<=2){q.surrender=true;s.enemies.filter(e=>e.hp>0).forEach(e=>e.surrender=true);s.armed=false;say(s,'chase.whiteflag');emit(s,'checkpoint');}}
 }else if(chaseMounted(s)){
  if(q.travel>55&&!q.pursuit){q.pursuit=true;q.riderX=-26;q.riderZ=-28;say(s,'chase.pursuit');}
  if(q.pursuit){const path=[[-28,-55],[-28,-89],[-28,-119],[-22,-126],[-22,-153],[-18,-175],[-18,-205],[0,-225]],[x,z]=path[Math.min(7,q.riderLeg)],a={x:q.riderX,z:q.riderZ};approach(s,a,x,z,dt,5.3,collide);q.riderX=a.x;q.riderZ=a.z;if(q.riderLeg<8&&dist(a,{x,z})<1)q.riderLeg++;if(dist(a,p)<17&&s.time-q.lastShot>10&&!blocked(s.level,{...a,y:2.2},{...p,y:2.2})){q.warning=2.2;q.lastShot=s.time;emit(s,'riderWarning');}if(q.warning>0&&q.warning<=dt){emit(s,'enemyShot',a);if(dist(a,p)<15){p.health=Math.max(1,p.health-(s.difficulty==='story'?6:12));s.lastDamage=s.time;emit(s,'hurt');}}}
 }
}
export function chaseContext(s){const q=s.chase;if(chaseOperating(s))return 'Stay at the forward line and face the approaching troops. E calls each section volley; let the section reload before the second.';if(s.level==='cowpens'&&s.stage<2)return 'Take Ward’s order, then form at the forward line. Morgan commands the battle; you lead one local section.';if(s.level==='cowpens')return s.stage===3?'An ordered withdrawal. Keep the actual section close; retreat behind the Continental line.':s.stage===4?'Face north toward the approaching line. Wait until they have advanced, then give the turn order.':s.stage>=6?'The flank has broken the local charge. Surrendered men are no longer targets.':'Morgan commands this battle. Rowan carries and executes one section’s orders.';if(chaseMounted(s))return 'Brake to collect the western dispatch. Cross the raised bridge; the flooded water cannot be jumped.';return 'Heavier cloth and tents reduce the horse’s pace. A lighter load leaves the extra canvas; both choices must deliver the ferry order.';}
