// Chapter 6, opening installment. Original crew fiction within sourced events.
export const VERSION='4.0.0';
export const SAVE_KEY='dc-us-history-chapter6-opening-v1';
export const NAMES={ROWAN:'Rowan Vale',WARD:'Elias Ward',MARA:'Mara Reed',ISAIAH:'Isaiah Mercer',THOMAS:'Thomas Vale',RUNNER:'Nathan Cole',MILITIA:'Militia captain'};
export const SPEAKERS={ROWAN:['am_fenrir',1.00,'en-us'],WARD:['bm_george',.96,'en-gb'],MARA:['af_heart',1.00,'en-us'],ISAIAH:['am_michael',.98,'en-us'],THOMAS:['bm_fable',.98,'en-gb'],RUNNER:['am_puck',1.04,'en-us'],MILITIA:['bm_george',1.04,'en-gb']};
const line=(id,speaker,text)=>({id,speaker,text});
export const LINES=[
 line('release.0','THOMAS','The release is signed. Give him his coat.'),
 line('release.1','ROWAN','Ward? It’s me.'),
 line('release.2','WARD','I know your footsteps. You still hurry when you’re frightened.'),
 line('release.3','ROWAN','Can you walk?'),
 line('release.4','WARD','With a little help. Don’t make a ceremony of it.'),
 line('help','WARD','Easy. They gave me my coat back. Not quite my legs.'),
 line('releasewalk','MARA','Bring him to the wagon. There’s a blanket beside me.'),
 line('gate.0','MARA','Hold still. This buckle never liked you.'),
 line('gate.1','WARD','You kept the wagon.'),
 line('gate.2','ISAIAH','And a place in it. We weren’t leaving you here.'),
 line('gate.3','THOMAS','You asked me to find him, Rowan. I kept my word.'),
 line('gate.4','ROWAN','Then come with us.'),
 line('gate.5','THOMAS','You’re my family. That doesn’t make this rebellion right.'),
 line('gate.6','WARD','Let him go. A man can open a door without crossing it.'),
 line('night.0','WARD','Gage has troops moving out of Boston. They’re after the powder at Concord.'),
 line('night.1','ROWAN','Again? Cambridge. Charlestown. How much more will they take?'),
 line('night.2','WARD','They came away empty-handed at Salem. New Hampshire took the guns at Fort William and Mary. People are ready.'),
 line('night.3','ROWAN','Then we get the warning to them. The north farm first.'),
 line('farm.0','RUNNER','British troops? I’ll wake the others. Our minutemen can assemble in a minute.'),
 line('farm.1','WARD','Some of those men fought the French with me. They know what a musket sounds like. Ring the meeting bell.'),
 line('bell.0','RUNNER','Revere was stopped by a British patrol. Other riders are carrying the warning on.'),
 line('bell.1','ROWAN','One rider doesn’t carry the whole country. Get your neighbors out.'),
 line('ridge','WARD','The lanterns are gathering on the road. Keep to the trees. We meet the others beyond the ridge.'),
 line('patrol','WARD','Lantern ahead. Stay low behind the fence. Let the patrol pass.'),
 line('spotted','WARD','They’ve seen us! Break their sight. Through the orchard!'),
 line('lex.0','MARA','People came out to see what was happening. Now they can’t get off the green.'),
 line('lex.1','WARD','Stay close. No one here knows what the next man will do.'),
 line('lex.2','ROWAN','Who fired?'),
 line('lex.3','WARD','I couldn’t see. Get down!'),
 line('lex.4','MARA','There’s someone by the wall. Rowan, help me get him out!'),
 line('rescue.0','RUNNER','My leg. I can’t put any weight on it.'),
 line('rescue.1','ROWAN','Put your arm over me. We’re going to that wagon.'),
 line('rescue.2','MARA','I’ve got him. There’s another man behind the fence. Bring him through the garden.'),
 line('rescue.3','WARD','The lane is clear. Leave the green. Now!'),
 line('concord.0','WARD','They reached Concord. Now they’re falling back toward Boston, and more militia are coming in along the road.'),
 line('concord.1','MARA','Our wagon has wounded aboard. I need that crossing clear.'),
 line('concord.2','WARD','Take the spare musket. One shot, then reload. Use the wall while your hands are busy.'),
 line('armed','WARD','Hold the stone wall. Keep their fire off the wagon. I’ll watch the left.'),
 line('wave.1','WARD','They’re coming through the smoke. Don’t stand in the open!'),
 line('wave.2','MARA','The wheel’s free! A little longer. Keep them back!'),
 line('clear','MARA','We’re across! Rowan, Ward, fall back to the orchard!'),
 line('reload','WARD','Reload behind cover. That wall is worth more than another shot.'),
 line('end.0','ROWAN','This morning I thought getting the warning through would be enough.'),
 line('end.1','WARD','It got these people out. That was enough for this morning.'),
 line('end.2','MARA','Militia are marching toward Boston from everywhere. They’re surrounding the city.'),
 line('end.3','ROWAN','And Thomas is still inside.'),
 line('end.4','WARD','Then we keep a road open. We leave with everyone we can.'),
 line('end.5','ISAIAH','I’ll find us a way through the harbor. You get some sleep.'),
 line('retry','WARD','Find cover. Breathe. We try the route again.'),
];
export const SCENES={
 release:{level:'release',title:'An unfinished promise',place:'BOSTON · EARLY 1775',music:'home',lines:['release.0','release.1','release.2','release.3','release.4'],after:'release'},
 gate:{level:'release',title:'A place in the wagon',place:'BOSTON · EARLY 1775',music:'home',lines:Array.from({length:7},(_,i)=>'gate.'+i),after:'nightIntro'},
 nightIntro:{level:'night',title:'The Powder Road',place:'MASSACHUSETTS · NIGHT OF APRIL 18–19, 1775',music:'night',lines:Array.from({length:4},(_,i)=>'night.'+i),after:'night'},
 lexington:{level:'lexington',title:'The first light',place:'LEXINGTON · APRIL 19, 1775',music:null,lines:Array.from({length:5},(_,i)=>'lex.'+i),after:'lexington'},
 concordIntro:{level:'concord',title:'A road home',place:'NEAR CONCORD · LATER ON APRIL 19, 1775',music:'tension',lines:Array.from({length:3},(_,i)=>'concord.'+i),after:'concord'},
 ending:{level:'end',title:'Everyone we can',place:'OUTSIDE BOSTON · AFTER APRIL 19, 1775',music:'home',lines:Array.from({length:6},(_,i)=>'end.'+i),after:'complete'},
};
export const LEVELS={
 release:{title:'An unfinished promise',place:'BOSTON · EARLY 1775',spawn:[0,13],bounds:[-18,18,-18,22],music:'home',goals:[{x:0,z:2,label:'Help Ward down the steps',verb:'Help Ward',time:1},{x:8,z:10,label:'Bring Ward to the wagon',verb:'Help Ward into the wagon',time:1.2}]},
 night:{title:'The Powder Road',place:'APRIL 18–19, 1775 · NIGHT',spawn:[0,19],bounds:[-24,24,-125,24],music:'night',goals:[{x:-8,z:-22,label:'Warn the north farm',verb:'Knock on the farmhouse door',time:1},{x:9,z:-61,label:'Ring the meeting bell',verb:'Ring the bell',time:1.2},{x:-3,z:-115,label:'Reach the far side of the ridge',verb:'Follow the path to Lexington',time:.8}]},
 lexington:{title:'The first light',place:'APRIL 19, 1775 · LEXINGTON',spawn:[0,17],bounds:[-25,25,-31,24],music:'tension',goals:[{x:-7,z:-4,label:'Reach the wounded runner',verb:'Help the wounded runner',time:1},{x:14,z:16,label:'Bring him to Mara’s wagon',verb:'Lower him into the wagon',time:1},{x:-13,z:-16,label:'Find the man behind the fence',verb:'Help the wounded man',time:1},{x:14,z:16,label:'Get him into the wagon',verb:'Help him aboard',time:1},{x:19,z:23,label:'Leave the green with the crew',verb:'Leave by the garden lane',time:.6}]},
 concord:{title:'A road home',place:'APRIL 19, 1775 · NEAR CONCORD',spawn:[3,18],bounds:[-24,24,-42,26],music:'battle',goals:[{x:2,z:9,label:'Take the spare musket',verb:'Take the musket',time:.8},{x:0,z:4,label:'Cover the wagon from the stone wall',verb:'Hold this position',time:0},{x:18,z:23,label:'Fall back to the orchard',verb:'Leave with the crew',time:.7}]},
};
export const FACTS=[
 ['A promise kept','Rowan, Mara, Isaiah, Ward, Thomas, and the local rescues are fictional. Ward survived the Chapter 5 fire and surrendered. Thomas remains a Loyalist. Isaiah is a free Black man who survived his 1770 shoulder wound.','Crew continuity'],
 ['The powder raids','Gage used Boston as a base for seizures of colonial weapons and powder. Cambridge and Charlestown lost supplies; resistance met the troops at Salem. Colonists seized Fort William and Mary in New Hampshire.','Handout §6.1, paragraphs 8–9'],
 ['Minutemen','Local militia prepared to assemble rapidly. Many members had experience in the French and Indian War. The fictional farm and bell route illustrates this wider mobilization.','Handout §6.1, paragraph 9'],
 ['A network of riders','Paul Revere was one of several warning riders. A British patrol captured him before he completed the ride to Concord. The warning continued through other people.','Handout §6.1, paragraph 10'],
 ['The first shot','Fighting occurred at Lexington and Concord on April 19, 1775. It remains uncertain who fired the first shot; this scene deliberately does not identify a shooter.','Handout §6.1, paragraph 10'],
 ['The road back','British troops retreated toward Boston under attacks by expanding militia forces. The player’s local wagon defense is fictional, not a reconstruction of a particular recorded engagement.','Handout §6.1, paragraph 10'],
 ['A siege begins','After Lexington and Concord, militia converged on Boston and besieged the city. Ticonderoga and the fighting at Breed’s Hill come later in the campaign.','Handout §6.1, paragraph 11'],
];
