import test from 'node:test';import assert from 'node:assert/strict';
import {fresh,tick,collide,currentGoal,goalNear,snapshot,restore} from './c6-sim.mjs';
import {inlandCanUse,inlandFamilyPath} from './c6-inland.mjs';
import {LEVELS,SCENES,LINES,continueProgress} from './c6-data.mjs';
import {rememberOutcome,cleanRecord} from './c6-record.mjs';
const step=(s,input={},sec=1)=>{const events=[];for(let i=0;i<sec/.025;i++)events.push(...tick(s,input,.025));return events;};
function walk(s,x,z){const key=p=>p.x+','+p.z,start={x:Math.round(s.player.x),z:Math.round(s.player.z)},queue=[start],parents=new Map([[key(start),null]]);let end;
 for(let i=0;i<queue.length&&i<26000;i++){const p=queue[i];if(p.x===Math.round(x)&&p.z===Math.round(z)){end=p;break;}for(const [dx,dz] of [[1,0],[-1,0],[0,1],[0,-1]]){const n={x:p.x+dx,z:p.z+dz};if(parents.has(key(n))||collide(s,n.x,n.z,.3,0))continue;parents.set(key(n),p);queue.push(n);}}assert.ok(end,'walkable '+x+','+z);const path=[];while(end){path.unshift(end);end=parents.get(key(end));}
 for(const p of path)for(let i=0;i<100&&Math.hypot(p.x-s.player.x,p.z-s.player.z)>.15;i++){s.player.yaw=0;tick(s,{right:p.x-s.player.x>.1,left:p.x-s.player.x<-.1,back:p.z-s.player.z>.1,forward:p.z-s.player.z<-.1},.025);assert.equal(s.failed,false,'player survives actual walking');if(s.level==='countrystandoff'&&s.inland.route)assert.equal(collide(s,s.inland.familyX,s.inland.familyZ,.22,0),false,'family clear of physical walls');}assert.ok(Math.hypot(s.player.x-x,s.player.z-z)<.6,'arrived '+x+','+z);}
function use(s){assert.ok(goalNear(s),'near stage '+s.stage);assert.ok(inlandCanUse(s),'usable stage '+s.stage);step(s,{interact:true},currentGoal(s).time+.2);}
function go(s){const g=currentGoal(s);walk(s,g.x,g.z);use(s);}
function finishHouse(route){let s=fresh('countrystandoff');go(s);go(s);assert.ok(s.inland.bucket);go(s);assert.ok(s.inland.doused&&!s.inland.torch&&!s.inland.bucket);go(s);walk(s,route==='witness'?-18:5,route==='witness'?-8:-29);use(s);assert.equal(s.inland.route,route);assert.equal(collide(s,route==='witness'?0:5,route==='witness'?-11:-25,.3,3),false);s=restore(snapshot(s));const path=inlandFamilyPath(s.inland);for(let i=0;i<5;i++){const [x,z]=path[i+1];walk(s,x,z);for(let j=0;j<1800&&s.inland.familyLeg<i+1;j++)tick(s,{},.025);assert.ok(s.inland.familyLeg>=i+1,'family physically reached leg '+(i+1));}walk(s,0,25);use(s);assert.ok(s.finished&&s.inland.familySafe);assert.equal(s.kills,0);const saved={};rememberOutcome(saved,s);assert.equal(saved.outcomes.countrystandoff.rescues,3);assert.equal(saved.outcomes.countrystandoff.houseRoute,route);return s;}
test('Camden loses the field while all four physically withdraw to three covered turns',()=>{let s=fresh('camdenfall','normal');go(s);go(s);go(s);assert.equal(s.inland.squad.length,4);for(const [x,z] of [[-19,-7],[-19,17],[0,25]]){const stage=s.stage;const center=s.inland.squad.reduce((a,n)=>({x:a.x+n.x/4,z:a.z+n.z/4}),{x:0,z:0});if(Math.hypot(center.x-s.player.x,center.z-s.player.z)>5)walk(s,center.x,center.z);walk(s,x,z);for(let i=0;i<2200&&!inlandCanUse(s);i++){const a=s.inland.squad[0];if(Math.hypot(a.x-s.player.x,a.z-s.player.z)>11)walk(s,a.x,a.z);tick(s,{},.025);}walk(s,x,z);use(s);assert.equal(s.stage,stage+1);if(s.stage===4)s=restore(snapshot(s));}assert.ok(s.finished&&s.inland.retreated);assert.ok(s.enemies.some(e=>e.hp>0),'survival does not require killing the British army');});
test('leaving a remote squad or killing enemies cannot complete a retreat marker',()=>{const s=fresh('camdenfall');s.stage=3;s.inland.rallied=true;s.inland.squad=Array.from({length:4},(_,i)=>({x:i,z:-31,yaw:0}));s.player.x=-19;s.player.z=-7;step(s,{interact:true},4);assert.equal(s.stage,3);assert.equal(s.inland.leg,0);assert.equal(inlandCanUse(s),false);const pitch=s.player.pitch;step(s,{lookUp:true},.2);assert.ok(s.player.pitch>pitch);});
test('both oath decisions remain distinct and open the real checkpoint only after papers are issued',()=>{for(const choice of ['sworn','refused']){let s=fresh('oathroad');assert.equal(collide(s,0,-45,.3,3),true);go(s);go(s);walk(s,choice==='sworn'?-8:8,0);use(s);assert.equal(s.inland.oath,choice);assert.equal(collide(s,0,-45,.3,0),false);s=restore(snapshot(s));while(!s.finished)go(s);const saved={};rememberOutcome(saved,s);assert.equal(saved.outcomes.oathroad.oathChoice,choice);assert.ok(saved.outcomes.oathroad.propertyLost);}});
test('both witnessed front passage and rear escape physically bring the household to shelter',()=>{finishHouse('witness');finishHouse('rear');});
test('closed doors cannot be jumped and a remote household cannot be recorded as saved',()=>{const s=fresh('countrystandoff');assert.equal(collide(s,0,-11,.3,4),true);assert.equal(collide(s,5,-25,.3,4),true);s.stage=5;s.inland.route='rear';s.player.z=25;step(s,{interact:true},5);assert.equal(s.stage,5);assert.equal(s.inland.familySafe,false);assert.equal(s.inland.familyLeg,0);});
test('dated supply work needs a carried bundle, market receipt and discipline notice',()=>{let s=fresh('supplyline');go(s);go(s);assert.ok(s.carrying&&s.inland.cloth&&!s.inland.loaded);s=restore(snapshot(s));while(!s.finished)go(s);assert.ok(!s.carrying&&s.inland.loaded&&s.inland.sale&&s.inland.discipline&&s.inland.roll);});
test('inland saves reject malformed choices and physics and carry only completed distinct outcomes',()=>{for(const level of Object.keys(LEVELS).filter(k=>['camdenfall','oathroad','countrystandoff','supplyline'].includes(k))){const raw=snapshot(fresh(level));assert.ok(restore(raw));for(const patch of [{oath:'automatic'},{route:'kill'},{leg:4},{familyLeg:6},{familyX:999},{fire:2},{bucket:1},{volley:-1},{squad:[{x:1,z:1,yaw:Infinity}]}]){const bad=structuredClone(raw);Object.assign(bad.inland,patch);assert.equal(restore(bad),null);}}const saved={};const s=fresh('oathroad');s.inland.oath='refused';assert.equal(rememberOutcome(saved,s),false);s.finished=true;rememberOutcome(saved,s);assert.equal(cleanRecord(saved,LEVELS,SCENES).outcomes.oathroad.oathChoice,'refused');});
test('Charleston migrates to Camden and the dates keep Greene and Reed out of earlier scenes',()=>{assert.equal(continueProgress({complete:true,completedPart:'south',seen:['southEnding']}).scene,'inlandIntro');const done={complete:true,completedPart:'inland',seen:['inlandEnding']};assert.equal(continueProgress(done).scene,'chaseIntro');assert.equal(SCENES.southEnding.after,'inlandIntro');assert.equal(SCENES.inlandEnding.after,'chaseIntro');assert.match(SCENES.inlandGreene.place,/DECEMBER 2/);assert.match(SCENES.inlandSupply.place,/DECEMBER 27/);const text=LINES.filter(l=>l.id.startsWith('inland.')).map(l=>l.text).join(' ');for(const phrase of ['Gates','Cornwallis','North Carolina','June third','Hudson Valley','attainder','William Franklin','Connecticut','December second','October','Esther DeBerdt Reed','September eighteenth','Sarah Franklin Bache','two thousand shirts','not during Valley Forge','pardons','every week','older boundary'])assert.ok(text.includes(phrase),phrase);});
