// Local crew fiction inside a historical defeat and a divided southern war.
const g=(x,z,label,verb,time=1.2)=>({x,z,label,verb,time});
export const INLAND_LEVELS={
 camdenfall:{title:'Country Against Itself',place:'CAMDEN · AUGUST 16, 1780 · ROWAN VALE',spawn:[0,25],bounds:[-36,36,-68,34],music:'inland',mode:'SQUAD WITHDRAWAL / LOSING FIELD',intro:'inlandIntro',after:'inlandRetreat',description:'Reach the local line, rally the crew and bring the actual withdrawing squad through two covered positions. Gates’s army loses Camden even if you get out.',goals:[g(-4,20,'Take Ward’s withdrawal packet','Take the packet'),g(-8,9,'Take cartridges for the local withdrawal','Take the cartridges'),g(0,-32,'Rally the scattered local section','Call the section together',2),g(-19,-7,'Bring the squad to the first covered turn','Wait for all four at cover',1.5),g(-19,17,'Bring the squad down the wooded lane','Keep them together at the second turn',1.5),g(0,25,'Leave the losing field with the section','Take the northbound road',1.5)]},
 oathroad:{title:'What a Signature Costs',place:'PATRIOT DISTRICT CHECKPOINT · SEPTEMBER 1, 1780 · A FICTIONAL LOCAL ENCOUNTER',spawn:[0,25],bounds:[-36,36,-63,34],music:'inlandquiet',mode:'OATH / DIVIDED FAMILY / PROPERTY LOSS',intro:'inlandOath',after:'inlandNotice',description:'Hear a family’s decision at an oath desk, witness the signed or refused route and bring their actual permit or restricted release through the checkpoint. Thomas arrives with a separate property notice.',goals:[g(-4,19,'Read the report changing Charleston parole conditions','Take the June report'),g(5,10,'Hear Joseph and Hannah’s decision at the oath desk','Listen to the family'),g(0,0,'Witness the family’s chosen route at one of the desks','Witness their decision',1.5),g(-18,-9,'Hear the merchant’s reason for keeping British trade','Hear his account'),g(18,-17,'Hear the tenant’s older dispute with a Patriot landlord','Hear his account'),g(-4,-34,'Read Thomas’s Pennsylvania property notice','Read the forfeited-estate notice',2),g(0,-51,'Bring the family’s papers to the far checkpoint','Present their papers',1.5)]},
 countrystandoff:{title:'The House with a Light',place:'SOUTH CAROLINA COUNTRYSIDE · SEPTEMBER 2, 1780 · A FICTIONAL HOUSEHOLD',spawn:[0,25],bounds:[-36,36,-58,34],music:'inland',mode:'ARSON INTERRUPTION / NEGOTIATION OR ESCAPE / FAMILY ESCORT',intro:'inlandHouse',after:'inlandPassage',description:'People are inside the house. Interrupt the porch fire, uncover the neighbor’s older dispute, then secure witnessed front passage or open a rear escape. Bring the moving family to shelter.',goals:[g(-5,-8,'Speak to Hannah through the front window','Call to the household'),g(-18,12,'Take a full bucket from the well','Take the water',1.5),g(0,-8,'Put out the porch fire before clearing a route','Douse the porch',2),g(-18,-8,'Read the fence claim and confront its author','Read the older claim',2),g(0,-8,'Secure witnessed passage or open the rear escape','Choose a passage',2.5),g(0,25,'Stay with the household until it reaches the road shelter','Wait for the family at shelter',1.5)]},
 supplyline:{title:'Hands Beyond the Field',place:'PHILADELPHIA SUPPLY DEPOT · DECEMBER 27, 1780 · ROWAN VALE',spawn:[0,25],bounds:[-36,36,-65,34],music:'inlandquiet',mode:'SUPPLY WORK / MARKET CROWD / DISCIPLINE',intro:'inlandSupply',after:'inlandEnding',description:'Trace the Philadelphia women’s work through its dated papers, share the camp’s cloth work and settle a fair-price supply complaint. Carry a real bundle to the army’s supply wagon.',goals:[g(-4,19,'Read the dated Philadelphia women’s receipt','Take the receipt'),g(12,8,'Collect Anne’s prepared cloth bundle','Lift the bundle',1.5),g(0,-10,'Carry the bundle to the supply wagon','Load the bundle',2),g(-19,-18,'Hear the women asking for a fair market price','Hear the supply complaint'),g(17,-26,'Bring the public receipt to the merchant','Agree a witnessed sale',2),g(-5,-38,'Read the army’s desertion and discipline notice','Read the notice',1.5),g(0,22,'Return the supply roll to Ward','Return the signed roll')]},
};
const DITCHES=[[-6,-22,13,1,1.2],[8,-43,15,1,1.2],[-19,-37,8,1,1.2],[-28,-8,5,17,4],[9,-9,7,9,4]];
const ROAD=[[-27,10,8,12,5],[27,-8,8,12,5],[-28,-30,9,12,5],[28,-39,9,12,5]];
const HOUSE=[[-7,-18,.4,14,4.5],[7,-18,.4,14,4.5],[-6,-11,2,.4,4.5],[-3,-11,.8,.4,4.5],[-4.2,-11,1.6,.4,.6],[4.8,-11,4.4,.4,4.5],[-1.85,-25,10.7,.4,4.5],[6.9,-25,.8,.4,4.5],[-29,-17,7,14,5],[29,-16,7,14,5],[-28,5,8,10,4]];
export const INLAND_BLOCKS={camdenfall:DITCHES,oathroad:ROAD,countrystandoff:HOUSE,supplyline:[[-28,5,9,14,4],[28,-9,9,14,4],[0,-14,4,5,2.4],[-27,-34,8,12,4],[27,-43,8,12,4]]};
const dist=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z),emit=(s,type,data={})=>s.events.push({type,...data}),say=(s,id)=>emit(s,'voice',{id});
export function freshInland(){return {packet:false,cartridges:false,rallied:false,squad:[],leg:0,volley:0,retreated:false,parole:false,oath:'',papers:false,merchant:false,tenant:false,property:false,checkpoint:false,window:false,bucket:false,doused:false,claim:false,route:'',familyX:0,familyZ:-18,familyLeg:0,familySafe:false,fire:0,torch:true,receipt:false,cloth:false,loaded:false,complaint:false,sale:false,discipline:false,roll:false};}
export function validInland(q,b){return !!q&&['packet','cartridges','rallied','retreated','parole','papers','merchant','tenant','property','checkpoint','window','bucket','doused','claim','familySafe','torch','receipt','cloth','loaded','complaint','sale','discipline','roll'].every(k=>typeof q[k]==='boolean')&&['leg','volley','familyX','familyZ','familyLeg','fire'].every(k=>Number.isFinite(q[k]))&&Number.isInteger(q.leg)&&q.leg>=0&&q.leg<=3&&Number.isInteger(q.familyLeg)&&q.familyLeg>=0&&q.familyLeg<=5&&q.volley>=0&&q.volley<1000000&&q.fire>=0&&q.fire<=1&&['','sworn','refused'].includes(q.oath)&&['','witness','rear'].includes(q.route)&&q.familyX>=b[0]&&q.familyX<=b[1]&&q.familyZ>=b[2]&&q.familyZ<=b[3]&&Array.isArray(q.squad)&&q.squad.length<=4&&q.squad.every(a=>['x','z','yaw'].every(k=>Number.isFinite(a[k]))&&a.x>=b[0]&&a.x<=b[1]&&a.z>=b[2]&&a.z<=b[3]);}
export const inlandWithdrawing=s=>s.level==='camdenfall'&&s.inland?.rallied&&!s.inland.retreated;
export const inlandEscorting=s=>s.level==='countrystandoff'&&!!s.inland?.route&&!s.inland.familySafe;
export const inlandOperating=()=>false;
export function inlandBlocked(s,x,z,r){const q=s.inland;if(s.level==='oathroad'&&!q.papers&&Math.abs(z+45)<.25+r)return true;if(s.level==='countrystandoff'){if(Math.abs(x+4.2)<.8+r&&Math.abs(z+11)<.2+r)return true;if(q.route!=='witness'&&Math.abs(x)<2.6+r&&Math.abs(z+11)<.2+r)return true;if(q.route!=='rear'&&Math.abs(x-5)<1.5+r&&Math.abs(z+25)<.2+r)return true;}return false;}
export function inlandGoal(s){const q=s.inland,g=INLAND_LEVELS[s.level].goals[s.stage];if(!g)return null;
 if(s.level==='countrystandoff'&&s.stage===5&&q.familyLeg<5&&dist(s.player,{x:q.familyX,z:q.familyZ})>9)return {...g,x:q.familyX,z:q.familyZ,label:'Return to the household through the opened door',verb:'Stay with the household'};
 if(s.level==='oathroad'&&s.stage===2){const sworn=dist(s.player,{x:-8,z:0})<=dist(s.player,{x:8,z:0});return {...g,x:sworn?-8:8,z:0,label:sworn?'Witness Joseph’s oath at the left desk':'Witness Joseph’s refusal at the right desk',verb:sworn?'Witness the oath':'Witness the refusal and restricted release'};}
 if(s.level==='countrystandoff'&&s.stage===4){const witness=dist(s.player,{x:-18,z:-8})<=dist(s.player,{x:5,z:-29});return {...g,x:witness?-18:5,z:witness?-8:-29,label:witness?'Show the fence claim and secure witnessed front passage':'Open the rear door into the garden',verb:witness?'Secure witnessed passage':'Move the rear door’s bar'};}
 return g;
}
export const inlandNear=s=>!!inlandGoal(s)&&dist(s.player,inlandGoal(s))<2.5;
export function inlandCanUse(s){const q=s.inland;if(s.level==='camdenfall'&&s.stage>=3)return q.squad.length===4&&q.leg>=s.stage-2&&q.squad.every(a=>dist(a,INLAND_LEVELS[s.level].goals[s.stage])<5);if(s.level==='countrystandoff'&&s.stage===5)return q.familyLeg===5&&dist({x:q.familyX,z:q.familyZ},{x:0,z:25})<2;return true;}
function next(s){s.stage++;s.hold=0;emit(s,'checkpoint');if(s.stage>=INLAND_LEVELS[s.level].goals.length){s.finished=true;emit(s,'finish');}}
export function interactInland(s){const q=s.inland,st=s.stage;
 if(s.level==='camdenfall'){
  if(st===0){q.packet=true;say(s,'inland.packet');}if(st===1){q.cartridges=true;s.armed=true;s.ammo=12;say(s,'inland.cartridges');}if(st===2){q.rallied=true;q.squad=Array.from({length:4},(_,i)=>({x:(i-1.5)*1.7,z:-31,yaw:0}));s.enemies=Array.from({length:9},(_,i)=>({id:i,x:(i%5-2)*5,z:-57-Math.floor(i/5)*4,hp:1,yaw:Math.PI,cooldown:5+i*.4,dead:0,fired:0,moving:false,route:[0,20]}));say(s,'inland.rally');}if(st===3)say(s,'inland.first');if(st===4)say(s,'inland.second');if(st===5){q.retreated=true;say(s,'inland.out');}
 }else if(s.level==='oathroad'){
  if(st===0){q.parole=true;say(s,'inland.parole');}if(st===1)say(s,'inland.family');if(st===2){q.oath=inlandGoal(s).x<0?'sworn':'refused';q.papers=true;say(s,'inland.oath.'+q.oath);}if(st===3){q.merchant=true;say(s,'inland.merchant');}if(st===4){q.tenant=true;say(s,'inland.tenant');}if(st===5){q.property=true;say(s,'inland.property');}if(st===6){q.checkpoint=true;say(s,'inland.checkpoint.'+q.oath);}
 }else if(s.level==='countrystandoff'){
  if(st===0){q.window=true;say(s,'inland.window');}if(st===1){q.bucket=true;say(s,'inland.water');}if(st===2){q.bucket=false;q.doused=true;q.torch=false;q.fire=0;emit(s,'water');say(s,'inland.douse');}if(st===3){q.claim=true;say(s,'inland.claim');}if(st===4){q.route=inlandGoal(s).x<0?'witness':'rear';s.armed=false;say(s,'inland.route.'+q.route);}if(st===5){q.familySafe=true;say(s,'inland.safe');}
 }else{
  if(st===0){q.receipt=true;say(s,'inland.receipt');}if(st===1){q.cloth=true;s.carrying=true;say(s,'inland.cloth');}if(st===2){q.loaded=true;s.carrying=false;say(s,'inland.load');}if(st===3){q.complaint=true;say(s,'inland.complaint');}if(st===4){q.sale=true;say(s,'inland.sale');}if(st===5){q.discipline=true;say(s,'inland.discipline');}if(st===6){q.roll=true;say(s,'inland.roll');}
 }next(s);
}
function approach(s,a,x,z,pace,dt,collide){const d=dist(a,{x,z}),step=Math.min(d,dt*pace),nx=a.x+(x-a.x)/(d||1)*step,nz=a.z+(z-a.z)/(d||1)*step,old={x:a.x,z:a.z};if(!collide(s,nx,nz,.22,0)){a.x=nx;a.z=nz;}else{if(!collide(s,nx,a.z,.22,0))a.x=nx;if(!collide(s,a.x,nz,.22,0))a.z=nz;}if(dist(a,old)>.001)a.yaw=Math.atan2(-(a.x-old.x),-(a.z-old.z));}
export const inlandFamilyPath=q=>q.route==='rear'?[[0,-18],[5,-18],[5,-29],[23,-29],[23,18],[0,25]]:[[0,-18],[0,-5],[-19,-5],[-19,18],[0,25],[0,25]];
export function updateInland(s,input,dt,{collide,blocked}){const q=s.inland,p=s.player;q.volley=Math.max(0,q.volley-dt);
 if(inlandWithdrawing(s)){
  const targets=[[-19,-7],[-19,17],[0,25]],index=Math.min(2,Math.max(0,s.stage-3)),target=targets[index],center={x:q.squad.reduce((n,a)=>n+a.x,0)/4,z:q.squad.reduce((n,a)=>n+a.z,0)/4};
  if(dist(p,center)<13){q.squad.forEach((a,i)=>approach(s,a,target[0]+(i-1.5)*1.5,target[1]+(i%2)*.6,2.6,dt,collide));if(q.leg<=index&&q.squad.every(a=>dist(a,{x:target[0],z:target[1]})<3.6)){q.leg=index+1;emit(s,'checkpoint');}}
  // Only a loaded physical shot or a nearby covering order buys space; survival never wins Camden.
  if(input.interact&&q.volley===0&&!inlandNear(s)&&dist(p,center)<12){q.volley=7;const e=s.enemies.find(a=>a.hp>0);if(e)e.cooldown+=6;emit(s,'inlandVolley');}
  for(const e of s.enemies){e.fired=Math.max(0,e.fired-dt);if(e.hp<=0){e.dead+=dt;continue;}const d=dist(e,p);if(d>16){approach(s,e,p.x,p.z,1,dt,collide);e.moving=true;}e.yaw=Math.atan2(-(p.x-e.x),-(p.z-e.z));e.cooldown-=dt;e.aiming=e.cooldown<1.6;if(e.cooldown<=0&&d<48&&!blocked(s.level,{...e,y:1.4},{...p,y:input.crouch?1:1.7})){e.cooldown=9;e.fired=.2;emit(s,'enemyShot',e);if((e.id+Math.floor(s.time))%4===0){p.health=Math.max(0,p.health-(s.difficulty==='story'?4:9));s.lastDamage=s.time;emit(s,'hurt');}}}
 }
 if(s.level==='countrystandoff'){
  if(q.window&&!q.doused){q.fire=Math.min(1,q.fire+dt*.014);if(dist(p,{x:0,z:-10})<1.7&&q.fire>.65){p.health=Math.max(1,p.health-dt*2);s.lastDamage=s.time;}}
  if(inlandEscorting(s)&&dist(p,{x:q.familyX,z:q.familyZ})<13){const path=inlandFamilyPath(q),[x,z]=path[Math.min(5,q.familyLeg+1)],a={x:q.familyX,z:q.familyZ};approach(s,a,x,z,2.1,dt,collide);q.familyX=a.x;q.familyZ=a.z;if(q.familyLeg<5&&dist(a,{x,z})<.5){q.familyLeg++;emit(s,'checkpoint');}}
 }
}
export function inlandContext(s){const q=s.inland;if(inlandWithdrawing(s))return 'Keep all four close. E away from a marker orders covering fire; F fires, R reloads, C crouches. The squad must reach each turn before you leave.';if(s.level==='oathroad'&&s.stage===2)return 'Left desk: witness Joseph’s oath. Right desk: witness refusal and a restricted release. The signed choice stays in the family’s record.';if(s.level==='countrystandoff')return inlandEscorting(s)?'Stay within thirteen meters of the family. Walk with them through the opened door and along the chosen passage.':s.stage===4?'Front: a public witness against the revenge claim. Rear: open the garden door. Both routes require putting out the porch fire first.':'The house is occupied. Water stops the porch fire; a cleared door gives people a way out.';if(s.level==='supplyline')return s.carrying?'The bundle is on your shoulder. Bring it to the supply wagon before taking another task.':'These papers are dated December 1780. The Philadelphia work continues after Reed’s death; it belongs to this supply network.';return 'Thomas’s Pennsylvania property notice is a separate process from this southern oath checkpoint.';}

