import test from 'node:test';
import assert from 'node:assert/strict';
import {fresh,tick,collide,currentGoal,goalNear,restore,snapshot,blocked} from './c6-sim.mjs';
import {SCENES,LEVELS,LINES,continueProgress} from './c6-data.mjs';
import {philadelphiaDefending,philadelphiaCanUse,WAGON_ROUTE} from './c6-philadelphia.mjs';
import {rememberOutcome,cleanRecord} from './c6-record.mjs';
const step=(s,input={},seconds=1)=>{let events=[];for(let i=0;i<seconds/.025;i++)events.push(...tick(s,input,.025));return events;};
function walk(s,x,z,extra={}){const start={x:Math.round(s.player.x),z:Math.round(s.player.z)},key=p=>p.x+','+p.z,queue=[start],parents=new Map([[key(start),null]]);let end;
 for(let i=0;i<queue.length&&i<19000;i++){const p=queue[i];if(p.x===Math.round(x)&&p.z===Math.round(z)){end=p;break;}for(const [dx,dz] of [[1,0],[-1,0],[0,1],[0,-1]]){const n={x:p.x+dx,z:p.z+dz};if(parents.has(key(n))||collide(s,n.x,n.z,.3,0))continue;parents.set(key(n),p);queue.push(n);}}
 assert.ok(end,'physical route to '+x+','+z);const path=[];while(end){path.unshift(end);end=parents.get(key(end));}
 for(const p of path)for(let i=0;i<80&&Math.hypot(p.x-s.player.x,p.z-s.player.z)>.14;i++){s.player.yaw=0;tick(s,{...extra,right:p.x-s.player.x>.1,left:p.x-s.player.x<-.1,back:p.z-s.player.z>.1,forward:p.z-s.player.z<-.1,crouch:s.armed},.025);assert.equal(s.failed,false,'alive on route');}assert.ok(Math.hypot(s.player.x-x,s.player.z-z)<.5);
}
function use(s){assert.ok(goalNear(s));assert.ok(philadelphiaCanUse(s));step(s,{interact:true},(currentGoal(s).time||1)+.2);}
function cover(s){walk(s,-14,-8);for(let i=0;i<7000&&philadelphiaDefending(s);i++)tick(s,{interact:true,crouch:true},.025);assert.equal(s.stage,3);}
function choose(s,route){walk(s,0,-38);use(s);assert.equal(collide(s,0,-55),true);walk(s,route==='foot'?-22:23,route==='foot'?-34:-32);use(s);assert.equal(s.philadelphia.route,route);}
function escort(s){for(let i=0;i<16000&&s.stage===2;i++){const q=s.philadelphia,target=WAGON_ROUTE[q.wagonStep]||WAGON_ROUTE.at(-1),dx=target.x-s.player.x,dz=target.z-s.player.z;s.player.yaw=0;const far=Math.hypot(q.wagonX-s.player.x,q.wagonZ-s.player.z)>5;const gx=far?q.wagonX+2:target.x+2,gz=far?q.wagonZ+1:target.z+1;tick(s,{interact:true,right:gx-s.player.x>.15,left:gx-s.player.x<-.15,back:gz-s.player.z>.15,forward:gz-s.player.z<-.15},.025);assert.equal(s.failed,false);}assert.equal(s.stage,3,'wagon reaches the far road through the wider bridge');}
test('Brandywine withdraws after a real covering phase and extracts the courier on foot',()=>{const s=fresh('brandywine','story');for(let i=0;i<2;i++){const g=currentGoal(s);walk(s,g.x,g.z);use(s);}cover(s);for(let i=3;i<7;i++){const g=currentGoal(s);walk(s,g.x,g.z);use(s);}assert.equal(s.finished,true);assert.ok(s.philadelphia.flank&&s.philadelphia.rescued&&s.philadelphia.dispatch);assert.equal(s.carrying,false);assert.ok(s.enemies.every(e=>e.retreat));});
test('the withdrawal lane cannot complete when abandoned and suffers actual pressure',()=>{const s=fresh('brandywine','story');s.stage=2;s.armed=true;s.player.x=0;s.player.z=30;const before=s.philadelphia.line;step(s,{},12);assert.equal(s.philadelphia.clock,0);assert.equal(s.stage,2);assert.ok(s.philadelphia.line<before);});
test('Congress packing physically carries and stows journals, marks Howe’s route, and seals the load',()=>{const s=fresh('recordshall');for(let i=0;i<7;i++){const g=currentGoal(s);walk(s,g.x,g.z);use(s);if(i===1)assert.equal(s.philadelphia.holding,'journals');if(i===2)assert.equal(s.philadelphia.holding,'');if(!s.finished)assert.ok(restore(snapshot(s)));}assert.ok(s.finished&&s.philadelphia.journals&&s.philadelphia.map&&s.philadelphia.marked&&s.philadelphia.covered);});
test('the cart detour requires actual escort input, pauses safely, crosses physically, and saves the full load',()=>{let s=fresh('congressroad');choose(s,'wagon');step(s,{interact:true},10);assert.equal(s.philadelphia.wagonZ,18,'remote use cannot move a wagon');walk(s,2,18);step(s,{},3);assert.equal(s.philadelphia.wagonZ,18,'released brake assist stops travel');step(s,{interact:true},2);assert.ok(s.philadelphia.wagonZ<18);s=restore(snapshot(s));escort(s);assert.ok(s.philadelphia.recordsSecured&&s.philadelphia.pressSaved);assert.ok(s.philadelphia.wagonTravel>145);for(let i=3;i<5;i++){const g=currentGoal(s);walk(s,g.x,g.z);use(s);}assert.equal(s.finished,true);assert.equal(s.philadelphia.far,true);});
test('the footbridge route fetches the real journals and waits for a collision-aware crew crossing',()=>{const s=fresh('congressroad');choose(s,'foot');assert.equal(s.carrying,false,'selecting a distant route does not teleport journals into your arms');walk(s,0,18);step(s,{interact:true},1.6);assert.equal(s.carrying,true);assert.equal(s.philadelphia.holding,'journals');assert.ok(s.philadelphia.gate);walk(s,-22,-72);step(s,{interact:true},1.6);assert.equal(s.stage,3);assert.equal(s.carrying,false);assert.equal(s.philadelphia.pressSaved,false);assert.ok(s.philadelphia.recordsSecured);for(let i=0;i<7000&&s.philadelphia.crewStep<5;i++)tick(s,{},.025);assert.equal(s.philadelphia.crewStep,5);assert.ok(s.philadelphia.crewZ<-80);for(let i=3;i<5;i++){const g=currentGoal(s);walk(s,g.x,g.z);use(s);}assert.equal(s.finished,true);assert.equal(s.philadelphia.wagonZ,18);});
test('road water, gate and failed central timber block shortcutting, including jump-height movement',()=>{const s=fresh('congressroad');s.philadelphia.bridgeBroken=true;assert.equal(collide(s,0,-55,.3,2),true);assert.equal(collide(s,-22,-55,.3,0),false);assert.equal(collide(s,23,-55,.3,0),false);assert.equal(collide(s,23,-35,.3,0),true);s.philadelphia.gate=true;assert.equal(collide(s,23,-35,.3,0),false);assert.equal(collide(s,-18,-55,.3,0),true);});
test('real E tap controls toggle wagon assistance, keep walking at its pace, and set the brake',()=>{const s=fresh('congressroad');s.stage=2;Object.assign(s.philadelphia,{route:'wagon',gate:true,crewStarted:true});s.player.x=2;s.player.z=18;tick(s,{useTap:true},.025);assert.ok(s.philadelphia.assist);step(s,{forward:true,useTap:false},10);assert.ok(s.philadelphia.wagonZ<1);assert.ok(Math.abs(s.player.z-s.philadelphia.wagonZ)<.5);tick(s,{useTap:true},.025);assert.equal(s.philadelphia.assist,false);const parked=s.philadelphia.wagonZ;step(s,{interact:true,useTap:false},3);assert.equal(s.philadelphia.wagonZ,parked,'the generic interaction latch cannot override a set brake');});
test('Philadelphia saves validate branch physics and completed outcomes retain the chosen load',()=>{for(const level of ['brandywine','recordshall','congressroad']){const raw=snapshot(fresh(level));assert.ok(restore(raw));for(const patch of [{route:'fast'},{wagonStep:99},{crewStep:0},{crewX:1000},{gate:1},{holding:'all'},{collapse:2}]){const bad=structuredClone(raw);Object.assign(bad.philadelphia,patch);assert.equal(restore(bad),null);}}const s=fresh('congressroad');s.finished=true;Object.assign(s.philadelphia,{route:'foot',recordsSecured:true,pressSaved:false,far:true});const saved={outcomes:{},skipped:[]};rememberOutcome(saved,s);const clean=cleanRecord(saved,LEVELS,SCENES);assert.equal(clean.outcomes.congressroad.route,'foot');assert.ok(clean.outcomes.congressroad.recordsSecured&&clean.outcomes.congressroad.peopleTogether);assert.equal(clean.outcomes.congressroad.pressSaved,false);});
test('winter saves continue to Philadelphia and the campaign separates September departure from occupation',()=>{const old={complete:true,completedPart:'crossing',seen:[],checkpoint:null};assert.equal(continueProgress(old).scene,'philadelphiaIntro');const done={...old,completedPart:'philadelphia',seen:['philadelphiaEnding']};assert.equal(continueProgress(done).scene,'albanyIntro');assert.equal(SCENES.crossingEnding.after,'philadelphiaIntro');assert.equal(SCENES.philadelphiaEnding.after,'albanyIntro');const text=LINES.filter(l=>/^(philadelphia\.|records\.|road\.)/.test(l.id)).map(l=>l.text).join(' ');for(const word of ['September eleventh','Chesapeake','fifteen thousand','Congress','Germain','Lord North','Albany','Montreal','Oswego','Clinton','York','September twenty-sixth','coming weeks'])assert.ok(text.includes(word),word);});
