// M16 working module. Integrate after preserving the verified 4.15 release.
const g=(x,z,label,verb,time=1.2)=>({x,z,label,verb,time});
export const PRICE_LEVELS={
 priceprovision:{title:'What Paper Can Buy',place:'LOCAL PROVISION DEPOT · MARCH 14, 1781 · FICTIONAL CREW STOP',spawn:[0,25],bounds:[-35,35,-52,34],music:'pricequiet',mode:'PROVISION / DEPRECIATION / WORK OR BARTER',intro:'priceIntro',after:'priceField',description:'Read the paper account, hear why it will not buy the whole load, then barter carried linen or physically help the flour cart. Keep the state note with the receipt.',goals:[g(-4,20,'Take the Continental paper account','Take the account'),g(8,8,'Bring the paper to the provision merchant','Offer the paper'),g(0,-5,'Choose linen barter or work for the flour','Choose the local agreement',1.5),g(8,-27,'Bring the actual linen or flour cart to the merchant','Complete the delivery',1.5),g(-5,-38,'Take the state-issued note and witnessed receipt','Close the account',1.5)]},
 guilfordfield:{title:'The Price of the Field',place:'GUILFORD COURTHOUSE · MARCH 15, 1781 · ROWAN VALE',spawn:[0,25],bounds:[-38,38,-68,34],music:'price',mode:'COVERED PASSAGE / CASUALTY / EXTRACTION',intro:'priceField',after:'priceTreatment',description:'Hold one local withdrawal lane. Reach the wounded militia soldier, then help carry Ward to Mara after he is struck. The historical field cannot be won by this small section.',goals:[g(-4,20,'Take the local withdrawal order','Take the order'),g(-8,9,'Collect the section cartridges and dressing','Take the reserve'),g(0,-28,'Keep the local withdrawal lane open','E gives covering fire',0),g(-19,-31,'Reach the wounded militia soldier behind the wall','Reach them',1.5),g(-19,-29,'Help Ward onto your shoulder','Support Ward',1.5),g(0,20,'Bring Ward physically to Mara’s temporary cover','Let Mara take his weight',1.5)]},
 guilfordexit:{title:'The People Still Here',place:'GUILFORD WITHDRAWAL ROAD · MARCH 15, 1781 · AFTER WARD’S DEATH',spawn:[0,25],bounds:[-38,38,-68,34],music:'pricequiet',mode:'WOUNDED STRANGER / CREW WITHDRAWAL / CARE',intro:'priceAfter',after:'priceBurial',description:'Return for the wounded militia soldier and bring him to care. Accompany the surviving crew through covered turns. A saved person and retained supplies are local outcomes; Ward’s death remains.',goals:[g(-4,20,'Take Mara’s dressing and the surviving names','Take the care roll'),g(-19,-31,'Support the wounded militia soldier','Bring him with you',1.5),g(0,20,'Bring the actual wounded man to care','Deliver him to care',1.5),g(0,-24,'Gather the surviving crew behind the rear line','Gather the crew',1.5),g(-20,-10,'Keep the actual crew together at the wooded turn','Wait for everyone',1.5),g(-20,16,'Bring the surviving crew through the second turn','Keep moving together',1.5),g(0,25,'Bring the crew to the north road','Close the surviving roll',1.5)]},
};
export const PRICE_BLOCKS={priceprovision:[[-24,8,9,12,4],[25,-12,9,14,4],[-17,-26,10,.9,1.1]],guilfordfield:[[-19,-34,12,1,1.2],[12,-24,10,1,1.1],[-28,5,5,15,4],[29,-48,7,14,4]],guilfordexit:[[-19,-34,12,1,1.2],[12,-24,10,1,1.1],[-28,5,5,15,4],[29,-48,7,14,4]]};
const dist=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z),emit=(s,type,data={})=>s.events.push({type,...data}),say=(s,id)=>emit(s,'voice',{id});
export function freshPrice(level){return {paper:false,merchant:false,agreement:'',linen:false,delivered:false,stateNote:false,order:false,reserve:false,line:0,passage:[],volley:0,useHeld:false,wardShot:false,wardCarried:false,wardCover:false,wardDead:level==='guilfordexit',wardX:-19,wardZ:-29,cartX:-12,cartZ:-5,cartLeg:0,careRoll:false,stranger:false,strangerSafe:false,strangerX:-19,strangerZ:-31,crew:[],crewLeg:0,crewSafe:false,buried:false};}
export function validPrice(q,b){return !!q&&['paper','merchant','linen','delivered','stateNote','order','reserve','useHeld','wardShot','wardCarried','wardCover','wardDead','careRoll','stranger','strangerSafe','crewSafe','buried'].every(k=>typeof q[k]==='boolean')&&['','work','linen'].includes(q.agreement)&&['line','volley','wardX','wardZ','cartX','cartZ','cartLeg','strangerX','strangerZ','crewLeg'].every(k=>Number.isFinite(q[k]))&&q.line>=0&&q.line<=36&&q.volley>=0&&q.volley<=7&&Number.isInteger(q.cartLeg)&&q.cartLeg>=0&&q.cartLeg<=2&&Number.isInteger(q.crewLeg)&&q.crewLeg>=0&&q.crewLeg<=3&&[['wardX','wardZ'],['cartX','cartZ'],['strangerX','strangerZ']].every(([x,z])=>q[x]>=b[0]&&q[x]<=b[1]&&q[z]>=b[2]&&q[z]<=b[3])&&Array.isArray(q.passage)&&q.passage.length<=6&&q.passage.every(a=>['x','z','yaw'].every(k=>Number.isFinite(a[k]))&&a.x>=b[0]&&a.x<=b[1]&&a.z>=b[2]&&a.z<=b[3])&&Array.isArray(q.crew)&&q.crew.length<=3&&q.crew.every(a=>['x','z','yaw'].every(k=>Number.isFinite(a[k]))&&a.x>=b[0]&&a.x<=b[1]&&a.z>=b[2]&&a.z<=b[3]);}
export const priceFighting=s=>s.level==='guilfordfield'&&s.stage===2;
export const priceCart=s=>s.level==='priceprovision'&&s.stage===3&&s.price.agreement==='work';
export const priceCarrying=s=>s.price&&(s.level==='guilfordfield'&&s.stage===5||s.level==='guilfordexit'&&s.stage===2);
export const priceFollowing=s=>s.level==='guilfordexit'&&s.stage>=4&&!s.price.crewSafe;
export function priceGoal(s){const q=s.price,g=PRICE_LEVELS[s.level].goals[s.stage];if(!g)return null;if(s.level==='priceprovision'&&s.stage===2){const work=dist(s.player,{x:-12,z:-5})<=dist(s.player,{x:12,z:-5});return {...g,x:work?-12:12,label:work?'Work the flour cart; retain the spare linen':'Barter the spare linen for flour',verb:work?'Help the flour cart':'Take the barter linen'};}if(priceCart(s)&&dist(s.player,{x:q.cartX,z:q.cartZ})>5)return {...g,x:q.cartX,z:q.cartZ,label:'Return to the flour cart',verb:'Walk beside the cart'};if(priceFollowing(s)&&q.crew.length&&dist(s.player,q.crew[0])>10)return {...g,x:q.crew[0].x,z:q.crew[0].z,label:'Return to the surviving crew',verb:'Stay with the crew'};return g;}
export const priceNear=s=>!!priceGoal(s)&&dist(s.player,priceGoal(s))<2.5;
export function priceCanUse(s){const q=s.price;if(priceFighting(s))return false;if(priceCart(s))return q.cartLeg===2&&dist({x:q.cartX,z:q.cartZ},{x:8,z:-27})<2;if(priceFollowing(s)){const g=PRICE_LEVELS[s.level].goals[s.stage];return q.crew.length===3&&q.crewLeg>=s.stage-3&&q.crew.every(a=>dist(a,g)<5);}return true;}
function next(s){s.stage++;s.hold=0;emit(s,'checkpoint');if(s.stage>=PRICE_LEVELS[s.level].goals.length){s.finished=true;emit(s,'finish');}}
export function interactPrice(s){const q=s.price,st=s.stage;
 if(s.level==='priceprovision'){if(st===0){q.paper=true;say(s,'price.paper');}if(st===1){q.merchant=true;say(s,'price.merchant');}if(st===2){q.agreement=priceGoal(s).x<0?'work':'linen';q.linen=q.agreement==='linen';s.carrying=q.linen;say(s,'price.agreement.'+q.agreement);}if(st===3){q.delivered=true;s.carrying=false;say(s,'price.flour');}if(st===4){q.stateNote=true;say(s,'price.state');}}
 else if(s.level==='guilfordfield'){if(st===0){q.order=true;say(s,'price.order');}if(st===1){q.reserve=true;q.passage=Array.from({length:6},(_,i)=>({x:(i%3-1)*2,z:-36-Math.floor(i/3)*4,yaw:Math.PI}));s.armed=true;s.ammo=18;s.enemies=Array.from({length:8},(_,i)=>({id:i,x:(i%4-1.5)*5,z:-57-Math.floor(i/4)*4,hp:1,yaw:Math.PI,cooldown:5+i,dead:0,fired:0,moving:false,route:[0,-15]}));say(s,'price.reserve');}if(st===3){q.wardShot=true;say(s,'price.ward.bridge');next(s);emit(s,'priceScene',{key:'priceHit'});return;}if(st===4){q.wardCarried=true;s.carrying=true;s.armed=false;say(s,'price.ward.support');}if(st===5){q.wardCover=true;s.carrying=false;say(s,'price.ward.cover');}}
 else{if(st===0){q.careRoll=true;say(s,'price.care.roll');}if(st===1){q.stranger=true;s.carrying=true;say(s,'price.stranger');}if(st===2){q.strangerSafe=true;s.carrying=false;say(s,'price.care');}if(st===3){q.crew=Array.from({length:3},(_,i)=>({x:(i-1)*2,z:-24,yaw:0}));say(s,'price.crew');}if(st>=4){q.crewLeg=st-3;say(s,'price.turn.'+(st-3));if(st===6)q.crewSafe=true;}}
 next(s);
}
function move(s,a,x,z,dt,pace,collide){const d=dist(a,{x,z}),v=Math.min(d,dt*pace),nx=a.x+(x-a.x)/(d||1)*v,nz=a.z+(z-a.z)/(d||1)*v;if(!collide(s,nx,a.z,.25,0))a.x=nx;if(!collide(s,a.x,nz,.25,0))a.z=nz;a.yaw=Math.atan2(-(x-a.x),-(z-a.z));}
export function updatePrice(s,input,dt,{collide,blocked}){const q=s.price,p=s.player,use=!!input.useTap||!!input.interact&&!q.useHeld;q.useHeld=!!input.interact;q.volley=Math.max(0,q.volley-dt);
 if(priceCart(s)&&dist(p,{x:q.cartX,z:q.cartZ})<5){const path=[[0,-5],[8,-27]],[x,z]=path[Math.min(q.cartLeg,1)],a={x:q.cartX,z:q.cartZ};move(s,a,x,z,dt,input.jump?0:1.7,collide);q.cartX=a.x;q.cartZ=a.z;if(q.cartLeg<2&&dist(a,{x,z})<1)q.cartLeg++;}
 if(priceFighting(s)){if(dist(p,{x:0,z:-28})<12){q.line=Math.min(36,q.line+dt);if(use&&q.volley===0){q.volley=7;emit(s,'priceVolley');emit(s,'orderUsed');const e=s.enemies.find(e=>e.hp>0);if(e)e.hp=0;}if(q.line===36&&q.passage.length===6&&q.passage.every(a=>a.z>17)){say(s,'price.withdraw');next(s);}}}
 if(s.level==='guilfordfield'&&q.reserve){q.passage.forEach(a=>move(s,a,a.x,18,dt,2,collide));}
 if(s.level==='guilfordfield'){for(const e of s.enemies){e.fired=Math.max(0,e.fired-dt);if(e.hp<=0){e.dead+=dt;continue;}e.moving=e.z<-14;if(e.moving)move(s,e,e.x,-14,dt,1,collide);e.cooldown-=dt;if(e.cooldown<=0&&dist(e,p)<48&&!blocked(s.level,{...e,y:1.4},{...p,y:input.crouch?1:1.7})){e.cooldown=10;e.fired=.15;emit(s,'enemyShot',e);if((e.id+Math.floor(s.time))%5===0&&!q.wardCarried){p.health=Math.max(0,p.health-(s.difficulty==='story'?4:9));s.lastDamage=s.time;emit(s,'hurt');}}}}
 if(priceCarrying(s)){const b=PRICE_LEVELS[s.level].bounds;let x=p.x+Math.cos(p.yaw)*.7,z=p.z-Math.sin(p.yaw)*.7;if(collide(s,x,z,.25,0)){x=p.x;z=p.z;}x=Math.max(b[0]+.3,Math.min(b[1]-.3,x));z=Math.max(b[2]+.3,Math.min(b[3]-.3,z));if(s.level==='guilfordfield'){q.wardX=x;q.wardZ=z;}else{q.strangerX=x;q.strangerZ=z;}}
 if(priceFollowing(s)){const center=q.crew.reduce((a,n)=>({x:a.x+n.x/3,z:a.z+n.z/3}),{x:0,z:0});if(dist(center,p)<13){const [x,z]=[[-20,-10],[-20,16],[0,25]][Math.min(2,s.stage-4)];q.crew.forEach((a,i)=>move(s,a,x+(i-1)*2,z,dt,2.2,collide));if(q.crew.every(a=>dist(a,{x,z})<5))q.crewLeg=Math.max(q.crewLeg,s.stage-3);}}
}
export function priceContext(s){const q=s.price;if(priceFighting(s))return 'Hold the marked lane while people withdraw. Use cover and reload; E buys room with section fire.';if(priceCarrying(s))return s.level==='guilfordfield'?'Ward cannot stand. Support him to Mara behind the rear cover.':'The wounded man is leaning on you. Bring him to care.';if(priceFollowing(s))return 'Keep the surviving crew close. Each turn waits for their actual arrival.';if(priceCart(s))return 'Walk beside the flour cart. Space holds the brake. The load moves only with your help.';if(s.level==='priceprovision')return 'Bring the account to the merchant. Choose work or linen; complete the actual delivery.';return q.wardShot?'Ward was struck helping the militia soldier. He is still at the wall; the carry remains to be done.':'Greene’s army must leave this field with people still able to march.';}
