import test from 'node:test';import assert from 'node:assert/strict';
import {fresh,tick,collide,currentGoal,goalNear,snapshot,restore} from './c6-sim.mjs';
import {priceCanUse,priceCarrying,priceFollowing} from './c6-price.mjs';
import {LEVELS,SCENES,LINES,continueProgress} from './c6-data.mjs';
import {rememberOutcome,rememberScene,cleanRecord} from './c6-record.mjs';
const step=(s,input={},sec=1)=>{const events=[];for(let i=0;i<sec/.025;i++)events.push(...tick(s,input,.025));return events;};
function walk(s,x,z){const key=p=>p.x+','+p.z,start={x:Math.round(s.player.x),z:Math.round(s.player.z)},queue=[start],parents=new Map([[key(start),null]]);let end;
 for(let i=0;i<queue.length&&i<45000;i++){const p=queue[i];if(p.x===Math.round(x)&&p.z===Math.round(z)){end=p;break;}for(const [dx,dz] of [[1,0],[-1,0],[0,1],[0,-1]]){const n={x:p.x+dx,z:p.z+dz};if(parents.has(key(n))||collide(s,n.x,n.z,.3,0))continue;parents.set(key(n),p);queue.push(n);}}assert.ok(end,'walkable '+x+','+z);const path=[];while(end){path.unshift(end);end=parents.get(key(end));}
 for(const p of path)for(let i=0;i<100&&Math.hypot(p.x-s.player.x,p.z-s.player.z)>.15;i++){s.player.yaw=0;tick(s,{right:p.x-s.player.x>.1,left:p.x-s.player.x<-.1,back:p.z-s.player.z>.1,forward:p.z-s.player.z<-.1},.025);assert.equal(s.failed,false,'survives walking stage '+s.stage);}assert.ok(Math.hypot(s.player.x-x,s.player.z-z)<.6,'arrived '+x+','+z);}
function use(s){assert.ok(goalNear(s),'near stage '+s.stage);assert.ok(priceCanUse(s),'usable stage '+s.stage);const stage=s.stage,ev=step(s,{interact:true},currentGoal(s).time+.2);assert.equal(s.stage,stage+1);return ev;}
function go(s){const g=currentGoal(s);walk(s,g.x,g.z);return use(s);}
function provision(agreement){let s=fresh('priceprovision');go(s);go(s);walk(s,agreement==='work'?-12:12,-5);use(s);assert.equal(s.price.agreement,agreement);if(agreement==='work'){for(let i=0;i<6000&&s.price.cartLeg<2;i++){const q=s.price;walk(s,q.cartX,q.cartZ);step(s,{},.35);}assert.equal(s.price.cartLeg,2);}go(s);s=restore(snapshot(s));go(s);assert.ok(s.finished&&s.price.delivered&&s.price.stateNote);assert.equal(s.carrying,false);return s;}
test('both provision agreements require the actual delivery and preserve a distinct completed account',()=>{for(const agreement of ['work','linen']){const s=provision(agreement),r={};rememberOutcome(r,s);assert.equal(r.outcomes.priceprovision.provisionAgreement,agreement);assert.ok(r.outcomes.priceprovision.provisionDelivered&&r.outcomes.priceprovision.stateNote);assert.equal(r.outcomes.priceprovision.rescues,0);}});
test('flour cart cannot move remotely, jump while braked, or satisfy a distant delivery',()=>{const s=fresh('priceprovision');s.stage=3;s.price.agreement='work';step(s,{},3);assert.equal(s.price.cartX,-12);s.player.x=-12;s.player.z=-5;step(s,{jump:true},2);assert.equal(s.price.cartX,-12);assert.equal(s.player.y,0);s.player.x=8;s.player.z=-27;step(s,{interact:true},3);assert.equal(s.price.delivered,false);assert.equal(s.stage,3);});
test('local field withdrawal moves six people, strikes Ward, saves a resumable wound checkpoint and carries him physically',()=>{let s=fresh('guilfordfield');go(s);go(s);walk(s,0,-28);step(s,{interact:true,crouch:true},37);assert.equal(s.stage,3);assert.equal(s.price.passage.filter(a=>a.z>17).length,6);assert.ok(s.price.line===36);const ev=go(s);assert.ok(ev.some(e=>e.type==='checkpoint')&&ev.some(e=>e.type==='priceScene'&&e.key==='priceHit'));assert.ok(s.price.wardShot&&!s.price.wardCarried&&!s.price.wardCover);s=restore(snapshot(s));assert.ok(s&&s.stage===4&&s.price.wardShot);go(s);assert.ok(priceCarrying(s)&&s.carrying&&!s.armed);walk(s,0,20);assert.ok(Math.hypot(s.price.wardX,s.price.wardZ-20)<1.5);use(s);assert.ok(s.finished&&s.price.wardCover);const r={};rememberOutcome(r,s);assert.equal(r.outcomes.guilfordfield.rescues,0,'carrying Ward does not claim he survived');assert.equal(r.outcomes.guilfordfield.wardBroughtToCare,true);});
test('field timer cannot advance away from the lane and section fire needs a second command',()=>{const s=fresh('guilfordfield');go(s);go(s);step(s,{interact:true},40);assert.equal(s.price.line,0);assert.equal(s.stage,2);walk(s,0,-28);step(s,{interact:true},.1);const killed=s.enemies.filter(e=>e.hp<=0).length;step(s,{interact:true},10);assert.equal(s.enemies.filter(e=>e.hp<=0).length,killed);step(s,{},.1);step(s,{interact:true},.1);assert.equal(s.enemies.filter(e=>e.hp<=0).length,killed+1);});
test('wounded stranger reaches care and three actual survivors accompany every covered turn without Ward',()=>{let s=fresh('guilfordexit');assert.equal(s.price.wardDead,true);go(s);go(s);assert.ok(priceCarrying(s));go(s);assert.equal(s.price.strangerSafe,true);s=restore(snapshot(s));go(s);assert.ok(priceFollowing(s)&&s.price.crew.length===3);for(let n=0;n<3;n++){const g=currentGoal(s);walk(s,g.x,g.z);for(let i=0;i<3000&&!priceCanUse(s);i++)tick(s,{},.025);use(s);}assert.ok(s.finished&&s.price.crewSafe&&s.price.wardDead);const r={};rememberOutcome(r,s);assert.equal(r.outcomes.guilfordexit.rescues,1);assert.ok(r.outcomes.guilfordexit.guilfordCrewSafe&&r.outcomes.guilfordexit.strangerBroughtToCare);});
test('distant survivors cannot finish a turn and a carried person stays within valid world bounds',()=>{const s=fresh('guilfordexit');s.stage=4;s.price.crew=[-2,0,2].map(x=>({x,z:-24,yaw:0}));s.player.x=-20;s.player.z=-10;step(s,{interact:true},3);assert.equal(s.stage,4);assert.equal(priceCanUse(s),false);s.stage=2;s.price.stranger=true;s.carrying=true;s.player.x=37.6;s.player.z=33.6;s.player.yaw=0;step(s,{},.1);assert.ok(restore(snapshot(s)));assert.equal(collide(s,s.price.strangerX,s.price.strangerZ,.25,0),false);});
test('watched or skipped treatment and burial record the same fate, with separate watch records',()=>{for(const skipped of [false,true]){const r={};rememberScene(r,'priceTreatment',skipped);rememberScene(r,'priceBurial',skipped);const clean=cleanRecord(r,LEVELS,SCENES);assert.equal(clean.story.wardFate,'dead');assert.equal(clean.story.wardBuried,true);assert.equal(r.seen.includes('priceTreatment'),!skipped);assert.equal(r.skipped.includes('priceTreatment'),skipped);}assert.equal(cleanRecord({story:{wardFate:'alive',wardBuried:1}},LEVELS,SCENES).story.wardFate,'');});
test('malformed price saves are rejected and earlier completed campaigns continue into Guilford',()=>{const raw=snapshot(fresh('guilfordfield'));assert.ok(restore(raw));for(const patch of [{agreement:'gold'},{wardX:99},{cartZ:-999},{line:37},{volley:8},{wardDead:1},{crew:[{x:0,z:0,yaw:NaN}]},{passage:[{x:0,z:0,yaw:NaN}]}]){const bad=structuredClone(raw);Object.assign(bad.price,patch);assert.equal(restore(bad),null);}assert.equal(continueProgress({complete:true,completedPart:'chase',seen:['chaseEnding']}).scene,'priceIntro');const done={complete:true,completedPart:'price',seen:['priceEnding']};assert.equal(continueProgress(done).scene,'seaIntro');assert.equal(SCENES.chaseEnding.after,'priceIntro');assert.equal(SCENES.priceHit.after,'checkpoint');assert.equal(SCENES.priceTreatment.after,'priceAfter');assert.equal(SCENES.priceEnding.after,'seaIntro');});
test('Guilford dates, separate field and human consequences, and attributed currency example remain explicit',()=>{assert.match(SCENES.priceField.place,/MARCH 15, 1781/);assert.match(SCENES.priceBurial.place,/MARCH 16, 1781/);const text=LINES.filter(l=>l.id.startsWith('price.')).map(l=>l.text).join(' ');for(const phrase of ['Continental currency','borrowing in Europe','gold and silver','one hundred forty-six','reported example','not a fixed rate','states printed','Not worth a Continental','holds the Guilford field','British paid heavily','Greene’s army','hill outside Boston','after March eighteenth','Wilmington','Virginia','southern interior','stopped breathing','Elias Ward'])assert.ok(text.includes(phrase),phrase);});
