import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {QUESTIONS,QUESTION_BY_ID,TOPICS,pool,createRound,cleanRound,freshStudy,cleanStudy,answerStudy,nextStudy,missedIds,summary} from './c6-questions.mjs';
const rng=()=>{let seed=713;return()=>((seed=(Math.imul(seed,1664525)+1013904223)>>>0)/4294967296);};
const choose=(s,correct)=>{const d=s.round.deck[s.round.index],q=QUESTION_BY_ID.get(d.id);return d.order.indexOf(correct?q.correct:1);};
test('question bank covers all 54 source paragraphs, ten terms, and four sections without fiction',()=>{
 const ids=[3,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,23,24,25,26,27,28,29,30,31,32,33,34,35,37,38,39,40,41,42,43,44,45,47,48,49,50,51,52,53,54,55,56,57,58,59,60].map(n=>'P'+String(n).padStart(3,'0'));
 assert.deepEqual([...new Set(QUESTIONS.map(q=>q.paragraph))],ids);assert.equal(QUESTIONS.length,80);assert.equal(QUESTION_BY_ID.size,80);
 assert.deepEqual(pool('terms').map(q=>q.term),['minutemen','Mecklenburg Resolves','Dunmore’s Proclamation','republicanism','popular sovereignty','thirteen colonies','Hessians','Yorktown','confiscation acts','Continental currency']);
 for(const q of QUESTIONS){assert.equal(q.options.length,4);assert.equal(new Set(q.options).size,4);assert.ok(q.prompt.trim()&&q.explanation.trim());assert.ok(TOPICS.slice(2).some(([t])=>t===q.topic));assert.doesNotMatch(q.prompt,/Ward|Rowan|Mara|Isaiah|Jonas|Nathan/);assert.doesNotMatch(q.prompt+q.explanation,/\uFFFD/);if(q.reference)assert.match(q.reference[1],/^https:\/\//);}
});
test('whole-chapter practice balances all sections and shuffles unique questions and choices',()=>{
 const r=createRound({count:15,rng:rng()});assert.equal(r.deck.length,15);assert.equal(new Set(r.deck.map(d=>d.id)).size,15);
 const counts=TOPICS.slice(2).map(([t])=>r.deck.filter(d=>QUESTION_BY_ID.get(d.id).topic===t).length);assert.ok(counts.every(n=>n>=3&&n<=4));
 for(const d of r.deck)assert.deepEqual([...d.order].sort(),[0,1,2,3]);assert.ok(new Set(r.deck.map(d=>d.order.indexOf(0))).size>=3);
 assert.notDeepEqual(r.deck,createRound({count:15,rng:()=>.9}).deck);assert.ok(cleanRound(r));
});
test('topic and key-term rounds contain only requested questions and cap length at the pool',()=>{for(const [topic]of TOPICS){const r=createRound({topic,count:'all',rng:rng()});assert.equal(r.deck.length,pool(topic).length);assert.ok(r.deck.every(d=>pool(topic).some(q=>q.id===d.id)));assert.ok(cleanRound(r));}assert.equal(createRound({topic:'terms',count:30}).deck.length,10);assert.equal(createRound({count:1}).deck.length,1);});
test('an answer scores the displayed choice, locks once, and cannot advance before an answer',()=>{let s={...freshStudy(),round:createRound({count:2,rng:rng()})};assert.equal(nextStudy(s),s);assert.equal(answerStudy(s,-1),s);s=answerStudy(s,choose(s,false));assert.equal(summary(s.round).right,0);assert.equal(missedIds(s).length,1);const answered=s;s=answerStudy(s,choose(s,true));assert.equal(s,answered);s=nextStudy(s);s=answerStudy(s,choose(s,true));assert.equal(summary(s.round).right,1);s=nextStudy(s);assert.equal(s.round.finished,true);assert.equal(summary(s.round).answered,2);assert.equal(nextStudy(s),s);});
test('missed review rechecks actual misses and clears them after a correct retry',()=>{let s={...freshStudy(),round:createRound({count:4,rng:rng()})};for(let i=0;i<4;i++){s=answerStudy(s,choose(s,i%2===0));s=nextStudy(s);}const ids=missedIds(s);assert.equal(ids.length,2);s={...s,round:createRound({ids,count:'all',rng:rng()})};assert.equal(s.round.kind,'missed');assert.deepEqual(s.round.deck.map(d=>d.id).sort(),[...ids].sort());for(let i=0;i<2;i++){s=answerStudy(s,choose(s,true));s=nextStudy(s);}assert.equal(missedIds(s).length,0);for(const id of ids)assert.deepEqual(s.attempts[id],{right:1,wrong:1,lastCorrect:true});});
test('reload retains the question, displayed choice order, feedback and later completion',()=>{let s={...freshStudy(),round:createRound({topic:'6.3',count:3,rng:rng()})};s=answerStudy(s,choose(s,false));s=nextStudy(s);s=answerStudy(s,choose(s,true));const loaded=cleanStudy(JSON.parse(JSON.stringify(s)));assert.deepEqual(loaded,s);assert.equal(loaded.round.index,1);assert.equal(loaded.round.answers.length,2);const tampered=structuredClone(s);tampered.round.answers[0].correct=true;assert.equal(cleanStudy(tampered).round.answers[0].correct,false);});
test('malformed and obsolete study saves fail closed without loading campaign records',()=>{const r=createRound({count:3,rng:rng()});const mutate=[x=>x.bankVersion=99,x=>x.index=-1,x=>x.index=3,x=>x.finished=true,x=>x.deck[1].id=x.deck[0].id,x=>x.deck[0].id='unknown',x=>x.deck[0].order=[0,0,2,3],x=>x.answers=[{id:x.deck[0].id,option:NaN}],x=>x.answers=[{id:x.deck[1].id,option:0}],x=>x.index=2];for(const f of mutate){const bad=structuredClone(r);f(bad);assert.equal(cleanRound(bad),null);}assert.deepEqual(cleanStudy({version:1,checkpoint:{level:'night'},outcomes:{},round:null}),freshStudy());assert.deepEqual(cleanStudy({version:99}),freshStudy());assert.deepEqual(cleanStudy({version:1,attempts:{[QUESTIONS[0].id]:{right:Infinity,wrong:0,lastCorrect:true},madeup:{right:1,wrong:0,lastCorrect:true}}}).attempts,{});});
test('historical qualifications remain explicit and link primary checks',()=>{const byP=p=>QUESTIONS.filter(q=>q.paragraph===p);assert.ok(byP('P043').some(q=>q.explanation.includes('September 28')&&q.explanation.includes('October 19')&&q.reference));assert.ok(byP('P043').some(q=>q.explanation.includes('tradition')&&q.reference));assert.ok(byP('P029').some(q=>q.explanation.includes('disease')&&q.reference));assert.ok(byP('P015').some(q=>q.explanation.includes('not a universal abolition')));assert.ok(byP('P045').some(q=>q.explanation.includes('not an automatic')));assert.ok(byP('P053').some(q=>q.explanation.includes('not everyone present was a combatant')));});
test('main-menu entry and separate study storage do not write campaign checkpoint state',()=>{const source=fs.readFileSync(new URL('./c6.mjs',import.meta.url),'utf8');assert.ok(source.includes("btn('Questions','study-open','secondary')"));assert.ok(source.includes("SAVE_KEY+'-questions-v1'"));const ui=fs.readFileSync(new URL('./c6-study.mjs',import.meta.url),'utf8');assert.doesNotMatch(ui,/saved\.checkpoint|saved\.scene|SAVE_KEY|speechSynthesis|AudioContext/);});
