// Dated, fictional local relief work inside the historical Charleston defeat.
const goal=(x,z,label,verb,time=1.2)=>({x,z,label,verb,time});
export const SOUTH_LEVELS={
 charlestondock:{title:'The South Breaks',place:'CHARLESTON · APRIL 1, 1780 · ROWAN VALE · SIEGE PHASE I',spawn:[0,25],bounds:[-36,36,-70,34],music:'south',mode:'RELIEF ARRIVAL / LOCAL DEFENSE',intro:'southIntro',after:'southFirst',description:'Bring a relief packet into Charleston, meet people arriving for different reasons and hold one local passage while the hospital supplies move.',goals:[goal(-4,19,'Take Ward’s relief packet','Take the packet'),goal(-18,11,'Reach Bennett at the Georgia dock','Hear why he came'),goal(17,5,'Meet the Creek visitor under safe passage','Listen at the marked parley'),goal(-3,-4,'Deliver the enlistment proposal to the clerk','Hear the rejected proposal'),goal(15,-14,'Secure the hospital’s powder crate','Take the covered crate'),goal(0,-29,'Brace the local defense before moving the supplies','Brace the earthwork',2),goal(0,-29,'Keep the hospital passage open','Direct a covering volley',0),goal(0,22,'Rejoin Samuel at the relief landing','Rejoin the relief crew')]},
 charlestonring:{title:'The Roads Close',place:'CHARLESTON · APRIL 14, 1780 · ROWAN VALE · SIEGE PHASE II',spawn:[0,25],bounds:[-36,36,-70,34],music:'south',mode:'SHELLFIRE / PATIENT CART / ENCIRCLEMENT',intro:'southRing',after:'southHospital',description:'The western road used earlier is closed. Bring two patients to the hospital cart, prepare its wheels and accompany the loaded cart down the eastern lane.',goals:[goal(-5,20,'Take Samuel’s hospital order','Take the patient roll'),goal(-18,-31,'Support the first wounded man','Support him'),goal(14,-33,'Put him onto the waiting hospital cart','Lower him onto the cart'),goal(3,-49,'Support the second wounded man','Support him'),goal(14,-33,'Bring him back to the same cart','Lower him beside the first man'),goal(14,-33,'Free and brace the hospital cart’s wheel','Clear the wheel',2.5),goal(0,22,'Walk the cart down the open eastern lane','Wait for the cart at the landing',1.5)]},
 charlestonlast:{title:'The Last Lantern',place:'CHARLESTON · MAY 9–12, 1780 · ROWAN VALE · SIEGE PHASE III',spawn:[0,25],bounds:[-36,36,-70,34],music:'southnight',mode:'BOMBARDMENT / RUBBLE / SURRENDER',intro:'southNight',after:'southSurrender',description:'Move under warned shellfire, physically cut through fallen timber and escort a civilian to the quay. The army’s surrender follows; this relief work cannot stop it.',goals:[goal(-4,19,'Take the last civilian shelter list','Take the list'),goal(19,-8,'Reach the fallen timber across the eastern lane','Take the rescue axe'),goal(19,-8,'Cut the fallen timber to reopen the shelter road','Strike inside the pale band',0),goal(19,-36,'Bring the civilian out of the shuttered shelter','Call her to the lantern'),goal(0,22,'Guide her to the small civilian landing','Wait for her at the quay'),goal(-5,20,'Set down your weapon with the relief papers','Lay down the musket',1.5)]},
 charlestonharbor:{title:'Under the Prison Ships',place:'CHARLESTON HARBOR · MAY 13, 1780 · ISAIAH MERCER · A FICTIONAL CIVILIAN PASSAGE',spawn:[0,22],bounds:[-44,44,-188,30],music:'southnight',mode:'ISAIAH · HARBOR STEALTH / SIGNAL / ESCAPE',intro:'southHarbor',after:'southEnding',description:'Hear Jonas’s chosen course, carry the civilian list, and take Isaiah’s small boat through guarded water. Signal across to Samuel’s prison hulk, then leave by the sheltered channel.',goals:[goal(-4,18,'Take Jonas’s message at the separate quay','Take the message'),goal(0,10,'Take the steering oar and the civilian list','Take the steering oar'),goal(-22,-45,'Reach the sheltered signal post','Take the shore signal',1.5),goal(18,-98,'Signal the hospital orderly’s prison ship','Wait for Samuel’s answering lantern',2),goal(-19,-132,'Wait in the sheltered western channel','Wait until the patrol turns away',0),goal(0,-170,'Bring the small civilian boat beyond the guarded harbor','Take the last landing rope',1.5)]},
};
const CITY_BLOCKS=[[-28,14,9,12,6],[27,15,10,11,6],[-10,-17,12,12,6],[28,-26,8,14,6],[-28,-41,9,14,6],[3,-37,8,12,6],[0,-25,11,1,1.2],[9,-52,10,1,1.25],[-23,-3,7,1,1.2]];
export const SOUTH_BLOCKS={charlestondock:CITY_BLOCKS,charlestonring:CITY_BLOCKS,charlestonlast:CITY_BLOCKS,charlestonharbor:[[0,-43,12,12,.8],[-34,-82,10,16,.8],[31,-111,12,16,.8],[0,-137,12,12,.8],[31,-94,5,17,.8]]};
const dist=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),angle=v=>Math.atan2(Math.sin(v),Math.cos(v)),emit=(s,type,data={})=>s.events.push({type,...data}),say=(s,id)=>emit(s,'voice',{id});
export function freshSouth(){return {packet:false,georgia:false,parley:false,proposal:false,powder:false,braced:false,line:0,volley:0,patients:0,carried:-1,cartReady:false,cartX:14,cartZ:-35,cartLeg:0,cartDelivered:false,list:false,axe:false,cuts:0,axePhase:0,axeHeld:false,axeFlash:0,civilian:false,civilianX:19,civilianZ:-36,civilianLeg:0,civilianSafe:false,disarmed:false,message:false,aboard:false,moored:true,boatX:0,boatZ:10,boatYaw:0,vx:0,vz:0,speed:0,impacts:0,bump:0,hull:100,signal:false,answered:false,coverTime:0,clear:false,exposure:0,patrolX:25,patrolZ:-91,patrolYaw:0,warning:0,shellClock:7,shellIn:0,shellX:0,shellZ:0,travel:0};}
export function validSouth(q,b){return !!q&&['packet','georgia','parley','proposal','powder','braced','cartReady','cartDelivered','list','axe','axeHeld','civilian','civilianSafe','disarmed','message','aboard','moored','signal','answered','clear'].every(k=>typeof q[k]==='boolean')&&['line','volley','patients','carried','cartX','cartZ','cartLeg','cuts','axePhase','axeFlash','civilianX','civilianZ','civilianLeg','boatX','boatZ','boatYaw','vx','vz','speed','impacts','bump','hull','coverTime','exposure','patrolX','patrolZ','patrolYaw','warning','shellClock','shellIn','shellX','shellZ','travel'].every(k=>Number.isFinite(q[k]))&&['line','volley','axeFlash','bump','warning','shellClock','shellIn','travel'].every(k=>q[k]>=0&&q[k]<1000000)&&Number.isInteger(q.patients)&&q.patients>=0&&q.patients<=2&&[-1,0,1].includes(q.carried)&&Number.isInteger(q.cuts)&&q.cuts>=0&&q.cuts<=3&&q.axePhase>=0&&q.axePhase<=1&&Number.isInteger(q.cartLeg)&&q.cartLeg>=0&&q.cartLeg<=3&&Number.isInteger(q.civilianLeg)&&q.civilianLeg>=0&&q.civilianLeg<=3&&q.speed>=0&&q.speed<=5.51&&q.hull>=1&&q.hull<=100&&q.coverTime>=0&&q.coverTime<=6.1&&q.exposure>=0&&q.exposure<=1&&Number.isInteger(q.impacts)&&q.impacts>=0&&q.impacts<10000&&[['cartX','cartZ'],['civilianX','civilianZ'],['boatX','boatZ']].every(([x,z])=>q[x]>=b[0]&&q[x]<=b[1]&&q[z]>=b[2]&&q[z]<=b[3]);}
export const southBoating=s=>s.level==='charlestonharbor'&&s.south?.aboard;
export const southFighting=s=>s.level==='charlestondock'&&s.stage===6;
export const southCutting=s=>s.level==='charlestonlast'&&s.stage===2&&Math.hypot(s.player.x-19,s.player.z+8)<2.5;
export const southEscorting=s=>s.level==='charlestonring'&&s.south?.cartReady&&!s.south.cartDelivered||s.level==='charlestonlast'&&s.south?.civilian&&!s.south.civilianSafe;
export const southOperating=s=>southFighting(s)||s.level==='charlestonlast'&&s.stage===2||s.level==='charlestonharbor'&&s.stage===4;
export function southWaterBlocked(s,x,z,r,feet){if(s.level==='charlestonharbor'&&!s.south.aboard&&feet<.5)return !(Math.abs(x)<5.7-r&&z>6);if(s.level==='charlestonring'&&Math.abs(x+19)<5+r&&Math.abs(z+3)<.7+r)return true;if(s.level==='charlestonlast'&&s.south.cuts<3&&Math.abs(x-19)<6+r&&Math.abs(z+12)<.65+r)return true;return false;}
export const southGoal=s=>SOUTH_LEVELS[s.level].goals[s.stage];
export const southNear=s=>!!southGoal(s)&&dist(s.player,southGoal(s))<(southBoating(s)?5:2.5);
export function southCanUse(s){const q=s.south;if(southOperating(s))return false;if(southBoating(s)&&q.speed>1.1)return false;if(s.level==='charlestonring'&&s.stage===6)return q.cartReady&&q.cartLeg===3&&dist({x:q.cartX,z:q.cartZ},{x:0,z:22})<3;if(s.level==='charlestonlast'&&s.stage===4)return q.civilian&&q.civilianLeg===3&&dist({x:q.civilianX,z:q.civilianZ},{x:0,z:22})<3;return true;}
function next(s){s.stage++;s.hold=0;emit(s,'checkpoint');if(s.stage>=SOUTH_LEVELS[s.level].goals.length){s.finished=true;emit(s,'finish');}}
export function interactSouth(s){const q=s.south,st=s.stage;
 if(s.level==='charlestondock'){
  if(st===0){q.packet=true;say(s,'south.packet');}if(st===1){q.georgia=true;say(s,'south.georgia');}if(st===2){q.parley=true;say(s,'south.creek');}if(st===3){q.proposal=true;say(s,'south.proposal');}if(st===4){q.powder=true;s.armed=true;s.ammo=12;say(s,'south.powder');}if(st===5){q.braced=true;s.enemies=Array.from({length:7},(_,i)=>({id:i,x:(i%4-1.5)*5,z:-56-Math.floor(i/4)*4,hp:1,yaw:Math.PI,cooldown:6+i*.7,dead:0,fired:0,moving:false,route:[0,-40]}));say(s,'south.brace');}if(st===7)say(s,'south.return');
 }else if(s.level==='charlestonring'){
  if(st===0)say(s,'south.hospital');if(st===1||st===3){s.carrying=true;q.carried=st===1?0:1;say(s,'south.patient.'+q.carried);}if(st===2||st===4){s.carrying=false;q.carried=-1;q.patients++;s.player.health=Math.min(100,s.player.health+20);say(s,'south.cart.'+q.patients);}if(st===5){q.cartReady=true;say(s,'south.wheel');}if(st===6){q.cartDelivered=true;say(s,'south.cart.safe');}
 }else if(s.level==='charlestonlast'){
  if(st===0){q.list=true;say(s,'south.list');}if(st===1){q.axe=true;q.axePhase=0;say(s,'south.axe');}if(st===3){q.civilian=true;say(s,'south.civilian');}if(st===4){q.civilianSafe=true;say(s,'south.civilian.safe');}if(st===5){q.disarmed=true;s.armed=false;say(s,'south.disarm');}
 }else{
  if(st===0){q.message=true;say(s,'south.message');}if(st===1){q.aboard=true;q.moored=false;s.player.x=q.boatX;s.player.z=q.boatZ;s.armed=false;say(s,'south.oar');}if(st===2){q.signal=true;say(s,'south.signal');}if(st===3){q.answered=true;say(s,'south.answer');}if(st===5){q.moored=true;q.speed=q.vx=q.vz=0;say(s,'south.harbor.safe');}
 }next(s);
}
export function southPatrolAt(t){return {x:25+Math.sin(t*.12)*5,z:-92+Math.sin(t*.09)*20,yaw:Math.sin(t*.16)>.15?Math.PI/2:-Math.PI/2};}
export const southSheltered=q=>q.boatX<-12&&q.boatZ<-122&&q.boatZ>-151&&q.speed<1.4;
export function moveSouthBoat(s,input,dt,collide){const q=s.south,p=s.player;if(q.moored)return;q.bump=Math.max(0,q.bump-dt);q.boatYaw=angle(q.boatYaw+(((input.left||input.leftTap)?1:0)-((input.right||input.rightTap)?1:0))*dt*.85);const brake=input.back||input.jump;if(input.forward&&!brake){q.vx-=Math.sin(q.boatYaw)*dt*(input.sprint?5:3.4);q.vz-=Math.cos(q.boatYaw)*dt*(input.sprint?5:3.4);}q.vx*=Math.exp(-dt*(brake?5:1.25));q.vz*=Math.exp(-dt*(brake?5:1.25));const speed=Math.hypot(q.vx,q.vz);if(speed>5.5){q.vx*=5.5/speed;q.vz*=5.5/speed;}const nx=q.boatX+q.vx*dt,nz=q.boatZ+q.vz*dt;if(collide(s,nx,nz,1.2,0)){q.vx*=-.25;q.vz*=-.25;if(q.bump===0){q.bump=1.5;q.impacts++;q.hull=Math.max(1,q.hull-7);say(s,'south.ground');emit(s,'wood');}}else{q.travel+=Math.hypot(nx-q.boatX,nz-q.boatZ);q.boatX=nx;q.boatZ=nz;}q.speed=Math.hypot(q.vx,q.vz);p.x=q.boatX;p.z=q.boatZ;}
function approach(s,a,tx,tz,dt,pace,collide){const d=dist(a,{x:tx,z:tz}),step=Math.min(d,dt*pace),nx=a.x+(tx-a.x)/(d||1)*step,nz=a.z+(tz-a.z)/(d||1)*step;if(!collide(s,nx,nz,.4,0)){a.x=nx;a.z=nz;}else{if(!collide(s,nx,a.z,.4,0))a.x=nx;if(!collide(s,a.x,nz,.4,0))a.z=nz;}}
export function updateSouth(s,input,dt,{collide,blocked}){const q=s.south,p=s.player;q.volley=Math.max(0,q.volley-dt);q.axeFlash=Math.max(0,q.axeFlash-dt);q.warning=Math.max(0,q.warning-dt);
 if(southFighting(s)){const present=dist(p,{x:0,z:-29})<12;if(present){q.line+=dt;const e=s.enemies.find(e=>e.hp>0);if(input.interact&&q.volley===0){q.volley=6;emit(s,'orderUsed');if(e){e.hp=0;emit(s,'southVolley');}}if(Math.floor(q.line/8)>Math.floor((q.line-dt)/8)&&e){e.hp=0;emit(s,'southVolley');}}for(const e of s.enemies){e.fired=Math.max(0,e.fired-dt);if(e.hp<=0){e.dead+=dt;continue;}e.cooldown-=dt;e.aiming=e.cooldown<1.3;if(e.cooldown<=0&&dist(e,p)<48&&!blocked(s.level,{...e,y:1.4},{...p,y:input.crouch?1:1.7})){e.fired=.2;e.cooldown=8;emit(s,'enemyShot',e);if((e.id+Math.floor(s.time))%4===0){p.health=Math.max(0,p.health-(s.difficulty==='story'?4:8));s.lastDamage=s.time;emit(s,'hurt');}}}if(present&&q.line>=35&&s.enemies.every(e=>e.hp<=0)){say(s,'south.held');next(s);}return;}
 if(s.level==='charlestonring'||s.level==='charlestonlast'){
  q.shellClock-=dt;if(q.shellClock<=0&&q.shellIn===0){q.shellClock=11;q.shellIn=2.6;q.shellX=p.x;q.shellZ=p.z;emit(s,'southShellWarning',{x:p.x,z:p.z});}if(q.shellIn>0){q.shellIn=Math.max(0,q.shellIn-dt);if(q.shellIn===0){emit(s,'shell',{x:q.shellX,z:q.shellZ});if(dist(p,{x:q.shellX,z:q.shellZ})<2.7){p.health=Math.max(1,p.health-(s.difficulty==='story'?8:18));s.lastDamage=s.time;emit(s,'hurt');}}}
  if(s.level==='charlestonring'&&q.cartReady&&!q.cartDelivered){const a={x:q.cartX,z:q.cartZ},path=[[19,-8],[19,12],[0,22]],[x,z]=path[q.cartLeg]||path[2];if(dist(p,a)<10&&!input.jump){approach(s,a,x,z,dt,1.85,collide);q.cartX=a.x;q.cartZ=a.z;if(dist(a,{x,z})<.8&&q.cartLeg<3){q.cartLeg++;emit(s,'checkpoint');}}}
  if(s.level==='charlestonlast'){
   if(s.stage===2){q.axePhase=(q.axePhase+dt*.48)%1;const pressed=(input.jump||input.strike)&&!q.axeHeld;q.axeHeld=!!(input.jump||input.strike);if(pressed&&southCutting(s)){q.axeFlash=.45;emit(s,'axeStroke');if(q.axePhase>=.39&&q.axePhase<=.64){q.cuts++;emit(s,'checkpoint');if(q.cuts===3){say(s,'south.timber');emit(s,'wood');next(s);}}else say(s,'south.miss');}}
   if(q.civilian&&!q.civilianSafe){const a={x:q.civilianX,z:q.civilianZ},path=[[19,-4],[19,12],[0,22]],[x,z]=path[q.civilianLeg]||path[2];if(dist(p,a)<10){approach(s,a,x,z,dt,2.1,collide);q.civilianX=a.x;q.civilianZ=a.z;if(dist(a,{x,z})<.8&&q.civilianLeg<3){q.civilianLeg++;emit(s,'checkpoint');}}}
  }return;
 }
 if(southBoating(s)){const patrol=southPatrolAt(s.time);q.patrolX=patrol.x;q.patrolZ=patrol.z;q.patrolYaw=patrol.yaw;const bearing=Math.atan2(-(p.x-patrol.x),-(p.z-patrol.z)),seen=dist(p,patrol)<31&&Math.abs(angle(bearing-patrol.yaw))<.6&&!blocked(s.level,{...patrol,y:.9},{...p,y:.8});q.exposure=clamp(q.exposure+dt*(seen&&!southSheltered(q)?.24:-.35),0,1);if(q.exposure>.7&&q.warning===0){q.warning=8;emit(s,'navalShot',patrol);q.hull=Math.max(1,q.hull-6);say(s,'south.lantern');}if(s.stage===4){if(southSheltered(q)&&q.exposure<.1){q.coverTime=Math.min(6,q.coverTime+dt);}else q.coverTime=Math.max(0,q.coverTime-dt);if(q.coverTime>=6){q.clear=true;say(s,'south.channel');next(s);}}}
}
export function southContext(s){const q=s.south;if(southFighting(s))return 'Stay with the hospital passage. E calls a volley; F fires, R reloads and C lowers you behind the earthwork.';if(southCutting(s))return 'Space strikes. Cut inside the pale band; three clean strokes open the road. WASD steps away.';if(southBoating(s))return s.stage===4?'West channel beyond the last shoal. Slow and stay out of the lantern until it turns away.':'W rows · A / D steer · S / Space steadies. Mouse and arrows look independently. E takes ropes only at low speed.';if(southEscorting(s))return s.level==='charlestonring'?'Stay within ten meters of the cart. Space stops it; normal walking matches its pace.':'Stay close to the civilian on the open eastern lane.';if(q.shellIn>0)return 'INCOMING SHELL · Leave the bright impact ring before it lands.';return s.level==='charlestonring'?'The western road is closed. Use the eastern lane and the cover beside the hospital.':s.level==='charlestonlast'?'The dates change between phases. Saving a few people cannot save Lincoln’s trapped army.':'The relief packet belongs to this dock. Listen to each person before moving the hospital supplies.';}
