const g=(x,z,label,verb,time=1.2)=>({x,z,label,verb,time});
export const SEA_LEVELS={
 capeschart:{title:'Two Edges of the Map',place:'LOWER CHESAPEAKE DEPOT · AUGUST 30, 1781 · ISAIAH MERCER',spawn:[0,25],bounds:[-35,35,-58,34],music:'seaquiet',mode:'ISAIAH / COALITION CHART / LOCAL PILOT PARTY',intro:'seaIntro',after:'seaRoad',description:'Read the separate land and sea approaches on a physical chart. Accompany Adrien and Lydia to the local boat and load the actual sealed dispatch.',goals:[g(-4,20,'Take the pilot order','Take the order'),g(8,4,'Place Yorktown and the British expectation','Set the port pin'),g(-8,-8,'Set the separate land approach','Set the land pin'),g(8,-17,'Set the fleet’s approach','Set the sea pin'),g(0,-44,'Bring both actual pilots to the boat','Wait for Adrien and Lydia',1.5),g(-3,-44,'Load the sealed coastal dispatch','Load the dispatch',1.5)]},
 capesrun:{title:'Close the Sea',place:'INSHORE COURIER REACH · SEPTEMBER 5, 1781 · ISAIAH MERCER',spawn:[0,25],bounds:[-48,48,-285,34],music:'sea',mode:'ISAIAH / COASTAL NAVIGATION / DISTANT FLEET BATTLE',intro:'seaRoad',after:'seaCrossed',description:'Steer a small inshore boat while the French and British fleets engage offshore. Hold in the lee, recover a rope, evade marked debris and deliver the local dispatch before docking slowly.',goals:[g(-4,20,'Take the coastal departure order','Take the order'),g(0,9,'Board with the two local pilots','Take the tiller'),g(-24,-66,'Hold slow in the western lee for four seconds','Check the sheltered reach'),g(-25,-114,'Stop beside the loose pilot rope','Recover the rope',1.5),g(8,-182,'Clear the marked reach and check the passage','Check the passage',1.5),g(-10,-225,'Deliver the local dispatch to the signal crew','Deliver the dispatch',1.5),g(0,-260,'Bring the actual boat slowly onto the landing rope','Dock the pilot boat',1.5)]},
 capesshore:{title:'The Trap Has Two Sides',place:'ALLIED COASTAL DEPOT · SEPTEMBER 27, 1781 · BEFORE THE INVESTMENT',spawn:[0,25],bounds:[-34,34,-52,34],music:'seaquiet',mode:'ISAIAH → ROWAN / SEA AND LAND / SIEGE STORES',intro:'seaArrival',after:'seaEnding',description:'Give Rowan the coastal packet. Keep the fleet and the land army separate on the chart, then carry local siege stores to the actual cart.',goals:[g(-4,20,'Hand the coastal dispatch to Rowan','Give the packet'),g(8,5,'Place the closed seaward route','Set the fleet pin'),g(-8,-9,'Place the land army and the chapter’s estimate','Set the land pin'),g(6,-24,'Take the local siege store bundle','Take the stores',1.5),g(-4,-39,'Deliver the actual stores to the cart','Load the cart',1.5)]},
};
export const SEA_BLOCKS={capeschart:[[-25,7,9,13,4],[25,-11,9,14,4],[-19,-28,9,1,1.2]],capesrun:[[15,-44,16,17,3],[-2,-89,19,15,2.4],[25,-125,18,20,3.4],[-25,-174,15,21,3.2],[27,-220,16,13,2.2]],capesshore:[[-24,7,9,13,4],[24,-15,9,14,4],[-20,-27,9,1,1.2]]};
const dist=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z),emit=(s,type,data={})=>s.events.push({type,...data}),say=(s,id)=>emit(s,'voice',{id});
const bound=(n,a,b)=>Math.max(a,Math.min(b,n)),angle=x=>Math.atan2(Math.sin(x),Math.cos(x));
export function freshSea(level){return {order:false,port:false,land:false,fleet:false,pilots:[],pilotsLoaded:false,sealed:false,mounted:false,boatX:0,boatZ:9,boatYaw:0,speed:0,hull:100,impacts:0,impactClock:0,lee:0,rope:false,passage:false,delivered:false,docked:false,chart:false,stores:false,loaded:false,wetness:0,warning:0,targetX:0,targetZ:0,shotClock:6,shotSide:0,crewMoving:false};}
export function validSea(q,b){return !!q&&['order','port','land','fleet','pilotsLoaded','sealed','mounted','rope','passage','delivered','docked','chart','stores','loaded','crewMoving'].every(k=>typeof q[k]==='boolean')&&['boatX','boatZ','boatYaw','speed','hull','impacts','impactClock','lee','wetness','warning','targetX','targetZ','shotClock','shotSide'].every(k=>Number.isFinite(q[k]))&&q.boatX>=b[0]&&q.boatX<=b[1]&&q.boatZ>=b[2]&&q.boatZ<=b[3]&&q.speed>=0&&q.speed<=8&&q.hull>=15&&q.hull<=100&&q.impacts>=0&&q.impacts<=10000&&q.impactClock>=0&&q.impactClock<=1.5&&q.lee>=0&&q.lee<=4&&q.wetness>=0&&q.wetness<=1&&q.warning>=0&&q.warning<=2.2&&q.shotClock>=0&&q.shotClock<=9&&Array.isArray(q.pilots)&&q.pilots.length<=2&&q.pilots.every(a=>['x','z','yaw'].every(k=>Number.isFinite(a[k]))&&a.x>=b[0]&&a.x<=b[1]&&a.z>=b[2]&&a.z<=b[3]);}
export const seaBoating=s=>s.level==='capesrun'&&s.sea.mounted;
export const seaFollowing=s=>s.level==='capeschart'&&s.stage===4;
export const seaCarrying=s=>s.level==='capesshore'&&s.stage===4;
export function seaWaterBlocked(s,x,z,r,feet){if(s.level==='capeschart'&&z<-39+r&&feet<.5&&Math.abs(x)>5-r)return true;if(s.level==='capesrun'&&!s.sea.mounted&&feet<.5&&!(Math.abs(x)<6-r&&z>0))return true;return false;}
export function seaGoal(s){const g=SEA_LEVELS[s.level].goals[s.stage];if(seaFollowing(s)&&s.sea.pilots.length&&dist(s.player,s.sea.pilots[0])>8)return {...g,x:s.sea.pilots[0].x,z:s.sea.pilots[0].z,label:'Return to Adrien and Lydia',verb:'Stay with the pilot party'};return g;}
export const seaNear=s=>!!seaGoal(s)&&dist(s.player,seaGoal(s))<(seaBoating(s)?4:2.5);
export function seaCanUse(s){const q=s.sea;if(seaFollowing(s))return q.pilots.length===2&&q.pilots.every(a=>dist(a,{x:0,z:-44})<3);if(seaBoating(s)){if(q.speed>1.05)return false;if(s.stage===2)return q.lee===4;if(s.stage===6)return q.rope&&q.speed<.8;}return true;}
function next(s){s.stage++;s.hold=0;emit(s,'checkpoint');if(s.stage>=SEA_LEVELS[s.level].goals.length){s.finished=true;emit(s,'finish');}}
export function interactSea(s){const q=s.sea,st=s.stage;
 if(s.level==='capeschart'){if(st===0){q.order=true;say(s,'sea.order');}if(st===1){q.port=true;say(s,'sea.port');}if(st===2){q.land=true;say(s,'sea.land');}if(st===3){q.fleet=true;q.pilots=[{x:3,z:-17,yaw:0},{x:5,z:-17,yaw:0}];say(s,'sea.pilots');}if(st===4){q.pilotsLoaded=true;say(s,'sea.aboard');}if(st===5){q.sealed=true;say(s,'sea.sealed');}}
 else if(s.level==='capesrun'){if(st===0){q.order=true;q.sealed=true;say(s,'sea.depart');}if(st===1){q.mounted=true;q.pilotsLoaded=true;s.player.x=q.boatX;s.player.z=q.boatZ;say(s,'sea.tiller');}if(st===2)say(s,'sea.lee');if(st===3){q.rope=true;say(s,'sea.rope');}if(st===4){q.passage=true;say(s,'sea.passage');}if(st===5){q.delivered=true;say(s,q.wetness>.2?'sea.delivered.damp':'sea.delivered.dry');}if(st===6){q.docked=true;say(s,'sea.docked');}}
 else{if(st===0){q.chart=true;say(s,'sea.handoff');}if(st===1){q.fleet=true;say(s,'sea.closed');}if(st===2){q.land=true;say(s,'sea.estimate');}if(st===3){q.stores=true;s.carrying=true;say(s,'sea.stores');}if(st===4){q.loaded=true;s.carrying=false;say(s,'sea.loaded');}}
 next(s);
}
export function moveSeaBoat(s,input,dt,collide){const q=s.sea,p=s.player;if(!seaBoating(s))return;const left=(input.left?1:0),right=(input.right?1:0);q.boatYaw=angle(q.boatYaw+(left-right)*dt*1.25+((input.leftTap?1:0)-(input.rightTap?1:0))*1.25/60);const brake=input.back||input.jump,max=input.sprint&&p.stamina>1?7.8:5.4,target=brake?0:input.forward?max:0;q.speed+=bound(target-q.speed,-(brake?6:1.4)*dt,2.5*dt);q.speed=bound(q.speed,0,7.8);q.impactClock=Math.max(0,q.impactClock-dt);const dx=-Math.sin(q.boatYaw)*q.speed*dt+Math.sin(s.time*.31)*dt*.04,dz=-Math.cos(q.boatYaw)*q.speed*dt,x=q.boatX+dx,z=q.boatZ+dz;if(collide(s,x,z,.65,0)){q.speed*=.2;if(q.impactClock===0){q.impacts++;q.impactClock=1.5;q.hull=Math.max(15,q.hull-5);q.wetness=Math.min(1,q.wetness+.045);emit(s,'seaImpact');say(s,'sea.obstacle');}}else{q.boatX=x;q.boatZ=z;}p.x=q.boatX;p.z=q.boatZ;p.y=0;p.vy=0;}
function move(s,a,x,z,dt,collide){const d=dist(a,{x,z}),n=Math.min(d,dt*1.8),nx=a.x+(x-a.x)/(d||1)*n,nz=a.z+(z-a.z)/(d||1)*n;if(!collide(s,nx,a.z,.25,0))a.x=nx;if(!collide(s,a.x,nz,.25,0))a.z=nz;a.yaw=Math.atan2(-(x-a.x),-(z-a.z));}
export function updateSea(s,input,dt,{collide}){const q=s.sea,p=s.player;
 if(seaFollowing(s)&&q.pilots.length){const center=q.pilots.reduce((a,n)=>({x:a.x+n.x/2,z:a.z+n.z/2}),{x:0,z:0});q.crewMoving=dist(center,p)<9;if(q.crewMoving)q.pilots.forEach((a,i)=>move(s,a,(i-.5)*1.5,-44,dt,collide));}
 if(seaBoating(s)){if(s.stage===2&&q.speed<1.1&&dist(p,{x:-24,z:-66})<6)q.lee=Math.min(4,q.lee+dt);const danger=p.z<-132&&p.z>-202&&p.x>-15&&p.x<30&&!q.delivered;if(q.warning>0){q.warning=Math.max(0,q.warning-dt);if(q.warning===0){emit(s,'seaDebris',{x:q.targetX,z:q.targetZ});if(dist(p,{x:q.targetX,z:q.targetZ})<4.7){q.hull=Math.max(15,q.hull-12);q.wetness=Math.min(1,q.wetness+.13);q.speed*=.6;q.impacts++;emit(s,'hurt');}}}else{q.shotClock=Math.max(0,q.shotClock-dt);if(danger&&q.shotClock===0){q.shotClock=9;q.warning=2.2;q.targetX=p.x;q.targetZ=p.z-2;q.shotSide=q.shotSide?0:1;emit(s,'seaWarning');}}}
}
export function seaContext(s){const q=s.sea;if(seaFollowing(s))return 'Adrien and Lydia move with you. The boat waits for both.';if(seaBoating(s)){if(s.stage===2)return 'Slow inside the western lee. The four-second check waits for the actual boat.';if(q.warning>0)return 'Marked debris ahead. Turn clear before it lands; keep the pilot party aboard.';return 'Your local dispatch crosses inshore. De Grasse’s fleet fights the offshore battle.';}if(seaCarrying(s))return 'Local siege stores in your arms. Bring the actual bundle to the cart.';return s.level==='capesshore'?'The sea route and the land army close different sides of Yorktown.':'Keep Yorktown, the land approach and the fleet on separate parts of the chart.';}
