import {TOPICS,QUESTIONS,QUESTION_BY_ID,pool,createRound,cleanStudy,freshStudy,answerStudy,nextStudy,missedIds,summary} from './c6-questions.mjs?v=1.0.0';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const button=(text,action,cls='primary',extra='')=>`<button class="${cls}" data-action="study-${action}" ${extra}>${text}</button>`;
const topicName=id=>TOPICS.find(t=>t[0]===id)?.[1]||'Whole chapter';
export class ChapterSixStudy{
 constructor({root,storageKey,onEnter,onHome,storage=localStorage}){this.root=root;this.storageKey=storageKey;this.onEnter=onEnter;this.onHome=onHome;this.storage=storage;this.active=false;this.screen='home';this.topic='all';this.count=15;this.canSave=true;this.data=freshStudy();try{this.data=cleanStudy(JSON.parse(storage.getItem(storageKey)));}catch{this.canSave=false;}}
 close(){this.active=false;}
 save(){try{this.storage.setItem(this.storageKey,JSON.stringify(this.data));}catch{this.canSave=false;}}
 open(){this.active=true;this.onEnter();this.landing();}
 shell(content){this.root.innerHTML=`<section class="panel study-panel"><div class="panel-inner study-inner">${content}${!this.canSave?'<p class="save-warning" role="status">Study progress cannot be saved in this browser. You can still finish this round.</p>':''}</div></section>`;this.root.querySelector('.panel').scrollTop=0;this.root.querySelector('[data-study-focus]')?.focus({preventScroll:true});}
 landing(){this.screen='home';const missed=missedIds(this.data),r=this.data.round,progress=summary(r),known=Object.keys(this.data.attempts).length,correct=Object.values(this.data.attempts).filter(a=>a.lastCorrect).length;
 this.shell(`<div class="study-top"><p class="eyebrow">Chapter 06 · Questions</p>${button('← Main menu','exit','quiet')}</div><h1 tabindex="-1" data-study-focus>Know the road.</h1><p class="study-intro">Practice the whole chapter, focus on a topic, or work through the questions you missed. One question at a time.</p><div class="study-settings"><label for="study-topic">Topic<select id="study-topic">${TOPICS.map(([id,name])=>`<option value="${id}" ${id===this.topic?'selected':''}>${esc(name)} · ${pool(id).length} questions</option>`).join('')}</select></label><label for="study-length">Round length<select id="study-length">${[15,30,'all'].map(n=>`<option value="${n}" ${n===this.count?'selected':''}>${n==='all'?'All questions':n+' questions'}</option>`).join('')}</select></label></div><div class="row">${button('Start practice →','start')}${r&&!r.finished?button(`Continue round · ${progress.answered}/${progress.total}`,'continue','secondary'):''}${missed.length?button(`Review missed · ${missed.length}`,'missed','secondary'):''}</div><p class="study-saved">${known?`${correct} correct on your latest try · ${known} of ${QUESTIONS.length} questions attempted`:`${QUESTIONS.length} questions · 10 bolded terms · All four sections`}<br>Progress saves on this browser. Campaign progress is kept separately.</p><details class="study-about"><summary>About these questions</summary><p>Practice questions based on your supplied <i>Chapter 6: America’s War for Independence</i>. They cover the chapter’s 54 substantive paragraphs and 10 bolded terms. These are practice questions, not a prediction of your teacher’s test. Explanations flag disputed claims and link historical checks where needed.</p></details>`);}
 start(ids=null){this.topic=this.root.querySelector('#study-topic')?.value||this.topic;const n=this.root.querySelector('#study-length')?.value;this.count=n==='all'?'all':Number(n)||this.count;this.data={...this.data,round:createRound({topic:this.topic,count:ids?'all':this.count,ids})};this.save();this.question();}
 question(){const r=this.data.round;if(!r)return this.landing();if(r.finished)return this.results();this.screen='question';const d=r.deck[r.index],q=QUESTION_BY_ID.get(d.id),answer=r.answers[r.index],answered=!!answer,score=summary(r);this.shell(`<div class="study-top"><p class="eyebrow">${esc(topicName(q.topic))}${q.term?' · Key term':''}</p>${button('Save & leave','leave','quiet')}</div><div class="study-status"><span>QUESTION ${r.index+1} <i>/ ${r.deck.length}</i>${r.kind==='missed'?' · MISSED REVIEW':''}</span><span>${score.right} correct</span></div><div class="study-progress" role="progressbar" aria-label="Questions answered" aria-valuenow="${score.answered}" aria-valuemin="0" aria-valuemax="${r.deck.length}"><i style="width:${score.answered/r.deck.length*100}%"></i></div><h1 class="study-question" tabindex="-1" data-study-focus>${esc(q.prompt)}</h1><div class="study-options" role="group" aria-label="Answer choices">${d.order.map((option,i)=>{const correct=answered&&option===q.correct,chosen=answered&&option===answer.option;return button(`<span class="study-number">${i+1}</span><span>${esc(q.options[option])}</span>${answered&&(correct||chosen)?`<b class="study-mark">${correct?'✓':'×'}</b>`:''}`,'answer',`study-option${correct?' correct':chosen?' wrong':''}`,`data-option="${i}" ${answered?'disabled':''} aria-label="${i+1}. ${esc(q.options[option])}${correct?' — Correct answer':chosen?' — Your answer, incorrect':''}"`);}).join('')}</div>${answered?`<div class="study-feedback ${answer.correct?'correct':'wrong'}" role="status"><h2>${answer.correct?'Correct.':'The correct answer:'}</h2>${!answer.correct?`<strong>${esc(q.options[q.correct])}</strong>`:''}<p>${esc(q.explanation)}</p><small>Chapter ${esc(q.topic)} · Supplied text ${q.paragraph}${q.reference?` · <a href="${q.reference[1]}" target="_blank" rel="noopener noreferrer">${esc(q.reference[0])} ↗</a>`:''}</small></div><div class="row">${button(r.index===r.deck.length-1?'See results →':'Next question →','next')}</div>`:'<p class="study-key-hint">Choose an answer · Press 1–4 or tap a choice</p>'}`);if(answered){this.root.querySelector('.study-feedback').setAttribute('tabindex','-1');this.root.querySelector('.study-feedback').focus({preventScroll:true});}}
 results(){this.screen='results';const r=this.data.round,s=summary(r),pct=Math.round(s.right/s.total*100);this.shell(`<div class="study-top"><p class="eyebrow">Chapter 06 · Round complete</p>${button('← Main menu','exit','quiet')}</div><h1 tabindex="-1" data-study-focus>${s.right===s.total?'Every answer landed.':'Keep the road in view.'}</h1><div class="study-score"><strong>${s.right}<i> / ${s.total}</i></strong><span>${pct}% correct this round</span></div><p>${s.missed.length?`${s.missed.length} question${s.missed.length===1?' needs':'s need'} another look. Retry them now, with the choices shuffled again.`:'You answered every question correctly in this round. Choose another topic or try the full chapter.'}</p><div class="row">${s.missed.length?button('Retry this round’s misses →','retry'):button('Another round →','landing')}${s.missed.length?button('Choose a new round','landing','secondary'):''}</div>${s.missed.length?`<details class="study-about"><summary>Review missed answers</summary>${s.missed.map(id=>{const q=QUESTION_BY_ID.get(id);return `<article class="study-review"><h2>${esc(q.prompt)}</h2><strong>${esc(q.options[q.correct])}</strong><p>${esc(q.explanation)}</p></article>`;}).join('')}</details>`:''}`);}
 handle(name,el){switch(name){case 'study-open':this.open();break;case 'study-exit':this.close();this.onHome();break;case 'study-landing':case 'study-leave':this.save();this.landing();break;case 'study-start':this.start();break;case 'study-continue':this.question();break;case 'study-missed':{const ids=missedIds(this.data);if(ids.length)this.start(ids);break;}case 'study-retry':{const ids=summary(this.data.round).missed;if(ids.length)this.start(ids);break;}case 'study-answer':this.data=answerStudy(this.data,Number(el?.dataset.option));this.save();this.question();break;case 'study-next':this.data=nextStudy(this.data);this.save();this.question();break;}}
 onKey(e){if(!this.active||e.target.matches('input,select,textarea')||e.ctrlKey||e.altKey||e.metaKey)return false;if(e.code==='Escape'){e.preventDefault();if(!e.repeat)this.screen==='home'?this.handle('study-exit'):this.handle('study-leave');return true;}if(this.screen!=='question')return false;const digit=/^(?:Digit|Numpad)([1-4])$/.exec(e.code);if(digit){e.preventDefault();if(!e.repeat)this.handle('study-answer',{dataset:{option:Number(digit[1])-1}});return true;}if(e.code==='Enter'&&!e.target.matches('button,a,summary')&&this.data.round.answers.length>this.data.round.index){e.preventDefault();if(!e.repeat)this.handle('study-next');return true;}return false;}
}
