import test from 'node:test';import assert from 'node:assert/strict';
import {fresh,tick,collide,currentGoal,goalNear,snapshot,restore,angle} from './c6-sim.mjs';
import {seaCanUse,seaBoating} from './c6-sea.mjs';
import {LEVELS,SCENES,LINES,continueProgress} from './c6-data.mjs';
import {rememberOutcome,cleanRecord,carryOutcome} from './c6-record.mjs';
const step=(s,input={},sec=1)=>{const events=[];for(let i=0;i<sec/.025;i++)events.push(...tick(s,input,.025));return events;};
function walk(s,x,z){const key=p=>p.x+','+p.z,start={x:Math.round(s.player.x),z:Math.round(s.player.z)},queue=[start],parents=new Map([[key(start),null]]);let end;
 for(let i=0;i<queue.length&&i<45000;i++){const p=queue[i];if(p.x===Math.round(x)&&p.z===Math.round(z)){end=p;break;}for(const [dx,dz] of [[1,0],[-1,0],[0,1],[0,-1]]){const n={x:p.x+dx,z:p.z+dz};if(parents.has(key(n))||collide(s,n.x,n.z,.3,0))continue;parents.set(key(n),p);queue.push(n);}}assert.ok(end,'walkable '+x+','+z);const path=[];while(end){path.unshift(end);end=parents.get(key(end));}
 for(const p of path)for(let i=0;i<100&&Math.hypot(p.x-s.player.x,p.z-s.player.z)>.15;i++){s.player.yaw=0;tick(s,{right:p.x-s.player.x>.1,left:p.x-s.player.x<-.1,back:p.z-s.player.z>.1,forward:p.z-s.player.z<-.1},.025);assert.equal(s.failed,false);}assert.ok(Math.hypot(s.player.x-x,s.player.z-z)<.6,'arrived '+x+','+z);}
function use(s){assert.ok(goalNear(s),'near stage '+s.stage);assert.ok(seaCanUse(s),'usable stage '+s.stage);const stage=s.stage;step(s,{interact:true},currentGoal(s).time+.2);assert.equal(s.stage,stage+1);}
function go(s){const g=currentGoal(s);walk(s,g.x,g.z);use(s);}
function sail(s,x,z){const q=s.sea;for(let i=0;i<12000;i++){const d=Math.hypot(x-q.boatX,z-q.boatZ);if(d<1.35&&q.speed<.6)break;const yaw=Math.atan2(-(x-q.boatX),-(z-q.boatZ)),turn=angle(yaw-q.boatYaw),steer=Math.abs(turn)>.018;tick(s,{left:steer&&turn>0,right:steer&&turn<0,forward:d>1.25&&Math.abs(turn)<.3,back:(d<5&&q.speed>.9)||d<1.25||Math.abs(turn)>.35,sprint:d>10},.025);assert.equal(s.failed,false);assert.equal(collide(s,q.boatX,q.boatZ,.64,0),false,'boat outside geometry');}assert.ok(Math.hypot(x-q.boatX,z-q.boatZ)<1.5,'boat arrived '+x+','+z);assert.ok(q.speed<1.1,'braked for interaction');}
test('all coalition chart pins and both actual pilots arrive before sealed loading',()=>{let s=fresh('capeschart');for(let i=0;i<4;i++)go(s);assert.equal(s.sea.pilots.length,2);walk(s,0,-44);for(let i=0;i<3000&&!seaCanUse(s);i++)tick(s,{},.025);use(s);s=restore(snapshot(s));go(s);assert.ok(s.finished&&s.sea.port&&s.sea.land&&s.sea.fleet&&s.sea.pilotsLoaded&&s.sea.sealed);const r={};rememberOutcome(r,s);assert.ok(r.outcomes.capeschart.pilotPartyLoaded&&r.outcomes.capeschart.coalitionChart);assert.equal(r.outcomes.capeschart.pilotsDelivered,false);});
test('complete steered coastal run holds in lee, stops for rope and dispatch, crosses hazards and docks',()=>{let s=fresh('capesrun');go(s);go(s);assert.ok(seaBoating(s));sail(s,-25,9);sail(s,-24,-66);step(s,{back:true},4.1);use(s);sail(s,-25,-114);use(s);s=restore(snapshot(s));sail(s,-25,-132);sail(s,-9,-132);sail(s,-9,-164);sail(s,8,-182);use(s);sail(s,-10,-225);use(s);sail(s,0,-260);use(s);assert.ok(s.finished&&s.sea.docked&&s.sea.delivered&&s.sea.rope&&s.sea.passage);assert.ok(s.sea.hull>=15);assert.equal(s.armed,false);assert.equal(s.enemies.length,0);const r={};rememberOutcome(r,s);assert.ok(r.outcomes.capesrun.pilotsDelivered&&r.outcomes.capesrun.coastalDispatch&&r.outcomes.capesrun.pilotRope&&r.outcomes.capesrun.seaPassage);assert.equal(r.outcomes.capesrun.rescues,0,'no claim to rescuing or winning the fleet battle');});
test('shore packet, separate coalition pins and real carried siege stores finish the dated handoff',()=>{const s=carryOutcome(fresh('capesshore'),{outcomes:{capesrun:{wetness:.36}}});assert.equal(s.sea.wetness,.36);for(let i=0;i<4;i++)go(s);assert.ok(s.carrying&&s.sea.stores);go(s);assert.ok(s.finished&&s.sea.loaded&&!s.carrying);const r={};rememberOutcome(r,s);assert.ok(r.outcomes.capesshore.siegeStores&&r.outcomes.capesshore.coalitionChart);});
test('remote pilots, rushed lee checks, fast collection and missing rope cannot finish gates',()=>{const s=fresh('capeschart');s.stage=4;s.sea.pilots=[{x:3,z:-17,yaw:0},{x:5,z:-17,yaw:0}];s.player.z=-44;step(s,{interact:true},3);assert.equal(s.stage,4);assert.equal(seaCanUse(s),false);const b=fresh('capesrun');Object.assign(b.sea,{mounted:true,boatX:-24,boatZ:-66,speed:3});b.player.x=-24;b.player.z=-66;b.stage=2;step(b,{forward:true,interact:true},1);assert.equal(b.sea.lee,0);assert.equal(b.stage,2);b.stage=3;b.sea.speed=5;assert.equal(seaCanUse(b),false);b.stage=6;b.sea.speed=0;assert.equal(seaCanUse(b),false);});
test('tiller, rapid taps, zero-time input and upward view stay finite and independent',()=>{const s=fresh('capesrun');s.stage=2;s.sea.mounted=true;step(s,{left:true,lookUp:true},.5);assert.ok(s.sea.boatYaw>.5);assert.equal(s.player.yaw,0);assert.ok(s.player.pitch>0);const yaw=s.sea.boatYaw;tick(s,{leftTap:1},0);assert.ok(s.sea.boatYaw>yaw&&Number.isFinite(s.sea.boatYaw));step(s,{lookRight:true},.5);assert.ok(s.player.yaw<0);assert.ok(s.sea.boatYaw>.5);});
test('marked debris warns first, can be dodged and leaves recoverable hull/paper consequences',()=>{for(const dodge of [false,true]){const s=fresh('capesrun');s.stage=4;Object.assign(s.sea,{mounted:true,boatX:8,boatZ:-182,shotClock:0});s.player.x=8;s.player.z=-182;const warning=step(s,{},.025);assert.ok(s.sea.warning>2&&warning.some(e=>e.type==='seaWarning'));assert.equal(s.sea.hull,100);if(dodge)step(s,{forward:true,right:true,sprint:true},2.3);else step(s,{},2.3);assert.equal(s.sea.hull,dodge?100:88);assert.equal(s.sea.impacts,dodge?0:1);assert.equal(s.failed,false);if(!dodge)assert.ok(s.sea.wetness>0);}const s=fresh('capesrun');s.stage=4;Object.assign(s.sea,{mounted:true,boatX:8,boatZ:-182,hull:15,warning:.01,targetX:8,targetZ:-182});step(s,{},.1);assert.equal(s.sea.hull,15);assert.equal(s.failed,false);});
test('boat islands block actual movement, foot cannot jump into chart water, and malformed saves reject',()=>{const s=fresh('capesrun');s.stage=2;Object.assign(s.sea,{mounted:true,boatX:15,boatZ:-30});s.player.x=15;s.player.z=-30;step(s,{forward:true},4);assert.ok(s.sea.impacts>0&&s.sea.boatZ>-35);const c=fresh('capeschart');c.player.z=-38;c.player.x=10;step(c,{forward:true,jump:true},1);assert.equal(c.player.y,0);assert.ok(c.player.z>-39);const raw=snapshot(fresh('capesrun'));assert.ok(restore(raw));for(const patch of [{boatX:99},{boatZ:-999},{speed:9},{hull:14},{warning:3},{mounted:1},{pilots:[{x:0,z:0,yaw:NaN}]}]){const bad=structuredClone(raw);Object.assign(bad.sea,patch);assert.equal(restore(bad),null);}assert.equal(cleanRecord({outcomes:{capesrun:{completed:true,pilotsDelivered:true,coastalDispatch:true,impacts:2}}},LEVELS,SCENES).outcomes.capesrun.impacts,2);});
test('Guilford migrates to Isaiah, offshore and late-September dates stay distinct, and commanders are credited',()=>{assert.equal(continueProgress({complete:true,completedPart:'price',seen:['priceEnding']}).scene,'seaIntro');const done={complete:true,completedPart:'sea',seen:['seaEnding']};assert.equal(continueProgress(done),done);assert.equal(SCENES.priceEnding.after,'seaIntro');assert.equal(SCENES.seaEnding.after,'complete');assert.match(SCENES.seaRoad.place,/SEPTEMBER 5, 1781/);assert.match(SCENES.seaArrival.place,/SEPTEMBER 27, 1781/);const lines=LINES.filter(l=>l.id.startsWith('sea.'));assert.ok(lines.every(l=>l.speaker!=='WARD'));const text=lines.map(l=>l.text).join(' ');for(const phrase of ['tobacco port','Virginia peninsula','Clinton','New York','Lafayette','Washington','Rochambeau','de Grasse','sixteen thousand','count depends','French and British fleets','No cannon','Ward’s name','Three weeks'])assert.ok(text.includes(phrase),phrase);});
