import test from 'node:test';import assert from 'node:assert/strict';
import {fresh,tick,collide,angle,currentGoal,goalNear,snapshot,restore} from './c6-sim.mjs';
import {southCanUse,southBoating,southSheltered} from './c6-south.mjs';
import {LEVELS,SCENES,LINES,continueProgress} from './c6-data.mjs';
import {rememberOutcome,cleanRecord} from './c6-record.mjs';
const step=(s,input={},seconds=1)=>{const ev=[];for(let i=0;i<seconds/.025;i++)ev.push(...tick(s,input,.025));return ev;};
function walk(s,x,z){const start={x:Math.round(s.player.x),z:Math.round(s.player.z)},key=p=>p.x+','+p.z,queue=[start],parents=new Map([[key(start),null]]);let end;
 for(let i=0;i<queue.length&&i<25000;i++){const p=queue[i];if(p.x===Math.round(x)&&p.z===Math.round(z)){end=p;break;}for(const [dx,dz] of [[1,0],[-1,0],[0,1],[0,-1]]){const n={x:p.x+dx,z:p.z+dz};if(parents.has(key(n))||collide(s,n.x,n.z,.3,0))continue;parents.set(key(n),p);queue.push(n);}}
 assert.ok(end,'walkable route to '+x+','+z);const path=[];while(end){path.unshift(end);end=parents.get(key(end));}
 for(const p of path)for(let i=0;i<120&&Math.hypot(p.x-s.player.x,p.z-s.player.z)>.14;i++){s.player.yaw=0;tick(s,{right:p.x-s.player.x>.1,left:p.x-s.player.x<-.1,back:p.z-s.player.z>.1,forward:p.z-s.player.z<-.1},.025);assert.equal(s.failed,false);if(s.level==='charlestonring'&&s.south.cartReady)assert.equal(collide(s,s.south.cartX,s.south.cartZ,.4,0),false);if(s.level==='charlestonlast'&&s.south.civilian)assert.equal(collide(s,s.south.civilianX,s.south.civilianZ,.4,0),false);}assert.ok(Math.hypot(s.player.x-x,s.player.z-z)<.6,'arrived at '+x+','+z);
}
function use(s){assert.ok(goalNear(s),'near stage '+s.stage);assert.ok(southCanUse(s),'usable stage '+s.stage);step(s,{interact:true,jump:southBoating(s)},currentGoal(s).time+.2);}
function go(s){const g=currentGoal(s);walk(s,g.x,g.z);use(s);}
function sail(s,x,z){assert.ok(southBoating(s));for(let i=0;i<12000;i++){const dx=x-s.player.x,dz=z-s.player.z,d=Math.hypot(dx,dz),desired=Math.atan2(-dx,-dz),turn=angle(desired-s.south.boatYaw);tick(s,{left:turn>.025,right:turn<-.025,forward:d>1.7&&Math.abs(turn)<.7,jump:d<2.6},.025);assert.equal(s.failed,false);if(d<3&&s.south.speed<.7)return;}assert.fail('sail failed to '+x+','+z+' from '+s.player.x+','+s.player.z);}
test('three southern hopes, the rejected proposal and a real local defense precede the hospital cart',()=>{const s=fresh('charlestondock');for(let i=0;i<6;i++)go(s);assert.ok(s.south.georgia&&s.south.parley&&s.south.proposal&&s.south.braced);assert.equal(s.enemies.length,7);for(let i=0;i<2400&&s.stage===6;i++)tick(s,{interact:true,crouch:true},.025);assert.equal(s.stage,7);assert.ok(s.south.line>=35&&s.enemies.every(e=>e.hp===0));go(s);assert.ok(s.finished);});
test('the hospital route supports both men and physically walks the loaded cart around the closed western road',()=>{let s=fresh('charlestonring');for(let i=0;i<6;i++)go(s);assert.equal(s.south.patients,2);assert.equal(collide(s,-19,-3,.3,4),true);const held={x:s.south.cartX,z:s.south.cartZ};step(s,{jump:true},3);assert.equal(s.south.cartX,held.x);assert.equal(s.south.cartZ,held.z);s=restore(snapshot(s));assert.ok(s);for(const [x,z] of [[19,-8],[19,12],[0,22]]){walk(s,x,z);for(let i=0;i<2000&&Math.hypot(s.south.cartX-x,s.south.cartZ-z)>1;i++)tick(s,{},.025);}assert.equal(s.south.cartLeg,3);use(s);assert.ok(s.finished&&s.south.cartDelivered);const saved={};rememberOutcome(saved,s);assert.equal(saved.outcomes.charlestonring.hospitalPatients,2);assert.equal(saved.outcomes.charlestonring.rescues,2);});
test('timed physical axe strokes open the barred eastern lane and the actual civilian arrives before disarmament',()=>{let s=fresh('charlestonlast');go(s);go(s);assert.equal(collide(s,19,-12,.3,5),true);step(s,{interact:true},3);assert.equal(s.stage,2);for(let n=0;n<3;n++){for(let i=0;i<100&&!(s.south.axePhase>.45&&s.south.axePhase<.55);i++)tick(s,{},.025);tick(s,{jump:true},.025);tick(s,{},.025);}assert.equal(s.stage,3);assert.equal(s.south.cuts,3);assert.equal(s.player.y,0);assert.equal(collide(s,19,-12,.3,0),false);s=restore(snapshot(s));assert.ok(s);go(s);for(const [x,z] of [[19,-4],[19,12],[0,22]]){walk(s,x,z);for(let i=0;i<1600&&Math.hypot(s.south.civilianX-x,s.south.civilianZ-z)>1;i++)tick(s,{},.025);}assert.equal(s.south.civilianLeg,3);use(s);go(s);assert.ok(s.finished&&s.south.civilianSafe&&s.south.disarmed&&!s.armed);});
test('Isaiah navigates the prison harbor, hears Samuel and waits in real shelter before taking the final rope',()=>{let s=fresh('charlestonharbor');go(s);go(s);assert.ok(southBoating(s));sail(s,-22,-25);sail(s,-22,-45);use(s);sail(s,-22,-65);sail(s,18,-65);sail(s,18,-98);use(s);assert.ok(s.south.answered);s=restore(snapshot(s));sail(s,-19,-113);sail(s,-19,-132);step(s,{jump:true},7);assert.equal(s.stage,5);assert.ok(s.south.clear&&southSheltered(s.south));sail(s,-19,-160);sail(s,0,-170);use(s);assert.ok(s.finished&&s.south.message&&s.south.travel>200);assert.equal(s.kills,0);assert.equal(s.armed,false);const saved={};rememberOutcome(saved,s);assert.ok(saved.outcomes.charlestonharbor.samuelSignal);assert.equal(saved.outcomes.charlestonharbor.rescues,0,'a signal is not a prisoner rescue');});
test('remote tasks, moving ropes, the held axe and unattended escorts cannot skip the local work',()=>{const s=fresh('charlestonlast');s.stage=2;Object.assign(s.south,{list:true,axe:true,axePhase:.5});step(s,{jump:true},6);assert.equal(s.south.cuts,0);assert.equal(s.stage,2);s.player.x=19;s.player.z=-8;s.south.axeHeld=false;s.south.axePhase=.48;step(s,{jump:true},4);assert.equal(s.south.cuts,1,'a held key is one stroke');const c=fresh('charlestonring');c.stage=6;c.south.cartReady=true;c.south.patients=2;step(c,{},20);assert.equal(c.south.cartLeg,0);assert.equal(southCanUse(c),false);const b=fresh('charlestonharbor');b.south.aboard=true;b.stage=4;Object.assign(b.south,{boatX:0,boatZ:10,moored:false});step(b,{jump:true},10);assert.equal(b.stage,4);const before=b.south.boatYaw;step(b,{lookUp:true,lookLeft:true,jump:true},.5);assert.ok(b.player.pitch>0);assert.equal(b.south.boatYaw,before);tick(b,{leftTap:true,jump:true},.025);assert.ok(b.south.boatYaw>before);b.south.speed=2;b.stage=2;assert.equal(southCanUse(b),false);});
test('shells warn before recoverable impact, and a shoal cannot silently sink the civilian boat',()=>{const s=fresh('charlestonring');const ev=step(s,{},7.2);assert.ok(ev.some(e=>e.type==='southShellWarning'));assert.ok(s.south.shellIn>0);const hp=s.player.health;step(s,{},3);assert.ok(s.player.health<hp&&s.player.health>=1);const b=fresh('charlestonharbor');b.south.aboard=true;b.south.moored=false;b.player.z=-29;Object.assign(b.south,{boatZ:-29,vz:-4});step(b,{forward:true},4);assert.ok(b.south.impacts>0&&b.south.hull>=1);assert.ok(b.player.z>-36);});
test('dated siege saves reject invalid state and preserve only completed local outcomes',()=>{for(const level of ['charlestondock','charlestonring','charlestonlast','charlestonharbor']){const raw=snapshot(fresh(level));assert.ok(restore(raw),level);for(const patch of [{patients:3},{carried:2},{cartLeg:4},{cuts:4},{axePhase:2},{boatX:1000},{speed:9},{hull:0},{exposure:2},{message:1},{shellIn:-1},{civilianLeg:8}]){const bad=structuredClone(raw);Object.assign(bad.south,patch);assert.equal(restore(bad),null);}}const saved={};const s=fresh('charlestonharbor');s.south.answered=true;assert.equal(rememberOutcome(saved,s),false);s.finished=true;rememberOutcome(saved,s);const clean=cleanRecord(saved,LEVELS,SCENES);assert.equal(clean.outcomes.charlestonharbor.samuelSignal,true);assert.equal(clean.outcomes.charlestonharbor.rescues,0);});
test('the coastal checkpoint continues through six weeks, a historical loss and Jonas’s separate choice',()=>{assert.equal(continueProgress({complete:true,completedPart:'wider',seen:['widerEnding']}).scene,'southIntro');const done={complete:true,completedPart:'south',seen:['southEnding']};assert.equal(continueProgress(done),done);assert.equal(SCENES.widerEnding.after,'southIntro');assert.equal(SCENES.southEnding.after,'complete');assert.deepEqual(['southIntro','southRing','southNight','southSurrender'].map(k=>SCENES[k].place.match(/APRIL 1,|APRIL 14,|MAY 9,|MAY 12,/)[0]),['APRIL 1,','APRIL 14,','MAY 9,','MAY 12,']);const text=LINES.filter(l=>l.id.startsWith('south.')).map(l=>l.text).join(' ');for(const phrase of ['Savannah','Germain','Twenty Loyalist regiments','South Carolina and Georgia rejected','not every Creek town','May twelfth','six weeks','military government','Cornwallis','Lincoln','my consent','still on that ship'])assert.ok(text.includes(phrase),phrase);});
