// Prerecorded synthetic performances; generated locally with Kokoro-82M.
export const C6_VOICES = [
  {
    "id": "release.0",
    "speaker": "THOMAS",
    "text": "The release is signed. Give him his coat.",
    "voice": "bm_fable",
    "speed": 0.98,
    "lang": "en-gb",
    "file": "c6-voice-release-0-457484345.mp3",
    "duration": 3.112,
    "peak": 0.86,
    "rms": 0.1307
  },
  {
    "id": "release.1",
    "speaker": "ROWAN",
    "text": "Ward? It’s me.",
    "voice": "am_fenrir",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-release-1-550de5e9d.mp3",
    "duration": 1.259,
    "peak": 0.86,
    "rms": 0.1114
  },
  {
    "id": "release.2",
    "speaker": "WARD",
    "text": "I know your footsteps. You still hurry when you’re frightened.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-release-2-0c6a96ff1.mp3",
    "duration": 3.646,
    "peak": 0.7208,
    "rms": 0.15
  },
  {
    "id": "release.3",
    "speaker": "ROWAN",
    "text": "Can you walk?",
    "voice": "am_fenrir",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-release-3-89487b12f.mp3",
    "duration": 0.83,
    "peak": 0.86,
    "rms": 0.1439
  },
  {
    "id": "release.4",
    "speaker": "WARD",
    "text": "With a little help. Don’t make a ceremony of it.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-release-4-91a102e51.mp3",
    "duration": 2.944,
    "peak": 0.7098,
    "rms": 0.15
  },
  {
    "id": "help",
    "speaker": "WARD",
    "text": "Easy. They gave me my coat back. Not quite my legs.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-help-7c8cf82be.mp3",
    "duration": 3.774,
    "peak": 0.7002,
    "rms": 0.15
  },
  {
    "id": "releasewalk",
    "speaker": "MARA",
    "text": "Bring him to the wagon. There’s a blanket beside me.",
    "voice": "af_heart",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-releasewalk-594840009.mp3",
    "duration": 2.795,
    "peak": 0.86,
    "rms": 0.1185
  },
  {
    "id": "gate.0",
    "speaker": "MARA",
    "text": "Hold still. This buckle never liked you.",
    "voice": "af_heart",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-gate-0-b5d86f0ed.mp3",
    "duration": 2.424,
    "peak": 0.86,
    "rms": 0.1079
  },
  {
    "id": "gate.1",
    "speaker": "WARD",
    "text": "You kept the wagon.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-gate-1-ec176aad0.mp3",
    "duration": 1.431,
    "peak": 0.86,
    "rms": 0.147
  },
  {
    "id": "gate.2",
    "speaker": "ISAIAH",
    "text": "And a place in it. We weren’t leaving you here.",
    "voice": "am_michael",
    "speed": 0.98,
    "lang": "en-us",
    "file": "c6-voice-gate-2-811237426.mp3",
    "duration": 2.614,
    "peak": 0.86,
    "rms": 0.1247
  },
  {
    "id": "gate.3",
    "speaker": "THOMAS",
    "text": "You asked me to find him, Rowan. I kept my word.",
    "voice": "bm_fable",
    "speed": 0.98,
    "lang": "en-gb",
    "file": "c6-voice-gate-3-59a75eeb0.mp3",
    "duration": 3.726,
    "peak": 0.86,
    "rms": 0.0582
  },
  {
    "id": "gate.4",
    "speaker": "ROWAN",
    "text": "Then come with us.",
    "voice": "am_fenrir",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-gate-4-50f5d59ab.mp3",
    "duration": 1.032,
    "peak": 0.86,
    "rms": 0.1219
  },
  {
    "id": "gate.5",
    "speaker": "THOMAS",
    "text": "You’re my family. That doesn’t make this rebellion right.",
    "voice": "bm_fable",
    "speed": 0.98,
    "lang": "en-gb",
    "file": "c6-voice-gate-5-22da18500.mp3",
    "duration": 3.935,
    "peak": 0.86,
    "rms": 0.1078
  },
  {
    "id": "gate.6",
    "speaker": "WARD",
    "text": "Let him go. A man can open a door without crossing it.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-gate-6-1075020a8.mp3",
    "duration": 3.738,
    "peak": 0.7374,
    "rms": 0.15
  },
  {
    "id": "night.0",
    "speaker": "WARD",
    "text": "Gage has troops moving out of Boston. They’re after the powder at Concord.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-night-0-2d6f693cb.mp3",
    "duration": 4.938,
    "peak": 0.778,
    "rms": 0.15
  },
  {
    "id": "night.1",
    "speaker": "ROWAN",
    "text": "Again? Cambridge. Charlestown. How much more will they take?",
    "voice": "am_fenrir",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-night-1-b8900da7c.mp3",
    "duration": 3.585,
    "peak": 0.86,
    "rms": 0.1035
  },
  {
    "id": "night.2",
    "speaker": "WARD",
    "text": "They came away empty-handed at Salem. New Hampshire took the guns at Fort William and Mary. People are ready.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-night-2-f1ff2f1c4.mp3",
    "duration": 7.262,
    "peak": 0.86,
    "rms": 0.1422
  },
  {
    "id": "night.3",
    "speaker": "ROWAN",
    "text": "Then we get the warning to them. The north farm first.",
    "voice": "am_fenrir",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-night-3-63d6201f1.mp3",
    "duration": 3.031,
    "peak": 0.86,
    "rms": 0.0894
  },
  {
    "id": "farm.0",
    "speaker": "RUNNER",
    "text": "British troops? I’ll wake the others. Our minutemen can assemble in a minute.",
    "voice": "am_puck",
    "speed": 1.04,
    "lang": "en-us",
    "file": "c6-voice-farm-0-1e490b682.mp3",
    "duration": 4.001,
    "peak": 0.86,
    "rms": 0.1223
  },
  {
    "id": "farm.1",
    "speaker": "WARD",
    "text": "Some of those men fought the French with me. They know what a musket sounds like. Ring the meeting bell.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-farm-1-d320bd8a3.mp3",
    "duration": 6.097,
    "peak": 0.86,
    "rms": 0.1294
  },
  {
    "id": "bell.0",
    "speaker": "RUNNER",
    "text": "Revere was stopped by a British patrol. Other riders are carrying the warning on.",
    "voice": "am_puck",
    "speed": 1.04,
    "lang": "en-us",
    "file": "c6-voice-bell-0-95c7de7d0.mp3",
    "duration": 4.554,
    "peak": 0.86,
    "rms": 0.1291
  },
  {
    "id": "bell.1",
    "speaker": "ROWAN",
    "text": "One rider doesn’t carry the whole country. Get your neighbors out.",
    "voice": "am_fenrir",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-bell-1-34370320c.mp3",
    "duration": 3.553,
    "peak": 0.86,
    "rms": 0.1148
  },
  {
    "id": "ridge",
    "speaker": "WARD",
    "text": "The lanterns are gathering on the road. Keep to the trees. We meet the others beyond the ridge.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-ridge-245d54b29.mp3",
    "duration": 5.942,
    "peak": 0.7716,
    "rms": 0.15
  },
  {
    "id": "patrol",
    "speaker": "WARD",
    "text": "Lantern ahead. Stay low behind the fence. Let the patrol pass.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-patrol-b3dbd925a.mp3",
    "duration": 4.692,
    "peak": 0.7806,
    "rms": 0.15
  },
  {
    "id": "spotted",
    "speaker": "WARD",
    "text": "They’ve seen us! Break their sight. Through the orchard!",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-spotted-a06485281.mp3",
    "duration": 3.439,
    "peak": 0.7607,
    "rms": 0.15
  },
  {
    "id": "lex.0",
    "speaker": "MARA",
    "text": "People came out to see what was happening. Now they can’t get off the green.",
    "voice": "af_heart",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-lex-0-afbbe35c3.mp3",
    "duration": 3.972,
    "peak": 0.86,
    "rms": 0.1392
  },
  {
    "id": "lex.1",
    "speaker": "WARD",
    "text": "Stay close. No one here knows what the next man will do.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-lex-1-016855ab7.mp3",
    "duration": 3.955,
    "peak": 0.86,
    "rms": 0.1347
  },
  {
    "id": "lex.2",
    "speaker": "ROWAN",
    "text": "Who fired?",
    "voice": "am_fenrir",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-lex-2-b9def6f53.mp3",
    "duration": 0.83,
    "peak": 0.86,
    "rms": 0.1011
  },
  {
    "id": "lex.3",
    "speaker": "WARD",
    "text": "I couldn’t see. Get down!",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-lex-3-6befa445a.mp3",
    "duration": 2.178,
    "peak": 0.86,
    "rms": 0.1379
  },
  {
    "id": "lex.4",
    "speaker": "MARA",
    "text": "There’s someone by the wall. Rowan, help me get him out!",
    "voice": "af_heart",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-lex-4-5e152c175.mp3",
    "duration": 2.907,
    "peak": 0.86,
    "rms": 0.1359
  },
  {
    "id": "rescue.0",
    "speaker": "RUNNER",
    "text": "My leg. I can’t put any weight on it.",
    "voice": "am_puck",
    "speed": 1.04,
    "lang": "en-us",
    "file": "c6-voice-rescue-0-b3962624f.mp3",
    "duration": 1.88,
    "peak": 0.7877,
    "rms": 0.15
  },
  {
    "id": "rescue.1",
    "speaker": "ROWAN",
    "text": "Put your arm over me. We’re going to that wagon.",
    "voice": "am_fenrir",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-rescue-1-d4999af73.mp3",
    "duration": 2.663,
    "peak": 0.86,
    "rms": 0.1086
  },
  {
    "id": "rescue.2",
    "speaker": "MARA",
    "text": "I’ve got him. There’s another man behind the fence. Bring him through the garden.",
    "voice": "af_heart",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-rescue-2-a770f5ae3.mp3",
    "duration": 4.319,
    "peak": 0.8011,
    "rms": 0.15
  },
  {
    "id": "rescue.3",
    "speaker": "WARD",
    "text": "The lane is clear. Leave the green. Now!",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-rescue-3-b9ebf536a.mp3",
    "duration": 3.021,
    "peak": 0.6884,
    "rms": 0.15
  },
  {
    "id": "concord.0",
    "speaker": "WARD",
    "text": "They reached Concord. Now they’re falling back toward Boston, and more militia are coming in along the road.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-concord-0-4beff6152.mp3",
    "duration": 6.876,
    "peak": 0.6938,
    "rms": 0.15
  },
  {
    "id": "concord.1",
    "speaker": "MARA",
    "text": "Our wagon has wounded aboard. I need that crossing clear.",
    "voice": "af_heart",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-concord-1-899099d61.mp3",
    "duration": 3.209,
    "peak": 0.86,
    "rms": 0.1193
  },
  {
    "id": "concord.2",
    "speaker": "WARD",
    "text": "Take the spare musket. One shot, then reload. Use the wall while your hands are busy.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-concord-2-e298ed928.mp3",
    "duration": 5.998,
    "peak": 0.86,
    "rms": 0.1377
  },
  {
    "id": "armed",
    "speaker": "WARD",
    "text": "Hold the stone wall. Keep their fire off the wagon. I’ll watch the left.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-armed-b47383c82.mp3",
    "duration": 4.795,
    "peak": 0.7502,
    "rms": 0.15
  },
  {
    "id": "wave.1",
    "speaker": "WARD",
    "text": "They’re coming through the smoke. Don’t stand in the open!",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-wave-1-4423c0afc.mp3",
    "duration": 3.685,
    "peak": 0.7982,
    "rms": 0.15
  },
  {
    "id": "wave.2",
    "speaker": "MARA",
    "text": "The wheel’s free! A little longer. Keep them back!",
    "voice": "af_heart",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-wave-2-0d0628030.mp3",
    "duration": 2.844,
    "peak": 0.86,
    "rms": 0.1363
  },
  {
    "id": "clear",
    "speaker": "MARA",
    "text": "We’re across! Rowan, Ward, fall back to the orchard!",
    "voice": "af_heart",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-clear-92e53cbc7.mp3",
    "duration": 2.995,
    "peak": 0.86,
    "rms": 0.1262
  },
  {
    "id": "reload",
    "speaker": "WARD",
    "text": "Reload behind cover. That wall is worth more than another shot.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-reload-d89b3dfb3.mp3",
    "duration": 4.26,
    "peak": 0.6286,
    "rms": 0.15
  },
  {
    "id": "end.0",
    "speaker": "ROWAN",
    "text": "This morning I thought getting the warning through would be enough.",
    "voice": "am_fenrir",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-end-0-e1e031bbe.mp3",
    "duration": 2.943,
    "peak": 0.86,
    "rms": 0.0966
  },
  {
    "id": "end.1",
    "speaker": "WARD",
    "text": "It got these people out. That was enough for this morning.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-end-1-ef0e69c87.mp3",
    "duration": 3.446,
    "peak": 0.86,
    "rms": 0.1408
  },
  {
    "id": "end.2",
    "speaker": "MARA",
    "text": "Militia are marching toward Boston from everywhere. They’re surrounding the city.",
    "voice": "af_heart",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-end-2-33363ff71.mp3",
    "duration": 4.465,
    "peak": 0.86,
    "rms": 0.1489
  },
  {
    "id": "end.3",
    "speaker": "ROWAN",
    "text": "And Thomas is still inside.",
    "voice": "am_fenrir",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-end-3-43eab6075.mp3",
    "duration": 1.527,
    "peak": 0.86,
    "rms": 0.1175
  },
  {
    "id": "end.4",
    "speaker": "WARD",
    "text": "Then we keep a road open. We leave with everyone we can.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-end-4-e3098aea9.mp3",
    "duration": 3.942,
    "peak": 0.8433,
    "rms": 0.15
  },
  {
    "id": "end.5",
    "speaker": "ISAIAH",
    "text": "I’ll find us a way through the harbor. You get some sleep.",
    "voice": "am_michael",
    "speed": 0.98,
    "lang": "en-us",
    "file": "c6-voice-end-5-04875a883.mp3",
    "duration": 3.429,
    "peak": 0.86,
    "rms": 0.1341
  },
  {
    "id": "retry",
    "speaker": "WARD",
    "text": "Find cover. Breathe. We try the route again.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-retry-5c03f9327.mp3",
    "duration": 3.366,
    "peak": 0.86,
    "rms": 0.1428
  },
  {
    "id": "north.0",
    "speaker": "ISAIAH",
    "text": "There. Past the mist. Ticonderoga.",
    "voice": "am_michael",
    "speed": 0.98,
    "lang": "en-us",
    "file": "c6-voice-north-0-142ce2e3c.mp3",
    "duration": 2.686,
    "peak": 0.8139,
    "rms": 0.15
  },
  {
    "id": "north.1",
    "speaker": "ROWAN",
    "text": "Boston is the other way.",
    "voice": "am_fenrir",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-north-1-6979dbcad.mp3",
    "duration": 1.305,
    "peak": 0.86,
    "rms": 0.1095
  },
  {
    "id": "north.2",
    "speaker": "WARD",
    "text": "We can surround a city with men. To force the British out, we need guns.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-north-2-443b1a7f8.mp3",
    "duration": 4.989,
    "peak": 0.86,
    "rms": 0.1365
  },
  {
    "id": "north.3",
    "speaker": "RUNNER",
    "text": "Allen and Arnold are bringing the men up. They want us at the passage.",
    "voice": "am_puck",
    "speed": 1.04,
    "lang": "en-us",
    "file": "c6-voice-north-3-75d2594e1.mp3",
    "duration": 3.647,
    "peak": 0.7035,
    "rms": 0.15
  },
  {
    "id": "north.4",
    "speaker": "ISAIAH",
    "text": "I’ll keep the boat ready. Nathan, stay on Rowan’s shoulder.",
    "voice": "am_michael",
    "speed": 0.98,
    "lang": "en-us",
    "file": "c6-voice-north-4-16a164b04.mp3",
    "duration": 3.847,
    "peak": 0.86,
    "rms": 0.1184
  },
  {
    "id": "north.5",
    "speaker": "ROWAN",
    "text": "And if the sentry sees us?",
    "voice": "am_fenrir",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-north-5-014574074.mp3",
    "duration": 1.432,
    "peak": 0.86,
    "rms": 0.126
  },
  {
    "id": "north.6",
    "speaker": "WARD",
    "text": "We move together. This is a surprise, not a firing line.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-north-6-efae60f2a.mp3",
    "duration": 4.17,
    "peak": 0.7154,
    "rms": 0.15
  },
  {
    "id": "north.7",
    "speaker": "ISAIAH",
    "text": "Rowan. Leave room for everyone on the way back.",
    "voice": "am_michael",
    "speed": 0.98,
    "lang": "en-us",
    "file": "c6-voice-north-7-9a2291d60.mp3",
    "duration": 3.045,
    "peak": 0.86,
    "rms": 0.1123
  },
  {
    "id": "north.ready",
    "speaker": "WARD",
    "text": "The wall hides us. Left side of the passage. Watch where his lantern points.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-north-ready-fb24c3242.mp3",
    "duration": 5.053,
    "peak": 0.7812,
    "rms": 0.15
  },
  {
    "id": "north.signal",
    "speaker": "WARD",
    "text": "I see you. Taking the left door. Get that latch up for the others.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-north-signal-21e338f84.mp3",
    "duration": 4.374,
    "peak": 0.7644,
    "rms": 0.15
  },
  {
    "id": "north.alarm",
    "speaker": "RUNNER",
    "text": "My foot! Rowan, I’m caught!",
    "voice": "am_puck",
    "speed": 1.04,
    "lang": "en-us",
    "file": "c6-voice-north-alarm-ecfc569fe.mp3",
    "duration": 1.376,
    "peak": 0.86,
    "rms": 0.1266
  },
  {
    "id": "north.rescued",
    "speaker": "WARD",
    "text": "He’s clear! They’ve heard us. Open the passage. Our men are coming!",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-north-rescued-ef17c23d2.mp3",
    "duration": 4.264,
    "peak": 0.6634,
    "rms": 0.15
  },
  {
    "id": "north.taken",
    "speaker": "WARD",
    "text": "Through! Allen and Arnold have the courtyard. Secure the stores!",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-north-taken-89f040785.mp3",
    "duration": 4.159,
    "peak": 0.6843,
    "rms": 0.15
  },
  {
    "id": "capture.0",
    "speaker": "RUNNER",
    "text": "They’re giving up. The whole place.",
    "voice": "am_puck",
    "speed": 1.04,
    "lang": "en-us",
    "file": "c6-voice-capture-0-3fc46539f.mp3",
    "duration": 1.5,
    "peak": 0.7896,
    "rms": 0.15
  },
  {
    "id": "capture.1",
    "speaker": "WARD",
    "text": "Let them put their weapons down. Keep the way clear.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-capture-1-a777c4c93.mp3",
    "duration": 3.408,
    "peak": 0.7268,
    "rms": 0.15
  },
  {
    "id": "capture.2",
    "speaker": "ROWAN",
    "text": "All those guns. Sitting here while Boston stays shut.",
    "voice": "am_fenrir",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-capture-2-7c2f6b442.mp3",
    "duration": 3.003,
    "peak": 0.86,
    "rms": 0.1195
  },
  {
    "id": "capture.3",
    "speaker": "WARD",
    "text": "Taking them was the first problem. Moving them will be the next.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-capture-3-1db9b9f6f.mp3",
    "duration": 4.414,
    "peak": 0.86,
    "rms": 0.1408
  },
  {
    "id": "capture.4",
    "speaker": "RUNNER",
    "text": "I’ll watch this door. Get the inventory, Rowan.",
    "voice": "am_puck",
    "speed": 1.04,
    "lang": "en-us",
    "file": "c6-voice-capture-4-b1122bd4a.mp3",
    "duration": 2.458,
    "peak": 0.86,
    "rms": 0.0983
  },
  {
    "id": "north.stores",
    "speaker": "ROWAN",
    "text": "Powder dry. Shot stacked. Now something to fire it from.",
    "voice": "am_fenrir",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-north-stores-55da0591a.mp3",
    "duration": 3.4,
    "peak": 0.86,
    "rms": 0.109
  },
  {
    "id": "north.fitting",
    "speaker": "WARD",
    "text": "That gun. Broken fitting, sound barrel. Mark it. We’ll need a new carriage.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-north-fitting-f121d69fb.mp3",
    "duration": 5.058,
    "peak": 0.8567,
    "rms": 0.15
  },
  {
    "id": "north.pull",
    "speaker": "WARD",
    "text": "Rope tight. Back up slowly. I’ll keep the roller straight.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-north-pull-fa480516f.mp3",
    "duration": 3.981,
    "peak": 0.8331,
    "rms": 0.15
  },
  {
    "id": "north.weight",
    "speaker": "ROWAN",
    "text": "All that, just to move it a few feet.",
    "voice": "am_fenrir",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-north-weight-2f9d4f72b.mp3",
    "duration": 1.952,
    "peak": 0.86,
    "rms": 0.1371
  },
  {
    "id": "north.end.0",
    "speaker": "WARD",
    "text": "Don’t put your hand there. If it rolls, you lose it.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-north-end-0-44989d2b0.mp3",
    "duration": 3.535,
    "peak": 0.86,
    "rms": 0.1412
  },
  {
    "id": "north.end.1",
    "speaker": "ROWAN",
    "text": "You can barely close yours. Let me take the weight.",
    "voice": "am_fenrir",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-north-end-1-1b2b87e51.mp3",
    "duration": 2.908,
    "peak": 0.86,
    "rms": 0.1151
  },
  {
    "id": "north.end.2",
    "speaker": "WARD",
    "text": "You take the weight. I’ll tell you where to put it.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-north-end-2-628970275.mp3",
    "duration": 2.941,
    "peak": 0.8219,
    "rms": 0.15
  },
  {
    "id": "north.end.3",
    "speaker": "RUNNER",
    "text": "Allen and Arnold took the fort. Should I put your names beside the stores?",
    "voice": "am_puck",
    "speed": 1.04,
    "lang": "en-us",
    "file": "c6-voice-north-end-3-b97b42ab5.mp3",
    "duration": 3.895,
    "peak": 0.7441,
    "rms": 0.15
  },
  {
    "id": "north.end.4",
    "speaker": "ROWAN",
    "text": "Put down what we can use. Names won’t open Boston.",
    "voice": "am_fenrir",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-north-end-4-68ee4c47d.mp3",
    "duration": 3.276,
    "peak": 0.86,
    "rms": 0.1084
  },
  {
    "id": "north.end.5",
    "speaker": "WARD",
    "text": "Your brother’s still in there.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-north-end-5-2093836f3.mp3",
    "duration": 1.86,
    "peak": 0.6793,
    "rms": 0.15
  },
  {
    "id": "north.end.6",
    "speaker": "ROWAN",
    "text": "So are other people’s brothers. We find a road for these guns.",
    "voice": "am_fenrir",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-north-end-6-5e9a2c9e0.mp3",
    "duration": 3.729,
    "peak": 0.86,
    "rms": 0.1084
  },
  {
    "id": "north.end.7",
    "speaker": "WARD",
    "text": "Then keep that list dry. We’re going back to the siege.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-north-end-7-4301f8fd4.mp3",
    "duration": 3.569,
    "peak": 0.771,
    "rms": 0.15
  }
];
