// Prerecorded synthetic performances; generated locally with Kokoro-82M.
export const C6_VOICES = [
  {
    "id": "promise.intro.0",
    "speaker": "ISAIAH",
    "text": "November. Virginia. Different water. Same men deciding who belongs on it.",
    "voice": "am_michael",
    "speed": 0.98,
    "lang": "en-us",
    "file": "c6-voice-promise-intro-0-ed1a5ac0a.mp3",
    "duration": 5.462,
    "peak": 0.86,
    "rms": 0.1215
  },
  {
    "id": "promise.intro.1",
    "speaker": "MARA",
    "text": "The relief cargo is ashore. You can come back north with us.",
    "voice": "af_heart",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-promise-intro-1-084e02b4a.mp3",
    "duration": 3.489,
    "peak": 0.86,
    "rms": 0.1368
  },
  {
    "id": "promise.intro.2",
    "speaker": "ISAIAH",
    "text": "One more crossing. A shipwright named Jonas sent word. He has chosen a landing.",
    "voice": "am_michael",
    "speed": 0.98,
    "lang": "en-us",
    "file": "c6-voice-promise-intro-2-9e4a554bf.mp3",
    "duration": 5.543,
    "peak": 0.86,
    "rms": 0.1297
  },
  {
    "id": "promise.intro.3",
    "speaker": "MARA",
    "text": "Dunmore’s men?",
    "voice": "af_heart",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-promise-intro-3-bf465fd12.mp3",
    "duration": 0.958,
    "peak": 0.7333,
    "rms": 0.15
  },
  {
    "id": "promise.intro.4",
    "speaker": "ISAIAH",
    "text": "He wants to hear their offer for himself. I know the channels. That is what I can give him.",
    "voice": "am_michael",
    "speed": 0.98,
    "lang": "en-us",
    "file": "c6-voice-promise-intro-4-4ce037300.mp3",
    "duration": 5.527,
    "peak": 0.86,
    "rms": 0.1331
  },
  {
    "id": "promise.intro.5",
    "speaker": "MARA",
    "text": "And that shoulder?",
    "voice": "af_heart",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-promise-intro-5-83d28fcc2.mp3",
    "duration": 1.012,
    "peak": 0.6582,
    "rms": 0.15
  },
  {
    "id": "promise.intro.6",
    "speaker": "ISAIAH",
    "text": "Old wound. Five years old. It can manage an oar.",
    "voice": "am_michael",
    "speed": 0.98,
    "lang": "en-us",
    "file": "c6-voice-promise-intro-6-ecc6fc93e.mp3",
    "duration": 3.577,
    "peak": 0.86,
    "rms": 0.1388
  },
  {
    "id": "promise.intro.7",
    "speaker": "MARA",
    "text": "Then keep the lamp covered. I will keep a place for you.",
    "voice": "af_heart",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-promise-intro-7-5fae33fa9.mp3",
    "duration": 3.05,
    "peak": 0.86,
    "rms": 0.1227
  },
  {
    "id": "promise.join.0",
    "speaker": "JONAS",
    "text": "Isaiah? Jonas Bell. Push off. He has men watching the road.",
    "voice": "am_onyx",
    "speed": 0.98,
    "lang": "en-us",
    "file": "c6-voice-promise-join-0-cda3b8465.mp3",
    "duration": 4.1,
    "peak": 0.86,
    "rms": 0.1294
  },
  {
    "id": "promise.join.1",
    "speaker": "ISAIAH",
    "text": "The man who enslaves you?",
    "voice": "am_michael",
    "speed": 0.98,
    "lang": "en-us",
    "file": "c6-voice-promise-join-1-404772e39.mp3",
    "duration": 1.541,
    "peak": 0.7817,
    "rms": 0.15
  },
  {
    "id": "promise.join.2",
    "speaker": "JONAS",
    "text": "He calls himself a Patriot. Says no king can make him a slave. Then locks my door.",
    "voice": "am_onyx",
    "speed": 0.98,
    "lang": "en-us",
    "file": "c6-voice-promise-join-2-5675e3a24.mp3",
    "duration": 5.25,
    "peak": 0.86,
    "rms": 0.0669
  },
  {
    "id": "promise.join.3",
    "speaker": "ISAIAH",
    "text": "That paper. Dunmore’s proclamation?",
    "voice": "am_michael",
    "speed": 0.98,
    "lang": "en-us",
    "file": "c6-voice-promise-join-3-bc2f847a3.mp3",
    "duration": 2.531,
    "peak": 0.86,
    "rms": 0.1175
  },
  {
    "id": "promise.join.4",
    "speaker": "JONAS",
    "text": "November seventh. The royal governor offers freedom to enslaved people and indentured servants belonging to rebels.",
    "voice": "am_onyx",
    "speed": 0.98,
    "lang": "en-us",
    "file": "c6-voice-promise-join-4-9aee2759b.mp3",
    "duration": 6.947,
    "peak": 0.86,
    "rms": 0.0799
  },
  {
    "id": "promise.join.5",
    "speaker": "ISAIAH",
    "text": "Able and willing to bear arms. Joining the king’s troops. There are conditions.",
    "voice": "am_michael",
    "speed": 0.98,
    "lang": "en-us",
    "file": "c6-voice-promise-join-5-ea69e1bef.mp3",
    "duration": 5.156,
    "peak": 0.86,
    "rms": 0.1402
  },
  {
    "id": "promise.join.6",
    "speaker": "JONAS",
    "text": "I read them. My wife is on another estate. This promises nothing for her.",
    "voice": "am_onyx",
    "speed": 0.98,
    "lang": "en-us",
    "file": "c6-voice-promise-join-6-19ca77eb4.mp3",
    "duration": 4.358,
    "peak": 0.86,
    "rms": 0.1474
  },
  {
    "id": "promise.join.7",
    "speaker": "ISAIAH",
    "text": "I am free already. I cannot choose the risk for you.",
    "voice": "am_michael",
    "speed": 0.98,
    "lang": "en-us",
    "file": "c6-voice-promise-join-7-0ecb43371.mp3",
    "duration": 3.525,
    "peak": 0.86,
    "rms": 0.1365
  },
  {
    "id": "promise.join.8",
    "speaker": "JONAS",
    "text": "Then take me to the tender. I am choosing it.",
    "voice": "am_onyx",
    "speed": 0.98,
    "lang": "en-us",
    "file": "c6-voice-promise-join-8-15f51a9a1.mp3",
    "duration": 2.892,
    "peak": 0.86,
    "rms": 0.0797
  },
  {
    "id": "promise.contact.0",
    "speaker": "AGENT",
    "text": "Who sent this boat?",
    "voice": "bm_lewis",
    "speed": 0.99,
    "lang": "en-gb",
    "file": "c6-voice-promise-contact-0-be47763dd.mp3",
    "duration": 1.418,
    "peak": 0.86,
    "rms": 0.1267
  },
  {
    "id": "promise.contact.1",
    "speaker": "JONAS",
    "text": "I brought myself. Jonas Bell. Shipwright. I can serve.",
    "voice": "am_onyx",
    "speed": 0.98,
    "lang": "en-us",
    "file": "c6-voice-promise-contact-1-d712e9227.mp3",
    "duration": 3.5,
    "peak": 0.86,
    "rms": 0.0761
  },
  {
    "id": "promise.contact.2",
    "speaker": "AGENT",
    "text": "The man claiming you. Rebel, or loyal to the Crown?",
    "voice": "bm_lewis",
    "speed": 0.99,
    "lang": "en-gb",
    "file": "c6-voice-promise-contact-2-d4079de36.mp3",
    "duration": 3.45,
    "peak": 0.86,
    "rms": 0.0954
  },
  {
    "id": "promise.contact.3",
    "speaker": "JONAS",
    "text": "Rebel. Does your offer stop at a Loyalist’s door?",
    "voice": "am_onyx",
    "speed": 0.98,
    "lang": "en-us",
    "file": "c6-voice-promise-contact-3-e3b6d2936.mp3",
    "duration": 2.813,
    "peak": 0.8106,
    "rms": 0.15
  },
  {
    "id": "promise.contact.4",
    "speaker": "AGENT",
    "text": "His offer does not free people held by loyal subjects. His lordship needs soldiers.",
    "voice": "bm_lewis",
    "speed": 0.99,
    "lang": "en-gb",
    "file": "c6-voice-promise-contact-4-f5a7273af.mp3",
    "duration": 5.554,
    "peak": 0.86,
    "rms": 0.0962
  },
  {
    "id": "promise.contact.5",
    "speaker": "JONAS",
    "text": "And my wife?",
    "voice": "am_onyx",
    "speed": 0.98,
    "lang": "en-us",
    "file": "c6-voice-promise-contact-5-1b8315756.mp3",
    "duration": 1.143,
    "peak": 0.7846,
    "rms": 0.15
  },
  {
    "id": "promise.contact.6",
    "speaker": "AGENT",
    "text": "I cannot promise her passage. Join us at the sheltered inlet. Our boat will meet you there.",
    "voice": "bm_lewis",
    "speed": 0.99,
    "lang": "en-gb",
    "file": "c6-voice-promise-contact-6-1133186e4.mp3",
    "duration": 5.581,
    "peak": 0.86,
    "rms": 0.0922
  },
  {
    "id": "promise.contact.7",
    "speaker": "CLAIMANT",
    "text": "That is my shipwright! Dunmore is stealing our property! Stop that boat!",
    "voice": "am_eric",
    "speed": 1.03,
    "lang": "en-us",
    "file": "c6-voice-promise-contact-7-dd7697051.mp3",
    "duration": 3.651,
    "peak": 0.7775,
    "rms": 0.15
  },
  {
    "id": "promise.contact.8",
    "speaker": "ISAIAH",
    "text": "Skiff off the stern. Jonas, down! The mooring boom. Can you cut it?",
    "voice": "am_michael",
    "speed": 0.98,
    "lang": "en-us",
    "file": "c6-voice-promise-contact-8-e910c7e68.mp3",
    "duration": 4.553,
    "peak": 0.86,
    "rms": 0.1113
  },
  {
    "id": "promise.contact.9",
    "speaker": "JONAS",
    "text": "Put me alongside. I built enough of these.",
    "voice": "am_onyx",
    "speed": 0.98,
    "lang": "en-us",
    "file": "c6-voice-promise-contact-9-ce91ed592.mp3",
    "duration": 2.77,
    "peak": 0.86,
    "rms": 0.1323
  },
  {
    "id": "promise.end.0",
    "speaker": "JONAS",
    "text": "There. The inlet. They waited.",
    "voice": "am_onyx",
    "speed": 0.98,
    "lang": "en-us",
    "file": "c6-voice-promise-end-0-ae93968f0.mp3",
    "duration": 2.383,
    "peak": 0.86,
    "rms": 0.1161
  },
  {
    "id": "promise.end.1",
    "speaker": "ISAIAH",
    "text": "Your hands are shaking.",
    "voice": "am_michael",
    "speed": 0.98,
    "lang": "en-us",
    "file": "c6-voice-promise-end-1-1ccf7b7f3.mp3",
    "duration": 1.543,
    "peak": 0.739,
    "rms": 0.15
  },
  {
    "id": "promise.end.2",
    "speaker": "JONAS",
    "text": "They were shaking when I left the yard. I left anyway.",
    "voice": "am_onyx",
    "speed": 0.98,
    "lang": "en-us",
    "file": "c6-voice-promise-end-2-de08faf5b.mp3",
    "duration": 3.219,
    "peak": 0.86,
    "rms": 0.0934
  },
  {
    "id": "promise.end.3",
    "speaker": "ISAIAH",
    "text": "I will carry a message if you can get one out. For your wife.",
    "voice": "am_michael",
    "speed": 0.98,
    "lang": "en-us",
    "file": "c6-voice-promise-end-3-9bf509766.mp3",
    "duration": 3.833,
    "peak": 0.86,
    "rms": 0.1318
  },
  {
    "id": "promise.end.4",
    "speaker": "JONAS",
    "text": "Her name is Ruth. Do not let her become just another missing name.",
    "voice": "am_onyx",
    "speed": 0.98,
    "lang": "en-us",
    "file": "c6-voice-promise-end-4-ab77507c7.mp3",
    "duration": 3.957,
    "peak": 0.86,
    "rms": 0.1419
  },
  {
    "id": "promise.end.5",
    "speaker": "ISAIAH",
    "text": "Ruth Bell. I heard you.",
    "voice": "am_michael",
    "speed": 0.98,
    "lang": "en-us",
    "file": "c6-voice-promise-end-5-5666fc6a5.mp3",
    "duration": 1.748,
    "peak": 0.86,
    "rms": 0.1469
  },
  {
    "id": "promise.end.6",
    "speaker": "JONAS",
    "text": "I will do the rest myself. Thank you for the water.",
    "voice": "am_onyx",
    "speed": 0.98,
    "lang": "en-us",
    "file": "c6-voice-promise-end-6-60bf4d1c2.mp3",
    "duration": 3.215,
    "peak": 0.86,
    "rms": 0.1252
  },
  {
    "id": "creek.intro.0",
    "speaker": "ISAIAH",
    "text": "North Carolina. February twenty-seventh, seventeen seventy-six. Three months of carrying supplies along this coast.",
    "voice": "am_michael",
    "speed": 0.98,
    "lang": "en-us",
    "file": "c6-voice-creek-intro-0-849b7f06f.mp3",
    "duration": 8.109,
    "peak": 0.86,
    "rms": 0.0998
  },
  {
    "id": "creek.intro.1",
    "speaker": "RUNNER",
    "text": "The fighting at Moore’s Creek Bridge is over. Patriots broke the Loyalist advance this morning.",
    "voice": "am_puck",
    "speed": 1.04,
    "lang": "en-us",
    "file": "c6-voice-creek-intro-1-f45bf768c.mp3",
    "duration": 5.441,
    "peak": 0.86,
    "rms": 0.0741
  },
  {
    "id": "creek.intro.2",
    "speaker": "ISAIAH",
    "text": "I can still hear someone on the far bank.",
    "voice": "am_michael",
    "speed": 0.98,
    "lang": "en-us",
    "file": "c6-voice-creek-intro-2-8c03aaf6b.mp3",
    "duration": 2.47,
    "peak": 0.86,
    "rms": 0.1483
  },
  {
    "id": "creek.intro.3",
    "speaker": "RUNNER",
    "text": "Show the captain your dispatch. They stripped boards off the bridge before the attack. Mind the gap.",
    "voice": "am_puck",
    "speed": 1.04,
    "lang": "en-us",
    "file": "c6-voice-creek-intro-3-048cf7143.mp3",
    "duration": 5.519,
    "peak": 0.86,
    "rms": 0.1139
  },
  {
    "id": "creek.intro.4",
    "speaker": "ISAIAH",
    "text": "A man can drown on the winning side of a battle. Get a blanket ready.",
    "voice": "am_michael",
    "speed": 0.98,
    "lang": "en-us",
    "file": "c6-voice-creek-intro-4-288201d4e.mp3",
    "duration": 4.461,
    "peak": 0.86,
    "rms": 0.1198
  },
  {
    "id": "creek.end.0",
    "speaker": "RUNNER",
    "text": "He fought for the king. You knew that.",
    "voice": "am_puck",
    "speed": 1.04,
    "lang": "en-us",
    "file": "c6-voice-creek-end-0-af739bc7d.mp3",
    "duration": 1.581,
    "peak": 0.86,
    "rms": 0.0869
  },
  {
    "id": "creek.end.1",
    "speaker": "ISAIAH",
    "text": "So did the man who opened Ward’s cell. Get him water.",
    "voice": "am_michael",
    "speed": 0.98,
    "lang": "en-us",
    "file": "c6-voice-creek-end-1-4aecea41c.mp3",
    "duration": 3.416,
    "peak": 0.86,
    "rms": 0.1214
  },
  {
    "id": "creek.end.2",
    "speaker": "RUNNER",
    "text": "They say this victory has broken the Loyalist rising here.",
    "voice": "am_puck",
    "speed": 1.04,
    "lang": "en-us",
    "file": "c6-voice-creek-end-2-1566b21a8.mp3",
    "duration": 3.211,
    "peak": 0.8535,
    "rms": 0.15
  },
  {
    "id": "creek.end.3",
    "speaker": "ISAIAH",
    "text": "Here. Not everywhere. Families will still be on different sides tomorrow.",
    "voice": "am_michael",
    "speed": 0.98,
    "lang": "en-us",
    "file": "c6-voice-creek-end-3-2d6552a6f.mp3",
    "duration": 4.604,
    "peak": 0.86,
    "rms": 0.1112
  },
  {
    "id": "creek.end.4",
    "speaker": "RUNNER",
    "text": "And Jonas?",
    "voice": "am_puck",
    "speed": 1.04,
    "lang": "en-us",
    "file": "c6-voice-creek-end-4-51d1f8237.mp3",
    "duration": 0.837,
    "peak": 0.86,
    "rms": 0.1261
  },
  {
    "id": "creek.end.5",
    "speaker": "ISAIAH",
    "text": "Chose the British because he saw a way out of slavery. Some Black men serve with the Patriots. Service does not mean freedom is automatically granted.",
    "voice": "am_michael",
    "speed": 0.98,
    "lang": "en-us",
    "file": "c6-voice-creek-end-5-7f2742797.mp3",
    "duration": 10.243,
    "peak": 0.86,
    "rms": 0.0729
  },
  {
    "id": "creek.end.6",
    "speaker": "ISAIAH",
    "text": "I promised to carry a message. Not to pretend the country has answered him.",
    "voice": "am_michael",
    "speed": 0.98,
    "lang": "en-us",
    "file": "c6-voice-creek-end-6-b05fe9eb3.mp3",
    "duration": 4.656,
    "peak": 0.86,
    "rms": 0.1079
  },
  {
    "id": "promise.coda.0",
    "speaker": "MARA",
    "text": "A later dispatch. Virginia, seventeen seventy-six. Dunmore has fled the colony.",
    "voice": "af_heart",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-promise-coda-0-468a9ee05.mp3",
    "duration": 5.47,
    "peak": 0.86,
    "rms": 0.1193
  },
  {
    "id": "promise.coda.1",
    "speaker": "ISAIAH",
    "text": "He promised freedom where he needed soldiers. Even that limited offer frightened Patriot enslavers into stronger resistance.",
    "voice": "am_michael",
    "speed": 0.98,
    "lang": "en-us",
    "file": "c6-voice-promise-coda-1-60bbc5b03.mp3",
    "duration": 8.467,
    "peak": 0.86,
    "rms": 0.1051
  },
  {
    "id": "promise.coda.2",
    "speaker": "MARA",
    "text": "And the people who trusted his promise?",
    "voice": "af_heart",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-promise-coda-2-270da0ad3.mp3",
    "duration": 1.989,
    "peak": 0.86,
    "rms": 0.1266
  },
  {
    "id": "promise.coda.3",
    "speaker": "ISAIAH",
    "text": "Their search for freedom did not end when his ships left. Neither does our road.",
    "voice": "am_michael",
    "speed": 0.98,
    "lang": "en-us",
    "file": "c6-voice-promise-coda-3-0978df846.mp3",
    "duration": 4.818,
    "peak": 0.849,
    "rms": 0.15
  },
  {
    "id": "promise.reeds",
    "speaker": "JONAS",
    "text": "That lantern is passing. The tender is beyond the next island. Keep to the eastern channel.",
    "voice": "am_onyx",
    "speed": 0.98,
    "lang": "en-us",
    "file": "c6-voice-promise-reeds-4e032a074.mp3",
    "duration": 5.619,
    "peak": 0.86,
    "rms": 0.1354
  },
  {
    "id": "promise.spotted",
    "speaker": "ISAIAH",
    "text": "They have our wake. Slow down in the reeds. Make them lose us.",
    "voice": "am_michael",
    "speed": 0.98,
    "lang": "en-us",
    "file": "c6-voice-promise-spotted-3a565f89f.mp3",
    "duration": 3.998,
    "peak": 0.86,
    "rms": 0.1298
  },
  {
    "id": "promise.cut",
    "speaker": "JONAS",
    "text": "Rope is cut! Hard strokes, Isaiah! Straight through, then left for the inlet!",
    "voice": "am_onyx",
    "speed": 0.98,
    "lang": "en-us",
    "file": "c6-voice-promise-cut-508067811.mp3",
    "duration": 4.603,
    "peak": 0.86,
    "rms": 0.119
  },
  {
    "id": "promise.retry",
    "speaker": "ISAIAH",
    "text": "Breathe. Read the water. We can get through.",
    "voice": "am_michael",
    "speed": 0.98,
    "lang": "en-us",
    "file": "c6-voice-promise-retry-01d48c3a8.mp3",
    "duration": 2.735,
    "peak": 0.86,
    "rms": 0.1273
  },
  {
    "id": "creek.orders",
    "speaker": "MILITIA",
    "text": "Mecklenburg Resolves. May, seventeen seventy-five. Our county rejected the Crown’s authority when the rebellion began.",
    "voice": "bm_george",
    "speed": 1.04,
    "lang": "en-gb",
    "file": "c6-voice-creek-orders-b873aaf50.mp3",
    "duration": 8.219,
    "peak": 0.8548,
    "rms": 0.15
  },
  {
    "id": "creek.authority",
    "speaker": "MILITIA",
    "text": "The resolves put our militia under Congress, not the king. You may pass. Bring that wounded man back.",
    "voice": "bm_george",
    "speed": 1.04,
    "lang": "en-gb",
    "file": "c6-voice-creek-authority-3b9c93ceb.mp3",
    "duration": 6.246,
    "peak": 0.7547,
    "rms": 0.15
  },
  {
    "id": "creek.boards",
    "speaker": "ISAIAH",
    "text": "Boards are down. Easy across. The Loyalists tried to cross into Patriot fire this morning.",
    "voice": "am_michael",
    "speed": 0.98,
    "lang": "en-us",
    "file": "c6-voice-creek-boards-494821bad.mp3",
    "duration": 6.853,
    "peak": 0.86,
    "rms": 0.1278
  },
  {
    "id": "creek.lift",
    "speaker": "ISAIAH",
    "text": "I have you. Leave the weapon. Your arm over my shoulder.",
    "voice": "am_michael",
    "speed": 0.98,
    "lang": "en-us",
    "file": "c6-voice-creek-lift-26da86235.mp3",
    "duration": 3.586,
    "peak": 0.86,
    "rms": 0.1468
  },
  {
    "id": "creek.safe",
    "speaker": "RUNNER",
    "text": "Here. On the blanket. He is breathing. I will stay with him.",
    "voice": "am_puck",
    "speed": 1.04,
    "lang": "en-us",
    "file": "c6-voice-creek-safe-818bd9628.mp3",
    "duration": 3.082,
    "peak": 0.86,
    "rms": 0.1339
  },
  {
    "id": "release.0",
    "speaker": "THOMAS",
    "text": "The release is signed. Give him his coat.",
    "voice": "bm_fable",
    "speed": 0.98,
    "lang": "en-gb",
    "file": "c6-voice-release-0-457484345.mp3",
    "duration": 3.112,
    "peak": 0.86,
    "rms": 0.1307
  },
  {
    "id": "release.1",
    "speaker": "ROWAN",
    "text": "Ward? It’s me.",
    "voice": "am_fenrir",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-release-1-550de5e9d.mp3",
    "duration": 1.259,
    "peak": 0.86,
    "rms": 0.1114
  },
  {
    "id": "release.2",
    "speaker": "WARD",
    "text": "I know your footsteps. You still hurry when you’re frightened.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-release-2-0c6a96ff1.mp3",
    "duration": 3.646,
    "peak": 0.7208,
    "rms": 0.15
  },
  {
    "id": "release.3",
    "speaker": "ROWAN",
    "text": "Can you walk?",
    "voice": "am_fenrir",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-release-3-89487b12f.mp3",
    "duration": 0.83,
    "peak": 0.86,
    "rms": 0.1439
  },
  {
    "id": "release.4",
    "speaker": "WARD",
    "text": "With a little help. Don’t make a ceremony of it.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-release-4-91a102e51.mp3",
    "duration": 2.944,
    "peak": 0.7098,
    "rms": 0.15
  },
  {
    "id": "help",
    "speaker": "WARD",
    "text": "Easy. They gave me my coat back. Not quite my legs.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-help-7c8cf82be.mp3",
    "duration": 3.774,
    "peak": 0.7002,
    "rms": 0.15
  },
  {
    "id": "releasewalk",
    "speaker": "MARA",
    "text": "Bring him to the wagon. There’s a blanket beside me.",
    "voice": "af_heart",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-releasewalk-594840009.mp3",
    "duration": 2.795,
    "peak": 0.86,
    "rms": 0.1185
  },
  {
    "id": "gate.0",
    "speaker": "MARA",
    "text": "Hold still. This buckle never liked you.",
    "voice": "af_heart",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-gate-0-b5d86f0ed.mp3",
    "duration": 2.424,
    "peak": 0.86,
    "rms": 0.1079
  },
  {
    "id": "gate.1",
    "speaker": "WARD",
    "text": "You kept the wagon.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-gate-1-ec176aad0.mp3",
    "duration": 1.431,
    "peak": 0.86,
    "rms": 0.147
  },
  {
    "id": "gate.2",
    "speaker": "ISAIAH",
    "text": "And a place in it. We weren’t leaving you here.",
    "voice": "am_michael",
    "speed": 0.98,
    "lang": "en-us",
    "file": "c6-voice-gate-2-811237426.mp3",
    "duration": 2.614,
    "peak": 0.86,
    "rms": 0.1247
  },
  {
    "id": "gate.3",
    "speaker": "THOMAS",
    "text": "You asked me to find him, Rowan. I kept my word.",
    "voice": "bm_fable",
    "speed": 0.98,
    "lang": "en-gb",
    "file": "c6-voice-gate-3-59a75eeb0.mp3",
    "duration": 3.726,
    "peak": 0.86,
    "rms": 0.0582
  },
  {
    "id": "gate.4",
    "speaker": "ROWAN",
    "text": "Then come with us.",
    "voice": "am_fenrir",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-gate-4-50f5d59ab.mp3",
    "duration": 1.032,
    "peak": 0.86,
    "rms": 0.1219
  },
  {
    "id": "gate.5",
    "speaker": "THOMAS",
    "text": "You’re my family. That doesn’t make this rebellion right.",
    "voice": "bm_fable",
    "speed": 0.98,
    "lang": "en-gb",
    "file": "c6-voice-gate-5-22da18500.mp3",
    "duration": 3.935,
    "peak": 0.86,
    "rms": 0.1078
  },
  {
    "id": "gate.6",
    "speaker": "WARD",
    "text": "Let him go. A man can open a door without crossing it.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-gate-6-1075020a8.mp3",
    "duration": 3.738,
    "peak": 0.7374,
    "rms": 0.15
  },
  {
    "id": "night.0",
    "speaker": "WARD",
    "text": "Gage has troops moving out of Boston. They’re after the powder at Concord.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-night-0-2d6f693cb.mp3",
    "duration": 4.938,
    "peak": 0.778,
    "rms": 0.15
  },
  {
    "id": "night.1",
    "speaker": "ROWAN",
    "text": "Again? Cambridge. Charlestown. How much more will they take?",
    "voice": "am_fenrir",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-night-1-b8900da7c.mp3",
    "duration": 3.585,
    "peak": 0.86,
    "rms": 0.1035
  },
  {
    "id": "night.2",
    "speaker": "WARD",
    "text": "They came away empty-handed at Salem. New Hampshire took the guns at Fort William and Mary. People are ready.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-night-2-f1ff2f1c4.mp3",
    "duration": 7.262,
    "peak": 0.86,
    "rms": 0.1422
  },
  {
    "id": "night.3",
    "speaker": "ROWAN",
    "text": "Then we get the warning to them. The north farm first.",
    "voice": "am_fenrir",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-night-3-63d6201f1.mp3",
    "duration": 3.031,
    "peak": 0.86,
    "rms": 0.0894
  },
  {
    "id": "farm.0",
    "speaker": "RUNNER",
    "text": "British troops? I’ll wake the others. Our minutemen can assemble in a minute.",
    "voice": "am_puck",
    "speed": 1.04,
    "lang": "en-us",
    "file": "c6-voice-farm-0-1e490b682.mp3",
    "duration": 4.001,
    "peak": 0.86,
    "rms": 0.1223
  },
  {
    "id": "farm.1",
    "speaker": "WARD",
    "text": "Some of those men fought the French with me. They know what a musket sounds like. Ring the meeting bell.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-farm-1-d320bd8a3.mp3",
    "duration": 6.097,
    "peak": 0.86,
    "rms": 0.1294
  },
  {
    "id": "bell.0",
    "speaker": "RUNNER",
    "text": "Revere was stopped by a British patrol. Other riders are carrying the warning on.",
    "voice": "am_puck",
    "speed": 1.04,
    "lang": "en-us",
    "file": "c6-voice-bell-0-95c7de7d0.mp3",
    "duration": 4.554,
    "peak": 0.86,
    "rms": 0.1291
  },
  {
    "id": "bell.1",
    "speaker": "ROWAN",
    "text": "One rider doesn’t carry the whole country. Get your neighbors out.",
    "voice": "am_fenrir",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-bell-1-34370320c.mp3",
    "duration": 3.553,
    "peak": 0.86,
    "rms": 0.1148
  },
  {
    "id": "ridge",
    "speaker": "WARD",
    "text": "The lanterns are gathering on the road. Keep to the trees. We meet the others beyond the ridge.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-ridge-245d54b29.mp3",
    "duration": 5.942,
    "peak": 0.7716,
    "rms": 0.15
  },
  {
    "id": "patrol",
    "speaker": "WARD",
    "text": "Lantern ahead. Stay low behind the fence. Let the patrol pass.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-patrol-b3dbd925a.mp3",
    "duration": 4.692,
    "peak": 0.7806,
    "rms": 0.15
  },
  {
    "id": "spotted",
    "speaker": "WARD",
    "text": "They’ve seen us! Break their sight. Through the orchard!",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-spotted-a06485281.mp3",
    "duration": 3.439,
    "peak": 0.7607,
    "rms": 0.15
  },
  {
    "id": "lex.0",
    "speaker": "MARA",
    "text": "People came out to see what was happening. Now they can’t get off the green.",
    "voice": "af_heart",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-lex-0-afbbe35c3.mp3",
    "duration": 3.972,
    "peak": 0.86,
    "rms": 0.1392
  },
  {
    "id": "lex.1",
    "speaker": "WARD",
    "text": "Stay close. No one here knows what the next man will do.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-lex-1-016855ab7.mp3",
    "duration": 3.955,
    "peak": 0.86,
    "rms": 0.1347
  },
  {
    "id": "lex.2",
    "speaker": "ROWAN",
    "text": "Who fired?",
    "voice": "am_fenrir",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-lex-2-b9def6f53.mp3",
    "duration": 0.83,
    "peak": 0.86,
    "rms": 0.1011
  },
  {
    "id": "lex.3",
    "speaker": "WARD",
    "text": "I couldn’t see. Get down!",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-lex-3-6befa445a.mp3",
    "duration": 2.178,
    "peak": 0.86,
    "rms": 0.1379
  },
  {
    "id": "lex.4",
    "speaker": "MARA",
    "text": "There’s someone by the wall. Rowan, help me get him out!",
    "voice": "af_heart",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-lex-4-5e152c175.mp3",
    "duration": 2.907,
    "peak": 0.86,
    "rms": 0.1359
  },
  {
    "id": "rescue.0",
    "speaker": "RUNNER",
    "text": "My leg. I can’t put any weight on it.",
    "voice": "am_puck",
    "speed": 1.04,
    "lang": "en-us",
    "file": "c6-voice-rescue-0-b3962624f.mp3",
    "duration": 1.88,
    "peak": 0.7877,
    "rms": 0.15
  },
  {
    "id": "rescue.1",
    "speaker": "ROWAN",
    "text": "Put your arm over me. We’re going to that wagon.",
    "voice": "am_fenrir",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-rescue-1-d4999af73.mp3",
    "duration": 2.663,
    "peak": 0.86,
    "rms": 0.1086
  },
  {
    "id": "rescue.2",
    "speaker": "MARA",
    "text": "I’ve got him. There’s another man behind the fence. Bring him through the garden.",
    "voice": "af_heart",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-rescue-2-a770f5ae3.mp3",
    "duration": 4.319,
    "peak": 0.8011,
    "rms": 0.15
  },
  {
    "id": "rescue.3",
    "speaker": "WARD",
    "text": "The lane is clear. Leave the green. Now!",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-rescue-3-b9ebf536a.mp3",
    "duration": 3.021,
    "peak": 0.6884,
    "rms": 0.15
  },
  {
    "id": "concord.0",
    "speaker": "WARD",
    "text": "They reached Concord. Now they’re falling back toward Boston, and more militia are coming in along the road.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-concord-0-4beff6152.mp3",
    "duration": 6.876,
    "peak": 0.6938,
    "rms": 0.15
  },
  {
    "id": "concord.1",
    "speaker": "MARA",
    "text": "Our wagon has wounded aboard. I need that crossing clear.",
    "voice": "af_heart",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-concord-1-899099d61.mp3",
    "duration": 3.209,
    "peak": 0.86,
    "rms": 0.1193
  },
  {
    "id": "concord.2",
    "speaker": "WARD",
    "text": "Take the spare musket. One shot, then reload. Use the wall while your hands are busy.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-concord-2-e298ed928.mp3",
    "duration": 5.998,
    "peak": 0.86,
    "rms": 0.1377
  },
  {
    "id": "armed",
    "speaker": "WARD",
    "text": "Hold the stone wall. Keep their fire off the wagon. I’ll watch the left.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-armed-b47383c82.mp3",
    "duration": 4.795,
    "peak": 0.7502,
    "rms": 0.15
  },
  {
    "id": "wave.1",
    "speaker": "WARD",
    "text": "They’re coming through the smoke. Don’t stand in the open!",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-wave-1-4423c0afc.mp3",
    "duration": 3.685,
    "peak": 0.7982,
    "rms": 0.15
  },
  {
    "id": "wave.2",
    "speaker": "MARA",
    "text": "The wheel’s free! A little longer. Keep them back!",
    "voice": "af_heart",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-wave-2-0d0628030.mp3",
    "duration": 2.844,
    "peak": 0.86,
    "rms": 0.1363
  },
  {
    "id": "clear",
    "speaker": "MARA",
    "text": "We’re across! Rowan, Ward, fall back to the orchard!",
    "voice": "af_heart",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-clear-92e53cbc7.mp3",
    "duration": 2.995,
    "peak": 0.86,
    "rms": 0.1262
  },
  {
    "id": "reload",
    "speaker": "WARD",
    "text": "Reload behind cover. That wall is worth more than another shot.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-reload-d89b3dfb3.mp3",
    "duration": 4.26,
    "peak": 0.6286,
    "rms": 0.15
  },
  {
    "id": "end.0",
    "speaker": "ROWAN",
    "text": "This morning I thought getting the warning through would be enough.",
    "voice": "am_fenrir",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-end-0-e1e031bbe.mp3",
    "duration": 2.943,
    "peak": 0.86,
    "rms": 0.0966
  },
  {
    "id": "end.1",
    "speaker": "WARD",
    "text": "It got these people out. That was enough for this morning.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-end-1-ef0e69c87.mp3",
    "duration": 3.446,
    "peak": 0.86,
    "rms": 0.1408
  },
  {
    "id": "end.2",
    "speaker": "MARA",
    "text": "Militia are marching toward Boston from everywhere. They’re surrounding the city.",
    "voice": "af_heart",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-end-2-33363ff71.mp3",
    "duration": 4.465,
    "peak": 0.86,
    "rms": 0.1489
  },
  {
    "id": "end.3",
    "speaker": "ROWAN",
    "text": "And Thomas is still inside.",
    "voice": "am_fenrir",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-end-3-43eab6075.mp3",
    "duration": 1.527,
    "peak": 0.86,
    "rms": 0.1175
  },
  {
    "id": "end.4",
    "speaker": "WARD",
    "text": "Then we keep a road open. We leave with everyone we can.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-end-4-e3098aea9.mp3",
    "duration": 3.942,
    "peak": 0.8433,
    "rms": 0.15
  },
  {
    "id": "end.5",
    "speaker": "ISAIAH",
    "text": "I’ll find us a way through the harbor. You get some sleep.",
    "voice": "am_michael",
    "speed": 0.98,
    "lang": "en-us",
    "file": "c6-voice-end-5-04875a883.mp3",
    "duration": 3.429,
    "peak": 0.86,
    "rms": 0.1341
  },
  {
    "id": "retry",
    "speaker": "WARD",
    "text": "Find cover. Breathe. We try the route again.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-retry-5c03f9327.mp3",
    "duration": 3.366,
    "peak": 0.86,
    "rms": 0.1428
  },
  {
    "id": "north.0",
    "speaker": "ISAIAH",
    "text": "There. Past the mist. Ticonderoga.",
    "voice": "am_michael",
    "speed": 0.98,
    "lang": "en-us",
    "file": "c6-voice-north-0-142ce2e3c.mp3",
    "duration": 2.686,
    "peak": 0.8139,
    "rms": 0.15
  },
  {
    "id": "north.1",
    "speaker": "ROWAN",
    "text": "Boston is the other way.",
    "voice": "am_fenrir",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-north-1-6979dbcad.mp3",
    "duration": 1.305,
    "peak": 0.86,
    "rms": 0.1095
  },
  {
    "id": "north.2",
    "speaker": "WARD",
    "text": "We can surround a city with men. To force the British out, we need guns.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-north-2-443b1a7f8.mp3",
    "duration": 4.989,
    "peak": 0.86,
    "rms": 0.1365
  },
  {
    "id": "north.3",
    "speaker": "RUNNER",
    "text": "Allen and Arnold are bringing the men up. They want us at the passage.",
    "voice": "am_puck",
    "speed": 1.04,
    "lang": "en-us",
    "file": "c6-voice-north-3-75d2594e1.mp3",
    "duration": 3.647,
    "peak": 0.7035,
    "rms": 0.15
  },
  {
    "id": "north.4",
    "speaker": "ISAIAH",
    "text": "I’ll keep the boat ready. Nathan, stay on Rowan’s shoulder.",
    "voice": "am_michael",
    "speed": 0.98,
    "lang": "en-us",
    "file": "c6-voice-north-4-16a164b04.mp3",
    "duration": 3.847,
    "peak": 0.86,
    "rms": 0.1184
  },
  {
    "id": "north.5",
    "speaker": "ROWAN",
    "text": "And if the sentry sees us?",
    "voice": "am_fenrir",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-north-5-014574074.mp3",
    "duration": 1.432,
    "peak": 0.86,
    "rms": 0.126
  },
  {
    "id": "north.6",
    "speaker": "WARD",
    "text": "We move together. This is a surprise, not a firing line.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-north-6-efae60f2a.mp3",
    "duration": 4.17,
    "peak": 0.7154,
    "rms": 0.15
  },
  {
    "id": "north.7",
    "speaker": "ISAIAH",
    "text": "Rowan. Leave room for everyone on the way back.",
    "voice": "am_michael",
    "speed": 0.98,
    "lang": "en-us",
    "file": "c6-voice-north-7-9a2291d60.mp3",
    "duration": 3.045,
    "peak": 0.86,
    "rms": 0.1123
  },
  {
    "id": "north.ready",
    "speaker": "WARD",
    "text": "The wall hides us. Left side of the passage. Watch where his lantern points.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-north-ready-fb24c3242.mp3",
    "duration": 5.053,
    "peak": 0.7812,
    "rms": 0.15
  },
  {
    "id": "north.signal",
    "speaker": "WARD",
    "text": "I see you. Taking the left door. Get that latch up for the others.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-north-signal-21e338f84.mp3",
    "duration": 4.374,
    "peak": 0.7644,
    "rms": 0.15
  },
  {
    "id": "north.alarm",
    "speaker": "RUNNER",
    "text": "My foot! Rowan, I’m caught!",
    "voice": "am_puck",
    "speed": 1.04,
    "lang": "en-us",
    "file": "c6-voice-north-alarm-ecfc569fe.mp3",
    "duration": 1.376,
    "peak": 0.86,
    "rms": 0.1266
  },
  {
    "id": "north.rescued",
    "speaker": "WARD",
    "text": "He’s clear! They’ve heard us. Open the passage. Our men are coming!",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-north-rescued-ef17c23d2.mp3",
    "duration": 4.264,
    "peak": 0.6634,
    "rms": 0.15
  },
  {
    "id": "north.taken",
    "speaker": "WARD",
    "text": "Through! Allen and Arnold have the courtyard. Secure the stores!",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-north-taken-89f040785.mp3",
    "duration": 4.159,
    "peak": 0.6843,
    "rms": 0.15
  },
  {
    "id": "capture.0",
    "speaker": "RUNNER",
    "text": "They’re giving up. The whole place.",
    "voice": "am_puck",
    "speed": 1.04,
    "lang": "en-us",
    "file": "c6-voice-capture-0-3fc46539f.mp3",
    "duration": 1.5,
    "peak": 0.7896,
    "rms": 0.15
  },
  {
    "id": "capture.1",
    "speaker": "WARD",
    "text": "Let them put their weapons down. Keep the way clear.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-capture-1-a777c4c93.mp3",
    "duration": 3.408,
    "peak": 0.7268,
    "rms": 0.15
  },
  {
    "id": "capture.2",
    "speaker": "ROWAN",
    "text": "All those guns. Sitting here while Boston stays shut.",
    "voice": "am_fenrir",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-capture-2-7c2f6b442.mp3",
    "duration": 3.003,
    "peak": 0.86,
    "rms": 0.1195
  },
  {
    "id": "capture.3",
    "speaker": "WARD",
    "text": "Taking them was the first problem. Moving them will be the next.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-capture-3-1db9b9f6f.mp3",
    "duration": 4.414,
    "peak": 0.86,
    "rms": 0.1408
  },
  {
    "id": "capture.4",
    "speaker": "RUNNER",
    "text": "I’ll watch this door. Get the inventory, Rowan.",
    "voice": "am_puck",
    "speed": 1.04,
    "lang": "en-us",
    "file": "c6-voice-capture-4-b1122bd4a.mp3",
    "duration": 2.458,
    "peak": 0.86,
    "rms": 0.0983
  },
  {
    "id": "north.stores",
    "speaker": "ROWAN",
    "text": "Powder dry. Shot stacked. Now something to fire it from.",
    "voice": "am_fenrir",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-north-stores-55da0591a.mp3",
    "duration": 3.4,
    "peak": 0.86,
    "rms": 0.109
  },
  {
    "id": "north.fitting",
    "speaker": "WARD",
    "text": "That gun. Broken fitting, sound barrel. Mark it. We’ll need a new carriage.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-north-fitting-f121d69fb.mp3",
    "duration": 5.058,
    "peak": 0.8567,
    "rms": 0.15
  },
  {
    "id": "north.pull",
    "speaker": "WARD",
    "text": "Rope tight. Back up slowly. I’ll keep the roller straight.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-north-pull-fa480516f.mp3",
    "duration": 3.981,
    "peak": 0.8331,
    "rms": 0.15
  },
  {
    "id": "north.weight",
    "speaker": "ROWAN",
    "text": "All that, just to move it a few feet.",
    "voice": "am_fenrir",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-north-weight-2f9d4f72b.mp3",
    "duration": 1.952,
    "peak": 0.86,
    "rms": 0.1371
  },
  {
    "id": "north.end.0",
    "speaker": "WARD",
    "text": "Don’t put your hand there. If it rolls, you lose it.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-north-end-0-44989d2b0.mp3",
    "duration": 3.535,
    "peak": 0.86,
    "rms": 0.1412
  },
  {
    "id": "north.end.1",
    "speaker": "ROWAN",
    "text": "You can barely close yours. Let me take the weight.",
    "voice": "am_fenrir",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-north-end-1-1b2b87e51.mp3",
    "duration": 2.908,
    "peak": 0.86,
    "rms": 0.1151
  },
  {
    "id": "north.end.2",
    "speaker": "WARD",
    "text": "You take the weight. I’ll tell you where to put it.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-north-end-2-628970275.mp3",
    "duration": 2.941,
    "peak": 0.8219,
    "rms": 0.15
  },
  {
    "id": "north.end.3",
    "speaker": "RUNNER",
    "text": "Allen and Arnold took the fort. Should I put your names beside the stores?",
    "voice": "am_puck",
    "speed": 1.04,
    "lang": "en-us",
    "file": "c6-voice-north-end-3-b97b42ab5.mp3",
    "duration": 3.895,
    "peak": 0.7441,
    "rms": 0.15
  },
  {
    "id": "north.end.4",
    "speaker": "ROWAN",
    "text": "Put down what we can use. Names won’t open Boston.",
    "voice": "am_fenrir",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-north-end-4-68ee4c47d.mp3",
    "duration": 3.276,
    "peak": 0.86,
    "rms": 0.1084
  },
  {
    "id": "north.end.5",
    "speaker": "WARD",
    "text": "Your brother’s still in there.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-north-end-5-2093836f3.mp3",
    "duration": 1.86,
    "peak": 0.6793,
    "rms": 0.15
  },
  {
    "id": "north.end.6",
    "speaker": "ROWAN",
    "text": "So are other people’s brothers. We find a road for these guns.",
    "voice": "am_fenrir",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-north-end-6-5e9a2c9e0.mp3",
    "duration": 3.729,
    "peak": 0.86,
    "rms": 0.1084
  },
  {
    "id": "north.end.7",
    "speaker": "WARD",
    "text": "Then keep that list dry. We’re going back to the siege.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-north-end-7-4301f8fd4.mp3",
    "duration": 3.569,
    "peak": 0.771,
    "rms": 0.15
  },
  {
    "id": "hill.intro.0",
    "speaker": "RUNNER",
    "text": "Dispatch from Philadelphia. June fifteenth. Congress has appointed George Washington commander in chief.",
    "voice": "am_puck",
    "speed": 1.04,
    "lang": "en-us",
    "file": "c6-voice-hill-intro-0-12e0b7af9.mp3",
    "duration": 6.659,
    "peak": 0.86,
    "rms": 0.0981
  },
  {
    "id": "hill.intro.1",
    "speaker": "ROWAN",
    "text": "Then where is he?",
    "voice": "am_fenrir",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-hill-intro-1-982b21e90.mp3",
    "duration": 1.026,
    "peak": 0.86,
    "rms": 0.1213
  },
  {
    "id": "hill.intro.2",
    "speaker": "WARD",
    "text": "Not here yet. Today we hold with the men we have.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-hill-intro-2-90727184f.mp3",
    "duration": 3.578,
    "peak": 0.8266,
    "rms": 0.15
  },
  {
    "id": "hill.intro.3",
    "speaker": "MARA",
    "text": "This is Breed’s Hill. The road behind us runs over Bunker Hill. Remember it when the smoke comes.",
    "voice": "af_heart",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-hill-intro-3-676f42ab7.mp3",
    "duration": 5.746,
    "peak": 0.86,
    "rms": 0.1252
  },
  {
    "id": "hill.intro.4",
    "speaker": "ROWAN",
    "text": "Those ships can reach us from the harbor.",
    "voice": "am_fenrir",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-hill-intro-4-63767b6fe.mp3",
    "duration": 2.015,
    "peak": 0.86,
    "rms": 0.1084
  },
  {
    "id": "hill.intro.5",
    "speaker": "WARD",
    "text": "And these heights threaten Boston. That’s why the British want them back.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-hill-intro-5-f503a48c1.mp3",
    "duration": 4.642,
    "peak": 0.7299,
    "rms": 0.15
  },
  {
    "id": "hill.intro.6",
    "speaker": "MARA",
    "text": "I’ll have blankets behind the ridge. If you bring someone to me, go back for the next.",
    "voice": "af_heart",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-hill-intro-6-c18b01f62.mp3",
    "duration": 4.681,
    "peak": 0.86,
    "rms": 0.1243
  },
  {
    "id": "hill.intro.7",
    "speaker": "WARD",
    "text": "Brace this section. Place our reserve where you can reach it. Then come to the wall.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-hill-intro-7-eaa2817bf.mp3",
    "duration": 5.301,
    "peak": 0.7853,
    "rms": 0.15
  },
  {
    "id": "hill.braced",
    "speaker": "WARD",
    "text": "That will hold. Take these cartridges. Left post or right. You’ll have to fetch them under fire.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-hill-braced-5d3d2eb5b.mp3",
    "duration": 6.346,
    "peak": 0.8228,
    "rms": 0.15
  },
  {
    "id": "hill.left",
    "speaker": "ROWAN",
    "text": "Reserve on the left. Near the main line.",
    "voice": "am_fenrir",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-hill-left-4f8fdbbb0.mp3",
    "duration": 2.313,
    "peak": 0.86,
    "rms": 0.1269
  },
  {
    "id": "hill.right",
    "speaker": "ROWAN",
    "text": "Reserve on the right. If they turn the flank, we’ll need it there.",
    "voice": "am_fenrir",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-hill-right-e19f65ac6.mp3",
    "duration": 3.373,
    "peak": 0.86,
    "rms": 0.1121
  },
  {
    "id": "hill.first",
    "speaker": "WARD",
    "text": "First line coming up. Let them close. One shot, then get below the earthwork to reload.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-hill-first-d8b818b1b.mp3",
    "duration": 5.941,
    "peak": 0.8376,
    "rms": 0.15
  },
  {
    "id": "hill.volley",
    "speaker": "ROWAN",
    "text": "Together! Fire!",
    "voice": "am_fenrir",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-hill-volley-b404de282.mp3",
    "duration": 1.009,
    "peak": 0.86,
    "rms": 0.1138
  },
  {
    "id": "hill.flank",
    "speaker": "RUNNER",
    "text": "They’re falling back! The timbers on our right are loose. Rowan, help me close it!",
    "voice": "am_puck",
    "speed": 1.04,
    "lang": "en-us",
    "file": "c6-voice-hill-flank-4376b818a.mp3",
    "duration": 4.359,
    "peak": 0.86,
    "rms": 0.0854
  },
  {
    "id": "hill.second",
    "speaker": "WARD",
    "text": "Here they come again. Watch the right. Don’t spend every cartridge at once.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-hill-second-1e5ac9f23.mp3",
    "duration": 4.866,
    "peak": 0.7256,
    "rms": 0.15
  },
  {
    "id": "hill.reserve",
    "speaker": "ROWAN",
    "text": "Last reserve. Pass them down the line.",
    "voice": "am_fenrir",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-hill-reserve-642626d22.mp3",
    "duration": 2.185,
    "peak": 0.86,
    "rms": 0.1278
  },
  {
    "id": "hill.third",
    "speaker": "WARD",
    "text": "They’re forming a third time. Check your cartridges. Keep the rear lane open.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-hill-third-172231e07.mp3",
    "duration": 5.244,
    "peak": 0.86,
    "rms": 0.1344
  },
  {
    "id": "hill.gun",
    "speaker": "RUNNER",
    "text": "The gun! I can’t see the men at the gun!",
    "voice": "am_puck",
    "speed": 1.04,
    "lang": "en-us",
    "file": "c6-voice-hill-gun-f85155153.mp3",
    "duration": 1.868,
    "peak": 0.86,
    "rms": 0.128
  },
  {
    "id": "hill.break.0",
    "speaker": "ROWAN",
    "text": "The smoke’s lifting. Where did the gun crew go?",
    "voice": "am_fenrir",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-hill-break-0-31d9ead77.mp3",
    "duration": 2.621,
    "peak": 0.86,
    "rms": 0.1015
  },
  {
    "id": "hill.break.1",
    "speaker": "RUNNER",
    "text": "They’re at the earthwork!",
    "voice": "am_puck",
    "speed": 1.04,
    "lang": "en-us",
    "file": "c6-voice-hill-break-1-fd3e30924.mp3",
    "duration": 1.143,
    "peak": 0.736,
    "rms": 0.15
  },
  {
    "id": "hill.break.2",
    "speaker": "WARD",
    "text": "Down, Rowan! Down!",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-hill-break-2-562e9eded.mp3",
    "duration": 2.064,
    "peak": 0.8054,
    "rms": 0.15
  },
  {
    "id": "hill.break.3",
    "speaker": "ROWAN",
    "text": "I can still fire.",
    "voice": "am_fenrir",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-hill-break-3-9c5661b49.mp3",
    "duration": 1.121,
    "peak": 0.86,
    "rms": 0.1062
  },
  {
    "id": "hill.break.4",
    "speaker": "WARD",
    "text": "The men along the wall are empty. One musket can’t hold this hill. Get the wounded behind the ridge.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-hill-break-4-522e30cd4.mp3",
    "duration": 6.572,
    "peak": 0.8068,
    "rms": 0.15
  },
  {
    "id": "hill.break.5",
    "speaker": "ROWAN",
    "text": "I’ll call you when they’re clear. You follow my signal.",
    "voice": "am_fenrir",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-hill-break-5-07537a67f.mp3",
    "duration": 2.836,
    "peak": 0.86,
    "rms": 0.0805
  },
  {
    "id": "hill.lift",
    "speaker": "ROWAN",
    "text": "Arm around me. Look at the road, not at your leg.",
    "voice": "am_fenrir",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-hill-lift-739bb5361.mp3",
    "duration": 2.778,
    "peak": 0.86,
    "rms": 0.1285
  },
  {
    "id": "hill.mara",
    "speaker": "MARA",
    "text": "I have him. Another man fell by the right fence. Bring him through the gap.",
    "voice": "af_heart",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-hill-mara-411da8f3f.mp3",
    "duration": 4.312,
    "peak": 0.86,
    "rms": 0.1343
  },
  {
    "id": "hill.other",
    "speaker": "ROWAN",
    "text": "I’m here. Lean on me. We’re leaving together.",
    "voice": "am_fenrir",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-hill-other-ef3cf71c5.mp3",
    "duration": 2.369,
    "peak": 0.86,
    "rms": 0.1053
  },
  {
    "id": "hill.safe",
    "speaker": "MARA",
    "text": "Both breathing. Rowan, get Ward off that hill.",
    "voice": "af_heart",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-hill-safe-d369f95c0.mp3",
    "duration": 2.7,
    "peak": 0.86,
    "rms": 0.1288
  },
  {
    "id": "hill.signal",
    "speaker": "ROWAN",
    "text": "Ward! Fall back! We have a way through!",
    "voice": "am_fenrir",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-hill-signal-0d2643d24.mp3",
    "duration": 2.126,
    "peak": 0.86,
    "rms": 0.111
  },
  {
    "id": "hill.end.0",
    "speaker": "MARA",
    "text": "Easy. Lower him with me. Nathan, hold that cloth.",
    "voice": "af_heart",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-hill-end-0-3cc34cbe6.mp3",
    "duration": 3.222,
    "peak": 0.86,
    "rms": 0.1073
  },
  {
    "id": "hill.end.1",
    "speaker": "ROWAN",
    "text": "They have the redoubt.",
    "voice": "am_fenrir",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-hill-end-1-7b94961d6.mp3",
    "duration": 1.101,
    "peak": 0.86,
    "rms": 0.1275
  },
  {
    "id": "hill.end.2",
    "speaker": "WARD",
    "text": "They have the hill. Look at the road. Our men are still coming out.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-hill-end-2-02c15cf86.mp3",
    "duration": 4.261,
    "peak": 0.834,
    "rms": 0.15
  },
  {
    "id": "hill.end.3",
    "speaker": "ROWAN",
    "text": "I told you to follow my signal.",
    "voice": "am_fenrir",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-hill-end-3-988c24f49.mp3",
    "duration": 1.736,
    "peak": 0.86,
    "rms": 0.0959
  },
  {
    "id": "hill.end.4",
    "speaker": "WARD",
    "text": "You did. So I followed it.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-hill-end-4-14271c369.mp3",
    "duration": 2.095,
    "peak": 0.8439,
    "rms": 0.15
  },
  {
    "id": "hill.end.5",
    "speaker": "MARA",
    "text": "Rowan. His hand. Hold it while I bind his leg.",
    "voice": "af_heart",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-hill-end-5-3af4a30be.mp3",
    "duration": 2.952,
    "peak": 0.86,
    "rms": 0.1244
  },
  {
    "id": "hill.end.6",
    "speaker": "ROWAN",
    "text": "I’m here. I’m not going anywhere.",
    "voice": "am_fenrir",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-hill-end-6-301dcd850.mp3",
    "duration": 1.589,
    "peak": 0.86,
    "rms": 0.1113
  },
  {
    "id": "hill.legacy.0",
    "speaker": "RUNNER",
    "text": "The reports say more than two hundred British dead. Around eight hundred wounded. All for those hills.",
    "voice": "am_puck",
    "speed": 1.04,
    "lang": "en-us",
    "file": "c6-voice-hill-legacy-0-105582050.mp3",
    "duration": 5.955,
    "peak": 0.86,
    "rms": 0.0828
  },
  {
    "id": "hill.legacy.1",
    "speaker": "WARD",
    "text": "Gage took the ground. He still couldn’t break the siege around Boston.",
    "voice": "bm_george",
    "speed": 0.96,
    "lang": "en-gb",
    "file": "c6-voice-hill-legacy-1-405013d60.mp3",
    "duration": 4.488,
    "peak": 0.8369,
    "rms": 0.15
  },
  {
    "id": "hill.legacy.2",
    "speaker": "MARA",
    "text": "In August, the king declared the colonies in rebellion. This arrived from London.",
    "voice": "af_heart",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-hill-legacy-2-0821f8798.mp3",
    "duration": 4.776,
    "peak": 0.86,
    "rms": 0.1412
  },
  {
    "id": "hill.legacy.3",
    "speaker": "ROWAN",
    "text": "Then we keep the dispatches moving. People need to know what comes next.",
    "voice": "am_fenrir",
    "speed": 1,
    "lang": "en-us",
    "file": "c6-voice-hill-legacy-3-5359e123e.mp3",
    "duration": 4.203,
    "peak": 0.86,
    "rms": 0.0849
  }
];
