import test from 'node:test';import assert from 'node:assert/strict';
import {fresh,tick,collide,currentGoal,goalNear,restore,snapshot} from './c6-sim.mjs';
import {winterHauling,winterWashing,winterCanUse} from './c6-winter.mjs';
import {LEVELS,SCENES,LINES,continueProgress} from './c6-data.mjs';
import {rememberOutcome,cleanRecord} from './c6-record.mjs';
const step=(s,input={},seconds=1)=>{const e=[];for(let i=0;i<seconds/.025;i++)e.push(...tick(s,input,.025));return e;};
function walk(s,x,z){const start={x:Math.round(s.player.x),z:Math.round(s.player.z)},key=p=>p.x+','+p.z,queue=[start],parents=new Map([[key(start),null]]);let end;
 for(let i=0;i<queue.length&&i<25000;i++){const p=queue[i];if(p.x===Math.round(x)&&p.z===Math.round(z)){end=p;break;}for(const [dx,dz] of [[1,0],[-1,0],[0,1],[0,-1]]){const n={x:p.x+dx,z:p.z+dz};if(parents.has(key(n))||collide(s,n.x,n.z,.3,0))continue;parents.set(key(n),p);queue.push(n);}}
 assert.ok(end,'physical route to '+x+','+z);const path=[];while(end){path.unshift(end);end=parents.get(key(end));}
 for(const p of path)for(let i=0;i<110&&Math.hypot(p.x-s.player.x,p.z-s.player.z)>.14;i++){s.player.yaw=0;tick(s,{right:p.x-s.player.x>.1,left:p.x-s.player.x<-.1,back:p.z-s.player.z>.1,forward:p.z-s.player.z<-.1},.025);assert.equal(s.failed,false);}assert.ok(Math.hypot(s.player.x-x,s.player.z-z)<.5,'arrived at '+x+','+z);
}
function use(s){assert.ok(goalNear(s));assert.ok(winterCanUse(s),'usable stage '+s.stage);step(s,{interact:true},currentGoal(s).time+.15);}
function go(s){const g=currentGoal(s);walk(s,g.x,g.z);if(s.level==='drill')for(let i=0;i<400&&!winterCanUse(s);i++)tick(s,{},.025);use(s);}
function finishCamp(job,settlement){let s=fresh('campline');go(s);walk(s,job==='care'?-14:12,job==='care'?7:8);use(s);assert.equal(s.winter.job,job);go(s);
 if(job==='cloth'){walk(s,14,-19);tick(s,{interact:true},.025);assert.ok(winterWashing(s));for(const stroke of ['a','d','a','d','a','d'])tick(s,{washStroke:stroke},.025);assert.equal(s.stage,4);}else go(s);
 if(!winterCanUse(s))step(s,{},30);go(s);go(s);if(!winterCanUse(s))step(s,{},40);go(s);go(s);walk(s,settlement==='receipt'?19:12,10);use(s);assert.equal(s.winter.settlement,settlement);go(s);go(s);return s;}
test('the covered flour physically follows Mara over the surviving western crossing into shelter',()=>{let s=fresh('thawroad');go(s);go(s);go(s);assert.ok(winterHauling(s));step(s,{},23);assert.ok(s.winter.thaw>=.55);assert.equal(collide(s,0,-23),true);assert.equal(collide(s,-23,-23),false);walk(s,0,-11);walk(s,-23,-12);walk(s,-23,-31);walk(s,2,-31);walk(s,2,-54);for(let i=0;i<100&&s.stage===3;i++)tick(s,{},.025);assert.equal(s.stage,4,'load reaches the actual roof');assert.ok(s.winter.travel>80);s=restore(snapshot(s));go(s);go(s);assert.ok(s.finished&&s.winter.flourSecured&&!s.winter.hauled);});
test('the haul respects its brake, distance and Space, and thaw allows an already-on-the-ford player to leave',()=>{const s=fresh('thawroad');s.stage=3;s.player.x=14;s.player.z=18;const z=s.winter.sledZ;tick(s,{useTap:true},.025);assert.ok(s.winter.brake);step(s,{forward:true},1);assert.equal(s.winter.sledZ,z);s.winter.brake=false;const pz=s.player.z;step(s,{forward:true,jump:true},1);assert.equal(s.player.z,pz);assert.equal(s.player.y,0);s.player.z=-10;step(s,{},1);assert.equal(s.winter.sledZ,z,'a remote rope cannot pull');s.winter.thaw=1;s.player.x=0;s.player.z=-23;assert.equal(collide(s,0,-20),false,'can leave a changing ford');s.player.z=0;assert.equal(collide(s,0,-23,.3,2),true,'jumping cannot bypass the flooded route');});
test('care-first and laundry-first assignments both finish distinct real work and a supply bargain',()=>{for(const [job,settlement] of [['care','receipt'],['cloth','repair']]){const s=finishCamp(job,settlement);assert.ok(s.finished&&s.winter.care&&s.winter.cloth&&s.winter.helperDone&&s.winter.supplied&&s.winter.dispatch);assert.equal(s.carrying,false);if(job==='cloth'){assert.equal(s.winter.clean,6);assert.ok(s.winter.helperZ>3.8);}else assert.ok(s.winter.helperClock>=28);}});
test('wash controls require alternating strokes at the station and permit moving away and resuming saved work',()=>{let s=fresh('campline');s.stage=3;Object.assign(s.winter,{job:'cloth',atWash:true});s.player.x=14;s.player.z=-19;tick(s,{washStroke:'a'},.025);tick(s,{washStroke:'a'},.025);assert.equal(s.winter.clean,1);s=restore(snapshot(s));tick(s,{forward:true},.025);assert.equal(s.winter.atWash,false);step(s,{back:true},1);assert.ok(s.player.z>-16);tick(s,{washStroke:'d'},.025);assert.equal(s.winter.clean,1);walk(s,14,-19);tick(s,{interact:true},.025);assert.ok(winterWashing(s));tick(s,{washStroke:'d'},.025);assert.equal(s.winter.clean,2);assert.equal(s.stage,3);});
test('the detachment physically follows, changes formation, fires at wood and teaches the next section',()=>{const s=fresh('drill');go(s);go(s);assert.equal(s.winter.squad.length,6);go(s);walk(s,18,-10);step(s,{},4);assert.equal(winterCanUse(s),false,'wrong facing cannot halt the eastward column');s.player.yaw=-Math.PI/2;use(s);use(s);assert.equal(s.winter.formation,'line');walk(s,0,-37);step(s,{},5);use(s);assert.equal(s.stage,6);assert.ok(s.armed);for(let i=0;i<3;i++){s.player.yaw=Math.atan2(-((i-1)*7-s.player.x),-(-56-s.player.z));s.player.pitch=Math.atan2(1.5-1.65,Math.hypot((i-1)*7-s.player.x,-56-s.player.z));tick(s,{fire:true},.025);assert.equal(s.winter.targets[i],true);if(i<2)step(s,{reload:true},4.5);}assert.equal(s.stage,7);assert.equal(s.enemies.length,0);assert.equal(s.kills,0);go(s);assert.ok(s.finished&&s.winter.trained&&!s.armed);});
test('the practice range misses off-axis shots and waits for all three targets without live enemy units',()=>{const s=fresh('drill');s.stage=6;s.armed=true;s.player.x=0;s.player.z=-37;s.player.yaw=Math.PI;s.winter.squad=Array.from({length:6},(_,i)=>({x:i-3,z:-34,yaw:0}));tick(s,{fire:true},.025);assert.deepEqual(s.winter.targets,[false,false,false]);assert.equal(s.stage,6);assert.equal(s.enemies.length,0);});
test('winter saves validate physics and formations and preserve completed work without granting unfinished outcomes',()=>{for(const level of ['thawroad','campline','drill']){const raw=snapshot(fresh(level));assert.ok(restore(raw));for(const patch of [{job:'all'},{clean:7},{clean:.5},{sledX:1000},{thaw:2},{atWash:1},{targets:[true]},{squad:[{x:0,z:0,yaw:0}]},{helperClock:Infinity},{settlement:'free'}]){const bad=structuredClone(raw);Object.assign(bad.winter,patch);assert.equal(restore(bad),null);}}const saved={outcomes:{}};const s=fresh('drill');s.winter.trained=true;assert.equal(rememberOutcome(saved,s),false);s.finished=true;rememberOutcome(saved,s);const c=finishCamp('care','receipt');rememberOutcome(saved,c);const clean=cleanRecord(saved,LEVELS,SCENES);assert.ok(clean.outcomes.drill.formationTrained);assert.equal(clean.outcomes.campline.workDivision,'care');assert.equal(clean.outcomes.campline.supplyAgreement,'receipt');assert.equal(clean.outcomes.campline.rescues,1);});
test('Saratoga saves continue into winter and dated scenes keep alliance, spring disease and Lafayette distinct',()=>{const old={complete:true,completedPart:'albany',seen:['albanySurrender']};assert.equal(continueProgress(old).scene,'winterIntro');const done={...old,completedPart:'winter',seen:['winterAlliance']};assert.equal(continueProgress(done),done);assert.equal(SCENES.albanySurrender.after,'winterIntro');assert.equal(SCENES.winterAlliance.after,'complete');const text=LINES.filter(l=>/^(winter\.|camp\.|drill\.)/.test(l.id)).map(l=>l.text).join(' ');for(const term of ['February sixteenth','George Clinton','Congress','Prussian','model company','Continental','European loans','Daughters of Liberty','February sixth','May sixth','seventeen seventy-seven','Washington’s aide','no army-wide promise','spring shelters'])assert.ok(text.includes(term),term);});
