import test from 'node:test';import assert from 'node:assert/strict';
import {fresh,tick,collide,angle,currentGoal,goalNear,snapshot,restore} from './c6-sim.mjs';
import {widerCanUse,widerBoating,widerShelter} from './c6-wider.mjs';
import {LEVELS,SCENES,LINES,continueProgress} from './c6-data.mjs';
import {rememberOutcome,cleanRecord,carryOutcome} from './c6-record.mjs';
const step=(s,input={},seconds=1)=>{const ev=[];for(let i=0;i<seconds/.025;i++)ev.push(...tick(s,input,.025));return ev;};
function walk(s,x,z){const start={x:Math.round(s.player.x),z:Math.round(s.player.z)},key=p=>p.x+','+p.z,queue=[start],parents=new Map([[key(start),null]]);let end;
 for(let i=0;i<queue.length&&i<25000;i++){const p=queue[i];if(p.x===Math.round(x)&&p.z===Math.round(z)){end=p;break;}for(const [dx,dz] of [[1,0],[-1,0],[0,1],[0,-1]]){const n={x:p.x+dx,z:p.z+dz};if(parents.has(key(n))||collide(s,n.x,n.z,.3,0))continue;parents.set(key(n),p);queue.push(n);}}
 assert.ok(end,'walkable route to '+x+','+z);const path=[];while(end){path.unshift(end);end=parents.get(key(end));}
 for(const p of path)for(let i=0;i<110&&Math.hypot(p.x-s.player.x,p.z-s.player.z)>.14;i++){s.player.yaw=0;tick(s,{right:p.x-s.player.x>.1,left:p.x-s.player.x<-.1,back:p.z-s.player.z>.1,forward:p.z-s.player.z<-.1},.025);assert.equal(s.failed,false);if(s.level==='coastfire'&&s.wider.escort&&!s.wider.escorted){assert.equal(collide(s,s.wider.familyX,s.wider.familyZ,.25,0),false,'adult clear of scenery');assert.equal(collide(s,s.wider.familyX-.8,s.wider.familyZ+.7,.18,0),false,'child clear of scenery');}}assert.ok(Math.hypot(s.player.x-x,s.player.z-z)<.6,'arrived at '+x+','+z);
}
function use(s){assert.ok(goalNear(s),'near stage '+s.stage);assert.ok(widerCanUse(s),'usable stage '+s.stage);step(s,{interact:true,jump:widerBoating(s)},currentGoal(s).time+.2);}
function go(s){const g=currentGoal(s);walk(s,g.x,g.z);for(let i=0;i<500&&s.level==='monmouth'&&!widerCanUse(s);i++)tick(s,{},.025);use(s);}
function sail(s,x,z){assert.ok(widerBoating(s));for(let i=0;i<10000;i++){const dx=x-s.player.x,dz=z-s.player.z,d=Math.hypot(dx,dz),desired=Math.atan2(-dx,-dz),turn=angle(desired-s.wider.boatYaw);tick(s,{left:turn>.025,right:turn<-.025,forward:d>1.7&&Math.abs(turn)<.7,jump:d<2.6},.025);assert.equal(s.failed,false);if(d<3&&s.wider.speed<.7)return;}assert.fail('sail failed to '+x+','+z+' from '+s.player.x+','+s.player.z);}
function waitLeg(s,n){for(let i=0;i<1600&&s.wider.convoyLeg<n;i++)tick(s,{jump:true},.025);assert.ok(s.wider.convoyLeg>=n,'convoy physically reached leg '+n);}
function finishSea(route){let s=fresh('openwater');go(s);go(s);const sign=route==='fleet'?1:-1;sail(s,24*sign,-32);use(s);assert.equal(s.wider.route,route);waitLeg(s,1);sail(s,20*sign,-56);waitLeg(s,2);sail(s,18*sign,-97);use(s);assert.ok(s.wider.rescued&&s.wider.intercepted);s=restore(snapshot(s));sail(s,23*sign,-140);step(s,{jump:true},6);assert.equal(s.stage,5,'cover breaks pursuit');sail(s,18*sign,-148);waitLeg(s,4);sail(s,0,-175);waitLeg(s,5);use(s);assert.ok(s.finished&&s.wider.convoyDelivered&&s.wider.travel>175);assert.equal(s.kills,0);return s;}
test('the rallied Monmouth detachment physically turns, holds a local lane and leaves together',()=>{const s=fresh('monmouth','normal');go(s);go(s);go(s);assert.equal(widerCanUse(s),false,'turn needs actual eastward facing');s.player.yaw=-Math.PI/2;use(s);walk(s,0,-30);step(s,{},4);for(let i=0;i<3000&&s.stage===4;i++)tick(s,{interact:true,crouch:true},.025);assert.equal(s.stage,5);assert.ok(s.wider.lineClock>=36);assert.equal(s.enemies.length,8);assert.ok(s.enemies.every(e=>e.hp<=0));go(s);go(s);assert.ok(s.finished&&s.wider.ammoPassed&&s.wider.squad.length===6);});
test('both fleet and fog passages deliver the actual convoy and rescue after navigated shoals',()=>{for(const route of ['fleet','fog'])finishSea(route);});
test('a remote convoy cannot finish, fast approach cannot take a rope, and looking never turns the tiller',()=>{const s=fresh('openwater');s.stage=5;Object.assign(s.wider,{aboard:true,moored:false,route:'fleet',boatX:0,boatZ:-175,convoyX:10,convoyZ:10,convoyLeg:1});s.player.z=-175;assert.equal(widerCanUse(s),false);step(s,{interact:true,jump:true},3);assert.equal(s.stage,5);const before=s.wider.boatYaw;step(s,{lookUp:true,lookLeft:true,jump:true},.5);assert.ok(s.player.pitch>0);assert.equal(s.wider.boatYaw,before);tick(s,{leftTap:true,jump:true},.025);assert.ok(s.wider.boatYaw>before);s.wider.convoyX=0;s.wider.convoyZ=-171;s.wider.convoyLeg=5;s.wider.speed=2;assert.equal(widerCanUse(s),false);s.wider.speed=.5;assert.ok(widerCanUse(s));});
test('shoal impacts recover without losing passengers and cover requires a real chosen passage',()=>{const s=fresh('openwater');s.stage=2;Object.assign(s.wider,{aboard:true,moored:false,boatX:0,boatZ:-29,vz:-4});s.player.z=-29;step(s,{forward:true},3);assert.ok(s.wider.impacts>0);assert.ok(s.wider.hull>=1&&s.player.z>-31);assert.equal(s.player.y,0);Object.assign(s.wider,{route:'fog',boatX:-23,boatZ:-140,speed:2});assert.equal(widerShelter(s.wider),false);s.wider.speed=.5;assert.ok(widerShelter(s.wider));s.wider.route='fleet';assert.equal(widerShelter(s.wider),false);s.wider.boatX=23;assert.ok(widerShelter(s.wider));});
test('defensive fire needs a real loaded aligned shot and does not sink or count kills against a fleet',()=>{const s=fresh('openwater');s.stage=4;s.armed=true;Object.assign(s.wider,{aboard:true,moored:false,boatX:10,boatZ:-85,route:'fleet',rescued:true,intercepted:true,cutterX:25,cutterZ:-70});s.player.x=10;s.player.z=-85;s.player.yaw=0;tick(s,{fire:true,jump:true},.025);assert.equal(s.wider.defensiveShots,0);step(s,{reload:true,jump:true},4.5);s.player.yaw=Math.atan2(-(s.wider.cutterX-s.player.x),-(s.wider.cutterZ-s.player.z));s.player.pitch=0;tick(s,{fire:true,jump:true},.025);assert.equal(s.wider.defensiveShots,1);assert.ok(s.wider.pursuit<1);assert.equal(s.kills,0);assert.equal(s.enemies.length,0);});
test('the coast rescue requires water, the supported beam and a physical family escort before launch',()=>{let s=fresh('coastfire');go(s);go(s);go(s);assert.ok(s.carrying);go(s);assert.ok(s.wider.patient&&!s.carrying);go(s);go(s);assert.ok(s.wider.holdingBucket);assert.equal(collide(s,18,-38,.3,3),true,'cannot jump the unsupported beam');go(s);assert.ok(s.wider.doused&&!s.wider.holdingBucket);s=restore(snapshot(s));go(s);assert.equal(collide(s,18,-38,.3,0),false);go(s);assert.ok(s.wider.escort);for(const [x,z] of [[20,-43],[20,-19],[4,-2],[0,20]]){walk(s,x,z);for(let i=0;i<1200&&Math.hypot(s.wider.familyX-x,s.wider.familyZ-z)>1.8;i++)tick(s,{},.025);}walk(s,0,22);assert.ok(widerCanUse(s));use(s);go(s);assert.ok(s.finished&&s.wider.escorted&&s.wider.danbury&&s.wider.fairfield);const saved={};rememberOutcome(saved,s);assert.equal(saved.outcomes.coastfire.rescues,3);});
test('wide-war saves reject malformed physics, and completed outcomes carry choices without granting unfinished work',()=>{for(const level of ['monmouth','openwater','coastfire']){const raw=snapshot(fresh(level));assert.ok(restore(raw));for(const patch of [{route:'teleport'},{speed:10},{hull:0},{pursuit:2},{boatX:1000},{convoyLeg:6},{familyLeg:8},{doused:1},{squad:[{x:0,z:0,yaw:0}]},{lastShot:Infinity},{lineClock:-1}]){const bad=structuredClone(raw);Object.assign(bad.wider,patch);assert.equal(restore(bad),null);}}
 const saved={outcomes:{}};const s=fresh('openwater');s.wider.route='fog';s.wider.convoyDelivered=true;assert.equal(rememberOutcome(saved,s),false);s.finished=true;rememberOutcome(saved,s);const clean=cleanRecord(saved,LEVELS,SCENES);assert.ok(clean.outcomes.openwater.convoyDelivered);assert.equal(clean.outcomes.openwater.navalRoute,'fog');assert.ok(carryOutcome(fresh('monmouth'),{outcomes:{drill:{formationTrained:true}}}).wider.trainedBefore);});
test('the winter checkpoint continues into dated Monmouth, allied supplies and remembered coastal raids',()=>{assert.equal(continueProgress({complete:true,completedPart:'winter',seen:['winterAlliance']}).scene,'widerIntro');const done={complete:true,completedPart:'wider',seen:['widerEnding']};assert.equal(continueProgress(done).scene,'southIntro');assert.equal(SCENES.winterAlliance.after,'widerIntro');assert.equal(SCENES.widerEnding.after,'southIntro');const text=LINES.filter(l=>/^(wider\.|monmouth\.|coast\.)/.test(l.id)).map(l=>l.text).join(' ');for(const phrase of ['Clinton','New York','Valley Forge','Caribbean','Spain','not Spain recognizing','Danbury','April of seventeen seventy-seven','Fairfield','July seventh and eighth','Norwalk','Clothing and tent cloth','French money','naval forces'])assert.ok(text.includes(phrase),phrase);});
