import {paperContext,paperOperating,paperCanUse} from './c6-paper.mjs?v=4.6.0-published';
import {liftContext,liftHauling,liftCanUse} from './c6-lift.mjs?v=4.6.0-published';
import {promiseContext} from './c6-promise.mjs?v=4.6.0-published';
import {fixtureState} from './c6-fixtures.mjs?v=4.6.0-published';
import {hillContext,hillDefending,hillSupply,hillCanVolley} from './c6-hill.mjs?v=4.6.0-published';
import {fortContext} from './c6-fort.mjs?v=4.6.0-published';
import {SAVE_KEY,VERSION,LEVELS,SCENES,FACTS,NAMES,continueProgress} from './c6-data.mjs?v=4.6.0-published';
import {fresh,restore,snapshot,tick,currentGoal,goalNear,clamp,angle,distance} from './c6-sim.mjs?v=4.6.0-published';
import {sceneLead,sceneHold} from './c6-director.mjs?v=4.6.0-published';
import {applyLook,mouseButtons} from './c6-controls.mjs?v=4.6.0-published';
import {OpeningWorld} from './c6-world.mjs?v=4.6.0-published';
import {C6_VOICES} from './c6-voices.mjs?v=4.6.0-published';
import {C6_SCORE} from './c6-score.mjs?v=4.6.0-published';
import {DialogueDirector} from './dialogue.mjs';
import {MusicDirector} from './music.mjs';
const $=id=>document.getElementById(id),ui=$('ui'),canvas=$('world'),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const btn=(label,action,cls='primary',extra='')=>`<button class="${cls}" data-action="${action}" ${extra}>${label}</button>`;
const voices=new Map(C6_VOICES.map(v=>[v.id,v]));const coarse=matchMedia('(pointer:coarse)').matches;
// Local playtest fixtures are isolated from a player's campaign save.
const fixture=['localhost','127.0.0.1','[::1]'].includes(location.hostname)?new URLSearchParams(location.search).get('test'):null;
const sessionParams=new URLSearchParams(location.search);
const silentSession=sessionParams.get('muted')==='1';
const storageKey=fixture||sessionParams.get('preview')==='1'?SAVE_KEY+'-playtest':SAVE_KEY;
let prefs={music:.5,voice:.95,effects:.55,subtitles:true,reduced:matchMedia('(prefers-reduced-motion:reduce)').matches,large:false,difficulty:'normal',sensitivity:1,quality:'high',muted:false};
let saved={version:1,checkpoint:null,scene:null,complete:false,seen:[],prefs},storageOK=true;
try{const old=JSON.parse(localStorage.getItem(storageKey));if(old?.version===1){saved={...saved,...old,seen:Array.isArray(old.seen)?old.seen.filter(k=>SCENES[k]):[]};prefs={...prefs,...old.prefs};if(saved.checkpoint&&!restore(saved.checkpoint,prefs.difficulty))saved.checkpoint=null;if(saved.scene&&!SCENES[saved.scene])saved.scene=null;}}catch{storageOK=false;}
// Completed earlier campaign saves continue into the next installment without replaying the opening.
saved=continueProgress(saved);
let state='menu',beforePause='play',settingsBack='menu',model=null,world=null,film=null,keys={},aim=false,fire=false,autoWalk=false,interacting=false,replay=false,last=performance.now(),time=0,hurtUntil=0,saveUntil=0,footTime=0,worldError=null,captionSpeaker=null,fxContext=null,fxGain=null;
let pressed={},missionReplay=false,replayCheckpoint=null,touchCrouch=false,touchAim=false,hadPointerLock=false;
function persist(){saved.prefs=prefs;try{localStorage.setItem(storageKey,JSON.stringify(saved));}catch{storageOK=false;}}
const music=new MusicDirector({tracks:C6_SCORE,onStatus:s=>{document.body.dataset.music=s.id||'';document.body.dataset.musicState=s.state;}});
const dialogue=new DialogueDirector({media:$('speech'),lines:C6_VOICES,onCaption(line){captionSpeaker=line?.speaker||null;$('subtitle').innerHTML=line?`<b>${esc(NAMES[line.speaker]||line.speaker)}</b>${esc(line.text)}`:'';$('subtitle').classList.toggle('visible',!!line);},onActivity:active=>music.duck(active),onLast:l=>$('speech').dataset.clip=l.id});
function configure(){music.configure({enabled:!silentSession&&!prefs.muted&&prefs.music>0,volume:prefs.music});dialogue.configure({enabled:!silentSession&&!prefs.muted&&prefs.voice>0,volume:prefs.voice,subtitles:prefs.subtitles||silentSession||prefs.muted});document.body.dataset.muted=String(silentSession||!!prefs.muted);$('speech').muted=silentSession||!!prefs.muted||!prefs.voice;document.body.classList.toggle('large-captions',prefs.large);if(fxGain)fxGain.gain.value=silentSession||prefs.muted?0:prefs.effects*.5;}
function fx(kind,volume=1){if(silentSession||prefs.muted||!prefs.effects||state==='pause')return;try{fxContext??=new(window.AudioContext||window.webkitAudioContext)();if(!fxGain){fxGain=fxContext.createGain();fxGain.connect(fxContext.destination);}fxGain.gain.value=prefs.effects*.5;fxContext.resume();const ctx=fxContext,t=ctx.currentTime;
 if(kind==='bell'){for(const f of [510,1021,1407]){const o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=f;g.gain.setValueAtTime(.12*volume,t);g.gain.exponentialRampToValueAtTime(.0001,t+2.5);o.connect(g);g.connect(fxGain);o.start();o.stop(t+2.6);}return;}
 const len=kind==='shot'?.6:kind==='hurt'?.3:kind==='foot'?.09:.18,b=ctx.createBuffer(1,Math.ceil(ctx.sampleRate*len),ctx.sampleRate),d=b.getChannelData(0);
 for(let i=0;i<d.length;i++){const p=i/d.length;d[i]=(Math.random()*2-1)*Math.pow(1-p,kind==='shot'?4:2)*volume*(kind==='foot'?.15:1);}
 const src=ctx.createBufferSource(),filter=ctx.createBiquadFilter();src.buffer=b;filter.type='lowpass';filter.frequency.value=kind==='shot'?1800:kind==='foot'?160:600;src.connect(filter);filter.connect(fxGain);src.start();}catch{}}
function say(id){dialogue.say(id,{priority:1,ttl:Infinity});}
function resetInput(){keys={};touchPoint=null;hadPointerLock=false;touchCrouch=false;touchAim=false;pressed={};fire=false;aim=false;autoWalk=false;interacting=false;try{if(document.pointerLockElement)document.exitPointerLock();}catch{}}
function setState(next){state=next;document.body.dataset.state=state;document.body.classList.toggle('cinematic',state==='film');$('hud').hidden=state!=='play';$('film').hidden=state!=='film';$('touch').hidden=!(coarse&&state==='play');document.body.classList.toggle('touch',coarse&&state==='play');}
function ensureWorld(){if(world)return true;try{world=new OpeningWorld(canvas);world.configure(prefs);return true;}catch(e){worldError=e;console.error('Chapter 6 renderer:',e);return false;}}
function panel(content,narrow=false){ui.innerHTML=`<section class="panel ${narrow?'narrow':''}"><div class="panel-inner">${content}</div></section>`;}
function hide(){resetInput();dialogue.stop();setState('menu');}
function home(){hide();film=null;replay=false;missionReplay=false;replayCheckpoint=null;music.select('home');music.resume();const started=saved.checkpoint||saved.scene;
 ui.innerHTML=`<section class="menu"><header class="topline"><a class="brand" href="./">DC <i>/</i> US HISTORY</a><nav>${btn('Chapters','chapters','quiet')}${btn('Settings','settings','quiet')}</nav></header><div class="hero"><p class="eyebrow">Chapter 06 · America’s War for Independence</p><h1>THE LONG<br><span>ROAD HOME</span></h1><p class="lede">A promise kept. A country breaking.<br>From the first shot to a country on paper.</p><div class="row">${btn(started&&!saved.complete?'Continue the campaign →':'Begin the campaign →','start')}${btn('Mission select','missions','secondary')}</div><div class="edition"><span>NOW PLAYING · A COUNTRY ON PAPER</span><span>1775–1776</span><span>HEADPHONES RECOMMENDED</span></div>${!storageOK?'<p class="save-warning">Browser saving is unavailable. Keep this tab open to retain your session.</p>':''}</div><div class="chapter-number">06</div><footer class="menu-foot"><span>AN ORIGINAL STORY THROUGH REAL HISTORY</span><div class="row">${btn('Story scenes','scenes','quiet')}${btn('Controls','controls','quiet')}${btn('History & credits','archive','quiet')}</div></footer></section>`;
}
function chapters(){hide();setState('chapters');panel(`<p class="eyebrow">DC / US History</p><h1>Three roads through history.</h1><div class="chapters"><a class="chapter-card" href="chapter4.html"><span>CHAPTER 04</span><strong>Crown & Current</strong><p>1676–1763 · Building an empire.</p><span>Play →</span></a><a class="chapter-card" href="chapter5.html"><span>CHAPTER 05</span><strong>The Last Dispatch</strong><p>1763–1774 · A city on the edge.</p><span>Play →</span></a><button class="chapter-card" data-action="home"><span>CHAPTER 06 · CAMPAIGN</span><strong>The Long Road Home</strong><p>1775–1776 · Powder Road to the Declaration of Independence.</p><span>Play →</span></button></div><div class="row">${btn('Back','home','quiet')}</div>`);}
function scenes(){hide();setState('scenes');panel(`<p class="eyebrow">The Long Road Home · screening room</p><h1>The people you carry.</h1><p>Includes spoilers through A Country on Paper. Replays leave your campaign checkpoint intact.</p><div class="scene-list">${Object.entries(SCENES).map(([id,s],i)=>btn(`<span>${String(i+1).padStart(2,'0')} · ${esc(s.place)}</span><strong>${esc(s.title)}</strong>`,'scene','scene-card',`data-scene="${id}"`)).join('')}</div>${btn('Back','home','quiet')}`);}
function missions(){hide();missionReplay=false;setState('missions');panel(`<p class="eyebrow">Chapter 6 · Campaign missions</p><h1>Choose your road.</h1><p>Replay any mission. Your story checkpoint stays where you left it.</p><div class="mission-list">${Object.entries(LEVELS).map(([id,l],i)=>btn(`<span>${String(i+1).padStart(2,'0')} / ${l.mode||['REUNION','STEALTH','RESCUE','DEFENSE'][i]}</span><strong>${esc(l.title)}</strong><p>${l.description||['Bring Ward out of the prison courtyard.','Warn the countryside. Stay out of the lantern light.','Cross the green between volleys. Bring them home.','Fire. Reload in cover. Keep the wagon moving.'][i]}</p><i>Deploy →</i>`,'mission','mission-card',`data-mission="${id}"`)).join('')}</div><div class="row">${btn('Back','home','quiet')}${btn('Restart the story','new-story','quiet')}</div>`);}
function newStory(){setState('new-story');panel(`<p class="eyebrow">A new beginning</p><h1>Back to the prison gates?</h1><p>This replaces your current Chapter 6 checkpoint. Your settings and the other chapters stay saved.</p><div class="row">${btn('Begin again','confirm-new')}${btn('Keep my progress','missions','secondary')}</div>`,true);}
function missionComplete(){resetInput();dialogue.stop();setState('mission-complete');music.select('home');const shots=model.shotsFired||0;panel(`<p class="eyebrow">Mission complete · ${esc(LEVELS[model.level].title)}</p><h1>${model.paper?'The words got through.':model.lift?'The horizon lifted.':model.promise?'A passage kept.':model.level==='breeds'?'The people we carry.':model.level==='ticonderoga'?'The guns are ours.':model.level==='concord'?'The wagon made it.':model.level==='lexington'?'No one left behind.':model.level==='night'?'The warning got through.':'A promise kept.'}</h1><p>${Math.floor(model.time/60)}:${String(Math.floor(model.time%60)).padStart(2,'0')} on the road${model.level==='breeds'?' · Two wounded brought out · Crew together':model.level==='ticonderoga'?(model.fort.alarm?' · Nathan brought back safely':' · Undetected approach'):shots?' · '+Math.round(model.kills/shots*100)+'% accuracy':''}</p><div class="row">${btn('Choose a mission','missions')}${btn('Return to story','campaign','secondary')}</div>`,true);}
function controls(back='home'){setState('controls');panel(`<p class="eyebrow">Controls</p><h1>Stay close. Keep moving.</h1><div class="controls"><div><kbd>W A S D</kbd> Move</div><div>Mouse / <kbd>← ↑ ↓ →</kbd> Look</div><div><kbd>E</kbd> Interact near a person or object</div><div><kbd>C</kbd> Hold to crouch</div><div><kbd>Shift</kbd> Sprint</div><div><kbd>Space</kbd> Jump / brake a hauled load / press stroke / advance scene</div><div>Click / <kbd>F</kbd> Fire when armed</div><div>Right mouse / <kbd>Q</kbd> Aim</div><div><kbd>R</kbd> Reload</div><div><kbd>V</kbd> Toggle auto-walk; WASD cancels</div><div><kbd>P / Esc</kbd> Pause</div><div><kbd>M</kbd> Mute all sound</div><div>Touch: swipe to look; LOW and AIM toggle</div></div><p>Tap E to begin an interaction; moving away cancels it. Watch the warning before a Lexington volley. In Concord, E at the supply crate restores health and cartridges once. At Breed’s Hill, E at the line directs a volley; E at your reserve resupplies once. Keep low while the militia reload. Reload behind cover to recover. On the water, WASD rows relative to your view, Shift rows hard, and C toggles quiet strokes. Release movement to brake. Reeds hide a slow boat; change direction when a shot is marked on the water. On the gun road, WASD pulls once hitched, Space brakes the load, and the hauling camera keeps the rope and gun in view. Move the ballast across the sledge when Mara calls for it. At the hand press, E feeds or takes a sheet, D slides in, Space presses inside the pale band, and A slides out. W or S steps away; E at the handles resumes. Story difficulty gives more protection and aiming assistance.</p><div class="row">${btn('Back',back)}</div>`,true);}
function archive(){hide();setState('archive');panel(`<p class="eyebrow">Chapter 6 · Part I</p><h1>The history behind the road.</h1><p>Playable now: Ward’s release, the Powder Road, Lexington, the retreat from Concord, The Guns North at Ticonderoga, Hold Until Empty at Breed’s Hill, A King’s Promise in Virginia and North Carolina, and Lift the Horizon through the winter gun road, Dorchester Heights, and Boston’s evacuation, followed by A Country on Paper’s Philadelphia press and diplomatic dispatch. Later Chapter 6 missions remain in development.</p>${FACTS.map(([title,text,source])=>`<article class="fact"><h2>${esc(title)}</h2><p>${esc(text)}</p><small>${esc(source)}</small></article>`).join('')}<article class="fact"><h2>Production</h2><p>${C6_VOICES.length} prerecorded synthetic performances using stock Kokoro voices; ${Object.keys(C6_SCORE).length} original instrumental arrangements. Real-time scenes, original procedural environments, and the established crew rigs. No account, microphone, or AI service is needed to play.</p><p><a href="C6-SOURCES.md" target="_blank">Sources and historical scope</a> · <a href="C6-CREDITS.md" target="_blank">Voice, music, and art credits</a></p></article>${btn('Back','home','quiet')}`);}
function settings(back=state==='pause'?'pause':'home'){settingsBack=back;setState('settings');const slider=(id,label,help)=>`<label class="setting"><span>${label}<small>${help}</small></span><input aria-label="${label}" type="range" data-setting="${id}" min="0" max="1" step=".05" value="${prefs[id]}"></label>`;
 panel(`<p class="eyebrow">Settings</p><h1>Make room for the story.</h1><label class="setting"><span>Mute all sound<small>${silentSession?'This preview session is locked to silent.':'Also available with the M key.'}</small></span><input aria-label="Mute all sound" type="checkbox" data-setting="muted" ${prefs.muted||silentSession?'checked':''} ${silentSession?'disabled':''}></label>${slider('voice','Voice volume','Dialogue remains captioned if a recording fails.')}${slider('music','Music volume','The score lowers during speech.')}${slider('effects','Effects volume','Gunfire, footsteps, and interactions.')}<label class="setting"><span>Difficulty<small>Story reduces damage and adds aiming assistance.</small></span><select aria-label="Difficulty" data-setting="difficulty"><option value="normal" ${prefs.difficulty==='normal'?'selected':''}>Normal</option><option value="story" ${prefs.difficulty==='story'?'selected':''}>Story</option></select></label><label class="setting"><span>Look sensitivity</span><input aria-label="Look sensitivity" type="range" data-setting="sensitivity" min=".3" max="2" step=".1" value="${prefs.sensitivity}"></label><label class="setting"><span>Graphics<small>Performance reduces shadows and resolution.</small></span><select aria-label="Graphics" data-setting="quality"><option value="high" ${prefs.quality==='high'?'selected':''}>Detailed</option><option value="low" ${prefs.quality==='low'?'selected':''}>Performance</option></select></label>${[['subtitles','Subtitles'],['large','Larger captions'],['reduced','Reduced camera motion']].map(([k,v])=>`<label class="setting"><span>${v}</span><input type="checkbox" data-setting="${k}" ${prefs[k]?'checked':''}></label>`).join('')}<div class="row">${btn('Done','settings-done')}</div>`,true);}
function errorScreen(){setState('error');panel(`<p class="eyebrow">Graphics unavailable</p><h1>The road couldn’t open.</h1><p>This browser could not initialize WebGL. Try a browser with hardware acceleration enabled, or return to another chapter.</p><div class="row">${btn('Try again','retry-render')}${btn('Chapters','chapters','secondary')}</div>`,true);}
function start(){replay=false;missionReplay=false;if(fixture&&LEVELS[fixture]){const phase=sessionParams.get('phase');begin(fixtureState(fixture,phase,prefs.difficulty));if(phase==='break'&&fixture==='breeds')playScene('hillBreak');return;}if(saved.complete){saved.complete=false;saved.checkpoint=null;saved.scene='release';}if(saved.scene)return playScene(saved.scene);if(saved.checkpoint){model=restore(saved.checkpoint,prefs.difficulty);if(model)return begin(model);}playScene('release');}
function checkpoint(){if(missionReplay){replayCheckpoint=snapshot(model);saveUntil=time+2.8;return;}saved.checkpoint=snapshot(model);saved.scene=null;persist();saveUntil=time+2.8;}
function begin(s){if(!ensureWorld())return errorScreen();model=s;world.load(s.level);film=null;resetInput();dialogue.reset();setState('play');ui.innerHTML='';music.select(s.level==='tidewater'?(s.stage>=4?'battle':s.stage>=3?'tension':'tide'):s.level==='breeds'?(s.stage>=7?'tension':hillDefending(s)?'ridge':'tension'):LEVELS[s.level].music);music.resume();checkpoint();canvas.focus();last=performance.now();updateHUD();if(s.level==='release'&&s.stage===1)say('releasewalk');}
function playScene(key,preview=false){if(!ensureWorld())return errorScreen();resetInput();dialogue.stop();replay=preview;film={key,beat:0,time:0,elapsed:0,spoken:false,shot:false};world.load(SCENES[key].level);setState('film');ui.innerHTML='';if(!preview&&!missionReplay){saved.scene=key;persist();}if(SCENES[key].music){music.select(SCENES[key].music);music.resume();}else music.pause();$('scene-title').textContent=SCENES[key].title;$('scene-place').textContent=SCENES[key].place;last=performance.now();}
function advance(){if(!film)return;dialogue.stop();film.beat++;film.time=0;film.spoken=false;if(film.beat>=SCENES[film.key].lines.length)finishScene();}
function finishScene(){if(!film)return;const key=film.key;dialogue.stop();film=null;if(replay){replay=false;scenes();return;}if(!missionReplay&&!saved.seen.includes(key))saved.seen.push(key);const target=SCENES[key].after;document.body.dataset.nextScene=target;if(!missionReplay){saved.scene=null;persist();}if(missionReplay&&['northEnding','hillLegacy','promiseCoda','liftHome','paperCoda'].includes(key))return missionComplete();if(target==='checkpoint'){const point=missionReplay?replayCheckpoint:saved.checkpoint;const resumed=restore(point,prefs.difficulty);if(resumed){if(resumed.fort)resumed.fort.crew=1;return begin(resumed);}return begin(fresh(SCENES[key].level,prefs.difficulty));}if(LEVELS[target])begin(fresh(target,prefs.difficulty));else if(SCENES[target])playScene(target);else if(target==='complete'){if(missionReplay)missionComplete();else complete();}}
function finishLevel(){if(model.paper)return playScene(LEVELS[model.level].after);if(model.lift)return playScene(LEVELS[model.level].after);if(model.promise)return playScene(LEVELS[model.level].after);if(missionReplay){if(model.level==='breeds')return playScene('hillEnding');if(model.level==='ticonderoga')return playScene('northEnding');return missionComplete();}resetInput();dialogue.stop();const scene={release:'gate',night:'lexington',lexington:'concordIntro',concord:'ending',ticonderoga:'northEnding',breeds:'hillEnding'}[model.level];playScene(scene);}
function complete(){saved.complete=true;saved.scene=null;saved.checkpoint=null;persist();hide();setState('complete');music.select('home');music.resume();panel(`<p class="eyebrow">A Country on Paper · Complete</p><h1>The words got through.</h1><p>The neighborhood has its copies. The diplomatic packets are at the harbor. Thomas has read his brother’s work.</p><p>Next: No Ground Left, in New York. The rest of the Chapter 6 campaign remains in development.</p><div class="row">${btn('Back to the road','home')}${btn('Remember these events','archive','secondary')}${btn('Replay scenes','scenes','quiet')}</div>`,true);}
function pause(){if(!['play','film'].includes(state))return;beforePause=state;dialogue.pause();music.pause();fxContext?.suspend();resetInput();setState('pause');pausePanel();}
function pausePanel(){setState('pause');panel(`<p class="eyebrow">Paused · ${beforePause==='film'?'Story scene':esc(LEVELS[model?.level]?.title||'The Powder Road')}</p><h1>Take a breath.</h1><div class="row">${btn('Resume','resume')}${btn('Settings','settings','secondary')}${btn('Controls','pause-controls','quiet')}</div><div class="row">${beforePause==='play'?btn('Restart checkpoint','retry','quiet'):btn('Restart scene','restart-scene','quiet')}${btn('Return to title','home','quiet')}</div><p class="save-warning">${missionReplay?'This replay leaves your story checkpoint intact.':storageOK?'Your last checkpoint is saved.':'Browser saving is unavailable in this session.'}</p>`,true);}
function resume(){ui.innerHTML='';setState(beforePause);dialogue.resume();if(beforePause!=='film'||SCENES[film?.key]?.music)music.resume();fxContext?.resume();last=performance.now();canvas.focus();}
function fail(){dialogue.stop();music.pause();resetInput();setState('failed');panel(`<p class="eyebrow">The road is still there</p><h1>Find cover. Try again.</h1><p>${model.level==='tidewater'?'Use C in the reeds to lose the lanterns. Dodge the marked shots; use Shift to pull away from the pursuing boat.':model.level==='breeds'?'Stay at the earthworks during the assaults. Direct volleys when they are close, crouch to reload, and use your reserve. During withdrawal, the rear earthworks give you shelter.':model.level==='night'?'Break the patrol’s line of sight. Crouch behind fences and take the orchard route.':'Use the stone wall while reloading. Crouch to stay below incoming fire.'}</p><div class="row">${btn('Restart checkpoint','retry')}${btn('Use Story difficulty','story-retry','secondary')}${btn('Return to title','home','quiet')}</div>`,true);}
function retry(){const point=missionReplay?replayCheckpoint:saved.checkpoint;if(!point)return start();const restored=restore(point,prefs.difficulty);if(restored){restored.player.health=100;begin(restored);say(restored.lift?'lift.catch':restored.promise?'promise.retry':'retry');}else start();}
function updateHUD(){if(!model)return;const s=model,g=currentGoal(s),p=s.player;
 $('location').textContent=LEVELS[s.level].place;$('task').textContent=g?.label||'';$('context').textContent=s.paper?paperContext(s):s.lift?liftContext(s):s.promise?promiseContext(s):s.level==='breeds'?hillContext(s):s.level==='ticonderoga'?fortContext(s):s.carrying?(s.level==='release'?'Ward is leaning on you.':'Supporting a wounded man.'):s.level==='concord'&&s.stage===1?(distance(p,{x:0,z:4})>=19?'Return to the stone wall.':s.wagonHealth<75?'The wagon is taking fire. Stop their advance.':'Hold until Mara gets the wagon across.'):'';
 $('health').style.width=p.health+'%';$('health').style.background=p.health<35?'#cf7763':'';$('vitals').style.opacity=p.health<99?'1':'0';$('condition').textContent=p.health<35?'WOUNDED · FIND COVER':p.health<75?'HURT':s.carrying?(s.level==='breeds'&&s.stage===1?'CARRYING RESERVE':'MOVE TOGETHER'):'';
 $('weapon').textContent=s.paper?.atPress?`${s.paper.sheets} / 3 CLEAN SHEETS\n${s.paper.phase.toUpperCase()}`:liftHauling(s)?`${s.lift.brake?'BRAKE SET':'HAULING LINE'}\n${s.lift.speed.toFixed(1)} m/s`:s.level==='tidewater'?`${s.promise.quiet?'QUIET STROKES':s.promise.speed>8?'HARD STROKES':'ISAIAH · AT THE OARS'}\n${Math.round(p.stamina)}% STAMINA`:s.armed?s.reload>0?`RELOADING · ${s.reload.toFixed(1)}s`:s.loaded?`1   /   ${s.ammo}\nFLINTLOCK`:`EMPTY · R TO RELOAD\n${s.ammo} CARTRIDGES`:'';$('crosshair').hidden=!s.armed;$('crosshair').classList.toggle('hit',s.hit>0);$('reload-bar').hidden=!(s.reload>0);$('reload-bar').style.setProperty('--progress',((1-s.reload/4.2)*100)+'%');
 document.querySelectorAll('#touch [data-key="KeyF"],#touch [data-key="KeyR"],#touch [data-key="KeyQ"]').forEach(b=>b.hidden=!s.armed);
 const touchStroke=document.querySelector('#touch [data-key="Space"]');touchStroke.hidden=!liftHauling(s)&&!paperOperating(s);touchStroke.textContent=paperOperating(s)?'PRESS':'BRAKE';touchStroke.setAttribute('aria-label',paperOperating(s)?'Make a press stroke':'Brake hauled load');
 $('press-meter').hidden=!paperOperating(s)||s.paper.phase!=='stroke';if(paperOperating(s)){$('press-meter').style.setProperty('--beat',s.paper.beat*100+'%');$('press-meter').setAttribute('aria-label','Press stroke timing: '+Math.round(s.paper.beat*100)+' percent');}
 const defending=hillDefending(s),order=hillCanVolley(s);const near=goalNear(s)&&!paperOperating(s)&&(!s.paper||paperCanUse(s))&&!liftHauling(s)&&(!s.lift||liftCanUse(s))&&!defending&&!(s.level==='concord'&&s.stage===1)&&!(s.level==='ticonderoga'&&s.stage===6),supply=hillSupply(s)||s.level==='concord'&&s.stage===1&&!s.suppliesUsed&&distance(p,{x:2,z:9})<2.5;$('prompt').innerHTML=near||supply||order?`<kbd>${coarse?'USE':'E'}</kbd>${supply?'Take reserve cartridges':order?'Order volley':esc(g.verb)}`:'';$('prompt').style.setProperty('--progress',near&&g.time>0?Math.min(100,s.hold/g.time*100)+'%':'0%');
 $('hint').textContent=paperOperating(s)?'W / S step away · P pause':s.level==='tidewater'?'':s.time<16?(coarse?'Swipe to look':s.armed?'F / click fire · R reload · C cover':s.level==='night'?'Stay low · avoid lantern light · E warn':'WASD move · mouse / arrows look · E interact'):'';document.querySelector('#touch [data-key="KeyC"]').classList.toggle('active',touchCrouch);document.querySelector('#touch [data-key="KeyQ"]').classList.toggle('active',touchAim);$('convoy').hidden=!defending&&!(s.level==='concord'&&s.stage===1)&&!(s.level==='ticonderoga'&&s.stage===6);$('convoy').style.setProperty('--progress',Math.min(100,defending?s.hill.line:s.level==='ticonderoga'?s.fort.haul*100:s.defense/52*100)+'%');$('convoy').textContent=defending?`LINE HOLDING · ${Math.ceil(s.hill.teamAmmo)} CARTRIDGES`:s.level==='ticonderoga'?'MOVE TOGETHER':s.wagonHealth<60?'WAGON UNDER FIRE':'WAGON CROSSING';
 $('saved').textContent=time<saveUntil?(storageOK?'CHECKPOINT SAVED':'CHECKPOINT HELD FOR THIS SESSION'):'';$('awareness').textContent=s.level==='tidewater'&&s.promise.hidden?'HIDDEN':s.volleyWarning?'VOLLEY INCOMING · FIND COVER':s.alert>.8?'SPOTTED · BREAK SIGHT':s.alert>.15?(s.level==='ticonderoga'?'SENTRY IS LOOKING':'PATROL IS LOOKING'):'';$('awareness').style.setProperty('--progress',(s.volleyWarning?(s.time%9-6.5)/2.5:s.alert)*100+'%');
 const bearing=g?angle(Math.atan2(-(g.x-p.x),-(g.z-p.z))-p.yaw):0,screen=world?.goalScreen;
 $('direction').hidden=!g||paperOperating(s)||defending||near||s.level==='concord'&&s.stage===1;
 if(g&&screen&&!screen.behind&&Math.abs(screen.x)<.85&&Math.abs(screen.y)<.8){$('direction').style.left=(screen.x*.5+.5)*100+'%';$('direction').style.top=(-screen.y*.5+.5)*100+'%';$('direction').innerHTML='◇<small>'+Math.round(distance(p,g))+' m</small>'; }
 else{$('direction').style.left=bearing>0?'7%':'93%';$('direction').style.top='48%';$('direction').textContent=bearing>0?'‹':'›';}
 document.body.dataset.level=s.level;document.body.dataset.stage=String(s.stage);document.body.dataset.route=s.fort?(s.fort.alarm?'rescue':'quiet'):'';canvas.dataset.position=`${p.x.toFixed(1)},${p.z.toFixed(1)}`;canvas.dataset.heading=p.yaw.toFixed(3);canvas.dataset.pitch=p.pitch.toFixed(3);
}
function input(){return {forward:keys.KeyW||autoWalk,back:keys.KeyS,left:keys.KeyA,right:keys.KeyD,rightTap:pressed.KeyD,leftTap:pressed.KeyA,crouch:keys.KeyC||touchCrouch,sprint:keys.ShiftLeft||keys.ShiftRight,lookLeft:keys.ArrowLeft||pressed.ArrowLeft,lookRight:keys.ArrowRight||pressed.ArrowRight,lookUp:keys.ArrowUp||pressed.ArrowUp,lookDown:keys.ArrowDown||pressed.ArrowDown,jump:keys.Space||pressed.Space,press:pressed.Space,useTap:pressed.KeyE,interact:keys.KeyE||interacting,reload:keys.KeyR||pressed.KeyR,fire:keys.KeyF||fire||pressed.KeyF,aim:keys.KeyQ||aim||touchAim};}
function action(name,el){document.body.dataset.lastAction=name;music.unlock();fxContext?.resume();if(name==='home')home();else if(name==='start')start();else if(name==='missions')missions();else if(name==='mission'){missionReplay=true;replayCheckpoint=null;if(LEVELS[el.dataset.mission].intro)playScene(LEVELS[el.dataset.mission].intro);else begin(fresh(el.dataset.mission,prefs.difficulty));}else if(name==='campaign'){missionReplay=false;start();}else if(name==='new-story')newStory();else if(name==='confirm-new'){saved.complete=false;saved.checkpoint=null;saved.scene='release';missionReplay=false;persist();start();}else if(name==='chapters')chapters();else if(name==='scenes')scenes();else if(name==='scene')playScene(el.dataset.scene,true);else if(name==='archive')archive();else if(name==='controls')controls();else if(name==='pause-controls')controls('pause-back');else if(name==='pause-back')pausePanel();else if(name==='settings')settings();else if(name==='settings-done'){persist();settingsBack==='pause'?pausePanel():home();}else if(name==='pause')pause();else if(name==='resume')resume();else if(name==='next')advance();else if(name==='skip')finishScene();else if(name==='restart-scene')playScene(film.key,replay);else if(name==='retry')retry();else if(name==='story-retry'){prefs.difficulty='story';persist();retry();}else if(name==='retry-render'){world=null;worldError=null;if(ensureWorld())home();else errorScreen();}}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(b)action(b.dataset.action,b);});
document.addEventListener('input',e=>{const k=e.target.dataset.setting;if(!k)return;prefs[k]=e.target.type==='checkbox'?e.target.checked:e.target.tagName==='SELECT'?e.target.value:Number(e.target.value);configure();if(k==='quality')world?.configure(prefs);if(model)model.difficulty=prefs.difficulty;persist();});
document.addEventListener('keydown',e=>{if(e.target.matches('input,select,textarea'))return;if(['Space','ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.code))e.preventDefault();if(e.code==='KeyM'&&!e.repeat){prefs.muted=!prefs.muted;configure();persist();return;}if(e.code==='Escape'||e.code==='KeyP'){if(e.repeat)return;if(state==='pause')resume();else pause();return;}if(state==='film'&&e.code==='Space'){if(!e.repeat)advance();return;}if(state!=='play')return;keys[e.code]=true;if(!e.repeat)pressed[e.code]=(pressed[e.code]||0)+1;if(e.code==='KeyE'&&!e.repeat)interacting=true;if(e.code==='KeyC'&&!e.repeat&&model.level==='tidewater')touchCrouch=!touchCrouch;if(e.code==='KeyV'&&!e.repeat)autoWalk=!autoWalk;if(['KeyW','KeyA','KeyS','KeyD'].includes(e.code))autoWalk=false;});
document.addEventListener('keyup',e=>{keys[e.code]=false;});
canvas.addEventListener('pointerdown',e=>{
 if(state!=='play'||e.pointerType==='touch')return;
 if(document.pointerLockElement!==canvas){try{canvas.requestPointerLock?.()?.catch?.(()=>{});}catch{}return;}
 ({fire,aim}=mouseButtons(e.buttons));if(e.button===0)pressed.KeyF=true;
});
document.addEventListener('pointerup',e=>{if(e.pointerType!=='touch')({fire,aim}=mouseButtons(e.buttons));});
document.addEventListener('pointercancel',()=>{fire=false;aim=false;});
document.addEventListener('pointerlockchange',()=>{if(document.pointerLockElement===canvas)hadPointerLock=true;else if(hadPointerLock){hadPointerLock=false;if(state==='play')pause();}});
canvas.addEventListener('contextmenu',e=>e.preventDefault());
document.addEventListener('mousemove',e=>{if(state==='play'&&document.pointerLockElement===canvas)applyLook(model.player,e.movementX,e.movementY,prefs.sensitivity);});
let touchPoint=null;
canvas.addEventListener('pointerdown',e=>{if(e.pointerType==='touch'&&state==='play'&&!touchPoint){touchPoint={id:e.pointerId,x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);}});
canvas.addEventListener('pointermove',e=>{if(touchPoint&&state==='play'&&e.pointerId===touchPoint.id){applyLook(model.player,e.clientX-touchPoint.x,e.clientY-touchPoint.y,prefs.sensitivity,true);touchPoint.x=e.clientX;touchPoint.y=e.clientY;}});
for(const type of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(type,e=>{if(touchPoint?.id===e.pointerId)touchPoint=null;});
document.querySelectorAll('[data-key]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);if(b.dataset.key==='KeyC'){touchCrouch=!touchCrouch;return;}if(b.dataset.key==='KeyQ'){touchAim=!touchAim;return;}keys[b.dataset.key]=true;pressed[b.dataset.key]=(pressed[b.dataset.key]||0)+1;if(b.dataset.key==='KeyE')interacting=true;});for(const type of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(type,()=>keys[b.dataset.key]=false);});
window.addEventListener('blur',()=>{if(['play','film'].includes(state))pause();});document.addEventListener('visibilitychange',()=>{music.setHidden(document.hidden);if(document.hidden&&['play','film'].includes(state))pause();});window.addEventListener('resize',()=>world?.resize());
canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();pause();worldError=new Error('Graphics context lost');});canvas.addEventListener('webglcontextrestored',()=>{world=null;ensureWorld();home();});
function frame(now){const frameStart=performance.now(),raw=(now-last)/1000,dt=Math.min(.05,Math.max(0,raw));last=now;time+=dt;
 try{
  if(state==='play'){
   if(keys.KeyW||keys.KeyA||keys.KeyS||keys.KeyD)interacting=false;
   const control=input(),events=tick(model,control,dt);pressed={};dialogue.update(dt);
   for(const e of events){if(e.type==='voice')say(e.id);else if(e.type==='checkpoint'){interacting=false;checkpoint();if(model.level==='tidewater')music.select(model.stage>=4?'battle':model.stage>=3?'tension':'tide');if(model.level==='breeds')music.select(hillDefending(model)?'ridge':'tension');if(model.level==='night'&&model.stage===2)say('ridge');if(model.level==='release'&&model.stage===1)say('releasewalk');}else if(e.type==='hillVolley'){fx('shot',.7);for(const x of [-17,-8,1,10]){world.smoke(x,1.6,1.2);world.trace(x,1.6,x,-25);}}else if(e.type==='volleyOrder'){interacting=false;say('hill.volley');}else if(e.type==='shell'){fx('shot',.9);world.smoke(e.x,e.z,3.5);}else if(e.type==='promiseScene'){playScene(e.key);break;}else if(e.type==='paperAction'){interacting=false;fx('wood',.3);}else if(e.type==='pressStroke'){fx('wood',.6);}else if(e.type==='paperGust'){fx('foot',.25);}else if(e.type==='wood'){fx('wood',.3);}else if(e.type==='loadSlip'){fx('wood',.6);interacting=false;}else if(e.type==='waterShot'){fx('shot',.55);world.smoke(e.x,e.z,.55);}else if(e.type==='hillBreak'){playScene('hillBreak');break;}else if(e.type==='fortCapture'){playScene('fortCapture');break;}else if(e.type==='finish'){if(!dialogue.current&&!dialogue.queue.length)finishLevel();break;}else if(e.type==='fail'){fail();break;}else if(e.type==='shot'){fx('shot');world.smoke(e.x-Math.sin(model.player.yaw),e.z-Math.cos(model.player.yaw));}else if(e.type==='enemyShot'){fx('shot',Math.min(.5,10/Math.max(1,distance(model.player,e))));world.smoke(e.x,e.z,.75);world.trace(e.x,e.z,model.player.x,model.player.z);}else if(e.type==='volley'){fx('shot',.8);for(const x of [-7,-2,3,7]){world.smoke(x,-23,1.6);world.trace(x,-23,model.player.x+x*.2,model.player.z);}}else if(e.type==='resupply'){interacting=false;checkpoint();fx('wood',.4);}else if(e.type==='rescue')fx('wood',.25);else if(e.type==='hurt'){fx('hurt',.4);hurtUntil=time+.28;}else if(e.type==='bell'){fx('bell');world.bellUntil=model.time+2;}else if(e.type==='reload'||e.type==='loaded')fx('wood',.25);}
   if(state==='play'&&model.finished&&!dialogue.current&&!dialogue.queue.length)finishLevel();
   if(state==='play'){world.render(model,control,dt,{reduced:prefs.reduced,voice:captionSpeaker});updateHUD();if(model.level!=='tidewater'&&(control.forward||control.back||control.left||control.right)&&time-footTime>(control.sprint?.30:.46)){footTime=time;fx('foot');}}
  }else if(state==='film'&&film){const f=film,spec=SCENES[f.key],line=voices.get(spec.lines[f.beat]);f.time+=dt;f.elapsed+=dt;dialogue.update(dt);
   const lead=sceneLead(f.beat),hold=sceneHold(f.key,f.beat);if(!f.spoken&&f.time>lead){f.spoken=true;say(line.id);}
   if(f.key==='promiseContact'&&f.beat===8&&!f.shot){f.shot=true;fx('shot',.4);world.smoke(27,-80,.8);}
   if(f.key==='lexington'&&f.beat===2&&!f.shot){f.shot=true;fx('shot',.75);world.smoke(1,-20,3);if(!prefs.reduced)hurtUntil=time+.08;}
   world.film(f.key,f.beat,f.time,dt,{speaking:f.spoken&&!!dialogue.current,reduced:prefs.reduced,elapsed:f.elapsed});$('film-progress').style.width=((f.beat+Math.min(1,f.time/(line.duration+lead+hold)))/spec.lines.length*100)+'%';document.querySelector('.film-title').style.opacity=f.beat===0&&f.time<4.5?'1':'0';canvas.dataset.scene=f.key;canvas.dataset.beat=String(f.beat);
   if(f.spoken&&!dialogue.current&&f.time>lead+line.duration+hold)advance();
  }else if(['menu','chapters','scenes','archive','complete','missions','mission-complete','new-story'].includes(state)){if(ensureWorld())world.menu(time,dt);}
  $('impact').style.opacity=time<hurtUntil&&!prefs.reduced?'.6':'0';
 }catch(e){console.error('Chapter 6 frame:',e);setState('error');panel(`<h1>The scene stopped.</h1><p>Your last checkpoint is saved. Reload to try again.</p>${btn('Return to title','home')}`,true);}
 canvas.dataset.renderMs=(performance.now()-frameStart).toFixed(1);canvas.dataset.frameMs=(raw*1000).toFixed(0);requestAnimationFrame(frame);
}
configure();home();requestAnimationFrame(frame);document.body.dataset.version=VERSION;







