import {SAVE_KEY,VERSION,LEVELS,SCENES,FACTS,NAMES} from './c6-data.mjs?v=4.0.4';
import {fresh,restore,snapshot,tick,currentGoal,goalNear,clamp,angle,distance} from './c6-sim.mjs?v=4.0.4';
import {OpeningWorld} from './c6-world.mjs?v=4.0.4';
import {C6_VOICES} from './c6-voices.mjs?v=4.0.4';
import {C6_SCORE} from './c6-score.mjs?v=4.0.4';
import {DialogueDirector} from './dialogue.mjs';
import {MusicDirector} from './music.mjs';
const $=id=>document.getElementById(id),ui=$('ui'),canvas=$('world'),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const btn=(label,action,cls='primary',extra='')=>`<button class="${cls}" data-action="${action}" ${extra}>${label}</button>`;
const voices=new Map(C6_VOICES.map(v=>[v.id,v]));const coarse=matchMedia('(pointer:coarse)').matches;
// Local playtest fixtures are isolated from a player's campaign save.
const fixture=['localhost','127.0.0.1','[::1]'].includes(location.hostname)?new URLSearchParams(location.search).get('test'):null;
const storageKey=fixture?SAVE_KEY+'-playtest':SAVE_KEY;
let prefs={music:.5,voice:.95,effects:.55,subtitles:true,reduced:matchMedia('(prefers-reduced-motion:reduce)').matches,large:false,difficulty:'normal',sensitivity:1};
let saved={version:1,checkpoint:null,scene:null,complete:false,seen:[],prefs},storageOK=true;
try{const old=JSON.parse(localStorage.getItem(storageKey));if(old?.version===1){saved={...saved,...old,seen:Array.isArray(old.seen)?old.seen.filter(k=>SCENES[k]):[]};prefs={...prefs,...old.prefs};if(saved.checkpoint&&!restore(saved.checkpoint,prefs.difficulty))saved.checkpoint=null;if(saved.scene&&!SCENES[saved.scene])saved.scene=null;}}catch{storageOK=false;}
let state='menu',beforePause='play',settingsBack='menu',model=null,world=null,film=null,keys={},aim=false,fire=false,autoWalk=false,interacting=false,replay=false,last=performance.now(),time=0,hurtUntil=0,saveUntil=0,footTime=0,worldError=null,captionSpeaker=null,fxContext=null,fxGain=null;
let pressed={};
function persist(){saved.prefs=prefs;try{localStorage.setItem(storageKey,JSON.stringify(saved));}catch{storageOK=false;}}
const music=new MusicDirector({tracks:C6_SCORE,onStatus:s=>{document.body.dataset.music=s.id||'';document.body.dataset.musicState=s.state;}});
const dialogue=new DialogueDirector({media:$('speech'),lines:C6_VOICES,onCaption(line){captionSpeaker=line?.speaker||null;$('subtitle').innerHTML=line?`<b>${esc(NAMES[line.speaker]||line.speaker)}</b>${esc(line.text)}`:'';$('subtitle').classList.toggle('visible',!!line);},onActivity:active=>music.duck(active),onLast:l=>$('speech').dataset.clip=l.id});
function configure(){music.configure({enabled:prefs.music>0,volume:prefs.music});dialogue.configure({enabled:prefs.voice>0,volume:prefs.voice,subtitles:prefs.subtitles});document.body.classList.toggle('large-captions',prefs.large);if(fxGain)fxGain.gain.value=prefs.effects*.5;}
function fx(kind,volume=1){if(!prefs.effects||state==='pause')return;try{fxContext??=new(window.AudioContext||window.webkitAudioContext)();if(!fxGain){fxGain=fxContext.createGain();fxGain.connect(fxContext.destination);}fxGain.gain.value=prefs.effects*.5;fxContext.resume();const ctx=fxContext,t=ctx.currentTime;
 if(kind==='bell'){for(const f of [510,1021,1407]){const o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=f;g.gain.setValueAtTime(.12*volume,t);g.gain.exponentialRampToValueAtTime(.0001,t+2.5);o.connect(g);g.connect(fxGain);o.start();o.stop(t+2.6);}return;}
 const len=kind==='shot'?.6:kind==='hurt'?.3:kind==='foot'?.09:.18,b=ctx.createBuffer(1,Math.ceil(ctx.sampleRate*len),ctx.sampleRate),d=b.getChannelData(0);
 for(let i=0;i<d.length;i++){const p=i/d.length;d[i]=(Math.random()*2-1)*Math.pow(1-p,kind==='shot'?4:2)*volume*(kind==='foot'?.15:1);}
 const src=ctx.createBufferSource(),filter=ctx.createBiquadFilter();src.buffer=b;filter.type='lowpass';filter.frequency.value=kind==='shot'?1800:kind==='foot'?160:600;src.connect(filter);filter.connect(fxGain);src.start();}catch{}}
function say(id){dialogue.say(id,{priority:1,ttl:Infinity});}
function resetInput(){keys={};pressed={};fire=false;aim=false;autoWalk=false;interacting=false;try{if(document.pointerLockElement)document.exitPointerLock();}catch{}}
function setState(next){state=next;document.body.dataset.state=state;document.body.classList.toggle('cinematic',state==='film');$('hud').hidden=state!=='play';$('film').hidden=state!=='film';$('touch').hidden=!(coarse&&state==='play');document.body.classList.toggle('touch',coarse&&state==='play');}
function ensureWorld(){if(world)return true;try{world=new OpeningWorld(canvas);return true;}catch(e){worldError=e;console.error('Chapter 6 renderer:',e);return false;}}
function panel(content,narrow=false){ui.innerHTML=`<section class="panel ${narrow?'narrow':''}"><div class="panel-inner">${content}</div></section>`;}
function hide(){resetInput();dialogue.stop();setState('menu');}
function home(){hide();film=null;replay=false;music.select('home');music.resume();const started=saved.checkpoint||saved.scene;
 ui.innerHTML=`<section class="menu"><header class="topline"><a class="brand" href="./">DC <i>/</i> US HISTORY</a><nav>${btn('Chapters','chapters','quiet')}${btn('Settings','settings','quiet')}</nav></header><div class="hero"><p class="eyebrow">Chapter 06 · America’s War for Independence</p><h1>THE LONG<br><span>ROAD HOME</span></h1><p class="lede">A promise kept. A country breaking.<br>Get your people through the first light.</p><div class="row">${btn(started&&!saved.complete?'Continue the opening →':'Begin the opening →','start')}${btn('Story scenes','scenes','secondary')}</div><div class="edition"><span>PART I · THE POWDER ROAD</span><span>1775</span><span>HEADPHONES RECOMMENDED</span></div>${!storageOK?'<p class="save-warning">Browser saving is unavailable. Keep this tab open to retain your session.</p>':''}</div><div class="chapter-number">06</div><footer class="menu-foot"><span>AN ORIGINAL STORY THROUGH REAL HISTORY</span><div class="row">${btn('Controls','controls','quiet')}${btn('History & credits','archive','quiet')}</div></footer></section>`;
}
function chapters(){hide();setState('chapters');panel(`<p class="eyebrow">DC / US History</p><h1>Three roads through history.</h1><div class="chapters"><a class="chapter-card" href="chapter4.html"><span>CHAPTER 04</span><strong>Crown & Current</strong><p>1676–1763 · Building an empire.</p><span>Play →</span></a><a class="chapter-card" href="chapter5.html"><span>CHAPTER 05</span><strong>The Last Dispatch</strong><p>1763–1774 · A city on the edge.</p><span>Play →</span></a><button class="chapter-card" data-action="home"><span>CHAPTER 06 · OPENING</span><strong>The Long Road Home</strong><p>1775 · A warning in the dark.</p><span>Play →</span></button></div><div class="row">${btn('Back','home','quiet')}</div>`);}
function scenes(){hide();setState('scenes');panel(`<p class="eyebrow">The Long Road Home · screening room</p><h1>The story in six scenes.</h1><p>Includes the opening’s ending. Replays leave your campaign checkpoint intact.</p><div class="scene-list">${Object.entries(SCENES).map(([id,s],i)=>btn(`<span>0${i+1} · ${esc(s.place)}</span><strong>${esc(s.title)}</strong>`,'scene','scene-card',`data-scene="${id}"`)).join('')}</div>${btn('Back','home','quiet')}`);}
function controls(back='home'){setState('controls');panel(`<p class="eyebrow">Controls</p><h1>Stay close. Keep moving.</h1><div class="controls"><div><kbd>W A S D</kbd> Move</div><div>Mouse / <kbd>← ↑ ↓ →</kbd> Look</div><div><kbd>E</kbd> Interact near a person or object</div><div><kbd>C</kbd> Hold to crouch</div><div><kbd>Shift</kbd> Sprint</div><div><kbd>Space</kbd> Jump / advance scene</div><div>Click / <kbd>F</kbd> Fire when armed</div><div>Right mouse / <kbd>Q</kbd> Aim</div><div><kbd>R</kbd> Reload</div><div><kbd>V</kbd> Toggle walking forward</div><div><kbd>P / Esc</kbd> Pause</div><div>Touch: movement buttons + swipe to look</div></div><p>Tap E to begin an interaction; moving away cancels it. Reload behind cover. Story difficulty gives more protection and aiming assistance.</p><div class="row">${btn('Back',back)}</div>`,true);}
function archive(){hide();setState('archive');panel(`<p class="eyebrow">Chapter 6 · Part I</p><h1>The history behind the road.</h1><p>This installment covers Ward’s fictional release and the events around Lexington and Concord. The rest of Chapter 6 is planned, not yet playable.</p>${FACTS.map(([title,text,source])=>`<article class="fact"><h2>${esc(title)}</h2><p>${esc(text)}</p><small>${esc(source)}</small></article>`).join('')}<article class="fact"><h2>Production</h2><p>49 prerecorded synthetic performances using stock Kokoro voices; four original instrumental arrangements. Real-time scenes, original procedural environments, and the established crew rigs. No account, microphone, or AI service is needed to play.</p><p><a href="C6-SOURCES.md" target="_blank">Sources and historical scope</a> · <a href="C6-CREDITS.md" target="_blank">Voice, music, and art credits</a></p></article>${btn('Back','home','quiet')}`);}
function settings(back=state==='pause'?'pause':'home'){settingsBack=back;setState('settings');const slider=(id,label,help)=>`<label class="setting"><span>${label}<small>${help}</small></span><input aria-label="${label}" type="range" data-setting="${id}" min="0" max="1" step=".05" value="${prefs[id]}"></label>`;
 panel(`<p class="eyebrow">Settings</p><h1>Make room for the story.</h1>${slider('voice','Voice volume','Dialogue remains captioned if a recording fails.')}${slider('music','Music volume','The score lowers during speech.')}${slider('effects','Effects volume','Gunfire, footsteps, and interactions.')}<label class="setting"><span>Difficulty<small>Story reduces damage and adds aiming assistance.</small></span><select aria-label="Difficulty" data-setting="difficulty"><option value="normal" ${prefs.difficulty==='normal'?'selected':''}>Normal</option><option value="story" ${prefs.difficulty==='story'?'selected':''}>Story</option></select></label>${[['subtitles','Subtitles'],['large','Larger captions'],['reduced','Reduced camera motion']].map(([k,v])=>`<label class="setting"><span>${v}</span><input type="checkbox" data-setting="${k}" ${prefs[k]?'checked':''}></label>`).join('')}<div class="row">${btn('Done','settings-done')}</div>`,true);}
function errorScreen(){setState('error');panel(`<p class="eyebrow">Graphics unavailable</p><h1>The road couldn’t open.</h1><p>This browser could not initialize WebGL. Try a browser with hardware acceleration enabled, or return to another chapter.</p><div class="row">${btn('Try again','retry-render')}${btn('Chapters','chapters','secondary')}</div>`,true);}
function start(){replay=false;if(fixture&&LEVELS[fixture])return begin(fresh(fixture,prefs.difficulty));if(saved.complete){saved.complete=false;saved.checkpoint=null;saved.scene='release';}if(saved.scene)return playScene(saved.scene);if(saved.checkpoint){model=restore(saved.checkpoint,prefs.difficulty);if(model)return begin(model);}playScene('release');}
function checkpoint(){saved.checkpoint=snapshot(model);saved.scene=null;persist();saveUntil=time+2.8;}
function begin(s){if(!ensureWorld())return errorScreen();model=s;world.load(s.level);film=null;resetInput();dialogue.reset();setState('play');ui.innerHTML='';music.select(LEVELS[s.level].music);music.resume();checkpoint();canvas.focus();last=performance.now();updateHUD();if(s.level==='release'&&s.stage===0)say('releasewalk');}
function playScene(key,preview=false){if(!ensureWorld())return errorScreen();resetInput();dialogue.stop();replay=preview;film={key,beat:0,time:0,spoken:false,shot:false};world.load(SCENES[key].level);setState('film');ui.innerHTML='';if(!preview){saved.scene=key;persist();}if(SCENES[key].music){music.select(SCENES[key].music);music.resume();}else music.pause();$('scene-title').textContent=SCENES[key].title;$('scene-place').textContent=SCENES[key].place;last=performance.now();}
function advance(){if(!film)return;dialogue.stop();film.beat++;film.time=0;film.spoken=false;if(film.beat>=SCENES[film.key].lines.length)finishScene();}
function finishScene(){if(!film)return;const key=film.key;dialogue.stop();film=null;if(replay){replay=false;scenes();return;}if(!saved.seen.includes(key))saved.seen.push(key);const target=SCENES[key].after;document.body.dataset.nextScene=target;saved.scene=null;persist();if(LEVELS[target])begin(fresh(target,prefs.difficulty));else if(SCENES[target])playScene(target);else if(target==='complete')complete();}
function finishLevel(){resetInput();dialogue.stop();const scene={release:'gate',night:'lexington',lexington:'concordIntro',concord:'ending'}[model.level];playScene(scene);}
function complete(){saved.complete=true;saved.scene=null;saved.checkpoint=null;persist();hide();setState('complete');music.select('home');music.resume();panel(`<p class="eyebrow">Part I complete</p><h1>Everyone we can.</h1><p>Ward is home. The warning got through. Your crew brought the wounded off the road.</p><p>Militia are gathering around Boston. The war—and the rest of Chapter 6—lies ahead.</p><div class="row">${btn('Back to the road','home')}${btn('Remember these events','archive','secondary')}${btn('Replay scenes','scenes','quiet')}</div>`,true);}
function pause(){if(!['play','film'].includes(state))return;beforePause=state;dialogue.pause();music.pause();fxContext?.suspend();resetInput();setState('pause');pausePanel();}
function pausePanel(){setState('pause');panel(`<p class="eyebrow">Paused · ${beforePause==='film'?'Story scene':esc(LEVELS[model?.level]?.title||'The Powder Road')}</p><h1>Take a breath.</h1><div class="row">${btn('Resume','resume')}${btn('Settings','settings','secondary')}${btn('Controls','pause-controls','quiet')}</div><div class="row">${beforePause==='play'?btn('Restart checkpoint','retry','quiet'):btn('Restart scene','restart-scene','quiet')}${btn('Return to title','home','quiet')}</div><p class="save-warning">${storageOK?'Your last checkpoint is saved.':'Browser saving is unavailable in this session.'}</p>`,true);}
function resume(){ui.innerHTML='';setState(beforePause);dialogue.resume();if(beforePause!=='film'||SCENES[film?.key]?.music)music.resume();fxContext?.resume();last=performance.now();canvas.focus();}
function fail(){dialogue.stop();music.pause();resetInput();setState('failed');panel(`<p class="eyebrow">The road is still there</p><h1>Find cover. Try again.</h1><p>${model.level==='night'?'Break the patrol’s line of sight. Crouch behind fences and take the orchard route.':'Use the stone wall while reloading. Crouch to stay below incoming fire.'}</p><div class="row">${btn('Restart checkpoint','retry')}${btn('Use Story difficulty','story-retry','secondary')}${btn('Return to title','home','quiet')}</div>`,true);}
function retry(){if(!saved.checkpoint)return start();const restored=restore(saved.checkpoint,prefs.difficulty);if(restored){restored.player.health=100;begin(restored);say('retry');}else start();}
function updateHUD(){if(!model)return;const s=model,g=currentGoal(s),p=s.player;
 $('location').textContent=LEVELS[s.level].place;$('task').textContent=g?.label||'';$('context').textContent=s.carrying?(s.level==='release'?'Ward is leaning on you.':'Supporting a wounded man.'):s.level==='concord'&&s.stage===1?(distance(p,{x:0,z:4})>=19?'Return to the stone wall.':s.wagonHealth<75?'The wagon is taking fire. Stop their advance.':'Hold until Mara gets the wagon across.'):'';
 $('health').style.width=p.health+'%';$('health').style.background=p.health<35?'#cf7763':'';$('vitals').style.opacity=p.health<99||s.armed?'1':'.35';$('condition').textContent=p.health<35?'WOUNDED · FIND COVER':p.health<75?'HURT':s.carrying?'MOVE TOGETHER':'';
 $('weapon').textContent=s.armed?s.reload>0?`RELOADING · ${s.reload.toFixed(1)}s`:s.loaded?`1   /   ${s.ammo}\nFLINTLOCK`:`EMPTY · R TO RELOAD\n${s.ammo} CARTRIDGES`:'';$('crosshair').hidden=!s.armed;
 document.querySelectorAll('#touch [data-key="KeyF"],#touch [data-key="KeyR"]').forEach(b=>b.hidden=!s.armed);
 const near=goalNear(s)&&!(s.level==='concord'&&s.stage===1);$('prompt').innerHTML=near?`<kbd>${coarse?'USE':'E'}</kbd>${esc(g.verb)}${s.hold>0?' · '+Math.min(100,Math.round(s.hold/g.time*100))+'%':''}`:'';
 $('hint').textContent=coarse?'Swipe to look':s.armed?'F / click fire · R reload · C cover · P pause':s.time<20?'WASD move · mouse / arrows look · E interact · P pause':'';
 $('saved').textContent=time<saveUntil?(storageOK?'CHECKPOINT SAVED':'CHECKPOINT HELD FOR THIS SESSION'):'';$('awareness').textContent=s.alert>.8?'SPOTTED · BREAK SIGHT':s.alert>.3?'PATROL IS LOOKING':'';
 const bearing=g?angle(Math.atan2(-(g.x-p.x),-(g.z-p.z))-p.yaw):0,screen=world?.goalScreen;
 $('direction').hidden=near||s.level==='concord'&&s.stage===1;
 if(screen&&!screen.behind&&Math.abs(screen.x)<.85&&Math.abs(screen.y)<.8){$('direction').style.left=(screen.x*.5+.5)*100+'%';$('direction').style.top=(-screen.y*.5+.5)*100+'%';$('direction').textContent='◇';}
 else{$('direction').style.left=bearing>0?'7%':'93%';$('direction').style.top='48%';$('direction').textContent=bearing>0?'‹':'›';}
 document.body.dataset.level=s.level;document.body.dataset.stage=String(s.stage);canvas.dataset.position=`${p.x.toFixed(1)},${p.z.toFixed(1)}`;
}
function input(){return {forward:keys.KeyW||autoWalk,back:keys.KeyS,left:keys.KeyA,right:keys.KeyD,crouch:keys.KeyC,sprint:keys.ShiftLeft,lookLeft:keys.ArrowLeft,lookRight:keys.ArrowRight,lookUp:keys.ArrowUp,lookDown:keys.ArrowDown,jump:keys.Space||pressed.Space,interact:keys.KeyE||interacting,reload:keys.KeyR||pressed.KeyR,fire:keys.KeyF||fire||pressed.KeyF,aim:keys.KeyQ||aim};}
function action(name,el){document.body.dataset.lastAction=name;music.unlock();fxContext?.resume();if(name==='home')home();else if(name==='start')start();else if(name==='chapters')chapters();else if(name==='scenes')scenes();else if(name==='scene')playScene(el.dataset.scene,true);else if(name==='archive')archive();else if(name==='controls')controls();else if(name==='pause-controls')controls('pause-back');else if(name==='pause-back')pausePanel();else if(name==='settings')settings();else if(name==='settings-done'){persist();settingsBack==='pause'?pausePanel():home();}else if(name==='pause')pause();else if(name==='resume')resume();else if(name==='next')advance();else if(name==='skip')finishScene();else if(name==='restart-scene')playScene(film.key,replay);else if(name==='retry')retry();else if(name==='story-retry'){prefs.difficulty='story';persist();retry();}else if(name==='retry-render'){world=null;worldError=null;if(ensureWorld())home();else errorScreen();}}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(b)action(b.dataset.action,b);});
document.addEventListener('input',e=>{const k=e.target.dataset.setting;if(!k)return;prefs[k]=e.target.type==='checkbox'?e.target.checked:e.target.tagName==='SELECT'?e.target.value:Number(e.target.value);configure();if(model)model.difficulty=prefs.difficulty;persist();});
document.addEventListener('keydown',e=>{if(e.target.matches('input,select,textarea'))return;if(['Space','ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.code))e.preventDefault();if(e.code==='Escape'||e.code==='KeyP'){if(e.repeat)return;if(state==='pause')resume();else pause();return;}if(state==='film'&&e.code==='Space'){if(!e.repeat)advance();return;}if(state!=='play')return;keys[e.code]=true;if(!e.repeat)pressed[e.code]=true;if(e.code==='KeyE'&&!e.repeat)interacting=true;if(e.code==='KeyV'&&!e.repeat)autoWalk=!autoWalk;});
document.addEventListener('keyup',e=>{keys[e.code]=false;});
canvas.addEventListener('click',()=>{if(state==='play'&&!coarse){try{canvas.requestPointerLock?.()?.catch?.(()=>{});}catch{}}});
canvas.addEventListener('pointerdown',e=>{if(state!=='play'||e.pointerType==='touch')return;if(e.button===0&&document.pointerLockElement===canvas){fire=true;pressed.KeyF=true;}if(e.button===2)aim=true;});
document.addEventListener('pointerup',()=>{fire=false;aim=false;});canvas.addEventListener('contextmenu',e=>e.preventDefault());
document.addEventListener('mousemove',e=>{if(state==='play'&&document.pointerLockElement===canvas){model.player.yaw=angle(model.player.yaw-e.movementX*.0022*prefs.sensitivity);model.player.pitch=clamp(model.player.pitch-e.movementY*.0022*prefs.sensitivity,-.9,.85);}});
let touchPoint=null;canvas.addEventListener('pointerdown',e=>{if(e.pointerType==='touch'&&state==='play'){touchPoint=[e.clientX,e.clientY];canvas.setPointerCapture(e.pointerId);}});canvas.addEventListener('pointermove',e=>{if(touchPoint&&state==='play'){model.player.yaw=angle(model.player.yaw-(e.clientX-touchPoint[0])*.006);model.player.pitch=clamp(model.player.pitch-(e.clientY-touchPoint[1])*.005,-.9,.85);touchPoint=[e.clientX,e.clientY];}});canvas.addEventListener('pointerup',()=>touchPoint=null);canvas.addEventListener('pointercancel',()=>touchPoint=null);
document.querySelectorAll('[data-key]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys[b.dataset.key]=true;pressed[b.dataset.key]=true;if(b.dataset.key==='KeyE')interacting=true;});for(const type of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(type,()=>keys[b.dataset.key]=false);});
window.addEventListener('blur',()=>{if(['play','film'].includes(state))pause();});document.addEventListener('visibilitychange',()=>{music.setHidden(document.hidden);if(document.hidden&&['play','film'].includes(state))pause();});window.addEventListener('resize',()=>world?.resize());
canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();pause();worldError=new Error('Graphics context lost');});canvas.addEventListener('webglcontextrestored',()=>{world=null;ensureWorld();home();});
function frame(now){const frameStart=performance.now(),raw=(now-last)/1000,dt=Math.min(.05,Math.max(0,raw));last=now;time+=dt;
 try{
  if(state==='play'){
   if(keys.KeyW||keys.KeyA||keys.KeyS||keys.KeyD)interacting=false;
   const control=input(),events=tick(model,control,dt);pressed={};dialogue.update(dt);
   for(const e of events){if(e.type==='voice')say(e.id);else if(e.type==='checkpoint'){interacting=false;checkpoint();if(model.level==='night'&&model.stage===2)say('ridge');}else if(e.type==='finish'){finishLevel();break;}else if(e.type==='fail'){fail();break;}else if(e.type==='shot'){fx('shot');world.smoke(e.x-Math.sin(model.player.yaw),e.z-Math.cos(model.player.yaw));}else if(e.type==='enemyShot'){fx('shot',Math.min(.5,10/Math.max(1,distance(model.player,e))));world.smoke(e.x,e.z,.75);}else if(e.type==='hurt'){fx('hurt',.4);hurtUntil=time+.28;}else if(e.type==='bell'){fx('bell');world.bellUntil=model.time+2;}else if(e.type==='reload'||e.type==='loaded')fx('wood',.25);}
   if(state==='play'){world.render(model,control,dt,{reduced:prefs.reduced,voice:captionSpeaker});updateHUD();if((control.forward||control.back||control.left||control.right)&&time-footTime>(control.sprint?.30:.46)){footTime=time;fx('foot');}}
  }else if(state==='film'&&film){const f=film,spec=SCENES[f.key],line=voices.get(spec.lines[f.beat]);f.time+=dt;dialogue.update(dt);
   const lead=f.beat===0?2:1.0;if(!f.spoken&&f.time>lead){f.spoken=true;say(line.id);}
   if(f.key==='lexington'&&f.beat===2&&!f.shot){f.shot=true;fx('shot',.75);world.smoke(1,-20,3);if(!prefs.reduced)hurtUntil=time+.08;}
   world.film(f.key,f.beat,f.time,dt,{speaking:f.spoken&&!!dialogue.current,reduced:prefs.reduced});$('film-progress').style.width=((f.beat+Math.min(1,f.time/(line.duration+lead+1.5)))/spec.lines.length*100)+'%';document.querySelector('.film-title').style.opacity=f.beat===0&&f.time<4.5?'1':'0';canvas.dataset.scene=f.key;canvas.dataset.beat=String(f.beat);
   if(f.spoken&&!dialogue.current&&f.time>lead+line.duration+1.5)advance();
  }else if(['menu','chapters','scenes','archive','complete'].includes(state)){if(ensureWorld())world.menu(time,dt);}
  $('impact').style.opacity=time<hurtUntil&&!prefs.reduced?'.6':'0';
 }catch(e){console.error('Chapter 6 frame:',e);setState('error');panel(`<h1>The scene stopped.</h1><p>Your last checkpoint is saved. Reload to try again.</p>${btn('Return to title','home')}`,true);}
 canvas.dataset.renderMs=(performance.now()-frameStart).toFixed(1);canvas.dataset.frameMs=(raw*1000).toFixed(0);requestAnimationFrame(frame);
}
configure();home();requestAnimationFrame(frame);document.body.dataset.version=VERSION;





